#!/usr/bin/env python3
"""A3 packs: vi pl nl fa fil zsm af ca el uk sw."""
from tools.lib.extended_banks import _add
from tools.lib.bank_builder import build_a3, v, g, d


def register():
    for code, rows in DATA.items():
        _add(code, "A3", build_a3(rows))


def _vi():
    return [
        ("Kế hoạch gần: sẽ / định.",
         v([("kỳ thi", "", "exam"), ("môn", "", "subject"), ("bài tập", "", "homework"),
            ("thời khóa biểu", "", "timetable"), ("hạn", "", "deadline"),
            ("ôn", "", "revise", "verb"), ("bài giảng", "", "lecture"), ("ghi chú", "", "notes")]),
         g("sẽ / định + động từ", "Kế hoạch đã quyết.", "tối nay tôi sẽ ôn",
           [("Tối nay tôi sẽ ôn.", "", "I'm going to revise tonight."),
            ("Cô ấy sẽ nghỉ bài giảng.", "", "She's going to miss the lecture."),
            ("Bạn định xong bài tập không?", "", "Are you going to finish the homework?")],
           ["Không nói ‘tôi sẽ để ôn’.", "sẽ + động từ trần."]),
         d([("Ana", "Mai có thi không?", "", "Have you got an exam tomorrow?"),
            ("Luis", "Có, sử. Tan học tôi sẽ ôn.", "", "Yes, history. I'll revise after class."),
            ("Ana", "Học ở thư viện nhé?", "", "Shall we study in the library?"),
            ("Luis", "Được. Hạn ghi chú là hôm nay.", "", "Yes. The notes deadline is today.")])),
        ("Sở thích: thích + động từ.",
         v([("sở thích", "", "hobby"), ("ghita", "", "guitar"), ("đội", "", "team"),
            ("tập", "", "practice"), ("cuối tuần", "", "weekend"),
            ("tham gia", "", "join", "verb"), ("hòa nhạc", "", "concert"), ("vẽ", "", "draw", "verb")]),
         g("thích + động từ", "Thích đi với động từ hoặc danh từ.", "tôi thích chơi ghita",
           [("Tôi thích chơi ghita.", "", "I like playing guitar."),
            ("Cô ấy không thích đợi.", "", "She doesn't like waiting."),
            ("Cuối tuần bạn thích vẽ không?", "", "Do you like drawing at weekends?")],
           ["Không ‘tôi thích để chơi’.", "không thích, không phải chẳng thích luôn."]),
         d([("Asha", "Cuối tuần bạn làm gì?", "", "What do you do at the weekend?"),
            ("Ben", "Chơi ghita. Thứ bảy có hòa nhạc.", "", "I play guitar. There's a concert on Saturday."),
            ("Asha", "Tôi thích vẽ. Đi không?", "", "I like drawing. Are you coming?"),
            ("Ben", "Sau buổi tập.", "", "Yes, after practice.")])),
        ("Vé.",
         v([("sân ga", "", "platform"), ("vé khứ hồi", "", "return ticket"),
            ("trễ", "", "delay"), ("hành lý", "", "luggage"), ("cửa", "", "gate"),
            ("hộ chiếu", "", "passport"), ("đặt", "", "book", "verb"), ("đổi tàu", "", "change trains", "verb")]),
         g("phải + động từ", "Bắt buộc bên ngoài.", "bạn phải đưa hộ chiếu",
           [("Bạn phải đưa hộ chiếu.", "", "You have to show your passport."),
            ("Chúng ta phải đổi tàu ở Huế.", "", "We have to change in Huế."),
            ("Hôm nay không phải đặt.", "", "He doesn't have to book today.")],
           ["phải + động từ.", "không phải ≠ cấm."]),
         d([("Quầy", "Một chiều hay khứ hồi?", "", "Single or return?"),
            ("Nina", "Khứ hồi. Sân ga nào?", "", "Return. Which platform?"),
            ("Quầy", "Số 4. Trễ một chút.", "", "Platform 4. There's a short delay."),
            ("Nina", "Phải đổi tàu không?", "", "Do I have to change?")])),
        ("Nhà hàng.",
         v([("thực đơn", "", "menu"), ("hóa đơn", "", "bill"), ("món khai vị", "", "starter"),
            ("dị ứng", "", "allergic"), ("cay", "", "spicy", "adj"),
            ("gợi ý", "", "recommend"), ("tiền típ", "", "tip"), ("bàn", "", "table")]),
         g("cho tôi / tôi muốn", "Gọi món lịch sự.", "cho tôi món súp",
           [("Cho tôi món súp.", "", "I'd like the soup."),
            ("Cay không?", "", "Would you like it spicy?"),
            ("Cho xem thực đơn.", "", "I'd like to see the menu.")],
           ["Với phục vụ, ‘đưa cái này’ thô.", "cho tôi + danh từ."]),
         d([("Phục vụ", "Gọi món được chưa?", "", "Ready to order?"),
            ("Sam", "Cho tôi mì. Có cay không?", "", "I'd like the pasta. Is it spicy?"),
            ("Phục vụ", "Một chút. Có dị ứng không?", "", "A little. Are you allergic?"),
            ("Sam", "Không. Cuối cùng tính tiền.", "", "No. The bill at the end, please.")])),
        ("Mời.",
         v([("lời mời", "", "invitation"), ("bận", "", "busy", "adj"), ("gặp", "", "catch up", "verb"),
            ("mang", "", "bring", "verb"), ("tiệc", "", "party"), ("rảnh", "", "free", "adj"),
            ("có lẽ", "", "maybe"), ("tuần sau", "", "next week")]),
         g("hay là", "Gợi ý.", "hay là gặp lúc bảy giờ?",
           [("Hay là gặp lúc bảy giờ?", "", "Why don't we meet at seven?"),
            ("Tuần sau gặp nhé?", "", "What if we catch up next week?"),
            ("Mang đồ ăn đi.", "", "Let's bring some food.")],
           ["Chỉ ‘không’ thì cứng: nêu lý do.", "hay là không phải lệnh."]),
         d([("Riya", "Thứ sáu có tiệc. Đi không?", "", "There's a party Friday. Shall we go?"),
            ("Omar", "Thứ sáu bận. Tuần sau?", "", "I'm busy Friday. Next week?"),
            ("Riya", "Chủ nhật? Sau sáu giờ tôi rảnh.", "", "Sunday? I'm free after six."),
            ("Omar", "Được. Tôi mang món ngọt.", "", "Perfect. I'll bring dessert.")])),
        ("Thời tiết: nếu.",
         v([("dự báo", "", "forecast"), ("mưa rào", "", "shower"), ("ẩm", "", "humid", "adj"),
            ("hủy", "", "cancel", "verb"), ("trong nhà", "", "indoor"), ("ô", "", "umbrella"),
            ("độ", "", "degree"), ("tạnh", "", "clear up")]),
         g("nếu + hiện tại", "Điều kiện thật.", "nếu mưa thì chúng ta hủy",
           [("Nếu mưa thì chúng ta hủy dã ngoại.", "", "If it rains, we'll cancel the picnic."),
            ("Nếu dự báo đẹp thì đi bộ.", "", "If the forecast is good, we'll walk."),
            ("Nếu không tạnh thì ở trong nhà.", "", "If it doesn't clear up, we'll stay inside.")],
           ["Đừng chồng sẽ trong mệnh đề nếu.", "thì đưa kết quả."]),
         d([("Jen", "Dự báo bảo mưa rào.", "", "The forecast says showers."),
            ("Kai", "Nếu mưa thì vào bảo tàng.", "", "If it rains, we'll go to the museum."),
            ("Jen", "Vẫn mang ô.", "", "Take an umbrella anyway."),
            ("Kai", "Nếu tạnh thì đi ven sông.", "", "If it clears up, we'll walk by the river.")])),
        ("Mua sắm.",
         v([("cỡ", "", "size"), ("hóa đơn", "", "receipt"), ("hoàn tiền", "", "refund"),
            ("giảm giá", "", "discount"), ("tiền mặt", "", "cash"), ("thẻ", "", "card"),
            ("vừa", "", "fit", "verb"), ("đổi", "", "exchange", "verb")]),
         g("hơn / hơn …", "So sánh.", "áo này rẻ hơn cái kia",
           [("Áo này rẻ hơn cái kia.", "", "This shirt is cheaper than that one."),
            ("Cái xanh đắt hơn.", "", "The blue one is more expensive."),
            ("Cỡ M vừa hơn.", "", "Size M fits better.")],
           ["Không ‘hơn rẻ hơn’.", "hơn đứng sau tính từ."]),
         d([("Cửa hàng", "Thẻ hay tiền mặt?", "", "Card or cash?"),
            ("Lila", "Thẻ. Có cỡ nhỏ hơn không?", "", "Card. Have you got a smaller size?"),
            ("Cửa hàng", "Có. Giữ hóa đơn để hoàn tiền.", "", "Yes. Keep the receipt for a refund."),
            ("Lila", "Có giảm giá sinh viên không?", "", "Is there a student discount?")])),
        ("Thói quen.",
         v([("đi làm", "", "commute", "verb"), ("ca", "", "shift"), ("báo thức", "", "alarm"),
            ("tiết kiệm", "", "save", "verb"), ("mục tiêu", "", "goal"), ("thói quen", "", "habit"),
            ("tháng sau", "", "next month"), ("thường", "", "usually", "adv")]),
         g("thường hiện tại vs sẽ", "Giờ tàu là hiện tại; quyết định là sẽ.", "tôi thường ra lúc bảy giờ",
           [("Tôi thường ra lúc bảy giờ.", "", "I usually leave at seven."),
            ("Tháng sau tôi sẽ tiết kiệm.", "", "I'm going to save next month."),
            ("Ca của tôi bắt đầu lúc chín.", "", "My shift starts at nine.")],
           ["Giờ in sẵn đừng dùng sẽ.", "Đừng trộn hôm qua với sẽ."]),
         d([("Dana", "Thường bắt đầu lúc mấy?", "", "What time do you usually start?"),
            ("Ned", "Chín giờ. Tháng sau tôi sẽ đổi.", "", "The shift starts at nine. I'm going to change it next month."),
            ("Dana", "Sao?", "", "Why?"),
            ("Ned", "Muốn đường đi làm ngắn hơn. Đó là mục tiêu.", "", "I want a shorter commute. That's the goal.")])),
    ]


def _nl():
    return [
        ("Dichtbije plannen: gaan + infinitief.",
         v([("examen", "", "exam"), ("vak", "", "subject"), ("huiswerk", "", "homework"),
            ("rooster", "", "timetable"), ("deadline", "", "deadline"),
            ("herhalen", "", "revise", "verb"), ("college", "", "lecture"), ("aantekeningen", "", "notes")]),
         g("gaan + infinitief", "Een besluit voor vlakbij.", "ik ga vanavond herhalen",
           [("Ik ga vanavond herhalen.", "", "I'm going to revise tonight."),
            ("Zij gaat het college missen.", "", "She's going to miss the lecture."),
            ("Ga je het huiswerk afmaken?", "", "Are you going to finish the homework?")],
           ["Niet ‘ik ga te herhalen’.", "gaan vervoegen, tweede werkwoord blijft infinitief."]),
         d([("Ana", "Heb je morgen een examen?", "", "Have you got an exam tomorrow?"),
            ("Luis", "Ja, geschiedenis. Na de les ga ik herhalen.", "", "Yes, history. I'll revise after class."),
            ("Ana", "Samen in de bibliotheek?", "", "Shall we study in the library?"),
            ("Luis", "Ja. De deadline van de aantekeningen is vandaag.", "", "Yes. The notes deadline is today.")])),
        ("Hobby's: graag + werkwoord.",
         v([("hobby", "", "hobby"), ("gitaar", "", "guitar"), ("team", "", "team"),
            ("training", "", "practice"), ("weekend", "", "weekend"),
            ("meedoen", "", "join", "verb"), ("concert", "", "concert"), ("tekenen", "", "draw", "verb")]),
         g("graag", "Graag staat bij het werkwoord.", "ik speel graag gitaar",
           [("Ik speel graag gitaar.", "", "I like playing guitar."),
            ("Zij wacht niet graag.", "", "She doesn't like waiting."),
            ("Teken je in het weekend graag?", "", "Do you like drawing at weekends?")],
           ["Niet ‘ik graag speel’.", "graag na het vervoegde werkwoord."]),
         d([("Asha", "Wat doe je in het weekend?", "", "What do you do at the weekend?"),
            ("Ben", "Ik speel gitaar. Zaterdag is er een concert.", "", "I play guitar. There's a concert on Saturday."),
            ("Asha", "Ik teken graag. Kom je?", "", "I like drawing. Are you coming?"),
            ("Ben", "Na de training.", "", "Yes, after practice.")])),
        ("Kaartje.",
         v([("perron", "", "platform"), ("retour", "", "return ticket"),
            ("vertraging", "", "delay"), ("bagage", "", "luggage"), ("gate", "", "gate"),
            ("paspoort", "", "passport"), ("boeken", "", "book", "verb"), ("overstappen", "", "change trains", "verb")]),
         g("moeten + infinitief", "Externe plicht.", "je moet je paspoort laten zien",
           [("Je moet je paspoort laten zien.", "", "You have to show your passport."),
            ("We moeten in Utrecht overstappen.", "", "We have to change in Utrecht."),
            ("Hij hoeft vandaag niet te boeken.", "", "He doesn't have to book today.")],
           ["moeten + kale infinitief.", "hoeft niet ≠ mag niet."]),
         d([("Loket", "Enkel of retour?", "", "Single or return?"),
            ("Nina", "Retour. Welk perron?", "", "Return. Which platform?"),
            ("Loket", "Perron 4. Er is een korte vertraging.", "", "Platform 4. There's a short delay."),
            ("Nina", "Moet ik overstappen?", "", "Do I have to change?")])),
        ("Restaurant.",
         v([("menu", "", "menu"), ("rekening", "", "bill"), ("voorgerecht", "", "starter"),
            ("allergisch", "", "allergic", "adj"), ("pittig", "", "spicy", "adj"),
            ("aanraden", "", "recommend", "verb"), ("fooien", "", "tip"), ("tafel", "", "table")]),
         g("ik wil graag", "Beleefde bestelling.", "ik wil graag de soep",
           [("Ik wil graag de soep.", "", "I'd like the soup."),
            ("Mag het pittig?", "", "Would you like it spicy?"),
            ("Mag ik het menu zien?", "", "I'd like to see the menu.")],
           ["‘Geef dit’ is grof tegen de ober.", "graag maakt het beleefd."]),
         d([("Ober", "Mag ik uw bestelling?", "", "Ready to order?"),
            ("Sam", "Ik wil graag de pasta. Is die pittig?", "", "I'd like the pasta. Is it spicy?"),
            ("Ober", "Een beetje. Bent u allergisch?", "", "A little. Are you allergic?"),
            ("Sam", "Nee. De rekening aan het eind, alstublieft.", "", "No. The bill at the end, please.")])),
        ("Uitnodiging.",
         v([("uitnodiging", "", "invitation"), ("bezet", "", "busy", "adj"), ("afspreken", "", "catch up", "verb"),
            ("meenemen", "", "bring", "verb"), ("feest", "", "party"), ("vrij", "", "free", "adj"),
            ("misschien", "", "maybe"), ("volgende week", "", "next week")]),
         g("zullen we / waarom niet", "Voorstel.", "zullen we om zeven uur afspreken?",
           [("Zullen we om zeven uur afspreken?", "", "Why don't we meet at seven?"),
            ("Volgende week dan?", "", "What if we catch up next week?"),
            ("Laten we eten meenemen.", "", "Let's bring some food.")],
           ["Alleen ‘nee’ is hard: geef een reden.", "zullen we is een vraag."]),
         d([("Riya", "Vrijdag is er een feest. Gaan we?", "", "There's a party Friday. Shall we go?"),
            ("Omar", "Vrijdag ben ik bezet. Volgende week?", "", "I'm busy Friday. Next week?"),
            ("Riya", "Zondag? Na zessen ben ik vrij.", "", "Sunday? I'm free after six."),
            ("Omar", "Prima. Ik neem het nagerecht mee.", "", "Perfect. I'll bring dessert.")])),
        ("Weer: als.",
         v([("verwachting", "", "forecast"), ("bui", "", "shower"), ("vochtig", "", "humid", "adj"),
            ("afzeggen", "", "cancel", "verb"), ("binnen", "", "indoor"), ("paraplu", "", "umbrella"),
            ("graad", "", "degree"), ("opklaren", "", "clear up", "verb")]),
         g("als + tegenwoordige tijd", "Echte voorwaarde.", "als het regent, zeggen we af",
           [("Als het regent, zeggen we de picknick af.", "", "If it rains, we'll cancel the picnic."),
            ("Als de verwachting goed is, lopen we.", "", "If the forecast is good, we'll walk."),
            ("Als het niet opklaart, blijven we binnen.", "", "If it doesn't clear up, we'll stay inside.")],
           ["Geen zullen in de als-zin.", "als introduceert de voorwaarde."]),
         d([("Jen", "De verwachting zegt buien.", "", "The forecast says showers."),
            ("Kai", "Als het regent, gaan we naar het museum.", "", "If it rains, we'll go to the museum."),
            ("Jen", "Neem toch een paraplu.", "", "Take an umbrella anyway."),
            ("Kai", "Als het opklaart, lopen we langs de rivier.", "", "If it clears up, we'll walk by the river.")])),
        ("Winkelen.",
         v([("maat", "", "size"), ("bonnetje", "", "receipt"), ("terugbetaling", "", "refund"),
            ("korting", "", "discount"), ("contant", "", "cash"), ("kaart", "", "card"),
            ("passen", "", "fit", "verb"), ("ruilen", "", "exchange", "verb")]),
         g("vergelijkend", "-er dan / meer … dan.", "dit overhemd is goedkoper dan dat",
           [("Dit overhemd is goedkoper dan dat.", "", "This shirt is cheaper than that one."),
            ("De blauwe is duurder.", "", "The blue one is more expensive."),
            ("Maat M past beter.", "", "Size M fits better.")],
           ["Niet ‘meer goedkoper’.", "dan bij ongelijkheid."]),
         d([("Winkel", "Pin of contant?", "", "Card or cash?"),
            ("Lila", "Pin. Heeft u een kleinere maat?", "", "Card. Have you got a smaller size?"),
            ("Winkel", "Ja. Bewaar het bonnetje voor terugbetaling.", "", "Yes. Keep the receipt for a refund."),
            ("Lila", "Is er studentenkaartkorting?", "", "Is there a student discount?")])),
        ("Gewoonte.",
         v([("forenzen", "", "commute", "verb"), ("dienst", "", "shift"), ("wekker", "", "alarm"),
            ("sparen", "", "save", "verb"), ("doel", "", "goal"), ("gewoonte", "", "habit"),
            ("volgende maand", "", "next month"), ("meestal", "", "usually", "adv")]),
         g("meestal + tegenwoordig vs gaan", "Rooster is tegenwoordig; besluit is gaan.", "meestal vertrek ik om zeven",
           [("Meestal vertrek ik om zeven.", "", "I usually leave at seven."),
            ("Volgende maand ga ik sparen.", "", "I'm going to save next month."),
            ("Mijn dienst begint om negen.", "", "My shift starts at nine.")],
           ["Niet gaan gebruiken voor een gedrukt rooster.", "Niet gisteren en gaan mengen."]),
         d([("Dana", "Hoe laat begin je meestal?", "", "What time do you usually start?"),
            ("Ned", "Om negen. Volgende maand ga ik het veranderen.", "", "The shift starts at nine. I'm going to change it next month."),
            ("Dana", "Waarom?", "", "Why?"),
            ("Ned", "Ik wil een kortere reis. Dat is het doel.", "", "I want a shorter commute. That's the goal.")])),
    ]


def _fil():
    return [
        ("Malapit na plano: mag- + -na.",
         v([("pagsusulit", "", "exam"), ("asignatura", "", "subject"), ("takdang-aralin", "", "homework"),
            ("iskedyul", "", "timetable"), ("deadline", "", "deadline"),
            ("magreview", "", "revise", "verb"), ("leksiyon", "", "lecture"), ("notes", "", "notes")]),
         g("mag- + na", "Desisyong malapit.", "magrereview ako mamaya",
           [("Magrereview ako mamaya.", "", "I'm going to revise tonight."),
            ("Mawawalan siya ng leksiyon.", "", "She's going to miss the lecture."),
            ("Tatapusin mo ba ang takdang-aralin?", "", "Are you going to finish the homework?")],
           ["Huwag ‘ako na magreview ng mali ang ayos’.", "Ang aspect ang nagpapakita ng plano."]),
         d([("Ana", "May pagsusulit ka ba bukas?", "", "Have you got an exam tomorrow?"),
            ("Luis", "Oo, kasaysayan. Magrereview ako pagkatapos ng klase.", "", "Yes, history. I'll revise after class."),
            ("Ana", "Sa library tayo mag-aral?", "", "Shall we study in the library?"),
            ("Luis", "Sige. Deadline ng notes ay ngayon.", "", "Yes. The notes deadline is today.")])),
        ("Libangan: gusto + mag-.",
         v([("libangan", "", "hobby"), ("gitara", "", "guitar"), ("koponan", "", "team"),
            ("pagsasanay", "", "practice"), ("linggo", "", "weekend"),
            ("sumali", "", "join", "verb"), ("konsiyerto", "", "concert"), ("magguhit", "", "draw", "verb")]),
         g("gusto + mag-", "Gusto ay sinusundan ng mag- o ng pangngalan.", "gusto kong tumugtog ng gitara",
           [("Gusto kong tumugtog ng gitara.", "", "I like playing guitar."),
            ("Ayaw niyang maghintay.", "", "She doesn't like waiting."),
            ("Gusto mo bang magguhit tuwing linggo?", "", "Do you like drawing at weekends?")],
           ["Huwag ‘ako gusto tumugtog’ nang walang kong.", "gusto ko, ayaw niya."]),
         d([("Asha", "Ano'ng ginagawa mo tuwing linggo?", "", "What do you do at the weekend?"),
            ("Ben", "Tumutugtog ako ng gitara. May konsiyerto sa Sabado.", "", "I play guitar. There's a concert on Saturday."),
            ("Asha", "Gusto kong magguhit. Sasama ka?", "", "I like drawing. Are you coming?"),
            ("Ben", "Pagkatapos ng pagsasanay.", "", "Yes, after practice.")])),
        ("Tiket.",
         v([("plataporma", "", "platform"), ("ticket na pauwi", "", "return ticket"),
            ("delay", "", "delay"), ("bagahe", "", "luggage"), ("gate", "", "gate"),
            ("pasaporte", "", "passport"), ("mag-book", "", "book", "verb"), ("lumipat ng tren", "", "change trains", "verb")]),
         g("kailangan + mag-", "Panlabas na utos.", "kailangan mong ipakita ang pasaporte",
           [("Kailangan mong ipakita ang pasaporte.", "", "You have to show your passport."),
            ("Kailangan nating lumipat sa Tarlac.", "", "We have to change in Tarlac."),
            ("Hindi niya kailangang mag-book ngayon.", "", "He doesn't have to book today.")],
           ["kailangan + ng tao + mag-.", "hindi kailangan ≠ bawal."]),
         d([("Kwelyo", "One-way o pauwi?", "", "Single or return?"),
            ("Nina", "Pauwi. Anong plataporma?", "", "Return. Which platform?"),
            ("Kwelyo", "Apat. May maikling delay.", "", "Platform 4. There's a short delay."),
            ("Nina", "Kailangan bang lumipat?", "", "Do I have to change?")])),
        ("Restawran.",
         v([("menu", "", "menu"), ("bill", "", "bill"), ("pampagana", "", "starter"),
            ("allergy", "", "allergic"), ("maanghang", "", "spicy", "adj"),
            ("magrekomenda", "", "recommend", "verb"), ("tip", "", "tip"), ("mesa", "", "table")]),
         g("pwede po / gusto ko po", "Magalang na order.", "gusto ko po ng sopas",
           [("Gusto ko po ng sopas.", "", "I'd like the soup."),
            ("Gusto n'yo po bang maanghang?", "", "Would you like it spicy?"),
            ("Patingin po ng menu.", "", "I'd like to see the menu.")],
           ["Sa waiter, ‘bigay mo ’to’ ay magaspang.", "po nagpapagalang."]),
         d([("Waiter", "Pwede na po bang umorder?", "", "Ready to order?"),
            ("Sam", "Pasta po. Maanghang ba?", "", "I'd like the pasta. Is it spicy?"),
            ("Waiter", "Konti. May allergy po ba?", "", "A little. Are you allergic?"),
            ("Sam", "Wala. Sa dulo na po ang bill.", "", "No. The bill at the end, please.")])),
        ("Anyaya.",
         v([("anyaya", "", "invitation"), ("abala", "", "busy", "adj"), ("magkita", "", "catch up", "verb"),
            ("magdala", "", "bring", "verb"), ("party", "", "party"), ("libre", "", "free", "adj"),
            ("baka", "", "maybe"), ("sa susunod na linggo", "", "next week")]),
         g("baka / tayo", "Mungkahi.", "magkita tayo nang alas-siyete?",
           [("Magkita tayo nang alas-siyete?", "", "Why don't we meet at seven?"),
            ("Sa susunod na linggo na lang?", "", "What if we catch up next week?"),
            ("Magdala tayo ng pagkain.", "", "Let's bring some food.")],
           ["Ang ‘hindi’ lang ay matigas: magbigay ng dahilan.", "tayo ay sama-sama, hindi utos."]),
         d([("Riya", "May party sa Biyernes. Punta tayo?", "", "There's a party Friday. Shall we go?"),
            ("Omar", "Abala ako sa Biyernes. Sa susunod na linggo?", "", "I'm busy Friday. Next week?"),
            ("Riya", "Linggo? Libre ako pagkatapos ng alas-sais.", "", "Sunday? I'm free after six."),
            ("Omar", "Sige. Ako ang magdadala ng panghimagas.", "", "Perfect. I'll bring dessert.")])),
        ("Panahon: kung.",
         v([("taya", "", "forecast"), ("ambon", "", "shower"), ("mahalumigmig", "", "humid", "adj"),
            ("kanselahin", "", "cancel", "verb"), ("sa loob", "", "indoor"), ("payong", "", "umbrella"),
            ("degree", "", "degree"), ("lumilinaw", "", "clear up", "verb")]),
         g("kung + aspect", "Totoong kundisyon.", "kung umulan, kakanselahin namin",
           [("Kung umulan, kakanselahin namin ang picnic.", "", "If it rains, we'll cancel the picnic."),
            ("Kung maganda ang taya, maglalakad kami.", "", "If the forecast is good, we'll walk."),
            ("Kung hindi lumilinaw, sa loob kami.", "", "If it doesn't clear up, we'll stay inside.")],
           ["Huwag magpatong ng dalawang future sa kung.", "kung ang kundisyon."]),
         d([("Jen", "Uulan daw ayon sa taya.", "", "The forecast says showers."),
            ("Kai", "Kung umulan, sa museo tayo.", "", "If it rains, we'll go to the museum."),
            ("Jen", "Magdala pa rin ng payong.", "", "Take an umbrella anyway."),
            ("Kai", "Kung lumininaw, maglakad tayo sa ilog.", "", "If it clears up, we'll walk by the river.")])),
        ("Pamimili.",
         v([("sukat", "", "size"), ("resibo", "", "receipt"), ("refund", "", "refund"),
            ("diskwento", "", "discount"), ("cash", "", "cash"), ("kard", "", "card"),
            ("kasya", "", "fit", "verb"), ("palitan", "", "exchange", "verb")]),
         g("mas … kaysa", "Paghahambing.", "mas mura ang damit na ito kaysa doon",
           [("Mas mura ang damit na ito kaysa doon.", "", "This shirt is cheaper than that one."),
            ("Mas mahal ang asul.", "", "The blue one is more expensive."),
            ("Mas kasya ang size M.", "", "Size M fits better.")],
           ["Huwag ‘mas mas mura’.", "kaysa ang ikalawang panig."]),
         d([("Tindahan", "Kard o cash?", "", "Card or cash?"),
            ("Lila", "Kard. May mas maliit na sukat?", "", "Card. Have you got a smaller size?"),
            ("Tindahan", "Meron. Itago ang resibo para sa refund.", "", "Yes. Keep the receipt for a refund."),
            ("Lila", "May student discount ba?", "", "Is there a student discount?")])),
        ("Gawi.",
         v([("byahe", "", "commute"), ("shift", "", "shift"), ("alarm", "", "alarm"),
            ("mag-ipon", "", "save", "verb"), ("layunin", "", "goal"), ("ugali", "", "habit"),
            ("sa susunod na buwan", "", "next month"), ("madalas", "", "usually", "adv")]),
         g("madalas + kasalukuyan vs mag-", "Ang oras ay kasalukuyan; ang desisyon ay mag-.", "madalas akong umalis nang alas-siyete",
           [("Madalas akong umalis nang alas-siyete.", "", "I usually leave at seven."),
            ("Sa susunod na buwan, mag-iipon ako.", "", "I'm going to save next month."),
            ("Nagsisimula ang shift ko nang alas-nuwebe.", "", "My shift starts at nine.")],
           ["Huwag gamitin ang mag- sa nakaimprentang oras.", "Huwag ihalo ang kahapon sa mag-."]),
         d([("Dana", "Anong oras ka madalas nagsisimula?", "", "What time do you usually start?"),
            ("Ned", "Alas-nuwebe. Papalitan ko sa susunod na buwan.", "", "The shift starts at nine. I'm going to change it next month."),
            ("Dana", "Bakit?", "", "Why?"),
            ("Ned", "Gusto ko ng mas maikling byahe. ’Yan ang layunin.", "", "I want a shorter commute. That's the goal.")])),
    ]


DATA = {"vi": _vi(), "nl": _nl(), "fil": _fil()}
