#!/usr/bin/env python3
"""A3 packs: zh ru ko ur bn ta tr vi id pl nl."""
from tools.lib.extended_banks import _add
from tools.lib.bank_builder import build_a3, v, g, d


def register():
    for code, rows in DATA.items():
        _add(code, "A3", build_a3(rows))


def _zh():
    return [
        ("用“要／打算”谈考试和近计划。",
         v([("考试", "kǎoshì", "exam"), ("科目", "kēmù", "subject"), ("作业", "zuòyè", "homework"),
            ("课程表", "kèchéngbiǎo", "timetable"), ("截止日期", "jiézhǐ rìqī", "deadline"),
            ("复习", "fùxí", "revise", "verb"), ("课", "kè", "lecture"), ("笔记", "bǐjì", "notes")]),
         g("要／打算 + 动词", "已经决定的近计划用要或打算，后面直接跟动词。", "我今晚要复习",
           [("我今晚要复习。", "wǒ jīnwǎn yào fùxí", "I'm going to revise tonight."),
            ("她要缺那堂课。", "tā yào quē nà táng kè", "She's going to miss the lecture."),
            ("你打算写完作业吗？", "nǐ dǎsuàn xiě wán zuòyè ma?", "Are you going to finish the homework?")],
           ["不要说“我要了复习”。", "打算后面仍是动词，不加“的”。"]),
         d([("安娜", "你明天有考试吗？", "nǐ míngtiān yǒu kǎoshì ma?", "Have you got an exam tomorrow?"),
            ("路易斯", "有，历史。下了课我要复习。", "yǒu, lìshǐ. xià le kè wǒ yào fùxí.", "Yes, history. I'll revise after class."),
            ("安娜", "去图书馆一起看？", "qù túshūguǎn yìqǐ kàn?", "Shall we study in the library?"),
            ("路易斯", "好。笔记的截止日期是今天。", "hǎo. bǐjì de jiézhǐ rìqī shì jīntiān.", "Yes. The notes deadline is today.")])),
        ("爱好：喜欢 + 动词。",
         v([("爱好", "àihào", "hobby"), ("吉他", "jítā", "guitar"), ("队", "duì", "team"),
            ("练习", "liànxí", "practice"), ("周末", "zhōumò", "weekend"),
            ("加入", "jiārù", "join", "verb"), ("音乐会", "yīnyuèhuì", "concert"), ("画画", "huàhuà", "draw", "verb")]),
         g("喜欢 + 动词", "喜欢后面直接跟动词或名词。", "我喜欢弹吉他",
           [("我喜欢弹吉他。", "wǒ xǐhuan tán jítā", "I like playing guitar."),
            ("她不喜欢等。", "tā bù xǐhuan děng", "She doesn't like waiting."),
            ("你周末喜欢画画吗？", "nǐ zhōumò xǐhuan huàhuà ma?", "Do you like drawing at weekends?")],
           ["不要说“我喜欢的弹”。", "否定是不喜欢，不是没喜欢。"]),
         d([("阿莎", "周末你做什么？", "zhōumò nǐ zuò shénme?", "What do you do at the weekend?"),
            ("本", "弹吉他。周六有音乐会。", "tán jítā. zhōuliù yǒu yīnyuèhuì.", "I play guitar. There's a concert on Saturday."),
            ("阿莎", "我喜欢画画。你来吗？", "wǒ xǐhuan huàhuà. nǐ lái ma?", "I like drawing. Are you coming?"),
            ("本", "练习完就来。", "liànxí wán jiù lái.", "Yes, after practice.")])),
        ("车票、站台、晚点。",
         v([("站台", "zhàntái", "platform"), ("往返票", "wǎngfǎn piào", "return ticket"),
            ("晚点", "wǎndiǎn", "delay"), ("行李", "xíngli", "luggage"), ("登机口", "dēngjīkǒu", "gate"),
            ("护照", "hùzhào", "passport"), ("订", "dìng", "book", "verb"), ("换乘", "huànchéng", "change trains", "verb")]),
         g("得 + 动词", "外部规定用得。", "你得出示护照",
           [("你得出示护照。", "nǐ děi chūshì hùzhào", "You have to show your passport."),
            ("我们得在南京换乘。", "wǒmen děi zài Nánjīng huànchéng", "We have to change in Nanjing."),
            ("他今天不用订。", "tā jīntiān bú yòng dìng", "He doesn't have to book today.")],
           ["得后面是动词，不是“得了出示”。", "不用 = 没有必要，不是禁止。"]),
         d([("窗口", "单程还是往返？", "dānchéng háishì wǎngfǎn?", "Single or return?"),
            ("妮娜", "往返。几号站台？", "wǎngfǎn. jǐ hào zhàntái?", "Return. Which platform?"),
            ("窗口", "四号。有点晚点。", "sì hào. yǒudiǎn wǎndiǎn.", "Platform 4. There's a short delay."),
            ("妮娜", "我得换乘吗？", "wǒ děi huànchéng ma?", "Do I have to change?")])),
        ("点菜和过敏。",
         v([("菜单", "càidān", "menu"), ("账单", "zhàngdān", "bill"), ("前菜", "qiáncài", "starter"),
            ("过敏", "guòmǐn", "allergic"), ("辣", "là", "spicy", "adj"),
            ("推荐", "tuījiàn", "recommend", "verb"), ("小费", "xiǎofèi", "tip"), ("桌子", "zhuōzi", "table")]),
         g("我想要／请给我", "客气点菜。", "我想要汤",
           [("我想要汤。", "wǒ xiǎng yào tāng", "I'd like the soup."),
            ("要辣的吗？", "yào là de ma?", "Would you like it spicy?"),
            ("请给我菜单。", "qǐng gěi wǒ càidān", "I'd like to see the menu.")],
           ["对服务员不要只说“给我这个”。", "想要后面是名词或动词。"]),
         d([("服务员", "可以点了吗？", "kěyǐ diǎn le ma?", "Ready to order?"),
            ("山姆", "我要面条。辣吗？", "wǒ yào miàntiáo. là ma?", "I'd like the pasta. Is it spicy?"),
            ("服务员", "一点点。您过敏吗？", "yìdiǎndiǎn. nín guòmǐn ma?", "A little. Are you allergic?"),
            ("山姆", "不。最后再结账。", "bù. zuìhòu zài jiézhàng.", "No. The bill at the end, please.")])),
        ("邀请和礼貌拒绝。",
         v([("邀请", "yāoqǐng", "invitation"), ("忙", "máng", "busy", "adj"), ("见面", "jiànmiàn", "catch up", "verb"),
            ("带", "dài", "bring", "verb"), ("聚会", "jùhuì", "party"), ("有空", "yǒu kòng", "free"),
            ("也许", "yěxǔ", "maybe"), ("下周", "xià zhōu", "next week")]),
         g("要不／不如", "建议，不是命令。", "要不七点见？",
           [("要不七点见？", "yàobù qī diǎn jiàn?", "Why don't we meet at seven?"),
            ("不如下周再聚？", "bùrú xià zhōu zài jù?", "What if we catch up next week?"),
            ("我们带点吃的吧。", "wǒmen dài diǎn chī de ba", "Let's bring some food.")],
           ["只说“不”很硬：要给理由。", "吧 把建议说软。"]),
         d([("丽雅", "周五有聚会。去吗？", "zhōuwǔ yǒu jùhuì. qù ma?", "There's a party Friday. Shall we go?"),
            ("奥马尔", "周五忙。下周？", "zhōuwǔ máng. xià zhōu?", "I'm busy Friday. Next week?"),
            ("丽雅", "周日？六点后我有空。", "zhōurì? liù diǎn hòu wǒ yǒu kòng.", "Sunday? I'm free after six."),
            ("奥马尔", "好。甜点我带。", "hǎo. tiándiǎn wǒ dài.", "Perfect. I'll bring dessert.")])),
        ("天气和如果。",
         v([("预报", "yùbào", "forecast"), ("阵雨", "zhènyǔ", "shower"), ("潮湿", "cháoshī", "humid", "adj"),
            ("取消", "qǔxiāo", "cancel", "verb"), ("室内", "shìnèi", "indoor"), ("伞", "sǎn", "umbrella"),
            ("度", "dù", "degree"), ("转晴", "zhuǎn qíng", "clear up", "verb")]),
         g("如果 + 现在，就…", "真实条件。", "如果下雨，我们就取消",
           [("如果下雨，我们就取消野餐。", "rúguǒ xià yǔ, wǒmen jiù qǔxiāo yěcān", "If it rains, we'll cancel the picnic."),
            ("如果预报好，我们就走路。", "rúguǒ yùbào hǎo, wǒmen jiù zǒulù", "If the forecast is good, we'll walk."),
            ("如果不转晴，我们就待在室内。", "rúguǒ bù zhuǎn qíng, wǒmen jiù dāi zài shìnèi", "If it doesn't clear up, we'll stay inside.")],
           ["如果句里不要再堆一个“会要是”。", "就 引出结果。"]),
         d([("珍", "预报说有阵雨。", "yùbào shuō yǒu zhènyǔ.", "The forecast says showers."),
            ("凯", "如果下雨，我们去博物馆。", "rúguǒ xià yǔ, wǒmen qù bówùguǎn.", "If it rains, we'll go to the museum."),
            ("珍", "还是带伞。", "háishì dài sǎn.", "Take an umbrella anyway."),
            ("凯", "如果转晴，我们沿河走。", "rúguǒ zhuǎn qíng, wǒmen yán hé zǒu.", "If it clears up, we'll walk by the river.")])),
        ("购物比较。",
         v([("尺码", "chǐmǎ", "size"), ("收据", "shōujù", "receipt"), ("退款", "tuìkuǎn", "refund"),
            ("折扣", "zhékòu", "discount"), ("现金", "xiànjīn", "cash"), ("卡", "kǎ", "card"),
            ("合身", "héshēn", "fit", "verb"), ("换", "huàn", "exchange", "verb")]),
         g("比", "A 比 B + 形容词。", "这件比那件便宜",
           [("这件衬衫比那件便宜。", "zhè jiàn chènshān bǐ nà jiàn piányi", "This shirt is cheaper than that one."),
            ("蓝色的更贵。", "lánsè de gèng guì", "The blue one is more expensive."),
            ("M码更合身。", "M mǎ gèng héshēn", "Size M fits better.")],
           ["不要说“更比较便宜”。", "比 的后面是比较对象。"]),
         d([("店员", "刷卡还是现金？", "shuākǎ háishì xiànjīn?", "Card or cash?"),
            ("莉拉", "刷卡。有小一号吗？", "shuākǎ. yǒu xiǎo yí hào ma?", "Card. Have you got a smaller size?"),
            ("店员", "有。退款请留收据。", "yǒu. tuìkuǎn qǐng liú shōujù.", "Yes. Keep the receipt for a refund."),
            ("莉拉", "有学生折扣吗？", "yǒu xuéshēng zhékòu ma?", "Is there a student discount?")])),
        ("习惯和打算。",
         v([("通勤", "tōngqín", "commute", "verb"), ("班", "bān", "shift"), ("闹钟", "nàozhōng", "alarm"),
            ("存", "cún", "save", "verb"), ("目标", "mùbiāo", "goal"), ("习惯", "xíguàn", "habit"),
            ("下个月", "xià ge yuè", "next month"), ("一般", "yìbān", "usually", "adv")]),
         g("一般 + 现在 vs 打算", "时刻表用现在；决定用打算／要。", "我一般七点出门",
           [("我一般七点出门。", "wǒ yìbān qī diǎn chūmén", "I usually leave at seven."),
            ("下个月我打算存钱。", "xià ge yuè wǒ dǎsuàn cún qián", "I'm going to save next month."),
            ("我的班九点开始。", "wǒ de bān jiǔ diǎn kāishǐ", "My shift starts at nine.")],
           ["印好的时刻表不要用打算。", "不要把昨天和打算混在一句。"]),
         d([("达娜", "你一般几点开始？", "nǐ yìbān jǐ diǎn kāishǐ?", "What time do you usually start?"),
            ("内德", "班九点。下个月我打算改。", "bān jiǔ diǎn. xià ge yuè wǒ dǎsuàn gǎi.", "The shift starts at nine. I'm going to change it next month."),
            ("达娜", "为什么？", "wèishénme?", "Why?"),
            ("内德", "想通勤短一点。这就是目标。", "xiǎng tōngqín duǎn yìdiǎn. zhè jiù shì mùbiāo.", "I want a shorter commute. That's the goal.")])),
    ]


def _ru():
    return [
        ("Собираться + инфинитив: планы и экзамен.",
         v([("экзамен", "ekzamen", "exam"), ("предмет", "predmet", "subject"), ("домашнее задание", "domashneye zadaniye", "homework"),
            ("расписание", "raspisaniye", "timetable"), ("срок", "srok", "deadline"),
            ("повторять", "povtoryat'", "revise", "verb"), ("лекция", "lektsiya", "lecture"), ("конспект", "konspekt", "notes")]),
         g("собираться + инфинитив", "Близкий план: я собираюсь + глагол.", "я собираюсь повторять",
           [("Я собираюсь повторять вечером.", "ya sobirayus' povtoryat' vecherom", "I'm going to revise tonight."),
            ("Она собирается пропустить лекцию.", "ona sobirayetsya propustit' lektsiyu", "She's going to miss the lecture."),
            ("Ты собираешься закончить задание?", "ty sobirayesh'sya zakonchit' zadaniye?", "Are you going to finish the homework?")],
           ["Не говорите «я собираюсь чтобы повторять».", "После собираться — инфинитив."]),
         d([("Ана", "У тебя завтра экзамен?", "u tebya zavtra ekzamen?", "Have you got an exam tomorrow?"),
            ("Луис", "Да, история. После пары буду повторять.", "da, istoriya. posle pary budu povtoryat'.", "Yes, history. I'll revise after class."),
            ("Ана", "В библиотеке позанимаемся?", "v biblioteke pozanimayemsya?", "Shall we study in the library?"),
            ("Луис", "Да. Срок конспекта — сегодня.", "da. srok konspekta — segodnya.", "Yes. The notes deadline is today.")])),
        ("Любить + инфинитив.",
         v([("хобби", "khobbi", "hobby"), ("гитара", "gitara", "guitar"), ("команда", "komanda", "team"),
            ("тренировка", "trenirovka", "practice"), ("выходные", "vykhodnyye", "weekend"),
            ("вступить", "vstupit'", "join", "verb"), ("концерт", "kontsert", "concert"), ("рисовать", "risovat'", "draw", "verb")]),
         g("любить + инфинитив", "После любить — инфинитив или существительное.", "я люблю играть на гитаре",
           [("Я люблю играть на гитаре.", "ya lyublyu igrat' na gitare", "I like playing guitar."),
            ("Ей не нравится ждать.", "yey ne nravitsya zhdat'", "She doesn't like waiting."),
            ("Ты любишь рисовать на выходных?", "ty lyubish' risovat' na vykhodnykh?", "Do you like drawing at weekends?")],
           ["Не «я люблю чтобы играть».", "играть на + инструмент."]),
         d([("Аша", "Что ты делаешь на выходных?", "chto ty delayesh' na vykhodnykh?", "What do you do at the weekend?"),
            ("Бен", "Играю на гитаре. В субботу концерт.", "igrayu na gitare. v subbotu kontsert.", "I play guitar. There's a concert on Saturday."),
            ("Аша", "Люблю рисовать. Пойдёшь?", "lyublyu risovat'. poydyosh'?", "I like drawing. Are you coming?"),
            ("Бен", "Да, после тренировки.", "da, posle trenirovki.", "Yes, after practice.")])),
        ("Билет и путь.",
         v([("платформа", "platforma", "platform"), ("билет туда и обратно", "bilet tuda i obratno", "return ticket"),
            ("задержка", "zaderzhka", "delay"), ("багаж", "bagazh", "luggage"), ("выход", "vykhod", "gate"),
            ("паспорт", "pasport", "passport"), ("бронировать", "bronirovat'", "book", "verb"), ("пересадка", "peresadka", "change trains")]),
         g("нужно / должен", "Внешняя необходимость.", "тебе нужно показать паспорт",
           [("Тебе нужно показать паспорт.", "tebe nuzhno pokazat' pasport", "You have to show your passport."),
            ("Нам нужна пересадка в Казани.", "nam nuzhna peresadka v Kazani", "We have to change in Kazan."),
            ("Ему сегодня не нужно бронировать.", "yemu segodnya ne nuzhno bronirovat'", "He doesn't have to book today.")],
           ["Нужно + инфинитив.", "Не путайте не нужно и нельзя."]),
         d([("Касса", "В одну сторону или туда и обратно?", "v odnu storonu ili tuda i obratno?", "Single or return?"),
            ("Нина", "Туда и обратно. Какая платформа?", "tuda i obratno. kakaya platforma?", "Return. Which platform?"),
            ("Касса", "Четвёртая. Небольшая задержка.", "chetvyortaya. nebol'shaya zaderzhka.", "Platform 4. There's a short delay."),
            ("Нина", "Нужна пересадка?", "nuzhna peresadka?", "Do I have to change?")])),
        ("Ресторан.",
         v([("меню", "menyu", "menu"), ("счёт", "schyot", "bill"), ("закуска", "zakuska", "starter"),
            ("аллергия", "allergiya", "allergic"), ("острый", "ostryy", "spicy", "adj"),
            ("советовать", "sovetovat'", "recommend", "verb"), ("чаевые", "chayevyye", "tip"), ("стол", "stol", "table")]),
         g("я бы хотел(а)", "Вежливый заказ.", "я бы хотел суп",
           [("Я бы хотел суп.", "ya by khotel sup", "I'd like the soup."),
            ("Сделать острым?", "sdelat' ostrym?", "Would you like it spicy?"),
            ("Можно меню?", "mozhno menyu?", "I'd like to see the menu.")],
           ["«Дай это» грубо официанту.", "бы хотел + существительное."]),
         d([("Официант", "Вы готовы заказать?", "vy gotovy zakazat'?", "Ready to order?"),
            ("Сэм", "Я бы хотел пасту. Она острая?", "ya by khotel pastu. ona ostraya?", "I'd like the pasta. Is it spicy?"),
            ("Официант", "Немного. Есть аллергия?", "nemnogo. yest' allergiya?", "A little. Are you allergic?"),
            ("Сэм", "Нет. Счёт в конце, пожалуйста.", "net. schyot v kontse, pozhaluysta.", "No. The bill at the end, please.")])),
        ("Приглашение.",
         v([("приглашение", "priglasheniye", "invitation"), ("занят", "zanyat", "busy", "adj"), ("встретиться", "vstretit'sya", "catch up", "verb"),
            ("принести", "prinesti", "bring", "verb"), ("вечеринка", "vecherinka", "party"), ("свободен", "svoboden", "free", "adj"),
            ("может быть", "mozhet byt'", "maybe"), ("на следующей неделе", "na sleduyushchey nedele", "next week")]),
         g("давай / не + ли", "Предложение.", "давай встретимся в семь",
           [("Давай встретимся в семь.", "davay vstretimsya v sem'", "Shall we meet at seven?"),
            ("Может, на следующей неделе?", "mozhet, na sleduyushchey nedele?", "What if we catch up next week?"),
            ("Давай принесём еду.", "davay prinesyom yedu", "Let's bring some food.")],
           ["Голое «нет» резко: дайте причину.", "давай + глагол в 1 л. мн."]),
         d([("Рия", "В пятницу вечеринка. Пойдём?", "v pyatnitsu vecherinka. poydyom?", "There's a party Friday. Shall we go?"),
            ("Омар", "В пятницу занят. На следующей неделе?", "v pyatnitsu zanyat. na sleduyushchey nedele?", "I'm busy Friday. Next week?"),
            ("Рия", "В воскресенье? После шести свободна.", "v voskresen'ye? posle shesti svobodna.", "Sunday? I'm free after six."),
            ("Омар", "Отлично. Десерт принесу я.", "otlichno. desert prinesu ya.", "Perfect. I'll bring dessert.")])),
        ("Погода: если.",
         v([("прогноз", "prognoz", "forecast"), ("ливень", "liven'", "shower"), ("влажный", "vlazhnyy", "humid", "adj"),
            ("отменить", "otmenit'", "cancel", "verb"), ("в помещении", "v pomeshchenii", "indoor"), ("зонт", "zont", "umbrella"),
            ("градус", "gradus", "degree"), ("проясниться", "proyasnit'sya", "clear up", "verb")]),
         g("если + наст., то будущее", "Реальное условие.", "если пойдёт дождь, мы отменим",
           [("Если пойдёт дождь, мы отменим пикник.", "yesli poydyot dozhd', my otmenim piknik", "If it rains, we'll cancel the picnic."),
            ("Если прогноз хороший, пойдём пешком.", "yesli prognoz khoroshiy, poydyom peshkom", "If the forecast is good, we'll walk."),
            ("Если не прояснится, останемся внутри.", "yesli ne proyasnitsya, ostanemsya vnutri", "If it doesn't clear up, we'll stay inside.")],
           ["В если не ставьте чистое будущее без нужды.", "то можно опустить."]),
         d([("Джен", "Прогноз обещает ливень.", "prognoz obeshchayet liven'.", "The forecast says showers."),
            ("Кай", "Если дождь — в музей.", "yesli dozhd' — v muzey.", "If it rains, we'll go to the museum."),
            ("Джен", "Зонт всё равно возьми.", "zont vsyo ravno voz'mi.", "Take an umbrella anyway."),
            ("Кай", "Если прояснится — вдоль реки.", "yesli proyasnitsya — vdol' reki.", "If it clears up, we'll walk by the river.")])),
        ("Магазин.",
         v([("размер", "razmer", "size"), ("чек", "chek", "receipt"), ("возврат", "vozvrat", "refund"),
            ("скидка", "skidka", "discount"), ("наличные", "nalichnyye", "cash"), ("карта", "karta", "card"),
            ("сидеть", "sidet'", "fit", "verb"), ("обменять", "obmenyat'", "exchange", "verb")]),
         g("сравнительная степень", "дешевле / более + прил.", "эта рубашка дешевле той",
           [("Эта рубашка дешевле той.", "eta rubashka deshevle toy", "This shirt is cheaper than that one."),
            ("Синяя дороже.", "sinyaya dorozhe", "The blue one is more expensive."),
            ("Размер M сидит лучше.", "razmer M sidit luchshe", "Size M fits better.")],
           ["Не «более дешевле».", "чем вводит второй член."]),
         d([("Магазин", "Картой или наличными?", "kartoy ili nalichnymi?", "Card or cash?"),
            ("Лила", "Картой. Есть размер меньше?", "kartoy. yest' razmer men'she?", "Card. Have you got a smaller size?"),
            ("Магазин", "Да. Чек сохраните для возврата.", "da. chek sokhranite dlya vozvrata.", "Yes. Keep the receipt for a refund."),
            ("Лила", "Есть студенческая скидка?", "yest' studencheskaya skidka?", "Is there a student discount?")])),
        ("Привычка и план.",
         v([("ездить на работу", "yezdit' na rabotu", "commute", "verb"), ("смена", "smena", "shift"), ("будильник", "budil'nik", "alarm"),
            ("копить", "kopit'", "save", "verb"), ("цель", "tsel'", "goal"), ("привычка", "privychka", "habit"),
            ("в следующем месяце", "v sleduyushchem mesyatse", "next month"), ("обычно", "obychno", "usually", "adv")]),
         g("обычно + наст. vs собираться", "Расписание — настоящее; решение — собираться.", "обычно я выхожу в семь",
           [("Обычно я выхожу в семь.", "obychno ya vykhozhu v sem'", "I usually leave at seven."),
            ("В следующем месяце собираюсь копить.", "v sleduyushchem mesyatse sobirayus' kopit'", "I'm going to save next month."),
            ("Смена начинается в девять.", "smena nachinayetsya v devyat'", "My shift starts at nine.")],
           ["Не используйте собираться для печатного расписания.", "Не мешайте вчера и собираюсь."]),
         d([("Дана", "Во сколько ты обычно начинаешь?", "vo skol'ko ty obychno nachinayesh'?", "What time do you usually start?"),
            ("Нед", "Смена в девять. В следующем месяце поменяю.", "smena v devyat'. v sleduyushchem mesyatse pomenyayu.", "The shift starts at nine. I'm going to change it next month."),
            ("Дана", "Почему?", "pochemu?", "Why?"),
            ("Нед", "Хочу короче дорогу. Это цель.", "khochu koroche dorogu. eto tsel'.", "I want a shorter commute. That's the goal.")])),
    ]


DATA = {"zh": _zh(), "ru": _ru()}
