#!/usr/bin/env python3
"""A3 packs: pl zsm af ca el fa sw uk ro."""
from tools.lib.extended_banks import _add
from tools.lib.bank_builder import build_a3, v, g, d


def register():
    for code, rows in DATA.items():
        _add(code, "A3", build_a3(rows))


def eight(lessons):
    if len(lessons) != 8:
        raise ValueError(len(lessons))
    return lessons


def _pl():
    return eight([
        ("Bliskie plany: zbierać się / będę.",
         v([("egzamin", "", "exam"), ("przedmiot", "", "subject"), ("praca domowa", "", "homework"),
            ("plan lekcji", "", "timetable"), ("termin", "", "deadline"),
            ("powtarzać", "", "revise", "verb"), ("wykład", "", "lecture"), ("notatki", "", "notes")]),
         g("będę + bezokolicznik", "Bliska decyzja.", "wieczorem będę powtarzać",
           [("Wieczorem będę powtarzać.", "", "I'm going to revise tonight."),
            ("Ona opuści wykład.", "", "She's going to miss the lecture."),
            ("Skończysz pracę domową?", "", "Are you going to finish the homework?")],
           ["Nie mów ‘będę żeby powtarzać’.", "Po będę — bezokolicznik."]),
         d([("Ana", "Masz jutro egzamin?", "", "Have you got an exam tomorrow?"),
            ("Luis", "Tak, historię. Po zajęciach będę powtarzać.", "", "Yes, history. I'll revise after class."),
            ("Ana", "Uczymy się w bibliotece?", "", "Shall we study in the library?"),
            ("Luis", "Tak. Termin notatek jest dziś.", "", "Yes. The notes deadline is today.")])),
        ("Hobby: lubić + bezokolicznik.",
         v([("hobby", "", "hobby"), ("gitara", "", "guitar"), ("drużyna", "", "team"),
            ("trening", "", "practice"), ("weekend", "", "weekend"),
            ("dołączyć", "", "join", "verb"), ("koncert", "", "concert"), ("rysować", "", "draw", "verb")]),
         g("lubić + bezokolicznik", "Po lubić — bezokolicznik albo rzeczownik.", "lubię grać na gitarze",
           [("Lubię grać na gitarze.", "", "I like playing guitar."),
            ("Ona nie lubi czekać.", "", "She doesn't like waiting."),
            ("Lubisz rysować w weekend?", "", "Do you like drawing at weekends?")],
           ["Nie ‘ja lubię żeby grać’.", "grać na + instrument."]),
         d([("Asha", "Co robisz w weekend?", "", "What do you do at the weekend?"),
            ("Ben", "Gram na gitarze. W sobotę jest koncert.", "", "I play guitar. There's a concert on Saturday."),
            ("Asha", "Lubię rysować. Przyjdziesz?", "", "I like drawing. Are you coming?"),
            ("Ben", "Po treningu.", "", "Yes, after practice.")])),
        ("Bilet.",
         v([("peron", "", "platform"), ("bilet powrotny", "", "return ticket"),
            ("opóźnienie", "", "delay"), ("bagaż", "", "luggage"), ("bramka", "", "gate"),
            ("paszport", "", "passport"), ("rezerwować", "", "book", "verb"), ("przesiadka", "", "change trains")]),
         g("musieć / trzeba", "Zewnętrzny obowiązek.", "musisz pokazać paszport",
           [("Musisz pokazać paszport.", "", "You have to show your passport."),
            ("Musimy się przesiąść w Poznaniu.", "", "We have to change in Poznań."),
            ("On nie musi dziś rezerwować.", "", "He doesn't have to book today.")],
           ["musieć + bezokolicznik.", "nie musi ≠ nie wolno."]),
         d([("Kasa", "W jedną stronę czy powrotny?", "", "Single or return?"),
            ("Nina", "Powrotny. Który peron?", "", "Return. Which platform?"),
            ("Kasa", "Czwarty. Krótkie opóźnienie.", "", "Platform 4. There's a short delay."),
            ("Nina", "Muszę się przesiąść?", "", "Do I have to change?")])),
        ("Restauracja.",
         v([("karta", "", "menu"), ("rachunek", "", "bill"), ("przystawka", "", "starter"),
            ("alergia", "", "allergic"), ("ostry", "", "spicy", "adj"),
            ("polecać", "", "recommend", "verb"), ("napiwek", "", "tip"), ("stolik", "", "table")]),
         g("poproszę", "Grzeczne zamówienie.", "poproszę zupę",
           [("Poproszę zupę.", "", "I'd like the soup."),
            ("Ostro?", "", "Would you like it spicy?"),
            ("Poproszę kartę.", "", "I'd like to see the menu.")],
           ["Kelnerowi ‘daj to’ brzmi ostro.", "poproszę + rzeczownik."]),
         d([("Kelner", "Mogę przyjąć zamówienie?", "", "Ready to order?"),
            ("Sam", "Poproszę makaron. Jest ostry?", "", "I'd like the pasta. Is it spicy?"),
            ("Kelner", "Trochę. Ma pan alergię?", "", "A little. Are you allergic?"),
            ("Sam", "Nie. Rachunek na końcu, proszę.", "", "No. The bill at the end, please.")])),
        ("Zaproszenie.",
         v([("zaproszenie", "", "invitation"), ("zajęty", "", "busy", "adj"), ("spotkać się", "", "catch up", "verb"),
            ("przynieść", "", "bring", "verb"), ("impreza", "", "party"), ("wolny", "", "free", "adj"),
            ("może", "", "maybe"), ("w przyszłym tygodniu", "", "next week")]),
         g("może / chodźmy", "Propozycja.", "może spotkamy się o siódmej?",
           [("Może spotkamy się o siódmej?", "", "Why don't we meet at seven?"),
            ("W przyszłym tygodniu?", "", "What if we catch up next week?"),
            ("Przynieśmy jedzenie.", "", "Let's bring some food.")],
           ["Samo ‘nie’ jest twarde: podaj powód.", "chodźmy to nie rozkaz."]),
         d([("Riya", "W piątek jest impreza. Idziemy?", "", "There's a party Friday. Shall we go?"),
            ("Omar", "W piątek jestem zajęty. W przyszłym tygodniu?", "", "I'm busy Friday. Next week?"),
            ("Riya", "Niedziela? Po szóstej jestem wolna.", "", "Sunday? I'm free after six."),
            ("Omar", "Super. Deser przyniosę ja.", "", "Perfect. I'll bring dessert.")])),
        ("Pogoda: jeśli.",
         v([("prognoza", "", "forecast"), ("przelotne deszcze", "", "shower"), ("wilgotno", "", "humid"),
            ("odwołać", "", "cancel", "verb"), ("w środku", "", "indoor"), ("parasol", "", "umbrella"),
            ("stopień", "", "degree"), ("rozpogodzić się", "", "clear up", "verb")]),
         g("jeśli + teraźniejszy", "Warunek realny.", "jeśli spadnie deszcz, odwołamy",
           [("Jeśli spadnie deszcz, odwołamy piknik.", "", "If it rains, we'll cancel the picnic."),
            ("Jeśli prognoza będzie dobra, pójdziemy.", "", "If the forecast is good, we'll walk."),
            ("Jeśli się nie rozpogodzi, zostaniemy w środku.", "", "If it doesn't clear up, we'll stay inside.")],
           ["Nie wkładaj przyszłego do jeśli bez potrzeby.", "to wprowadza skutek."]),
         d([("Jen", "Prognoza mówi o przelotnych deszczach.", "", "The forecast says showers."),
            ("Kai", "Jeśli deszcz, idziemy do muzeum.", "", "If it rains, we'll go to the museum."),
            ("Jen", "I tak weź parasol.", "", "Take an umbrella anyway."),
            ("Kai", "Jeśli się rozpogodzi, idziemy nad rzekę.", "", "If it clears up, we'll walk by the river.")])),
        ("Zakupy.",
         v([("rozmiar", "", "size"), ("paragon", "", "receipt"), ("zwrot", "", "refund"),
            ("zniżka", "", "discount"), ("gotówka", "", "cash"), ("karta", "", "card"),
            ("pasować", "", "fit", "verb"), ("wymienić", "", "exchange", "verb")]),
         g("stopień wyższy", "tańszy niż / bardziej.", "ta koszula jest tańsza niż tamta",
           [("Ta koszula jest tańsza niż tamta.", "", "This shirt is cheaper than that one."),
            ("Niebieska jest droższa.", "", "The blue one is more expensive."),
            ("Rozmiar M lepiej pasuje.", "", "Size M fits better.")],
           ["Nie ‘bardziej tańsza’.", "niż drugi człon."]),
         d([("Sklep", "Kartą czy gotówką?", "", "Card or cash?"),
            ("Lila", "Kartą. Jest mniejszy rozmiar?", "", "Card. Have you got a smaller size?"),
            ("Sklep", "Tak. Paragon proszę zachować na zwrot.", "", "Yes. Keep the receipt for a refund."),
            ("Lila", "Jest zniżka studencka?", "", "Is there a student discount?")])),
        ("Nawyk.",
         v([("dojazd", "", "commute"), ("zmiana", "", "shift"), ("budzik", "", "alarm"),
            ("oszczędzać", "", "save", "verb"), ("cel", "", "goal"), ("nawyk", "", "habit"),
            ("w przyszłym miesiącu", "", "next month"), ("zazwyczaj", "", "usually", "adv")]),
         g("zazwyczaj teraźniejszy vs będę", "Rozkład — teraźniejszy; decyzja — będę.", "zazwyczaj wychodzę o siódmej",
           [("Zazwyczaj wychodzę o siódmej.", "", "I usually leave at seven."),
            ("W przyszłym miesiącu będę oszczędzać.", "", "I'm going to save next month."),
            ("Moja zmiana zaczyna się o dziewiątej.", "", "My shift starts at nine.")],
           ["Nie używaj będę do drukowanego rozkładu.", "Nie mieszaj wczoraj i będę."]),
         d([("Dana", "O której zazwyczaj zaczynasz?", "", "What time do you usually start?"),
            ("Ned", "O dziewiątej. W przyszłym miesiącu zmienię.", "", "The shift starts at nine. I'm going to change it next month."),
            ("Dana", "Dlaczego?", "", "Why?"),
            ("Ned", "Chcę krótszy dojazd. Taki jest cel.", "", "I want a shorter commute. That's the goal.")])),
    ])


def _zsm():
    return eight([
        ("Rancangan dekat: akan / nak.",
         v([("peperiksaan", "", "exam"), ("mata pelajaran", "", "subject"), ("kerja rumah", "", "homework"),
            ("jadual", "", "timetable"), ("tarikh akhir", "", "deadline"),
            ("ulangkaji", "", "revise", "verb"), ("kuliah", "", "lecture"), ("nota", "", "notes")]),
         g("akan + kata kerja", "Keputusan yang sudah dibuat.", "saya akan ulangkaji malam ini",
           [("Saya akan ulangkaji malam ini.", "", "I'm going to revise tonight."),
            ("Dia akan tertinggal kuliah.", "", "She's going to miss the lecture."),
            ("Awak nak habiskan kerja rumah?", "", "Are you going to finish the homework?")],
           ["Jangan ‘saya akan untuk ulangkaji’.", "akan + kata kerja."]),
         d([("Ana", "Esok ada peperiksaan?", "", "Have you got an exam tomorrow?"),
            ("Luis", "Ada, sejarah. Lepas kelas saya akan ulangkaji.", "", "Yes, history. I'll revise after class."),
            ("Ana", "Belajar di perpustakaan?", "", "Shall we study in the library?"),
            ("Luis", "Ya. Tarikh akhir nota hari ini.", "", "Yes. The notes deadline is today.")])),
        ("Hobi: suka + kata kerja.",
         v([("hobi", "", "hobby"), ("gitar", "", "guitar"), ("pasukan", "", "team"),
            ("latihan", "", "practice"), ("hujung minggu", "", "weekend"),
            ("sertai", "", "join", "verb"), ("konsert", "", "concert"), ("melukis", "", "draw", "verb")]),
         g("suka + kata kerja", "Suka diikuti kata kerja atau nama.", "saya suka main gitar",
           [("Saya suka main gitar.", "", "I like playing guitar."),
            ("Dia tak suka menunggu.", "", "She doesn't like waiting."),
            ("Awak suka melukis hujung minggu?", "", "Do you like drawing at weekends?")],
           ["Bukan ‘saya suka untuk main’.", "tak suka, bukan haram."]),
         d([("Asha", "Hujung minggu awak buat apa?", "", "What do you do at the weekend?"),
            ("Ben", "Main gitar. Sabtu ada konsert.", "", "I play guitar. There's a concert on Saturday."),
            ("Asha", "Saya suka melukis. Nak ikut?", "", "I like drawing. Are you coming?"),
            ("Ben", "Lepas latihan.", "", "Yes, after practice.")])),
        ("Tiket.",
         v([("platform", "", "platform"), ("tiket pergi balik", "", "return ticket"),
            ("kelewatan", "", "delay"), ("bagasi", "", "luggage"), ("pintu", "", "gate"),
            ("pasport", "", "passport"), ("tempah", "", "book", "verb"), ("bertukar kereta api", "", "change trains", "verb")]),
         g("perlu / kena", "Kewajipan luar.", "awak kena tunjuk pasport",
           [("Awak kena tunjuk pasport.", "", "You have to show your passport."),
            ("Kita perlu bertukar di Ipoh.", "", "We have to change in Ipoh."),
            ("Dia tak perlu tempah hari ini.", "", "He doesn't have to book today.")],
           ["kena + kata kerja.", "tak perlu ≠ dilarang."]),
         d([("Kaunter", "Sehala atau pergi balik?", "", "Single or return?"),
            ("Nina", "Pergi balik. Platform mana?", "", "Return. Which platform?"),
            ("Kaunter", "Empat. Ada kelewatan sikit.", "", "Platform 4. There's a short delay."),
            ("Nina", "Perlu bertukar ke?", "", "Do I have to change?")])),
        ("Restoran.",
         v([("menu", "", "menu"), ("bil", "", "bill"), ("hidangan pembuka", "", "starter"),
            ("alahan", "", "allergic"), ("pedas", "", "spicy", "adj"),
            ("cadang", "", "recommend", "verb"), ("tip", "", "tip"), ("meja", "", "table")]),
         g("saya nak", "Pesanan sopan.", "saya nak sup",
           [("Saya nak sup.", "", "I'd like the soup."),
            ("Nak pedas?", "", "Would you like it spicy?"),
            ("Boleh tengok menu?", "", "I'd like to see the menu.")],
           ["Pada pelayan, ‘bagi ni’ kasar.", "nak + nama."]),
         d([("Pelayan", "Boleh order?", "", "Ready to order?"),
            ("Sam", "Saya nak pasta. Pedas ke?", "", "I'd like the pasta. Is it spicy?"),
            ("Pelayan", "Sikit. Ada alahan?", "", "A little. Are you allergic?"),
            ("Sam", "Tak. Bil kat hujung, terima kasih.", "", "No. The bill at the end, please.")])),
        ("Jemputan.",
         v([("jemputan", "", "invitation"), ("sibuk", "", "busy", "adj"), ("jumpa", "", "catch up", "verb"),
            ("bawa", "", "bring", "verb"), ("parti", "", "party"), ("lapang", "", "free"),
            ("mungkin", "", "maybe"), ("minggu depan", "", "next week")]),
         g("jika / jom", "Cadangan.", "jom jumpa jam tujuh?",
           [("Jom jumpa jam tujuh?", "", "Why don't we meet at seven?"),
            ("Minggu depan?", "", "What if we catch up next week?"),
            ("Kita bawa makanan.", "", "Let's bring some food.")],
           ["‘Tidak’ kosong keras: beri sebab.", "jom ajakan, bukan arahan kasar."]),
         d([("Riya", "Jumaat ada parti. Pergi?", "", "There's a party Friday. Shall we go?"),
            ("Omar", "Jumaat sibuk. Minggu depan?", "", "I'm busy Friday. Next week?"),
            ("Riya", "Ahad? Lepas enam saya lapang.", "", "Sunday? I'm free after six."),
            ("Omar", "Okay. Saya bawa pencuci mulut.", "", "Perfect. I'll bring dessert.")])),
        ("Cuaca: kalau.",
         v([("ramalan", "", "forecast"), ("hujan renyai", "", "shower"), ("lembap", "", "humid", "adj"),
            ("batal", "", "cancel", "verb"), ("dalam", "", "indoor"), ("payung", "", "umbrella"),
            ("darjah", "", "degree"), ("cerah", "", "clear up")]),
         g("kalau + sekarang", "Syarat nyata.", "kalau hujan, kita batal",
           [("Kalau hujan, kita batal piknik.", "", "If it rains, we'll cancel the picnic."),
            ("Kalau ramalan elok, kita jalan.", "", "If the forecast is good, we'll walk."),
            ("Kalau tak cerah, kita duduk dalam.", "", "If it doesn't clear up, we'll stay inside.")],
           ["Jangan tindan akan dalam klausa kalau.", "kalau = syarat."]),
         d([("Jen", "Ramalan kata hujan renyai.", "", "The forecast says showers."),
            ("Kai", "Kalau hujan, ke muzium.", "", "If it rains, we'll go to the museum."),
            ("Jen", "Bawa payung juga.", "", "Take an umbrella anyway."),
            ("Kai", "Kalau cerah, jalan tepi sungai.", "", "If it clears up, we'll walk by the river.")])),
        ("Beli-belah.",
         v([("saiz", "", "size"), ("resit", "", "receipt"), ("bayaran balik", "", "refund"),
            ("diskaun", "", "discount"), ("tunai", "", "cash"), ("kad", "", "card"),
            ("muat", "", "fit", "verb"), ("tukar", "", "exchange", "verb")]),
         g("lebih … daripada", "Perbandingan.", "baju ini lebih murah daripada itu",
           [("Baju ini lebih murah daripada itu.", "", "This shirt is cheaper than that one."),
            ("Yang biru lebih mahal.", "", "The blue one is more expensive."),
            ("Saiz M lebih muat.", "", "Size M fits better.")],
           ["Jangan ‘lebih lebih murah’.", "daripada pihak kedua."]),
         d([("Kedai", "Kad atau tunai?", "", "Card or cash?"),
            ("Lila", "Kad. Ada saiz lebih kecil?", "", "Card. Have you got a smaller size?"),
            ("Kedai", "Ada. Simpan resit untuk bayaran balik.", "", "Yes. Keep the receipt for a refund."),
            ("Lila", "Ada diskaun pelajar?", "", "Is there a student discount?")])),
        ("Tabiat.",
         v([("ulang-alik", "", "commute"), ("syif", "", "shift"), ("penggera", "", "alarm"),
            ("simpan", "", "save", "verb"), ("matlamat", "", "goal"), ("tabiat", "", "habit"),
            ("bulan depan", "", "next month"), ("biasanya", "", "usually", "adv")]),
         g("biasanya kini vs akan", "Jadual kini; keputusan akan.", "biasanya saya keluar jam tujuh",
           [("Biasanya saya keluar jam tujuh.", "", "I usually leave at seven."),
            ("Bulan depan saya akan simpan duit.", "", "I'm going to save next month."),
            ("Syif saya mula jam sembilan.", "", "My shift starts at nine.")],
           ["Jadual tercetak jangan pakai akan.", "Jangan campur semalam dengan akan."]),
         d([("Dana", "Biasanya mula jam berapa?", "", "What time do you usually start?"),
            ("Ned", "Jam sembilan. Bulan depan saya akan tukar.", "", "The shift starts at nine. I'm going to change it next month."),
            ("Dana", "Kenapa?", "", "Why?"),
            ("Ned", "Nak perjalanan lebih pendek. Itu matlamat.", "", "I want a shorter commute. That's the goal.")])),
    ])


DATA = {"pl": _pl(), "zsm": _zsm()}
