#!/usr/bin/env python3
"""A3 packs (and B3 where authored) for the remaining complete-true languages."""
from tools.lib.extended_banks import V, G, D, lesson, _add


def register():
    for code, builder in _BUILDERS.items():
        a3, b3 = builder()
        _add(code, "A3", a3)
        if b3:
            _add(code, "B3", b3)


def _L(n, title, learn, vocab, g, dlg):
    return lesson(n, title, learn, vocab, g, dlg)


def _BUILD_de():
    a3 = [
        _L(1, "Schule und Lernen", "Pläne mit werden + Infinitiv und dem Futur mit gehen.",
           [V("die Prüfung", "", "exam"), V("das Fach", "", "subject"), V("die Hausaufgabe", "", "homework"),
            V("der Stundenplan", "", "timetable"), V("die Frist", "", "deadline"), V("wiederholen", "", "revise", "verb"),
            V("die Vorlesung", "", "lecture"), V("die Notizen", "", "notes")],
           G("werden + Infinitiv", "Das Futur I: werden konjugiert + Infinitiv.",
             "ich werde + Infinitiv",
             [("Ich werde heute Abend wiederholen.", "", "I'm going to revise tonight."),
              ("Sie wird die Vorlesung verpassen.", "", "She's going to miss the lecture."),
              ("Wirst du die Hausaufgabe fertig machen?", "", "Are you going to finish the homework?")],
             ["Nicht 'ich werde zu wiederholen'.", "Werden konjugieren, das zweite Verb bleibt Infinitiv."]),
           D([("Ana", "Hast du morgen eine Prüfung?", "", "Have you got an exam tomorrow?"),
              ("Luis", "Ja, Geschichte. Ich werde nach dem Unterricht wiederholen.", "", "Yes, history. I'll revise after class."),
              ("Ana", "Sollen wir in der Bibliothek lernen?", "", "Shall we study in the library?"),
              ("Luis", "Ja. Die Frist für die Notizen ist heute.", "", "Yes. The notes deadline is today.")])),
        _L(2, "Freizeit", "Sagen, was man gern macht, mit gern + Verb.",
           [V("das Hobby", "", "hobby"), V("die Gitarre", "", "guitar"), V("die Mannschaft", "", "team"),
            V("das Training", "", "practice"), V("das Wochenende", "", "weekend"), V("mitmachen", "", "join", "verb"),
            V("das Konzert", "", "concert"), V("zeichnen", "", "draw", "verb")],
           G("gern + Verb", "Gern steht beim Verb, nicht wie englisches like + -ing.",
             "ich spiele gern",
             [("Ich spiele gern Gitarre.", "", "I like playing guitar."),
              ("Sie wartet nicht gern.", "", "She doesn't like waiting."),
              ("Zeichnest du am Wochenende gern?", "", "Do you like drawing at weekends?")],
             ["Nicht 'ich gern spiele'.", "Gern steht nach dem konjugierten Verb."]),
           D([("Asha", "Was machst du am Wochenende?", "", "What do you do at the weekend?"),
              ("Ben", "Ich spiele Gitarre. Am Samstag ist ein Konzert.", "", "I play guitar. There's a concert on Saturday."),
              ("Asha", "Ich zeichne gern. Kommst du mit?", "", "I like drawing. Are you coming?"),
              ("Ben", "Ja, nach dem Training.", "", "Yes, after practice.")])),
        _L(3, "Reisen", "Ticket, Gleis, Verspätung.",
           [V("das Gleis", "", "platform"), V("die Rückfahrkarte", "", "return ticket"), V("die Verspätung", "", "delay"),
            V("das Gepäck", "", "luggage"), V("das Gate", "", "gate"), V("der Pass", "", "passport"),
            V("buchen", "", "book", "verb"), V("umsteigen", "", "change trains", "verb")],
           G("müssen + Infinitiv", "Müssen ist äußere Pflicht.",
             "ich muss + Infinitiv",
             [("Du musst den Pass zeigen.", "", "You have to show your passport."),
              ("Wir müssen in Köln umsteigen.", "", "We have to change in Cologne."),
              ("Er muss heute nicht buchen.", "", "He doesn't have to book today.")],
             ["Nicht 'du musst zu zeigen'.", "Modalverb + reiner Infinitiv."]),
           D([("Schalter", "Einfach oder hin und zurück?", "", "Single or return?"),
              ("Nina", "Hin und zurück. Welches Gleis?", "", "Return. Which platform?"),
              ("Schalter", "Gleis 4. Es gibt eine kurze Verspätung.", "", "Platform 4. There's a short delay."),
              ("Nina", "Muss ich umsteigen?", "", "Do I have to change?")])),
        _L(4, "Essen", "Bestellen und Allergien nennen.",
           [V("die Speisekarte", "", "menu"), V("die Rechnung", "", "bill"), V("die Vorspeise", "", "starter"),
            V("allergisch", "", "allergic", "adj"), V("scharf", "", "spicy", "adj"),
            V("empfehlen", "", "recommend", "verb"), V("das Trinkgeld", "", "tip"), V("der Tisch", "", "table")],
           G("ich hätte gern", "Höfliche Bestellung mit Konjunktiv II.",
             "ich hätte gern + Nomen",
             [("Ich hätte gern die Suppe.", "", "I'd like the soup."),
              ("Möchten Sie es scharf?", "", "Would you like it spicy?"),
              ("Ich hätte gern die Speisekarte.", "", "I'd like the menu.")],
             ["Ich will ist grob zum Kellner.", "Hätte gern, nicht 'ich hätte gerne zu'."]),
           D([("Kellner", "Möchten Sie bestellen?", "", "Ready to order?"),
              ("Sam", "Ich hätte gern die Pasta. Ist sie scharf?", "", "I'd like the pasta. Is it spicy?"),
              ("Kellner", "Ein bisschen. Sind Sie allergisch?", "", "A little. Are you allergic?"),
              ("Sam", "Nein. Die Rechnung am Ende, bitte.", "", "No. The bill at the end, please.")])),
        _L(5, "Freunde", "Einladen und absagen mit Grund.",
           [V("die Einladung", "", "invitation"), V("beschäftigt", "", "busy", "adj"), V("sich treffen", "", "catch up", "verb"),
            V("mitbringen", "", "bring", "verb"), V("die Party", "", "party"), V("frei", "", "free", "adj"),
            V("vielleicht", "", "maybe"), V("nächste Woche", "", "next week")],
           G("sollen wir / wie wäre es mit", "Vorschläge, keine Befehle.",
             "Sollen wir + Infinitiv?",
             [("Sollen wir uns um sieben treffen?", "", "Shall we meet at seven?"),
              ("Wie wäre es mit nächster Woche?", "", "How about next week?"),
              ("Lass uns etwas zu essen mitbringen.", "", "Let's bring some food.")],
             ["Ein nacktes Nein klingt hart: Grund nennen.", "Sollen wir ist eine Frage."]),
           D([("Riya", "Freitag ist eine Party. Sollen wir gehen?", "", "There's a party Friday. Shall we go?"),
              ("Omar", "Freitag bin ich beschäftigt. Nächste Woche?", "", "I'm busy Friday. Next week?"),
              ("Riya", "Sonntag? Nach sechs bin ich frei.", "", "Sunday? I'm free after six."),
              ("Omar", "Perfekt. Ich bringe den Nachtisch mit.", "", "Perfect. I'll bring dessert.")])),
        _L(6, "Wetter", "Wenn + Präsens, dann Futur.",
           [V("die Vorhersage", "", "forecast"), V("der Schauer", "", "shower"), V("schwül", "", "humid", "adj"),
            V("absagen", "", "cancel", "verb"), V("drinnen", "", "indoor"), V("der Schirm", "", "umbrella"),
            V("das Grad", "", "degree"), V("aufklaren", "", "clear up", "verb")],
           G("wenn + Präsens", "Reale Bedingung: wenn + Präsens, Futur oder Präsens.",
             "wenn es regnet, werden wir …",
             [("Wenn es regnet, sagen wir das Picknick ab.", "", "If it rains, we'll cancel the picnic."),
              ("Wenn die Vorhersage gut ist, spazieren wir.", "", "If the forecast is good, we'll walk."),
              ("Wenn es nicht aufklart, bleiben wir drinnen.", "", "If it doesn't clear up, we'll stay inside.")],
             ["Kein werden in der wenn-Klausel.", "Nicht 'wenn es wird regnen'."]),
           D([("Jen", "Die Vorhersage sagt Schauer.", "", "The forecast says showers."),
              ("Kai", "Wenn es regnet, gehen wir ins Museum.", "", "If it rains, we'll go to the museum."),
              ("Jen", "Nimm trotzdem einen Schirm.", "", "Take an umbrella anyway."),
              ("Kai", "Wenn es aufklart, laufen wir am Fluss.", "", "If it clears up, we'll walk by the river.")])),
        _L(7, "Einkaufen", "Vergleich und Umtausch.",
           [V("die Größe", "", "size"), V("der Kassenbon", "", "receipt"), V("die Rückerstattung", "", "refund"),
            V("der Rabatt", "", "discount"), V("bar", "", "cash"), V("die Karte", "", "card"),
            V("passen", "", "fit", "verb"), V("umtauschen", "", "exchange", "verb")],
           G("Komparativ", "Adjektiv + -er + als. Gut → besser.",
             "billiger als",
             [("Dieses Hemd ist billiger als jenes.", "", "This shirt is cheaper than that one."),
              ("Das blaue ist teurer.", "", "The blue one is more expensive."),
              ("Größe M passt besser.", "", "Size M fits better.")],
             ["Nicht 'mehr billiger'.", "Als, nicht wie, beim Ungleichen."]),
           D([("Laden", "Bar oder mit Karte?", "", "Cash or card?"),
              ("Lila", "Mit Karte. Haben Sie das in einer kleineren Größe?", "", "Card. Have you got a smaller size?"),
              ("Laden", "Ja. Bewahren Sie den Bon für eine Rückerstattung auf.", "", "Yes. Keep the receipt for a refund."),
              ("Lila", "Gibt es Studentenrabatt?", "", "Is there a student discount?")])),
        _L(8, "Alltag", "Gewohnheit im Präsens, Plan mit werden.",
           [V("pendeln", "", "commute", "verb"), V("die Schicht", "", "shift"), V("der Wecker", "", "alarm"),
            V("sparen", "", "save", "verb"), V("das Ziel", "", "goal"), V("die Gewohnheit", "", "habit"),
            V("nächsten Monat", "", "next month"), V("normalerweise", "", "usually", "adv")],
           G("Präsens vs werden", "Präsens = Fahrplan; werden = Entscheidung.",
             "normalerweise + Präsens  /  ich werde + Inf",
             [("Normalerweise pendle ich um sieben.", "", "I usually commute at seven."),
              ("Ich werde nächsten Monat sparen.", "", "I'm going to save next month."),
              ("Meine Schicht beginnt um neun.", "", "My shift starts at nine.")],
             ["Nicht werden für einen gedruckten Fahrplan.", "Nicht gestern mit werden mischen."]),
           D([("Dana", "Wann fängst du normalerweise an?", "", "What time do you usually start?"),
              ("Ned", "Die Schicht beginnt um neun. Ich werde sie nächsten Monat ändern.", "", "The shift starts at nine. I'm going to change it next month."),
              ("Dana", "Warum?", "", "Why?"),
              ("Ned", "Ich will einen kürzeren Weg. Das ist das Ziel.", "", "I want a shorter commute. That's the goal.")])),
    ]
    return a3, None


def _BUILD_it():
    a3 = [
        _L(1, "Scuola e studio", "Piani prossimi con stare per / andare a.",
           [V("l'esame", "", "exam"), V("la materia", "", "subject"), V("i compiti", "", "homework"),
            V("l'orario", "", "timetable"), V("la scadenza", "", "deadline"), V("ripassare", "", "revise", "verb"),
            V("la lezione", "", "lecture"), V("gli appunti", "", "notes")],
           G("stare per + infinito", "Un piano già deciso, molto vicino.",
             "sto per + infinito",
             [("Sto per ripassare stasera.", "", "I'm about to revise tonight."),
              ("Lei sta per perdere la lezione.", "", "She's about to miss the lecture."),
              ("Stai per finire i compiti?", "", "Are you about to finish the homework?")],
             ["Non si dice 'sto ripassare'.", "Serve per + infinito."]),
           D([("Ana", "Hai un esame domani?", "", "Have you got an exam tomorrow?"),
              ("Luis", "Sì, di storia. Sto per ripassare dopo lezione.", "", "Yes, history. I'm going to revise after class."),
              ("Ana", "Studiamo in biblioteca?", "", "Shall we study in the library?"),
              ("Luis", "Sì. La scadenza degli appunti è oggi.", "", "Yes. The notes deadline is today.")])),
        _L(2, "Tempo libero", "Piacere + infinito.",
           [V("il passatempo", "", "hobby"), V("la chitarra", "", "guitar"), V("la squadra", "", "team"),
            V("l'allenamento", "", "practice"), V("il fine settimana", "", "weekend"), V("iscriversi", "", "join", "verb"),
            V("il concerto", "", "concert"), V("disegnare", "", "draw", "verb")],
           G("mi piace + infinito", "Piacere concorda con ciò che piace.",
             "mi piace + infinito",
             [("Mi piace suonare la chitarra.", "", "I like playing guitar."),
              ("Non le piace aspettare.", "", "She doesn't like waiting."),
              ("Ti piace disegnare nel fine settimana?", "", "Do you like drawing at weekends?")],
             ["Non si dice 'io piaccio suonare'.", "Il soggetto è la cosa che piace."]),
           D([("Asha", "Cosa fai nel fine settimana?", "", "What do you do at the weekend?"),
              ("Ben", "Suono la chitarra. Sabato c'è un concerto.", "", "I play guitar. There's a concert on Saturday."),
              ("Asha", "Mi piace disegnare. Vieni?", "", "I like drawing. Are you coming?"),
              ("Ben", "Sì, dopo l'allenamento.", "", "Yes, after practice.")])),
        _L(3, "Viaggio", "Biglietto e binario.",
           [V("il binario", "", "platform"), V("l'andata e ritorno", "", "return ticket"), V("il ritardo", "", "delay"),
            V("il bagaglio", "", "luggage"), V("il gate", "", "gate"), V("il passaporto", "", "passport"),
            V("prenotare", "", "book", "verb"), V("cambiare", "", "change trains", "verb")],
           G("dovere + infinito", "Obbligo esterno.",
             "devo + infinito",
             [("Devi mostrare il passaporto.", "", "You have to show your passport."),
              ("Dobbiamo cambiare a Milano.", "", "We have to change in Milan."),
              ("Lui non deve prenotare oggi.", "", "He doesn't have to book today.")],
             ["Non 'devi di mostrare'.", "Dovere + infinito nudo."]),
           D([("Sportello", "Solo andata o andata e ritorno?", "", "Single or return?"),
              ("Nina", "Andata e ritorno. Quale binario?", "", "Return. Which platform?"),
              ("Sportello", "Binario 4. C'è un piccolo ritardo.", "", "Platform 4. There's a short delay."),
              ("Nina", "Devo cambiare?", "", "Do I have to change?")])),
        _L(4, "Ristorante", "Ordinare con vorrei.",
           [V("il menu", "", "menu"), V("il conto", "", "bill"), V("l'antipasto", "", "starter"),
            V("allergico", "", "allergic", "adj"), V("piccante", "", "spicy", "adj"),
            V("consigliare", "", "recommend", "verb"), V("la mancia", "", "tip"), V("il tavolo", "", "table")],
           G("vorrei", "Condizionale di cortesia.",
             "vorrei + nome",
             [("Vorrei la zuppa, per favore.", "", "I'd like the soup."),
              ("La vuole piccante?", "", "Would you like it spicy?"),
              ("Vorrei vedere il menu.", "", "I'd like to see the menu.")],
             ["Voglio è secco col cameriere.", "Vorrei, non 'vorrei di'."]),
           D([("Cameriere", "Siete pronti per ordinare?", "", "Ready to order?"),
              ("Sam", "Vorrei la pasta. È piccante?", "", "I'd like the pasta. Is it spicy?"),
              ("Cameriere", "Un po'. È allergico?", "", "A little. Are you allergic?"),
              ("Sam", "No. Il conto alla fine, per favore.", "", "No. The bill at the end, please.")])),
        _L(5, "Amici", "Invito e rifiuto cortese.",
           [V("l'invito", "", "invitation"), V("occupato", "", "busy", "adj"), V("aggiornarsi", "", "catch up", "verb"),
            V("portare", "", "bring", "verb"), V("la festa", "", "party"), V("libero", "", "free", "adj"),
            V("forse", "", "maybe"), V("la settimana prossima", "", "next week")],
           G("perché non / e se", "Suggerimenti.",
             "Perché non + presente?",
             [("Perché non ci vediamo alle sette?", "", "Why don't we meet at seven?"),
              ("E se ci aggiorniamo la settimana prossima?", "", "What if we catch up next week?"),
              ("Portiamo da mangiare.", "", "Let's bring some food.")],
             ["Un no nudo è duro: dai un motivo.", "Perché non + presente."]),
           D([("Riya", "Venerdì c'è una festa. Andiamo?", "", "There's a party Friday. Shall we go?"),
              ("Omar", "Venerdì sono occupato. La settimana prossima?", "", "I'm busy Friday. Next week?"),
              ("Riya", "Domenica? Sono libero dopo le sei.", "", "Sunday? I'm free after six."),
              ("Omar", "Perfetto. Porto il dolce.", "", "Perfect. I'll bring dessert.")])),
        _L(6, "Tempo", "Se + presente, futuro.",
           [V("le previsioni", "", "forecast"), V("il temporale", "", "shower/storm"), V("umido", "", "humid", "adj"),
            V("annullare", "", "cancel", "verb"), V("al chiuso", "", "indoor"), V("l'ombrello", "", "umbrella"),
            V("il grado", "", "degree"), V("schiarire", "", "clear up", "verb")],
           G("se + presente", "Condizione reale.",
             "se piove, annulleremo",
             [("Se piove, annulleremo il picnic.", "", "If it rains, we'll cancel the picnic."),
              ("Se le previsioni sono belle, cammineremo.", "", "If the forecast is good, we'll walk."),
              ("Se non schiarisce, restiamo al chiuso.", "", "If it doesn't clear up, we'll stay inside.")],
             ["Niente futuro nella frase con se.", "Non 'se pioverà'."]),
           D([("Jen", "Le previsioni dicono temporali.", "", "The forecast says showers."),
              ("Kai", "Se piove, andiamo al museo.", "", "If it rains, we'll go to the museum."),
              ("Jen", "Porta l'ombrello lo stesso.", "", "Take an umbrella anyway."),
              ("Kai", "Se schiarisce, camminiamo sul fiume.", "", "If it clears up, we'll walk by the river.")])),
        _L(7, "Spesa", "Comparativi e reso.",
           [V("la taglia", "", "size"), V("lo scontrino", "", "receipt"), V("il rimborso", "", "refund"),
            V("lo sconto", "", "discount"), V("i contanti", "", "cash"), V("la carta", "", "card"),
            V("stare", "", "fit", "verb"), V("cambiare", "", "exchange", "verb")],
           G("comparativo", "Più/meno + agg + di.",
             "più economico di",
             [("Questa camicia è più economica di quella.", "", "This shirt is cheaper than that one."),
              ("Quella blu è più cara.", "", "The blue one is more expensive."),
              ("La taglia M mi sta meglio.", "", "Size M fits me better.")],
             ["Non 'più migliore'.", "Di introduce il secondo termine."]),
           D([("Negozio", "Carta o contanti?", "", "Card or cash?"),
              ("Lila", "Carta. Ce l'avete in una taglia più piccola?", "", "Card. Have you got a smaller size?"),
              ("Negozio", "Sì. Tenga lo scontrino per il rimborso.", "", "Yes. Keep the receipt for a refund."),
              ("Lila", "C'è lo sconto studenti?", "", "Is there a student discount?")])),
        _L(8, "Routine", "Presente vs stare per.",
           [V("pendolare", "", "commute", "verb"), V("il turno", "", "shift"), V("la sveglia", "", "alarm"),
            V("risparmiare", "", "save", "verb"), V("l'obiettivo", "", "goal"), V("l'abitudine", "", "habit"),
            V("il mese prossimo", "", "next month"), V("di solito", "", "usually", "adv")],
           G("presente vs stare per", "L'orario sta al presente; la decisione a stare per / futuro.",
             "di solito + presente",
             [("Di solito parto alle sette.", "", "I usually leave at seven."),
              ("Sto per risparmiare il mese prossimo.", "", "I'm going to save next month."),
              ("Il turno inizia alle nove.", "", "The shift starts at nine.")],
             ["Non usare stare per per un orario stampato.", "Non mescolare ieri e sto per."]),
           D([("Dana", "A che ora inizi di solito?", "", "What time do you usually start?"),
              ("Ned", "Il turno inizia alle nove. Lo cambio il mese prossimo.", "", "The shift starts at nine. I'm going to change it next month."),
              ("Dana", "Perché?", "", "Why?"),
              ("Ned", "Voglio un tragitto più corto. Questo è l'obiettivo.", "", "I want a shorter commute. That's the goal.")])),
    ]
    return a3, None


def _BUILD_pt():
    a3 = [
        _L(1, "Escola e estudos", "Planos próximos com ir + infinitivo.",
           [V("a prova", "", "exam"), V("a matéria", "", "subject"), V("o dever de casa", "", "homework"),
            V("o horário", "", "timetable"), V("o prazo", "", "deadline"), V("revisar", "", "revise", "verb"),
            V("a aula", "", "lecture"), V("as anotações", "", "notes")],
           G("ir + infinitivo", "Futuro próximo: ir conjugado + infinitivo.",
             "vou/vai + infinitivo",
             [("Vou revisar esta noite.", "", "I'm going to revise tonight."),
              ("Ela vai perder a aula.", "", "She's going to miss class."),
              ("Você vai terminar o dever?", "", "Are you going to finish the homework?")],
             ["Não se diz 'vou a revisar' no Brasil.", "Ir se conjuga; o outro verbo fica no infinitivo."]),
           D([("Ana", "Você tem prova amanhã?", "", "Have you got an exam tomorrow?"),
              ("Luis", "Sim, de história. Vou revisar depois da aula.", "", "Yes, history. I'm going to revise after class."),
              ("Ana", "Vamos estudar na biblioteca?", "", "Shall we study in the library?"),
              ("Luis", "Sim. O prazo das anotações é hoje.", "", "Yes. The notes deadline is today.")])),
        _L(2, "Tempo livre", "Gostar de + infinitivo.",
           [V("o passatempo", "", "hobby"), V("o violão", "", "guitar"), V("o time", "", "team"),
            V("o treino", "", "practice"), V("o fim de semana", "", "weekend"), V("entrar", "", "join", "verb"),
            V("o show", "", "concert"), V("desenhar", "", "draw", "verb")],
           G("gostar de", "Gostar pede de + infinitivo ou substantivo.",
             "eu gosto de + infinitivo",
             [("Eu gosto de tocar violão.", "", "I like playing guitar."),
              ("Ela não gosta de esperar.", "", "She doesn't like waiting."),
              ("Você gosta de desenhar no fim de semana?", "", "Do you like drawing at weekends?")],
             ["Não se diz 'eu gosto tocar'.", "O de não cai."]),
           D([("Asha", "O que você faz no fim de semana?", "", "What do you do at the weekend?"),
              ("Ben", "Toco violão. Sábado tem um show.", "", "I play guitar. There's a concert on Saturday."),
              ("Asha", "Gosto de desenhar. Você vem?", "", "I like drawing. Are you coming?"),
              ("Ben", "Sim, depois do treino.", "", "Yes, after practice.")])),
        _L(3, "Viagem", "Passagem e plataforma.",
           [V("a plataforma", "", "platform"), V("a ida e volta", "", "return ticket"), V("o atraso", "", "delay"),
            V("a bagagem", "", "luggage"), V("o portão", "", "gate"), V("o passaporte", "", "passport"),
            V("reservar", "", "book", "verb"), V("fazer baldeação", "", "change trains", "verb")],
           G("ter que / precisar", "Obrigação.",
             "você tem que + infinitivo",
             [("Você tem que mostrar o passaporte.", "", "You have to show your passport."),
              ("A gente precisa fazer baldeação em Campinas.", "", "We have to change in Campinas."),
              ("Ele não tem que reservar hoje.", "", "He doesn't have to book today.")],
             ["Não 'tem mostrar'.", "Ter que + infinitivo."]),
           D([("Guichê", "Só ida ou ida e volta?", "", "Single or return?"),
              ("Nina", "Ida e volta. Qual plataforma?", "", "Return. Which platform?"),
              ("Guichê", "Plataforma 4. Tem um atraso curto.", "", "Platform 4. There's a short delay."),
              ("Nina", "Eu tenho que fazer baldeação?", "", "Do I have to change?")])),
        _L(4, "Restaurante", "Eu gostaria de.",
           [V("o cardápio", "", "menu"), V("a conta", "", "bill"), V("a entrada", "", "starter"),
            V("alérgico", "", "allergic", "adj"), V("picante", "", "spicy", "adj"),
            V("recomendar", "", "recommend", "verb"), V("a gorjeta", "", "tip"), V("a mesa", "", "table")],
           G("eu gostaria de", "Pedido educado.",
             "eu gostaria de + substantivo",
             [("Eu gostaria da sopa, por favor.", "", "I'd like the soup."),
              ("Você quer picante?", "", "Would you like it spicy?"),
              ("Eu gostaria de ver o cardápio.", "", "I'd like to see the menu.")],
             ["Eu quero é mais seco com garçom.", "Gostaria de, não 'gostaria ver'."]),
           D([("Garçom", "Já podem pedir?", "", "Ready to order?"),
              ("Sam", "Eu gostaria do macarrão. É picante?", "", "I'd like the pasta. Is it spicy?"),
              ("Garçom", "Um pouco. Você é alérgico?", "", "A little. Are you allergic?"),
              ("Sam", "Não. A conta no final, por favor.", "", "No. The bill at the end, please.")])),
        _L(5, "Amigos", "Convite e recusa com motivo.",
           [V("o convite", "", "invitation"), V("ocupado", "", "busy", "adj"), V("pôr o papo em dia", "", "catch up", "verb"),
            V("trazer", "", "bring", "verb"), V("a festa", "", "party"), V("livre", "", "free", "adj"),
            V("talvez", "", "maybe"), V("semana que vem", "", "next week")],
           G("por que a gente não", "Sugestão.",
             "por que a gente não + presente?",
             [("Por que a gente não se encontra às sete?", "", "Why don't we meet at seven?"),
              ("E se a gente se vê semana que vem?", "", "What if we catch up next week?"),
              ("Vamos levar comida.", "", "Let's bring some food.")],
             ["Um não seco é duro: dê um motivo.", "Por que a gente não + presente."]),
           D([("Riya", "Sexta tem festa. A gente vai?", "", "There's a party Friday. Shall we go?"),
              ("Omar", "Sexta estou ocupado. Semana que vem?", "", "I'm busy Friday. Next week?"),
              ("Riya", "Domingo? Estou livre depois das seis.", "", "Sunday? I'm free after six."),
              ("Omar", "Perfeito. Eu levo a sobremesa.", "", "Perfect. I'll bring dessert.")])),
        _L(6, "Clima", "Se + presente, futuro.",
           [V("a previsão", "", "forecast"), V("o aguaceiro", "", "shower"), V("úmido", "", "humid", "adj"),
            V("cancelar", "", "cancel", "verb"), V("em ambiente fechado", "", "indoor"), V("o guarda-chuva", "", "umbrella"),
            V("o grau", "", "degree"), V("abrir", "", "clear up", "verb")],
           G("se + presente", "Condição real.",
             "se chover, a gente cancela",
             [("Se chover, a gente cancela o piquenique.", "", "If it rains, we'll cancel the picnic."),
              ("Se a previsão estiver boa, a gente caminha.", "", "If the forecast is good, we'll walk."),
              ("Se não abrir, a gente fica em ambiente fechado.", "", "If it doesn't clear up, we'll stay inside.")],
             ["Sem futuro na oração do se.", "Não 'se vai chover'."]),
           D([("Jen", "A previsão fala em aguaceiro.", "", "The forecast says showers."),
              ("Kai", "Se chover, a gente vai ao museu.", "", "If it rains, we'll go to the museum."),
              ("Jen", "Leva o guarda-chuva mesmo assim.", "", "Take an umbrella anyway."),
              ("Kai", "Se abrir, a gente anda no rio.", "", "If it clears up, we'll walk by the river.")])),
        _L(7, "Compras", "Comparativo e troca.",
           [V("o tamanho", "", "size"), V("o cupom fiscal", "", "receipt"), V("o reembolso", "", "refund"),
            V("o desconto", "", "discount"), V("o dinheiro", "", "cash"), V("o cartão", "", "card"),
            V("servir", "", "fit", "verb"), V("trocar", "", "exchange", "verb")],
           G("comparativo", "Mais/menos + adj + do que.",
             "mais barato do que",
             [("Esta camisa é mais barata do que aquela.", "", "This shirt is cheaper than that one."),
              ("A azul é mais cara.", "", "The blue one is more expensive."),
              ("O tamanho M me serve melhor.", "", "Size M fits me better.")],
             ["Não 'mais melhor'.", "Do que introduz o segundo termo."]),
           D([("Loja", "Cartão ou dinheiro?", "", "Card or cash?"),
              ("Lila", "Cartão. Tem um tamanho menor?", "", "Card. Have you got a smaller size?"),
              ("Loja", "Tem. Guarde o cupom para reembolso.", "", "Yes. Keep the receipt for a refund."),
              ("Lila", "Tem desconto de estudante?", "", "Is there a student discount?")])),
        _L(8, "Rotina", "Presente vs ir + infinitivo.",
           [V("pendular", "", "commute", "verb"), V("o turno", "", "shift"), V("o despertador", "", "alarm"),
            V("juntar", "", "save", "verb"), V("o objetivo", "", "goal"), V("o hábito", "", "habit"),
            V("mês que vem", "", "next month"), V("geralmente", "", "usually", "adv")],
           G("presente vs ir", "Horário no presente; decisão com ir.",
             "geralmente + presente  /  vou + inf",
             [("Geralmente eu saio às sete.", "", "I usually leave at seven."),
              ("Vou juntar dinheiro mês que vem.", "", "I'm going to save next month."),
              ("Meu turno começa às nove.", "", "My shift starts at nine.")],
             ["Não use ir para horário impresso.", "Não misture ontem com vou."]),
           D([("Dana", "A que horas você começa, geralmente?", "", "What time do you usually start?"),
              ("Ned", "O turno começa às nove. Vou mudar mês que vem.", "", "The shift starts at nine. I'm going to change it next month."),
              ("Dana", "Por quê?", "", "Why?"),
              ("Ned", "Quero um caminho mais curto. Esse é o objetivo.", "", "I want a shorter commute. That's the goal.")])),
    ]
    return a3, None


_BUILDERS = {
    "de": _BUILD_de,
    "it": _BUILD_it,
    "pt": _BUILD_pt,
}
