#!/usr/bin/env python3
"""A3 packs for remaining complete-true languages (batch)."""
from tools.lib.extended_banks import _add
from tools.lib.bank_builder import build_a3, v, g, d


def register():
    for code, rows in DATA.items():
        _add(code, "A3", build_a3(rows))


def _bn():
    return [
        ("কাছের পরিকল্পনা: -তে যাচ্ছি।",
         v([("পরীক্ষা", "porīkṣā", "exam"), ("বিষয়", "biṣoy", "subject"), ("বাড়ির কাজ", "bāṛir kāj", "homework"),
            ("সময়সূচি", "samoysūci", "timetable"), ("শেষ তারিখ", "śeṣ tārikh", "deadline"),
            ("পুনরাবৃত্তি", "punorābṛtti", "revise"), ("ক্লাস", "klās", "lecture"), ("নোট", "noṭ", "notes")]),
         g("যাচ্ছি + করতে", "কাছের সিদ্ধান্ত।", "আজ রাতে আমি পুনরাবৃত্তি করতে যাচ্ছি",
           [("আজ রাতে আমি পুনরাবৃত্তি করতে যাচ্ছি।", "āj rāte āmi punorābṛtti korte jācchi", "I'm going to revise tonight."),
            ("সে ক্লাস মিস করতে যাচ্ছে।", "se klās mis korte jācche", "She's going to miss the lecture."),
            ("তুমি কি বাড়ির কাজ শেষ করতে যাচ্ছ?", "tumi ki bāṛir kāj śeṣ korte jāccho?", "Are you going to finish the homework?")],
           ["‘আমি যাচ্ছি পুনরাবৃত্তি’ ক্রম উল্টো।", "যাচ্ছি-র পরে ক্রিয়া।"]),
         d([("আনা", "কাল পরীক্ষা আছে?", "kāl porīkṣā āche?", "Have you got an exam tomorrow?"),
            ("লুইস", "হ্যাঁ, ইতিহাস। ক্লাসের পর পুনরাবৃত্তি করব।", "hyã, itihās. klāser por punorābṛtti korbo.", "Yes, history. I'll revise after class."),
            ("আনা", "লাইব্রেরিতে পড়ি?", "lāibrerite poṛi?", "Shall we study in the library?"),
            ("লুইস", "হ্যাঁ। নোটের শেষ তারিখ আজ।", "hyã. noṭer śeṣ tārikh āj.", "Yes. The notes deadline is today.")])),
        ("শখ: ভালো লাগে।",
         v([("শখ", "śokh", "hobby"), ("গিটার", "giṭār", "guitar"), ("দল", "dol", "team"),
            ("অনুশীলন", "onuśīlon", "practice"), ("সপ্তাহান্ত", "saptāhānto", "weekend"),
            ("যোগ দেওয়া", "jog deoa", "join", "verb"), ("কনসার্ট", "konsārṭ", "concert"), ("আঁকা", "ãkā", "draw", "verb")]),
         g("ভালো লাগে", "যাকে ভালো লাগে সেটা কর্তা নয়।", "আমার গিটার বাজাতে ভালো লাগে",
           [("আমার গিটার বাজাতে ভালো লাগে।", "āmār giṭār bājāte bhālo lāge", "I like playing guitar."),
            ("তার অপেক্ষা ভালো লাগে না।", "tār opekṣā bhālo lāge nā", "She doesn't like waiting."),
            ("সপ্তাহান্তে আঁকতে ভালো লাগে?", "saptāhānte ãkte bhālo lāge?", "Do you like drawing at weekends?")],
           ["‘আমি ভালো লাগে গিটার’ ভুল।", "লাগে বস্তুর সাথে মেলে।"]),
         d([("আশা", "সপ্তাহান্তে কী করো?", "saptāhānte kī koro?", "What do you do at the weekend?"),
            ("বেন", "গিটার বাজাই। শনিবার কনসার্ট।", "giṭār bājāi. śonibār konsārṭ.", "I play guitar. There's a concert on Saturday."),
            ("আশা", "আমার আঁকতে ভালো লাগে। আসবে?", "āmār ãkte bhālo lāge. āsbe?", "I like drawing. Are you coming?"),
            ("বেন", "অনুশীলনের পরে।", "onuśīloner pore.", "Yes, after practice.")])),
        ("টিকিট।",
         v([("প্ল্যাটফর্ম", "plætphôrm", "platform"), ("রিটার্ন টিকিট", "riṭārn ṭikiṭ", "return ticket"),
            ("দেরি", "deri", "delay"), ("মালপত্র", "mālpotra", "luggage"), ("গেট", "geṭ", "gate"),
            ("পাসপোর্ট", "pāsporṭ", "passport"), ("বুক করা", "buk kôra", "book", "verb"), ("ট্রেন বদলানো", "ṭren bôdāno", "change trains", "verb")]),
         g("হবে / লাগবে", "বাইরের দায়।", "পাসপোর্ট দেখাতে হবে",
           [("পাসপোর্ট দেখাতে হবে।", "pāsporṭ dekhāte hobe", "You have to show your passport."),
            ("রাজশাহীতে ট্রেন বদলাতে হবে।", "rājśāhīte ṭren bôdāte hobe", "We have to change in Rajshahi."),
            ("আজ বুক করতে হবে না।", "āj buk korte hobe nā", "He doesn't have to book today.")],
           ["হবে-র আগে ক্রিয়া।", "হবে না = দরকার নেই।"]),
         d([("কাউন্টার", "একমুখী না রিটার্ন?", "ekmukhī nā riṭārn?", "Single or return?"),
            ("নিনা", "রিটার্ন। কোন প্ল্যাটফর্ম?", "riṭārn. kon plætphôrm?", "Return. Which platform?"),
            ("কাউন্টার", "চার। একটু দেরি।", "cār. ektu deri.", "Platform 4. There's a short delay."),
            ("নিনা", "ট্রেন বদলাতে হবে?", "ṭren bôdāte hobe?", "Do I have to change?")])),
        ("রেস্তোরাঁ।",
         v([("মেনু", "menu", "menu"), ("বিল", "bil", "bill"), ("স্টার্টার", "stārṭār", "starter"),
            ("অ্যালার্জি", "ælārji", "allergic"), ("ঝাল", "jhāl", "spicy"),
            ("পরামর্শ", "pôrāmorśo", "recommend"), ("টিপ", "ṭip", "tip"), ("টেবিল", "ṭebil", "table")]),
         g("চাই / দেবেন কি", "ভদ্র অর্ডার।", "আমি স্যুপ চাই",
           [("আমি স্যুপ চাই।", "āmi syup cāi", "I'd like the soup."),
            ("ঝাল রাখব?", "jhāl rākhbo?", "Would you like it spicy?"),
            ("মেনুটা দেবেন কি?", "menutā deben ki?", "I'd like to see the menu.")],
           ["ওয়েটারকে শুধু ‘দাও’ কর্কশ।", "চাই-এর পরে নাম।"]),
         d([("ওয়েটার", "অর্ডার করবেন?", "ôrḍār korben?", "Ready to order?"),
            ("স্যাম", "পাস্তা চাই। ঝাল কি?", "pāstā cāi. jhāl ki?", "I'd like the pasta. Is it spicy?"),
            ("ওয়েটার", "একটু। অ্যালার্জি আছে?", "ektu. ælārji āche?", "A little. Are you allergic?"),
            ("স্যাম", "না। শেষে বিল দেবেন।", "nā. śeṣe bil deben.", "No. The bill at the end, please.")])),
        ("নিমন্ত্রণ।",
         v([("নিমন্ত্রণ", "nimontrôṇ", "invitation"), ("ব্যস্ত", "bæsto", "busy", "adj"), ("দেখা করা", "dekhā kôra", "catch up", "verb"),
            ("আনা", "ānā", "bring", "verb"), ("পার্টি", "pārṭi", "party"), ("ফাঁকা", "phãkā", "free", "adj"),
            ("হয়তো", "hôyto", "maybe"), ("আগামী সপ্তাহ", "āgāmī saptāh", "next week")]),
         g("কেন না / চলো", "প্রস্তাব।", "কেন না সাতটায় দেখা করি?",
           [("কেন না সাতটায় দেখা করি?", "keno nā sātṭāy dekhā kori?", "Why don't we meet at seven?"),
            ("আগামী সপ্তাহে দেখা করি?", "āgāmī saptāhe dekhā kori?", "What if we catch up next week?"),
            ("কিছু খাবার আনি।", "kichu khābār āni", "Let's bring some food.")],
           ["শুধু ‘না’ কঠিন — কারণ দিন।", "চলো আদেশ নয়।"]),
         d([("রিয়া", "শুক্রবার পার্টি। যাব?", "śukrobār pārṭi. jābo?", "There's a party Friday. Shall we go?"),
            ("ওমর", "শুক্রবার ব্যস্ত। আগামী সপ্তাহ?", "śukrobār bæsto. āgāmī saptāh?", "I'm busy Friday. Next week?"),
            ("রিয়া", "রবিবার? ছয়টার পর ফাঁকা।", "robibār? chôyṭār pôr phãkā.", "Sunday? I'm free after six."),
            ("ওমর", "ঠিক আছে। মিষ্টি আমি আনব।", "ṭhik āche. miṣṭi āmi ānbo.", "Perfect. I'll bring dessert.")])),
        ("আবহাওয়া: যদি।",
         v([("পূর্বাভাস", "pūrbābhās", "forecast"), ("ঝড়বৃষ্টি", "jhôṛbriṣṭi", "shower"), ("আর্দ্র", "ārdro", "humid", "adj"),
            ("বাতিল", "bātil", "cancel"), ("ঘরে", "ghôre", "indoor"), ("ছাতা", "chātā", "umbrella"),
            ("ডিগ্রি", "ḍigri", "degree"), ("পরিষ্কার হওয়া", "poriṣkār hôoa", "clear up", "verb")]),
         g("যদি + হয়, তবে", "আসল শর্ত।", "যদি বৃষ্টি হয় তবে বাতিল করব",
           [("যদি বৃষ্টি হয় তবে পিকনিক বাতিল করব।", "jodi briṣṭi hôy tôbe picnic bātil korbo", "If it rains, we'll cancel the picnic."),
            ("পূর্বাভাস ভালো হলে হাঁটব।", "pūrbābhās bhālo hole hãṭbo", "If the forecast is good, we'll walk."),
            ("পরিষ্কার না হলে ঘরে থাকব।", "poriṣkār nā hole ghôre thākbo", "If it doesn't clear up, we'll stay inside.")],
           ["যদি-র ভিতরে আরেক ভবিষ্যৎ না থাকে।", "তবে ফল দেয়।"]),
         d([("জেন", "পূর্বাভাসে ঝড়বৃষ্টি।", "pūrbābhāse jhôṛbriṣṭi.", "The forecast says showers."),
            ("কাই", "বৃষ্টি হলে যাদুঘরে যাব।", "briṣṭi hole jādughôre jābo.", "If it rains, we'll go to the museum."),
            ("জেন", "তারপরও ছাতা নাও।", "tārporo chātā nāo.", "Take an umbrella anyway."),
            ("কাই", "পরিষ্কার হলে নদীর ধারে হাঁটব।", "poriṣkār hole nodīr dhāre hãṭbo.", "If it clears up, we'll walk by the river.")])),
        ("কেনাকাটা।",
         v([("সাইজ", "sāij", "size"), ("রসিদ", "rosid", "receipt"), ("ফেরত", "phērot", "refund"),
            ("ছাড়", "chāṛ", "discount"), ("নগদ", "nôgod", "cash"), ("কার্ড", "kārḍ", "card"),
            ("মানানো", "mānāno", "fit", "verb"), ("বদল", "bôdol", "exchange")]),
         g("চেয়ে / আরও", "তুলনা।", "এই জামাটা ওটার চেয়ে সস্তা",
           [("এই জামাটা ওটার চেয়ে সস্তা।", "ei jāmāṭā oṭār ceye sôstā", "This shirt is cheaper than that one."),
            ("নীলটা আরও দামি।", "nīlṭā āro dāmi", "The blue one is more expensive."),
            ("এম সাইজ ভালো মানায়।", "em sāij bhālo mānāy", "Size M fits better.")],
           ["‘আরও সস্তা চেয়ে’ দ্বিগুণ নয়।", "চেয়ে দ্বিতীয় পক্ষ।"]),
         d([("দোকান", "কার্ড না নগদ?", "kārḍ nā nôgod?", "Card or cash?"),
            ("লীলা", "কার্ড। ছোট সাইজ আছে?", "kārḍ. choṭo sāij āche?", "Card. Have you got a smaller size?"),
            ("দোকান", "আছে। ফেরতের জন্য রসিদ রাখুন।", "āche. phēroter jonyo rosid rākhun.", "Yes. Keep the receipt for a refund."),
            ("লীলা", "ছাত্র ছাড় আছে?", "chātro chāṛ āche?", "Is there a student discount?")])),
        ("অভ্যাস ও পরিকল্পনা।",
         v([("যাতায়াত", "jātāyāt", "commute"), ("শিফট", "śiphṭ", "shift"), ("অ্যালার্ম", "ælārm", "alarm"),
            ("জমানো", "jômāno", "save", "verb"), ("লক্ষ্য", "lokkho", "goal"), ("অভ্যাস", "ôbhās", "habit"),
            ("আগামী মাস", "āgāmī mās", "next month"), ("সাধারণত", "sādhārônoto", "usually", "adv")]),
         g("সাধারণত বর্তমান vs যাচ্ছি", "সময়সূচি বর্তমান; সিদ্ধান্ত যাচ্ছি।", "সাধারণত সাতটায় বের হই",
           [("সাধারণত সাতটায় বের হই।", "sādhārônoto sātṭāy ber hoi", "I usually leave at seven."),
            ("আগামী মাসে টাকা জমাতে যাচ্ছি।", "āgāmī māse ṭākā jômāte jācchi", "I'm going to save next month."),
            ("আমার শিফট নয়টায় শুরু।", "āmār śiphṭ nôyṭāy śuru", "My shift starts at nine.")],
           ["ছাপানো সময়সূচিতে যাচ্ছি নয়।", "গতকাল আর যাচ্ছি মেশাবেন না।"]),
         d([("ডানা", "সাধারণত কখন শুরু?", "sādhārônoto kôkhon śuru?", "What time do you usually start?"),
            ("নেড", "নয়টায় শিফট। আগামী মাসে বদলাব।", "nôyṭāy śiphṭ. āgāmī māse bôdābo.", "The shift starts at nine. I'm going to change it next month."),
            ("ডানা", "কেন?", "keno?", "Why?"),
            ("নেড", "যাতায়াত ছোট চাই। এটাই লক্ষ্য।", "jātāyāt choṭo cāi. eṭāi lokkho.", "I want a shorter commute. That's the goal.")])),
    ]


def _tr():
    return [
        ("Yakın plan: -ecek.",
         v([("sınav", "", "exam"), ("ders", "", "subject"), ("ödev", "", "homework"),
            ("program", "", "timetable"), ("son tarih", "", "deadline"),
            ("tekrar etmek", "", "revise", "verb"), ("ders", "", "lecture"), ("not", "", "notes")]),
         g("-ecek", "Karar verilmiş yakın gelecek.", "bu akşam tekrar edeceğim",
           [("Bu akşam tekrar edeceğim.", "", "I'm going to revise tonight."),
            ("Dersi kaçıracak.", "", "She's going to miss the lecture."),
            ("Ödevi bitirecek misin?", "", "Are you going to finish the homework?")],
           ["-ecek'ten önce fiil kökü.", "dün ile -ecek'i karıştırmayın."]),
         d([("Ana", "Yarın sınavın var mı?", "", "Have you got an exam tomorrow?"),
            ("Luis", "Evet, tarih. Dersten sonra tekrar edeceğim.", "", "Yes, history. I'll revise after class."),
            ("Ana", "Kütüphanede çalışalım mı?", "", "Shall we study in the library?"),
            ("Luis", "Evet. Notların son tarihi bugün.", "", "Yes. The notes deadline is today.")])),
        ("Hobiler: -mek hoşuma gidiyor.",
         v([("hobi", "", "hobby"), ("gitar", "", "guitar"), ("takım", "", "team"),
            ("antrenman", "", "practice"), ("hafta sonu", "", "weekend"),
            ("katılmak", "", "join", "verb"), ("konser", "", "concert"), ("çizmek", "", "draw", "verb")]),
         g("-mek hoşuna gitmek", "Fiil + -mek + hoşuna gidiyor.", "gitar çalmak hoşuma gidiyor",
           [("Gitar çalmak hoşuma gidiyor.", "", "I like playing guitar."),
            ("Beklemek hoşuna gitmiyor.", "", "She doesn't like waiting."),
            ("Hafta sonu çizmek hoşuna gidiyor mu?", "", "Do you like drawing at weekends?")],
           ["‘Ben hoşuma gidiyor gitar’ yanlış.", "hoşuna, hoşuma kişiye göre değişir."]),
         d([("Asha", "Hafta sonu ne yapıyorsun?", "", "What do you do at the weekend?"),
            ("Ben", "Gitar çalıyorum. Cumartesi konser var.", "", "I play guitar. There's a concert on Saturday."),
            ("Asha", "Çizmek hoşuma gidiyor. Gelir misin?", "", "I like drawing. Are you coming?"),
            ("Ben", "Antrenmandan sonra.", "", "Yes, after practice.")])),
        ("Bilet.",
         v([("peron", "", "platform"), ("gidiş-dönüş", "", "return ticket"),
            ("gecikme", "", "delay"), ("bagaj", "", "luggage"), ("kapı", "", "gate"),
            ("pasaport", "", "passport"), ("ayırmak", "", "book", "verb"), ("aktarma", "", "change trains")]),
         g("-meli / gerek", "Dış zorunluluk.", "pasaport göstermelisin",
           [("Pasaport göstermelisin.", "", "You have to show your passport."),
            ("Eskişehir'de aktarma yapmalıyız.", "", "We have to change in Eskişehir."),
            ("Bugün ayırması gerekmiyor.", "", "He doesn't have to book today.")],
           ["-meli fiile eklenir.", "gerekmiyor yasak değildir."]),
         d([("Gişe", "Tek yön mı, gidiş-dönüş mü?", "", "Single or return?"),
            ("Nina", "Gidiş-dönüş. Hangi peron?", "", "Return. Which platform?"),
            ("Gişe", "Dört. Kısa bir gecikme var.", "", "Platform 4. There's a short delay."),
            ("Nina", "Aktarma yapmam gerekir mi?", "", "Do I have to change?")])),
        ("Restoran.",
         v([("menü", "", "menu"), ("hesap", "", "bill"), ("başlangıç", "", "starter"),
            ("alerji", "", "allergic"), ("acı", "", "spicy", "adj"),
            ("önermek", "", "recommend", "verb"), ("bahşiş", "", "tip"), ("masa", "", "table")]),
         g("isterim", "Kibar sipariş.", "çorba isterim",
           [("Çorba isterim.", "", "I'd like the soup."),
            ("Acı olsun mu?", "", "Would you like it spicy?"),
            ("Menüyü görebilir miyim?", "", "I'd like to see the menu.")],
           ["Garsona ‘ver şunu’ kaba.", "isterim + ad."]),
         d([("Garson", "Sipariş verecek misiniz?", "", "Ready to order?"),
            ("Sam", "Makarna isterim. Acı mı?", "", "I'd like the pasta. Is it spicy?"),
            ("Garson", "Biraz. Alerjiniz var mı?", "", "A little. Are you allergic?"),
            ("Sam", "Yok. Hesabı sonda lütfen.", "", "No. The bill at the end, please.")])),
        ("Davet.",
         v([("davet", "", "invitation"), ("meşgul", "", "busy", "adj"), ("buluşmak", "", "catch up", "verb"),
            ("getirmek", "", "bring", "verb"), ("parti", "", "party"), ("boş", "", "free", "adj"),
            ("belki", "", "maybe"), ("gelecek hafta", "", "next week")]),
         g("-elim / -sek", "Öneri.", "saat yedide buluşalım",
           [("Saat yedide buluşalım.", "", "Why don't we meet at seven?"),
            ("Gelecek hafta buluşsak?", "", "What if we catch up next week?"),
            ("Yiyecek getirelim.", "", "Let's bring some food.")],
           ["Sadece ‘hayır’ sert: sebep verin.", "-elim emir değildir."]),
         d([("Riya", "Cuma parti var. Gidelim mi?", "", "There's a party Friday. Shall we go?"),
            ("Omar", "Cuma meşgulüm. Gelecek hafta?", "", "I'm busy Friday. Next week?"),
            ("Riya", "Pazar? Altıdan sonra boşum.", "", "Sunday? I'm free after six."),
            ("Omar", "Tamam. Tatlıyı ben getiririm.", "", "Perfect. I'll bring dessert.")])),
        ("Hava: eğer.",
         v([("tahmin", "", "forecast"), ("sağanak", "", "shower"), ("nemli", "", "humid", "adj"),
            ("iptal etmek", "", "cancel", "verb"), ("içeri", "", "indoor"), ("şemsiye", "", "umbrella"),
            ("derece", "", "degree"), ("açılmak", "", "clear up", "verb")]),
         g("eğer + -se", "Gerçek koşul.", "yağmur yağarsa iptal ederiz",
           [("Yağmur yağarsa pikniği iptal ederiz.", "", "If it rains, we'll cancel the picnic."),
            ("Tahmin iyiyse yürürüz.", "", "If the forecast is good, we'll walk."),
            ("Açılmazsa içeride kalırız.", "", "If it doesn't clear up, we'll stay inside.")],
           ["eğer cümlesine bir daha -ecek yığmayın.", "-sa koşuldur."]),
         d([("Jen", "Tahmin sağanak diyor.", "", "The forecast says showers."),
            ("Kai", "Yağarsa müzeye gideriz.", "", "If it rains, we'll go to the museum."),
            ("Jen", "Yine de şemsiye al.", "", "Take an umbrella anyway."),
            ("Kai", "Açılırsa nehir kenarında yürürüz.", "", "If it clears up, we'll walk by the river.")])),
        ("Alışveriş.",
         v([("beden", "", "size"), ("fiş", "", "receipt"), ("iade", "", "refund"),
            ("indirim", "", "discount"), ("nakit", "", "cash"), ("kart", "", "card"),
            ("olmak", "", "fit", "verb"), ("değiştirmek", "", "exchange", "verb")]),
         g("daha / -den", "Karşılaştırma.", "bu gömlek ondan ucuz",
           [("Bu gömlek ondan ucuz.", "", "This shirt is cheaper than that one."),
            ("Mavisi daha pahalı.", "", "The blue one is more expensive."),
            ("M beden daha iyi oluyor.", "", "Size M fits better.")],
           ["daha ucuzdan demeyin.", "-den ikinci terim."]),
         d([("Dükkân", "Kart mı nakit mi?", "", "Card or cash?"),
            ("Lila", "Kart. Daha küçük beden var mı?", "", "Card. Have you got a smaller size?"),
            ("Dükkân", "Var. İade için fişi saklayın.", "", "Yes. Keep the receipt for a refund."),
            ("Lila", "Öğrenci indirimi var mı?", "", "Is there a student discount?")])),
        ("Alışkanlık.",
         v([("yolculuk", "", "commute"), ("vardiya", "", "shift"), ("alarm", "", "alarm"),
            ("biriktirmek", "", "save", "verb"), ("hedef", "", "goal"), ("alışkanlık", "", "habit"),
            ("gelecek ay", "", "next month"), ("genelde", "", "usually", "adv")]),
         g("genelde şimdiki vs -ecek", "Çizelge şimdiki; karar -ecek.", "genelde yedide çıkıyorum",
           [("Genelde yedide çıkıyorum.", "", "I usually leave at seven."),
            ("Gelecek ay biriktireceğim.", "", "I'm going to save next month."),
            ("Vardiyam dokuzda başlıyor.", "", "My shift starts at nine.")],
           ["Basılı saate -ecek yakışmaz.", "dün ile -ecek karışmasın."]),
         d([("Dana", "Genelde saat kaçta başlıyorsun?", "", "What time do you usually start?"),
            ("Ned", "Dokuzda. Gelecek ay değiştireceğim.", "", "The shift starts at nine. I'm going to change it next month."),
            ("Dana", "Neden?", "", "Why?"),
            ("Ned", "Daha kısa yol istiyorum. Hedef bu.", "", "I want a shorter commute. That's the goal.")])),
    ]


def _id():
    return [
        ("Rencana dekat: akan / mau.",
         v([("ujian", "", "exam"), ("mata pelajaran", "", "subject"), ("pekerjaan rumah", "", "homework"),
            ("jadwal", "", "timetable"), ("tenggat", "", "deadline"),
            ("mengulang", "", "revise", "verb"), ("kuliah", "", "lecture"), ("catatan", "", "notes")]),
         g("akan / mau + verba", "Rencana yang sudah diputuskan.", "saya akan mengulang malam ini",
           [("Saya akan mengulang malam ini.", "", "I'm going to revise tonight."),
            ("Dia akan bolos kuliah.", "", "She's going to miss the lecture."),
            ("Kamu mau menyelesaikan PR?", "", "Are you going to finish the homework?")],
           ["Jangan ‘saya akan untuk mengulang’.", "akan + verba mentah."]),
         d([("Ana", "Besok ada ujian?", "", "Have you got an exam tomorrow?"),
            ("Luis", "Ya, sejarah. Habis kelas saya akan mengulang.", "", "Yes, history. I'll revise after class."),
            ("Ana", "Belajar di perpustakaan?", "", "Shall we study in the library?"),
            ("Luis", "Ya. Tenggat catatan hari ini.", "", "Yes. The notes deadline is today.")])),
        ("Hobi: suka + verba.",
         v([("hobi", "", "hobby"), ("gitar", "", "guitar"), ("tim", "", "team"),
            ("latihan", "", "practice"), ("akhir pekan", "", "weekend"),
            ("bergabung", "", "join", "verb"), ("konser", "", "concert"), ("menggambar", "", "draw", "verb")]),
         g("suka + verba", "Suka diikuti verba atau nomina.", "saya suka main gitar",
           [("Saya suka main gitar.", "", "I like playing guitar."),
            ("Dia tidak suka menunggu.", "", "She doesn't like waiting."),
            ("Kamu suka menggambar di akhir pekan?", "", "Do you like drawing at weekends?")],
           ["Bukan ‘saya suka untuk main’.", "tidak suka, bukan tidak menyukai selalu."]),
         d([("Asha", "Akhir pekan kamu ngapain?", "", "What do you do at the weekend?"),
            ("Ben", "Main gitar. Sabtu ada konser.", "", "I play guitar. There's a concert on Saturday."),
            ("Asha", "Saya suka menggambar. Ikut?", "", "I like drawing. Are you coming?"),
            ("Ben", "Habis latihan.", "", "Yes, after practice.")])),
        ("Tiket.",
         v([("peron", "", "platform"), ("tiket pulang-pergi", "", "return ticket"),
            ("keterlambatan", "", "delay"), ("bagasi", "", "luggage"), ("pintu", "", "gate"),
            ("paspor", "", "passport"), ("memesan", "", "book", "verb"), ("transit", "", "change trains")]),
         g("harus + verba", "Kewajiban luar.", "kamu harus tunjukkan paspor",
           [("Kamu harus tunjukkan paspor.", "", "You have to show your passport."),
            ("Kita harus transit di Bandung.", "", "We have to change in Bandung."),
            ("Dia tidak harus memesan hari ini.", "", "He doesn't have to book today.")],
           ["harus + verba, tanpa ‘untuk’ wajib.", "tidak harus ≠ dilarang."]),
         d([("Loket", "Sekali jalan atau pulang-pergi?", "", "Single or return?"),
            ("Nina", "Pulang-pergi. Peron berapa?", "", "Return. Which platform?"),
            ("Loket", "Empat. Ada keterlambatan singkat.", "", "Platform 4. There's a short delay."),
            ("Nina", "Harus transit?", "", "Do I have to change?")])),
        ("Restoran.",
         v([("menu", "", "menu"), ("bon", "", "bill"), ("pembuka", "", "starter"),
            ("alergi", "", "allergic"), ("pedas", "", "spicy", "adj"),
            ("merekomendasikan", "", "recommend", "verb"), ("tip", "", "tip"), ("meja", "", "table")]),
         g("saya mau", "Pesanan sopan.", "saya mau sop",
           [("Saya mau sop.", "", "I'd like the soup."),
            ("Mau pedas?", "", "Would you like it spicy?"),
            ("Boleh lihat menu?", "", "I'd like to see the menu.")],
           ["Ke pelayan, ‘kasih ini’ kasar.", "mau + nomina."]),
         d([("Pelayan", "Sudah siap pesan?", "", "Ready to order?"),
            ("Sam", "Saya mau pasta. Pedas tidak?", "", "I'd like the pasta. Is it spicy?"),
            ("Pelayan", "Sedikit. Ada alergi?", "", "A little. Are you allergic?"),
            ("Sam", "Tidak. Bon di akhir, ya.", "", "No. The bill at the end, please.")])),
        ("Undangan.",
         v([("undangan", "", "invitation"), ("sibuk", "", "busy", "adj"), ("ketemu", "", "catch up", "verb"),
            ("bawa", "", "bring", "verb"), ("pesta", "", "party"), ("luang", "", "free"),
            ("mungkin", "", "maybe"), ("minggu depan", "", "next week")]),
         g("bagaimana kalau", "Saran, bukan perintah.", "bagaimana kalau ketemu jam tujuh?",
           [("Bagaimana kalau ketemu jam tujuh?", "", "Why don't we meet at seven?"),
            ("Minggu depan saja?", "", "What if we catch up next week?"),
            ("Kita bawa makanan.", "", "Let's bring some food.")],
           ["‘Tidak’ polos terasa keras: beri alasan.", "bagaimana kalau + klausa."]),
         d([("Riya", "Jumat ada pesta. Pergi?", "", "There's a party Friday. Shall we go?"),
            ("Omar", "Jumat sibuk. Minggu depan?", "", "I'm busy Friday. Next week?"),
            ("Riya", "Minggu? Setelah jam enam saya luang.", "", "Sunday? I'm free after six."),
            ("Omar", "Sip. Saya bawa pencuci mulut.", "", "Perfect. I'll bring dessert.")])),
        ("Cuaca: kalau.",
         v([("prakiraan", "", "forecast"), ("gerimis", "", "shower"), ("lembab", "", "humid", "adj"),
            ("membatalkan", "", "cancel", "verb"), ("di dalam", "", "indoor"), ("payung", "", "umbrella"),
            ("derajat", "", "degree"), ("cerah", "", "clear up")]),
         g("kalau + sekarang, akan", "Syarat nyata.", "kalau hujan, kita batalkan",
           [("Kalau hujan, kita batalkan piknik.", "", "If it rains, we'll cancel the picnic."),
            ("Kalau prakiraan bagus, kita jalan.", "", "If the forecast is good, we'll walk."),
            ("Kalau tidak cerah, kita di dalam.", "", "If it doesn't clear up, we'll stay inside.")],
           ["Jangan tumpuk akan di klausa kalau.", "kalau = syarat."]),
         d([("Jen", "Prakiraan bilang gerimis.", "", "The forecast says showers."),
            ("Kai", "Kalau hujan, ke museum.", "", "If it rains, we'll go to the museum."),
            ("Jen", "Tetap bawa payung.", "", "Take an umbrella anyway."),
            ("Kai", "Kalau cerah, jalan di sungai.", "", "If it clears up, we'll walk by the river.")])),
        ("Belanja.",
         v([("ukuran", "", "size"), ("struk", "", "receipt"), ("pengembalian", "", "refund"),
            ("diskon", "", "discount"), ("tunai", "", "cash"), ("kartu", "", "card"),
            ("muat", "", "fit", "verb"), ("tukar", "", "exchange", "verb")]),
         g("lebih ... daripada", "Perbandingan.", "kemeja ini lebih murah daripada itu",
           [("Kemeja ini lebih murah daripada itu.", "", "This shirt is cheaper than that one."),
            ("Yang biru lebih mahal.", "", "The blue one is more expensive."),
            ("Ukuran M lebih muat.", "", "Size M fits better.")],
           ["Jangan ‘lebih lebih murah’.", "daripada suku kedua."]),
         d([("Toko", "Kartu atau tunai?", "", "Card or cash?"),
            ("Lila", "Kartu. Ada ukuran lebih kecil?", "", "Card. Have you got a smaller size?"),
            ("Toko", "Ada. Simpan struk untuk pengembalian.", "", "Yes. Keep the receipt for a refund."),
            ("Lila", "Ada diskon pelajar?", "", "Is there a student discount?")])),
        ("Kebiasaan.",
         v([("pergi-pulang", "", "commute"), ("giliran", "", "shift"), ("alarm", "", "alarm"),
            ("menabung", "", "save", "verb"), ("tujuan", "", "goal"), ("kebiasaan", "", "habit"),
            ("bulan depan", "", "next month"), ("biasanya", "", "usually", "adv")]),
         g("biasanya kini vs akan", "Jadwal kini; keputusan akan.", "biasanya saya berangkat jam tujuh",
           [("Biasanya saya berangkat jam tujuh.", "", "I usually leave at seven."),
            ("Bulan depan saya akan menabung.", "", "I'm going to save next month."),
            ("Giliran saya mulai jam sembilan.", "", "My shift starts at nine.")],
           ["Jadwal tercetak jangan pakai akan.", "Jangan campur kemarin dan akan."]),
         d([("Dana", "Biasanya mulai jam berapa?", "", "What time do you usually start?"),
            ("Ned", "Jam sembilan. Bulan depan saya akan ganti.", "", "The shift starts at nine. I'm going to change it next month."),
            ("Dana", "Kenapa?", "", "Why?"),
            ("Ned", "Mau perjalanan lebih pendek. Itu tujuannya.", "", "I want a shorter commute. That's the goal.")])),
    ]


DATA = {"bn": _bn(), "tr": _tr(), "id": _id()}
