/* GENERATED by tools/adminstats.js — do not edit.
   Real numbers for admin.html, computed at build time from the
   same generators and validators that produce the site.
   Contains NO secrets and NO personal addresses: it is served
   publicly like every other file here.
   Regenerate: node tools/adminstats.js */
window.EKGURU_ADMIN_STATS = {
 "generated": "2026-09-12T06:45:10.591Z",
 "sections": {
  "countryPages": 158,
  "languagePages": 30,
  "nativePages": 6,
  "topicPillars": 34,
  "tools": 12,
  "dailyLessons": 30,
  "guides": 15,
  "questions": 43,
  "answers": 28,
  "locations": 32,
  "tutorProfiles": 4,
  "totalHtml": 606,
  "materials": 0
 },
 "countries": {
  "total": 196,
  "published": 158,
  "planned": 38,
  "tiers": {
   "A": 22,
   "B": 19,
   "C": 33,
   "D": 122
  },
  "tiersPublished": {
   "A": 22,
   "B": 19,
   "C": 33,
   "D": 84
  },
  "rows": [
   {
    "iso2": "US",
    "iso3": "USA",
    "name": "United States",
    "tier": "A",
    "currency": "USD",
    "utc": -5,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": true,
    "slug": "learn-hindi-from-usa/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "GB",
    "iso3": "GBR",
    "name": "United Kingdom",
    "tier": "A",
    "currency": "GBP",
    "utc": 0,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": true,
    "slug": "learn-hindi-from-uk/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "CA",
    "iso3": "CAN",
    "name": "Canada",
    "tier": "A",
    "currency": "CAD",
    "utc": -5,
    "languages": [
     "en",
     "fr"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": true,
    "slug": "learn-hindi-from-canada/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "AU",
    "iso3": "AUS",
    "name": "Australia",
    "tier": "A",
    "currency": "AUD",
    "utc": 10,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": true,
    "slug": "learn-hindi-from-australia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "AE",
    "iso3": "ARE",
    "name": "United Arab Emirates",
    "tier": "A",
    "currency": "AED",
    "utc": 4,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": true,
    "diaspora": true,
    "slug": "learn-hindi-from-uae/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "SG",
    "iso3": "SGP",
    "name": "Singapore",
    "tier": "A",
    "currency": "SGD",
    "utc": 8,
    "languages": [
     "en",
     "zh",
     "ms",
     "ta"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": true,
    "slug": "learn-hindi-from-singapore/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "DE",
    "iso3": "DEU",
    "name": "Germany",
    "tier": "A",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "de"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-germany/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "JP",
    "iso3": "JPN",
    "name": "Japan",
    "tier": "A",
    "currency": "JPY",
    "utc": 9,
    "languages": [
     "ja"
    ],
    "script": "Japanese",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-japan/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "ZA",
    "iso3": "ZAF",
    "name": "South Africa",
    "tier": "A",
    "currency": "ZAR",
    "utc": 2,
    "languages": [
     "en",
     "af",
     "zu"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-south-africa/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "NP",
    "iso3": "NPL",
    "name": "Nepal",
    "tier": "A",
    "currency": "NPR",
    "utc": 5.75,
    "languages": [
     "ne"
    ],
    "script": "Devanagari",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-nepal/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "ES",
    "iso3": "ESP",
    "name": "Spain",
    "tier": "A",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-spain/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BR",
    "iso3": "BRA",
    "name": "Brazil",
    "tier": "A",
    "currency": "BRL",
    "utc": -3,
    "languages": [
     "pt"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-brazil/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "FR",
    "iso3": "FRA",
    "name": "France",
    "tier": "A",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-france/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "MU",
    "iso3": "MUS",
    "name": "Mauritius",
    "tier": "A",
    "currency": "MUR",
    "utc": 4,
    "languages": [
     "en",
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-mauritius/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "FJ",
    "iso3": "FJI",
    "name": "Fiji",
    "tier": "A",
    "currency": "FJD",
    "utc": 12,
    "languages": [
     "en",
     "fj"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-fiji/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "TT",
    "iso3": "TTO",
    "name": "Trinidad and Tobago",
    "tier": "A",
    "currency": "TTD",
    "utc": -4,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-trinidad-and-tobago/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "GY",
    "iso3": "GUY",
    "name": "Guyana",
    "tier": "A",
    "currency": "GYD",
    "utc": -4,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-guyana/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "SR",
    "iso3": "SUR",
    "name": "Suriname",
    "tier": "A",
    "currency": "SRD",
    "utc": -3,
    "languages": [
     "nl"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-suriname/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "MY",
    "iso3": "MYS",
    "name": "Malaysia",
    "tier": "A",
    "currency": "MYR",
    "utc": 8,
    "languages": [
     "ms",
     "en"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": true,
    "slug": "learn-hindi-from-malaysia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "QA",
    "iso3": "QAT",
    "name": "Qatar",
    "tier": "A",
    "currency": "QAR",
    "utc": 3,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-qatar/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "SA",
    "iso3": "SAU",
    "name": "Saudi Arabia",
    "tier": "A",
    "currency": "SAR",
    "utc": 3,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-saudi-arabia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "OM",
    "iso3": "OMN",
    "name": "Oman",
    "tier": "B",
    "currency": "OMR",
    "utc": 4,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-oman/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "KW",
    "iso3": "KWT",
    "name": "Kuwait",
    "tier": "B",
    "currency": "KWD",
    "utc": 3,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-kuwait/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "NL",
    "iso3": "NLD",
    "name": "Netherlands",
    "tier": "B",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "nl"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": true,
    "slug": "learn-hindi-from-netherlands/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "IT",
    "iso3": "ITA",
    "name": "Italy",
    "tier": "B",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "it"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": true,
    "slug": "learn-hindi-from-italy/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "RU",
    "iso3": "RUS",
    "name": "Russia",
    "tier": "B",
    "currency": "RUB",
    "utc": 3,
    "languages": [
     "ru"
    ],
    "script": "Cyrillic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-russia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "TR",
    "iso3": "TUR",
    "name": "Türkiye",
    "tier": "B",
    "currency": "TRY",
    "utc": 3,
    "languages": [
     "tr"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-turkiye/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "ID",
    "iso3": "IDN",
    "name": "Indonesia",
    "tier": "B",
    "currency": "IDR",
    "utc": 7,
    "languages": [
     "id"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-indonesia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "TH",
    "iso3": "THA",
    "name": "Thailand",
    "tier": "B",
    "currency": "THB",
    "utc": 7,
    "languages": [
     "th"
    ],
    "script": "Thai",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-thailand/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "KR",
    "iso3": "KOR",
    "name": "South Korea",
    "tier": "B",
    "currency": "KRW",
    "utc": 9,
    "languages": [
     "ko"
    ],
    "script": "Hangul",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-south-korea/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "CN",
    "iso3": "CHN",
    "name": "China",
    "tier": "B",
    "currency": "CNY",
    "utc": 8,
    "languages": [
     "zh"
    ],
    "script": "Han",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-china/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "PL",
    "iso3": "POL",
    "name": "Poland",
    "tier": "B",
    "currency": "PLN",
    "utc": 1,
    "languages": [
     "pl"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-poland/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "KE",
    "iso3": "KEN",
    "name": "Kenya",
    "tier": "B",
    "currency": "KES",
    "utc": 3,
    "languages": [
     "sw",
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-kenya/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "TZ",
    "iso3": "TZA",
    "name": "Tanzania",
    "tier": "C",
    "currency": "TZS",
    "utc": 3,
    "languages": [
     "sw",
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-tanzania/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "MX",
    "iso3": "MEX",
    "name": "Mexico",
    "tier": "B",
    "currency": "MXN",
    "utc": -6,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-mexico/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "AR",
    "iso3": "ARG",
    "name": "Argentina",
    "tier": "C",
    "currency": "ARS",
    "utc": -3,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-argentina/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "PT",
    "iso3": "PRT",
    "name": "Portugal",
    "tier": "B",
    "currency": "EUR",
    "utc": 0,
    "languages": [
     "pt"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": true,
    "slug": "learn-hindi-from-portugal/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "IE",
    "iso3": "IRL",
    "name": "Ireland",
    "tier": "C",
    "currency": "EUR",
    "utc": 0,
    "languages": [
     "en",
     "ga"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-ireland/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "NZ",
    "iso3": "NZL",
    "name": "New Zealand",
    "tier": "B",
    "currency": "NZD",
    "utc": 12,
    "languages": [
     "en",
     "mi"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": true,
    "slug": "learn-hindi-from-new-zealand/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "CH",
    "iso3": "CHE",
    "name": "Switzerland",
    "tier": "C",
    "currency": "CHF",
    "utc": 1,
    "languages": [
     "de",
     "fr",
     "it"
    ],
    "script": "Latin",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-switzerland/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "SE",
    "iso3": "SWE",
    "name": "Sweden",
    "tier": "C",
    "currency": "SEK",
    "utc": 1,
    "languages": [
     "sv"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-sweden/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "NO",
    "iso3": "NOR",
    "name": "Norway",
    "tier": "D",
    "currency": "NOK",
    "utc": 1,
    "languages": [
     "no"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-norway/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "IL",
    "iso3": "ISR",
    "name": "Israel",
    "tier": "B",
    "currency": "ILS",
    "utc": 2,
    "languages": [
     "he"
    ],
    "script": "Hebrew",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-israel/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "LK",
    "iso3": "LKA",
    "name": "Sri Lanka",
    "tier": "B",
    "currency": "LKR",
    "utc": 5.5,
    "languages": [
     "si",
     "ta"
    ],
    "script": "Sinhala",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-sri-lanka/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BD",
    "iso3": "BGD",
    "name": "Bangladesh",
    "tier": "B",
    "currency": "BDT",
    "utc": 6,
    "languages": [
     "bn"
    ],
    "script": "Bengali",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-bangladesh/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "PK",
    "iso3": "PAK",
    "name": "Pakistan",
    "tier": "B",
    "currency": "PKR",
    "utc": 5,
    "languages": [
     "ur"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-pakistan/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "MM",
    "iso3": "MMR",
    "name": "Myanmar",
    "tier": "C",
    "currency": "MMK",
    "utc": 6.5,
    "languages": [
     "my"
    ],
    "script": "Myanmar",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-myanmar/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "PH",
    "iso3": "PHL",
    "name": "Philippines",
    "tier": "C",
    "currency": "PHP",
    "utc": 8,
    "languages": [
     "tl",
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-philippines/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "VN",
    "iso3": "VNM",
    "name": "Vietnam",
    "tier": "C",
    "currency": "VND",
    "utc": 7,
    "languages": [
     "vi"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-vietnam/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "EG",
    "iso3": "EGY",
    "name": "Egypt",
    "tier": "C",
    "currency": "EGP",
    "utc": 2,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-egypt/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "NG",
    "iso3": "NGA",
    "name": "Nigeria",
    "tier": "C",
    "currency": "NGN",
    "utc": 1,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-nigeria/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "GH",
    "iso3": "GHA",
    "name": "Ghana",
    "tier": "D",
    "currency": "GHS",
    "utc": 0,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-ghana/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "AF",
    "iso3": "AFG",
    "name": "Afghanistan",
    "tier": "C",
    "currency": "AFN",
    "utc": 4.5,
    "languages": [
     "ps",
     "fa"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-afghanistan/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "AL",
    "iso3": "ALB",
    "name": "Albania",
    "tier": "D",
    "currency": "ALL",
    "utc": 1,
    "languages": [
     "sq"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-albania/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "DZ",
    "iso3": "DZA",
    "name": "Algeria",
    "tier": "D",
    "currency": "DZD",
    "utc": 1,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-algeria/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "AD",
    "iso3": "AND",
    "name": "Andorra",
    "tier": "D",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "ca"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "AO",
    "iso3": "AGO",
    "name": "Angola",
    "tier": "D",
    "currency": "AOA",
    "utc": 1,
    "languages": [
     "pt"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "AG",
    "iso3": "ATG",
    "name": "Antigua and Barbuda",
    "tier": "D",
    "currency": "XCD",
    "utc": -4,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "AM",
    "iso3": "ARM",
    "name": "Armenia",
    "tier": "D",
    "currency": "AMD",
    "utc": 4,
    "languages": [
     "hy"
    ],
    "script": "Armenian",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-armenia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "AT",
    "iso3": "AUT",
    "name": "Austria",
    "tier": "C",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "de"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-austria/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "AZ",
    "iso3": "AZE",
    "name": "Azerbaijan",
    "tier": "D",
    "currency": "AZN",
    "utc": 4,
    "languages": [
     "az"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-azerbaijan/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BS",
    "iso3": "BHS",
    "name": "Bahamas",
    "tier": "D",
    "currency": "BSD",
    "utc": -5,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "BH",
    "iso3": "BHR",
    "name": "Bahrain",
    "tier": "C",
    "currency": "BHD",
    "utc": 3,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-bahrain/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BB",
    "iso3": "BRB",
    "name": "Barbados",
    "tier": "D",
    "currency": "BBD",
    "utc": -4,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-barbados/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BY",
    "iso3": "BLR",
    "name": "Belarus",
    "tier": "D",
    "currency": "BYN",
    "utc": 3,
    "languages": [
     "be",
     "ru"
    ],
    "script": "Cyrillic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-belarus/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BE",
    "iso3": "BEL",
    "name": "Belgium",
    "tier": "C",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "nl",
     "fr",
     "de"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-belgium/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BZ",
    "iso3": "BLZ",
    "name": "Belize",
    "tier": "D",
    "currency": "BZD",
    "utc": -6,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-belize/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BJ",
    "iso3": "BEN",
    "name": "Benin",
    "tier": "D",
    "currency": "XOF",
    "utc": 1,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "BT",
    "iso3": "BTN",
    "name": "Bhutan",
    "tier": "C",
    "currency": "BTN",
    "utc": 6,
    "languages": [
     "dz"
    ],
    "script": "Tibetan",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-bhutan/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BO",
    "iso3": "BOL",
    "name": "Bolivia",
    "tier": "D",
    "currency": "BOB",
    "utc": -4,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-bolivia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BA",
    "iso3": "BIH",
    "name": "Bosnia and Herzegovina",
    "tier": "D",
    "currency": "BAM",
    "utc": 1,
    "languages": [
     "bs"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-bosnia-and-herzegovina/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BW",
    "iso3": "BWA",
    "name": "Botswana",
    "tier": "D",
    "currency": "BWP",
    "utc": 2,
    "languages": [
     "en",
     "tn"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-botswana/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BN",
    "iso3": "BRN",
    "name": "Brunei",
    "tier": "D",
    "currency": "BND",
    "utc": 8,
    "languages": [
     "ms"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-brunei/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BG",
    "iso3": "BGR",
    "name": "Bulgaria",
    "tier": "D",
    "currency": "BGN",
    "utc": 2,
    "languages": [
     "bg"
    ],
    "script": "Cyrillic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-bulgaria/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "BF",
    "iso3": "BFA",
    "name": "Burkina Faso",
    "tier": "D",
    "currency": "XOF",
    "utc": 0,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "BI",
    "iso3": "BDI",
    "name": "Burundi",
    "tier": "D",
    "currency": "BIF",
    "utc": 2,
    "languages": [
     "fr",
     "rn"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "CV",
    "iso3": "CPV",
    "name": "Cabo Verde",
    "tier": "D",
    "currency": "CVE",
    "utc": -1,
    "languages": [
     "pt"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "KH",
    "iso3": "KHM",
    "name": "Cambodia",
    "tier": "D",
    "currency": "KHR",
    "utc": 7,
    "languages": [
     "km"
    ],
    "script": "Khmer",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-cambodia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "CM",
    "iso3": "CMR",
    "name": "Cameroon",
    "tier": "D",
    "currency": "XAF",
    "utc": 1,
    "languages": [
     "fr",
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-cameroon/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "CF",
    "iso3": "CAF",
    "name": "Central African Republic",
    "tier": "D",
    "currency": "XAF",
    "utc": 1,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "TD",
    "iso3": "TCD",
    "name": "Chad",
    "tier": "D",
    "currency": "XAF",
    "utc": 1,
    "languages": [
     "fr",
     "ar"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "CL",
    "iso3": "CHL",
    "name": "Chile",
    "tier": "C",
    "currency": "CLP",
    "utc": -4,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-chile/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "CO",
    "iso3": "COL",
    "name": "Colombia",
    "tier": "C",
    "currency": "COP",
    "utc": -5,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-colombia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "KM",
    "iso3": "COM",
    "name": "Comoros",
    "tier": "D",
    "currency": "KMF",
    "utc": 3,
    "languages": [
     "ar",
     "fr"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-comoros/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "CG",
    "iso3": "COG",
    "name": "Republic of the Congo",
    "tier": "D",
    "currency": "XAF",
    "utc": 1,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-congo/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "CD",
    "iso3": "COD",
    "name": "Democratic Republic of the Congo",
    "tier": "D",
    "currency": "CDF",
    "utc": 1,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-dr-congo/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "CR",
    "iso3": "CRI",
    "name": "Costa Rica",
    "tier": "D",
    "currency": "CRC",
    "utc": -6,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-costa-rica/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "CI",
    "iso3": "CIV",
    "name": "Côte d'Ivoire",
    "tier": "D",
    "currency": "XOF",
    "utc": 0,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-cote-divoire/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "HR",
    "iso3": "HRV",
    "name": "Croatia",
    "tier": "D",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "hr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-croatia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "CU",
    "iso3": "CUB",
    "name": "Cuba",
    "tier": "D",
    "currency": "CUP",
    "utc": -5,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-cuba/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "CY",
    "iso3": "CYP",
    "name": "Cyprus",
    "tier": "D",
    "currency": "EUR",
    "utc": 2,
    "languages": [
     "el",
     "tr"
    ],
    "script": "Greek",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-cyprus/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "CZ",
    "iso3": "CZE",
    "name": "Czechia",
    "tier": "C",
    "currency": "CZK",
    "utc": 1,
    "languages": [
     "cs"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-czechia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "DK",
    "iso3": "DNK",
    "name": "Denmark",
    "tier": "C",
    "currency": "DKK",
    "utc": 1,
    "languages": [
     "da"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-denmark/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "DJ",
    "iso3": "DJI",
    "name": "Djibouti",
    "tier": "D",
    "currency": "DJF",
    "utc": 3,
    "languages": [
     "fr",
     "ar"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-djibouti/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "DM",
    "iso3": "DMA",
    "name": "Dominica",
    "tier": "D",
    "currency": "XCD",
    "utc": -4,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "DO",
    "iso3": "DOM",
    "name": "Dominican Republic",
    "tier": "D",
    "currency": "DOP",
    "utc": -4,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-dominican-republic/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "EC",
    "iso3": "ECU",
    "name": "Ecuador",
    "tier": "D",
    "currency": "USD",
    "utc": -5,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-ecuador/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "SV",
    "iso3": "SLV",
    "name": "El Salvador",
    "tier": "D",
    "currency": "USD",
    "utc": -6,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-el-salvador/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "GQ",
    "iso3": "GNQ",
    "name": "Equatorial Guinea",
    "tier": "D",
    "currency": "XAF",
    "utc": 1,
    "languages": [
     "es",
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "ER",
    "iso3": "ERI",
    "name": "Eritrea",
    "tier": "D",
    "currency": "ERN",
    "utc": 3,
    "languages": [
     "ti",
     "ar"
    ],
    "script": "Ge'ez",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-eritrea/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "EE",
    "iso3": "EST",
    "name": "Estonia",
    "tier": "D",
    "currency": "EUR",
    "utc": 2,
    "languages": [
     "et"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-estonia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "SZ",
    "iso3": "SWZ",
    "name": "Eswatini",
    "tier": "D",
    "currency": "SZL",
    "utc": 2,
    "languages": [
     "en",
     "ss"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-eswatini/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "ET",
    "iso3": "ETH",
    "name": "Ethiopia",
    "tier": "D",
    "currency": "ETB",
    "utc": 3,
    "languages": [
     "am"
    ],
    "script": "Ge'ez",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-ethiopia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "FI",
    "iso3": "FIN",
    "name": "Finland",
    "tier": "C",
    "currency": "EUR",
    "utc": 2,
    "languages": [
     "fi",
     "sv"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-finland/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "GA",
    "iso3": "GAB",
    "name": "Gabon",
    "tier": "D",
    "currency": "XAF",
    "utc": 1,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-gabon/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "GM",
    "iso3": "GMB",
    "name": "Gambia",
    "tier": "D",
    "currency": "GMD",
    "utc": 0,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "GE",
    "iso3": "GEO",
    "name": "Georgia",
    "tier": "D",
    "currency": "GEL",
    "utc": 4,
    "languages": [
     "ka"
    ],
    "script": "Georgian",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-georgia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "GR",
    "iso3": "GRC",
    "name": "Greece",
    "tier": "C",
    "currency": "EUR",
    "utc": 2,
    "languages": [
     "el"
    ],
    "script": "Greek",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-greece/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "GD",
    "iso3": "GRD",
    "name": "Grenada",
    "tier": "D",
    "currency": "XCD",
    "utc": -4,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-grenada/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "GT",
    "iso3": "GTM",
    "name": "Guatemala",
    "tier": "D",
    "currency": "GTQ",
    "utc": -6,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-guatemala/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "GN",
    "iso3": "GIN",
    "name": "Guinea",
    "tier": "D",
    "currency": "GNF",
    "utc": 0,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "GW",
    "iso3": "GNB",
    "name": "Guinea-Bissau",
    "tier": "D",
    "currency": "XOF",
    "utc": 0,
    "languages": [
     "pt"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "HT",
    "iso3": "HTI",
    "name": "Haiti",
    "tier": "D",
    "currency": "HTG",
    "utc": -5,
    "languages": [
     "fr",
     "ht"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-haiti/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "HN",
    "iso3": "HND",
    "name": "Honduras",
    "tier": "D",
    "currency": "HNL",
    "utc": -6,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-honduras/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "HU",
    "iso3": "HUN",
    "name": "Hungary",
    "tier": "C",
    "currency": "HUF",
    "utc": 1,
    "languages": [
     "hu"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-hungary/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "IS",
    "iso3": "ISL",
    "name": "Iceland",
    "tier": "D",
    "currency": "ISK",
    "utc": 0,
    "languages": [
     "is"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-iceland/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "IN",
    "iso3": "IND",
    "name": "India",
    "tier": "A",
    "currency": "INR",
    "utc": 5.5,
    "languages": [
     "hi",
     "en"
    ],
    "script": "Devanagari",
    "travel": true,
    "diaspora": true,
    "slug": "learn-hindi-from-india/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "IR",
    "iso3": "IRN",
    "name": "Iran",
    "tier": "C",
    "currency": "IRR",
    "utc": 3.5,
    "languages": [
     "fa"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-iran/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "IQ",
    "iso3": "IRQ",
    "name": "Iraq",
    "tier": "D",
    "currency": "IQD",
    "utc": 3,
    "languages": [
     "ar",
     "ku"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-iraq/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "JM",
    "iso3": "JAM",
    "name": "Jamaica",
    "tier": "C",
    "currency": "JMD",
    "utc": -5,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-jamaica/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "JO",
    "iso3": "JOR",
    "name": "Jordan",
    "tier": "D",
    "currency": "JOD",
    "utc": 3,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-jordan/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "KZ",
    "iso3": "KAZ",
    "name": "Kazakhstan",
    "tier": "C",
    "currency": "KZT",
    "utc": 5,
    "languages": [
     "kk",
     "ru"
    ],
    "script": "Cyrillic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-kazakhstan/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "KI",
    "iso3": "KIR",
    "name": "Kiribati",
    "tier": "D",
    "currency": "AUD",
    "utc": 12,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "KP",
    "iso3": "PRK",
    "name": "North Korea",
    "tier": "D",
    "currency": "KPW",
    "utc": 9,
    "languages": [
     "ko"
    ],
    "script": "Hangul",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "XK",
    "iso3": "XKX",
    "name": "Kosovo",
    "tier": "D",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "sq",
     "sr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-kosovo/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "KG",
    "iso3": "KGZ",
    "name": "Kyrgyzstan",
    "tier": "D",
    "currency": "KGS",
    "utc": 6,
    "languages": [
     "ky",
     "ru"
    ],
    "script": "Cyrillic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-kyrgyzstan/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "LA",
    "iso3": "LAO",
    "name": "Laos",
    "tier": "D",
    "currency": "LAK",
    "utc": 7,
    "languages": [
     "lo"
    ],
    "script": "Lao",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-laos/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "LV",
    "iso3": "LVA",
    "name": "Latvia",
    "tier": "D",
    "currency": "EUR",
    "utc": 2,
    "languages": [
     "lv"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-latvia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "LB",
    "iso3": "LBN",
    "name": "Lebanon",
    "tier": "D",
    "currency": "LBP",
    "utc": 2,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-lebanon/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "LS",
    "iso3": "LSO",
    "name": "Lesotho",
    "tier": "D",
    "currency": "LSL",
    "utc": 2,
    "languages": [
     "en",
     "st"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-lesotho/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "LR",
    "iso3": "LBR",
    "name": "Liberia",
    "tier": "D",
    "currency": "LRD",
    "utc": 0,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "LY",
    "iso3": "LBY",
    "name": "Libya",
    "tier": "D",
    "currency": "LYD",
    "utc": 2,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-libya/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "LI",
    "iso3": "LIE",
    "name": "Liechtenstein",
    "tier": "D",
    "currency": "CHF",
    "utc": 1,
    "languages": [
     "de"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "LT",
    "iso3": "LTU",
    "name": "Lithuania",
    "tier": "C",
    "currency": "EUR",
    "utc": 2,
    "languages": [
     "lt"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-lithuania/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "LU",
    "iso3": "LUX",
    "name": "Luxembourg",
    "tier": "D",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "lb",
     "fr",
     "de"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-luxembourg/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "MG",
    "iso3": "MDG",
    "name": "Madagascar",
    "tier": "D",
    "currency": "MGA",
    "utc": 3,
    "languages": [
     "mg",
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-madagascar/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "MW",
    "iso3": "MWI",
    "name": "Malawi",
    "tier": "D",
    "currency": "MWK",
    "utc": 2,
    "languages": [
     "en",
     "ny"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-malawi/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "MV",
    "iso3": "MDV",
    "name": "Maldives",
    "tier": "C",
    "currency": "MVR",
    "utc": 5,
    "languages": [
     "dv"
    ],
    "script": "Thaana",
    "travel": true,
    "diaspora": false,
    "slug": "learn-hindi-from-maldives/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "ML",
    "iso3": "MLI",
    "name": "Mali",
    "tier": "D",
    "currency": "XOF",
    "utc": 0,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "MT",
    "iso3": "MLT",
    "name": "Malta",
    "tier": "D",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "mt",
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-malta/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "MH",
    "iso3": "MHL",
    "name": "Marshall Islands",
    "tier": "D",
    "currency": "USD",
    "utc": 12,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "MR",
    "iso3": "MRT",
    "name": "Mauritania",
    "tier": "D",
    "currency": "MRU",
    "utc": 0,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-mauritania/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "FM",
    "iso3": "FSM",
    "name": "Micronesia",
    "tier": "D",
    "currency": "USD",
    "utc": 11,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "MD",
    "iso3": "MDA",
    "name": "Moldova",
    "tier": "D",
    "currency": "MDL",
    "utc": 2,
    "languages": [
     "ro"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-moldova/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "MC",
    "iso3": "MCO",
    "name": "Monaco",
    "tier": "D",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "MN",
    "iso3": "MNG",
    "name": "Mongolia",
    "tier": "D",
    "currency": "MNT",
    "utc": 8,
    "languages": [
     "mn"
    ],
    "script": "Cyrillic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-mongolia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "ME",
    "iso3": "MNE",
    "name": "Montenegro",
    "tier": "D",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "sr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-montenegro/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "MA",
    "iso3": "MAR",
    "name": "Morocco",
    "tier": "C",
    "currency": "MAD",
    "utc": 1,
    "languages": [
     "ar",
     "fr"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-morocco/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "MZ",
    "iso3": "MOZ",
    "name": "Mozambique",
    "tier": "D",
    "currency": "MZN",
    "utc": 2,
    "languages": [
     "pt"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-mozambique/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "NA",
    "iso3": "NAM",
    "name": "Namibia",
    "tier": "D",
    "currency": "NAD",
    "utc": 2,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-namibia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "NR",
    "iso3": "NRU",
    "name": "Nauru",
    "tier": "D",
    "currency": "AUD",
    "utc": 12,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "NI",
    "iso3": "NIC",
    "name": "Nicaragua",
    "tier": "D",
    "currency": "NIO",
    "utc": -6,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-nicaragua/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "NE",
    "iso3": "NER",
    "name": "Niger",
    "tier": "D",
    "currency": "XOF",
    "utc": 1,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "MK",
    "iso3": "MKD",
    "name": "North Macedonia",
    "tier": "D",
    "currency": "MKD",
    "utc": 1,
    "languages": [
     "mk"
    ],
    "script": "Cyrillic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-north-macedonia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "PW",
    "iso3": "PLW",
    "name": "Palau",
    "tier": "D",
    "currency": "USD",
    "utc": 9,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "PS",
    "iso3": "PSE",
    "name": "Palestine",
    "tier": "D",
    "currency": "ILS",
    "utc": 2,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-palestine/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "PA",
    "iso3": "PAN",
    "name": "Panama",
    "tier": "D",
    "currency": "PAB",
    "utc": -5,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-panama/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "PG",
    "iso3": "PNG",
    "name": "Papua New Guinea",
    "tier": "D",
    "currency": "PGK",
    "utc": 10,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-papua-new-guinea/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "PY",
    "iso3": "PRY",
    "name": "Paraguay",
    "tier": "D",
    "currency": "PYG",
    "utc": -3,
    "languages": [
     "es",
     "gn"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-paraguay/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "PE",
    "iso3": "PER",
    "name": "Peru",
    "tier": "D",
    "currency": "PEN",
    "utc": -5,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-peru/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "RO",
    "iso3": "ROU",
    "name": "Romania",
    "tier": "C",
    "currency": "RON",
    "utc": 2,
    "languages": [
     "ro"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-romania/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "RW",
    "iso3": "RWA",
    "name": "Rwanda",
    "tier": "D",
    "currency": "RWF",
    "utc": 2,
    "languages": [
     "rw",
     "en",
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-rwanda/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "KN",
    "iso3": "KNA",
    "name": "Saint Kitts and Nevis",
    "tier": "D",
    "currency": "XCD",
    "utc": -4,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "LC",
    "iso3": "LCA",
    "name": "Saint Lucia",
    "tier": "D",
    "currency": "XCD",
    "utc": -4,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-saint-lucia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "VC",
    "iso3": "VCT",
    "name": "Saint Vincent and the Grenadines",
    "tier": "D",
    "currency": "XCD",
    "utc": -4,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-saint-vincent-and-the-grenadines/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "WS",
    "iso3": "WSM",
    "name": "Samoa",
    "tier": "D",
    "currency": "WST",
    "utc": 13,
    "languages": [
     "sm",
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "SM",
    "iso3": "SMR",
    "name": "San Marino",
    "tier": "D",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "it"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "ST",
    "iso3": "STP",
    "name": "São Tomé and Príncipe",
    "tier": "D",
    "currency": "STN",
    "utc": 0,
    "languages": [
     "pt"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "SN",
    "iso3": "SEN",
    "name": "Senegal",
    "tier": "D",
    "currency": "XOF",
    "utc": 0,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-senegal/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "RS",
    "iso3": "SRB",
    "name": "Serbia",
    "tier": "D",
    "currency": "RSD",
    "utc": 1,
    "languages": [
     "sr"
    ],
    "script": "Cyrillic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-serbia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "SC",
    "iso3": "SYC",
    "name": "Seychelles",
    "tier": "D",
    "currency": "SCR",
    "utc": 4,
    "languages": [
     "fr",
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-seychelles/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "SL",
    "iso3": "SLE",
    "name": "Sierra Leone",
    "tier": "D",
    "currency": "SLE",
    "utc": 0,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "SK",
    "iso3": "SVK",
    "name": "Slovakia",
    "tier": "D",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "sk"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-slovakia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "SI",
    "iso3": "SVN",
    "name": "Slovenia",
    "tier": "D",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "sl"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-slovenia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "SB",
    "iso3": "SLB",
    "name": "Solomon Islands",
    "tier": "D",
    "currency": "SBD",
    "utc": 11,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "SO",
    "iso3": "SOM",
    "name": "Somalia",
    "tier": "D",
    "currency": "SOS",
    "utc": 3,
    "languages": [
     "so",
     "ar"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-somalia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "SS",
    "iso3": "SSD",
    "name": "South Sudan",
    "tier": "D",
    "currency": "SSP",
    "utc": 2,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "SD",
    "iso3": "SDN",
    "name": "Sudan",
    "tier": "D",
    "currency": "SDG",
    "utc": 2,
    "languages": [
     "ar",
     "en"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-sudan/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "SY",
    "iso3": "SYR",
    "name": "Syria",
    "tier": "D",
    "currency": "SYP",
    "utc": 3,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-syria/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "TJ",
    "iso3": "TJK",
    "name": "Tajikistan",
    "tier": "C",
    "currency": "TJS",
    "utc": 5,
    "languages": [
     "tg"
    ],
    "script": "Cyrillic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-tajikistan/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "TL",
    "iso3": "TLS",
    "name": "Timor-Leste",
    "tier": "D",
    "currency": "USD",
    "utc": 9,
    "languages": [
     "pt",
     "tet"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-timor-leste/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "TG",
    "iso3": "TGO",
    "name": "Togo",
    "tier": "D",
    "currency": "XOF",
    "utc": 0,
    "languages": [
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "TO",
    "iso3": "TON",
    "name": "Tonga",
    "tier": "D",
    "currency": "TOP",
    "utc": 13,
    "languages": [
     "to",
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "TN",
    "iso3": "TUN",
    "name": "Tunisia",
    "tier": "D",
    "currency": "TND",
    "utc": 1,
    "languages": [
     "ar",
     "fr"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-tunisia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "TM",
    "iso3": "TKM",
    "name": "Turkmenistan",
    "tier": "D",
    "currency": "TMT",
    "utc": 5,
    "languages": [
     "tk"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-turkmenistan/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "TV",
    "iso3": "TUV",
    "name": "Tuvalu",
    "tier": "D",
    "currency": "AUD",
    "utc": 12,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "UG",
    "iso3": "UGA",
    "name": "Uganda",
    "tier": "C",
    "currency": "UGX",
    "utc": 3,
    "languages": [
     "en",
     "sw"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-uganda/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "UA",
    "iso3": "UKR",
    "name": "Ukraine",
    "tier": "C",
    "currency": "UAH",
    "utc": 2,
    "languages": [
     "uk"
    ],
    "script": "Cyrillic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-ukraine/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "UY",
    "iso3": "URY",
    "name": "Uruguay",
    "tier": "D",
    "currency": "UYU",
    "utc": -3,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-uruguay/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "UZ",
    "iso3": "UZB",
    "name": "Uzbekistan",
    "tier": "C",
    "currency": "UZS",
    "utc": 5,
    "languages": [
     "uz"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-uzbekistan/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "VU",
    "iso3": "VUT",
    "name": "Vanuatu",
    "tier": "D",
    "currency": "VUV",
    "utc": 11,
    "languages": [
     "bi",
     "en",
     "fr"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "VA",
    "iso3": "VAT",
    "name": "Vatican City",
    "tier": "D",
    "currency": "EUR",
    "utc": 1,
    "languages": [
     "it",
     "la"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": null,
    "status": "PLANNED",
    "indexable": false
   },
   {
    "iso2": "VE",
    "iso3": "VEN",
    "name": "Venezuela",
    "tier": "D",
    "currency": "VES",
    "utc": -4,
    "languages": [
     "es"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-venezuela/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "YE",
    "iso3": "YEM",
    "name": "Yemen",
    "tier": "D",
    "currency": "YER",
    "utc": 3,
    "languages": [
     "ar"
    ],
    "script": "Arabic",
    "travel": false,
    "diaspora": false,
    "slug": "learn-hindi-from-yemen/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "ZM",
    "iso3": "ZMB",
    "name": "Zambia",
    "tier": "D",
    "currency": "ZMW",
    "utc": 2,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-zambia/",
    "status": "PUBLISHED",
    "indexable": true
   },
   {
    "iso2": "ZW",
    "iso3": "ZWE",
    "name": "Zimbabwe",
    "tier": "D",
    "currency": "ZWG",
    "utc": 2,
    "languages": [
     "en"
    ],
    "script": "Latin",
    "travel": false,
    "diaspora": true,
    "slug": "learn-hindi-from-zimbabwe/",
    "status": "PUBLISHED",
    "indexable": true
   }
  ]
 },
 "languages": {
  "sourceLanguagePages": 30,
  "nativeLandingPages": 16,
  "rows": [
   {
    "code": "en",
    "name": "English",
    "slug": "learn-hindi-for-english-speakers/",
    "nativeLanding": null,
    "countries": 11
   },
   {
    "code": "es",
    "name": "Spanish",
    "slug": "learn-hindi-for-spanish-speakers/",
    "nativeLanding": "es/hindi/",
    "countries": 10
   },
   {
    "code": "fr",
    "name": "French",
    "slug": "learn-hindi-for-french-speakers/",
    "nativeLanding": "fr/hindi/",
    "countries": 7
   },
   {
    "code": "de",
    "name": "German",
    "slug": "learn-hindi-for-german-speakers/",
    "nativeLanding": "de/hindi/",
    "countries": 3
   },
   {
    "code": "ja",
    "name": "Japanese",
    "slug": "learn-hindi-for-japanese-speakers/",
    "nativeLanding": "ja/hindi/",
    "countries": 1
   },
   {
    "code": "pt",
    "name": "Portuguese",
    "slug": "learn-hindi-for-portuguese-speakers/",
    "nativeLanding": "pt/hindi/",
    "countries": 4
   },
   {
    "code": "ar",
    "name": "Arabic",
    "slug": "learn-hindi-for-arabic-speakers/",
    "nativeLanding": "ar/hindi/",
    "countries": 10
   },
   {
    "code": "bn",
    "name": "Bengali",
    "slug": "learn-hindi-for-bengali-speakers/",
    "nativeLanding": "bn/hindi/",
    "countries": 2
   },
   {
    "code": "ru",
    "name": "Russian",
    "slug": "learn-hindi-for-russian-speakers/",
    "nativeLanding": "ru/hindi/",
    "countries": 5
   },
   {
    "code": "zh",
    "name": "Chinese",
    "slug": "learn-hindi-for-chinese-speakers/",
    "nativeLanding": "zh/hindi/",
    "countries": 3
   },
   {
    "code": "ur",
    "name": "Urdu",
    "slug": "learn-hindi-for-urdu-speakers/",
    "nativeLanding": "ur/hindi/",
    "countries": 2
   },
   {
    "code": "ta",
    "name": "Tamil",
    "slug": "learn-hindi-for-tamil-speakers/",
    "nativeLanding": null,
    "countries": 4
   },
   {
    "code": "ko",
    "name": "Korean",
    "slug": "learn-hindi-for-korean-speakers/",
    "nativeLanding": "ko/hindi/",
    "countries": 1
   },
   {
    "code": "it",
    "name": "Italian",
    "slug": "learn-hindi-for-italian-speakers/",
    "nativeLanding": "it/hindi/",
    "countries": 2
   },
   {
    "code": "nl",
    "name": "Dutch",
    "slug": "learn-hindi-for-dutch-speakers/",
    "nativeLanding": null,
    "countries": 3
   },
   {
    "code": "tr",
    "name": "Turkish",
    "slug": "learn-hindi-for-turkish-speakers/",
    "nativeLanding": "tr/hindi/",
    "countries": 1
   },
   {
    "code": "id",
    "name": "Indonesian",
    "slug": "learn-hindi-for-indonesian-speakers/",
    "nativeLanding": "id/hindi/",
    "countries": 2
   },
   {
    "code": "vi",
    "name": "Vietnamese",
    "slug": "learn-hindi-for-vietnamese-speakers/",
    "nativeLanding": "vi/hindi/",
    "countries": 1
   },
   {
    "code": "th",
    "name": "Thai",
    "slug": "learn-hindi-for-thai-speakers/",
    "nativeLanding": null,
    "countries": 1
   },
   {
    "code": "pl",
    "name": "Polish",
    "slug": "learn-hindi-for-polish-speakers/",
    "nativeLanding": "pl/hindi/",
    "countries": 1
   },
   {
    "code": "fa",
    "name": "Persian",
    "slug": "learn-hindi-for-persian-speakers/",
    "nativeLanding": null,
    "countries": 3
   },
   {
    "code": "sw",
    "name": "Swahili",
    "slug": "learn-hindi-for-swahili-speakers/",
    "nativeLanding": null,
    "countries": 3
   },
   {
    "code": "te",
    "name": "Telugu",
    "slug": "learn-hindi-for-telugu-speakers/",
    "nativeLanding": null,
    "countries": 1
   },
   {
    "code": "mr",
    "name": "Marathi",
    "slug": "learn-hindi-for-marathi-speakers/",
    "nativeLanding": null,
    "countries": 1
   },
   {
    "code": "gu",
    "name": "Gujarati",
    "slug": "learn-hindi-for-gujarati-speakers/",
    "nativeLanding": null,
    "countries": 5
   },
   {
    "code": "pa",
    "name": "Punjabi",
    "slug": "learn-hindi-for-punjabi-speakers/",
    "nativeLanding": null,
    "countries": 4
   },
   {
    "code": "ne",
    "name": "Nepali",
    "slug": "learn-hindi-for-nepali-speakers/",
    "nativeLanding": null,
    "countries": 2
   },
   {
    "code": "ms",
    "name": "Malay",
    "slug": "learn-hindi-for-malay-speakers/",
    "nativeLanding": null,
    "countries": 3
   },
   {
    "code": "uk",
    "name": "Ukrainian",
    "slug": "learn-hindi-for-ukrainian-speakers/",
    "nativeLanding": null,
    "countries": 1
   },
   {
    "code": "he",
    "name": "Hebrew",
    "slug": "learn-hindi-for-hebrew-speakers/",
    "nativeLanding": null,
    "countries": 1
   }
  ]
 },
 "pairs": [
  {
   "source": "en",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "es",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "fr",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "de",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "ja",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "pt",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "ar",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "bn",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "ru",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "zh",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "ur",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "ta",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "ko",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "it",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "nl",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "tr",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "id",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "vi",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "th",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "pl",
   "target": "hi",
   "status": "live",
   "contentLevel": "native + english",
   "pageCount": 2,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "fa",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "sw",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "te",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "mr",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "gu",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "pa",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "ne",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "ms",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "uk",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  },
  {
   "source": "he",
   "target": "hi",
   "status": "live",
   "contentLevel": "english",
   "pageCount": 1,
   "tutorCount": 0,
   "indexable": true
  }
 ],
 "seo": {
  "pass": true,
  "critical": 0,
  "warnings": 0,
  "pages": 606,
  "sitemapUrls": 601,
  "sitemapFiles": 14,
  "brokenLinks": 0,
  "orphans": 0
 },
 "privacy": {
  "state": "FAIL",
  "fails": 215,
  "blocked": 0,
  "note": "722 files scanned, 4 secrets"
 },
 "gate": {
  "doctorProblems": 1,
  "doctorWarnings": 0,
  "doctorChecks": 11,
  "seoPass": true,
  "privacyState": "FAIL"
 },
 "tutors": [
  {
   "id": "sushila-g",
   "name": "Sushila G.",
   "completeness": 96,
   "missing": [
    "banner"
   ],
   "verified": true,
   "rating": 5,
   "reviews": 3,
   "lessons": 40,
   "price": 6,
   "routesPrivately": true,
   "holiday": false
  },
  {
   "id": "hemlata",
   "name": "Hemlata",
   "completeness": 91,
   "missing": [
    "youtubeId"
   ],
   "verified": true,
   "rating": null,
   "reviews": 0,
   "lessons": 0,
   "price": 12,
   "routesPrivately": true,
   "holiday": false
  },
  {
   "id": "shikha-dutta",
   "name": "Shikha Dutta",
   "completeness": 87,
   "missing": [
    "banner",
    "youtubeId"
   ],
   "verified": true,
   "rating": null,
   "reviews": 0,
   "lessons": 0,
   "price": 8,
   "routesPrivately": false,
   "holiday": false
  },
  {
   "id": "tara",
   "name": "Tara",
   "completeness": 87,
   "missing": [
    "banner",
    "youtubeId"
   ],
   "verified": false,
   "rating": null,
   "reviews": 0,
   "lessons": 0,
   "price": 8,
   "routesPrivately": true,
   "holiday": false
  }
 ],
 "sitemapUrls": [
  "",
  "find-tutors.html",
  "join.html",
  "name-in-hindi/",
  "tutor/",
  "contact/",
  "about/",
  "privacy/",
  "terms/",
  "disclaimer/",
  "tutor/sushila-g/",
  "tutor/hemlata/",
  "tutor/shikha-dutta/",
  "tutor/tara/",
  "hindi-tutor/",
  "hindi-tutor/delhi/",
  "hindi-tutor/mumbai/",
  "hindi-tutor/bangalore/",
  "hindi-tutor/chennai/",
  "hindi-tutor/kolkata/",
  "hindi-tutor/hyderabad/",
  "hindi-tutor/pune/",
  "hindi-tutor/jaipur/",
  "hindi-tutor/ahmedabad/",
  "hindi-tutor/lucknow/",
  "hindi-tutor/patna/",
  "hindi-tutor/chandigarh/",
  "hindi-tutor/united-states/",
  "hindi-tutor/united-kingdom/",
  "hindi-tutor/canada/",
  "hindi-tutor/australia/",
  "hindi-tutor/united-arab-emirates/",
  "hindi-tutor/singapore/",
  "hindi-tutor/germany/",
  "hindi-tutor/japan/",
  "hindi-tutor/spain/",
  "hindi-tutor/south-africa/",
  "hindi-tutor/nepal/",
  "hindi-tutor/london/",
  "hindi-tutor/new-york/",
  "hindi-tutor/toronto/",
  "hindi-tutor/dubai/",
  "hindi-tutor/sydney/",
  "hindi-tutor/melbourne/",
  "hindi-tutor/houston/",
  "hindi-tutor/san-francisco/",
  "hindi-tutor/worldwide/",
  "learn-hindi-by-country/",
  "learn-hindi-from-usa/",
  "learn-hindi-from-uk/",
  "learn-hindi-from-canada/",
  "learn-hindi-from-australia/",
  "learn-hindi-from-uae/",
  "learn-hindi-from-singapore/",
  "learn-hindi-from-germany/",
  "learn-hindi-from-japan/",
  "learn-hindi-from-south-africa/",
  "learn-hindi-from-nepal/",
  "learn-hindi-from-spain/",
  "learn-hindi-from-brazil/",
  "learn-hindi-from-france/",
  "learn-hindi-from-mauritius/",
  "learn-hindi-from-fiji/",
  "learn-hindi-from-trinidad-and-tobago/",
  "learn-hindi-from-guyana/",
  "learn-hindi-from-suriname/",
  "learn-hindi-from-malaysia/",
  "learn-hindi-from-qatar/",
  "learn-hindi-from-saudi-arabia/",
  "learn-hindi-from-oman/",
  "learn-hindi-from-kuwait/",
  "learn-hindi-from-netherlands/",
  "learn-hindi-from-italy/",
  "learn-hindi-from-russia/",
  "learn-hindi-from-turkiye/",
  "learn-hindi-from-indonesia/",
  "learn-hindi-from-thailand/",
  "learn-hindi-from-south-korea/",
  "learn-hindi-from-china/",
  "learn-hindi-from-poland/",
  "learn-hindi-from-kenya/",
  "learn-hindi-from-tanzania/",
  "learn-hindi-from-mexico/",
  "learn-hindi-from-argentina/",
  "learn-hindi-from-portugal/",
  "learn-hindi-from-ireland/",
  "learn-hindi-from-new-zealand/",
  "learn-hindi-from-switzerland/",
  "learn-hindi-from-sweden/",
  "learn-hindi-from-norway/",
  "learn-hindi-from-israel/",
  "learn-hindi-from-sri-lanka/",
  "learn-hindi-from-bangladesh/",
  "learn-hindi-from-pakistan/",
  "learn-hindi-from-myanmar/",
  "learn-hindi-from-philippines/",
  "learn-hindi-from-vietnam/",
  "learn-hindi-from-egypt/",
  "learn-hindi-from-nigeria/",
  "learn-hindi-from-ghana/",
  "learn-hindi-from-afghanistan/",
  "learn-hindi-from-albania/",
  "learn-hindi-from-algeria/",
  "learn-hindi-from-armenia/",
  "learn-hindi-from-austria/",
  "learn-hindi-from-azerbaijan/",
  "learn-hindi-from-bahrain/",
  "learn-hindi-from-barbados/",
  "learn-hindi-from-belarus/",
  "learn-hindi-from-belgium/",
  "learn-hindi-from-belize/",
  "learn-hindi-from-bhutan/",
  "learn-hindi-from-bolivia/",
  "learn-hindi-from-bosnia-and-herzegovina/",
  "learn-hindi-from-botswana/",
  "learn-hindi-from-brunei/",
  "learn-hindi-from-bulgaria/",
  "learn-hindi-from-cambodia/",
  "learn-hindi-from-cameroon/",
  "learn-hindi-from-chile/",
  "learn-hindi-from-colombia/",
  "learn-hindi-from-comoros/",
  "learn-hindi-from-congo/",
  "learn-hindi-from-dr-congo/",
  "learn-hindi-from-costa-rica/",
  "learn-hindi-from-cote-divoire/",
  "learn-hindi-from-croatia/",
  "learn-hindi-from-cuba/",
  "learn-hindi-from-cyprus/",
  "learn-hindi-from-czechia/",
  "learn-hindi-from-denmark/",
  "learn-hindi-from-djibouti/",
  "learn-hindi-from-dominican-republic/",
  "learn-hindi-from-ecuador/",
  "learn-hindi-from-el-salvador/",
  "learn-hindi-from-eritrea/",
  "learn-hindi-from-estonia/",
  "learn-hindi-from-eswatini/",
  "learn-hindi-from-ethiopia/",
  "learn-hindi-from-finland/",
  "learn-hindi-from-gabon/",
  "learn-hindi-from-georgia/",
  "learn-hindi-from-greece/",
  "learn-hindi-from-grenada/",
  "learn-hindi-from-guatemala/",
  "learn-hindi-from-haiti/",
  "learn-hindi-from-honduras/",
  "learn-hindi-from-hungary/",
  "learn-hindi-from-iceland/",
  "learn-hindi-from-india/",
  "learn-hindi-from-iran/",
  "learn-hindi-from-iraq/",
  "learn-hindi-from-jamaica/",
  "learn-hindi-from-jordan/",
  "learn-hindi-from-kazakhstan/",
  "learn-hindi-from-kosovo/",
  "learn-hindi-from-kyrgyzstan/",
  "learn-hindi-from-laos/",
  "learn-hindi-from-latvia/",
  "learn-hindi-from-lebanon/",
  "learn-hindi-from-lesotho/",
  "learn-hindi-from-libya/",
  "learn-hindi-from-lithuania/",
  "learn-hindi-from-luxembourg/",
  "learn-hindi-from-madagascar/",
  "learn-hindi-from-malawi/",
  "learn-hindi-from-maldives/",
  "learn-hindi-from-malta/",
  "learn-hindi-from-mauritania/",
  "learn-hindi-from-moldova/",
  "learn-hindi-from-mongolia/",
  "learn-hindi-from-montenegro/",
  "learn-hindi-from-morocco/",
  "learn-hindi-from-mozambique/",
  "learn-hindi-from-namibia/",
  "learn-hindi-from-nicaragua/",
  "learn-hindi-from-north-macedonia/",
  "learn-hindi-from-palestine/",
  "learn-hindi-from-panama/",
  "learn-hindi-from-papua-new-guinea/",
  "learn-hindi-from-paraguay/",
  "learn-hindi-from-peru/",
  "learn-hindi-from-romania/",
  "learn-hindi-from-rwanda/",
  "learn-hindi-from-saint-lucia/",
  "learn-hindi-from-saint-vincent-and-the-grenadines/",
  "learn-hindi-from-senegal/",
  "learn-hindi-from-serbia/",
  "learn-hindi-from-seychelles/",
  "learn-hindi-from-slovakia/",
  "learn-hindi-from-slovenia/",
  "learn-hindi-from-somalia/",
  "learn-hindi-from-sudan/",
  "learn-hindi-from-syria/",
  "learn-hindi-from-tajikistan/",
  "learn-hindi-from-timor-leste/",
  "learn-hindi-from-tunisia/",
  "learn-hindi-from-turkmenistan/",
  "learn-hindi-from-uganda/",
  "learn-hindi-from-ukraine/",
  "learn-hindi-from-uruguay/",
  "learn-hindi-from-uzbekistan/",
  "learn-hindi-from-venezuela/",
  "learn-hindi-from-yemen/",
  "learn-hindi-from-zambia/",
  "learn-hindi-from-zimbabwe/",
  "es/hindi/",
  "fr/hindi/",
  "de/hindi/",
  "pt/hindi/",
  "ja/hindi/",
  "ar/hindi/",
  "ko/hindi/",
  "it/hindi/",
  "tr/hindi/",
  "id/hindi/",
  "ru/hindi/",
  "zh/hindi/",
  "vi/hindi/",
  "pl/hindi/",
  "bn/hindi/",
  "ur/hindi/",
  "hindi/",
  "hindi/beginners/",
  "hindi/alphabet/",
  "hindi/pronunciation/",
  "hindi/grammar/",
  "hindi/vocabulary/",
  "hindi/verbs/",
  "hindi/sentence-structure/",
  "hindi/conversation/",
  "hindi/listening/",
  "hindi/speaking/",
  "hindi/reading/",
  "hindi/writing/",
  "hindi/numbers/",
  "hindi/time-date/",
  "hindi/greetings/",
  "hindi/phrases-travel/",
  "hindi/phrases-food/",
  "hindi/shopping/",
  "hindi/emergency/",
  "hindi/family/",
  "hindi/relationships/",
  "hindi/business/",
  "hindi/for-kids/",
  "hindi/heritage/",
  "hindi/bollywood/",
  "hindi/hindi-vs-urdu/",
  "hindi/indian-languages/",
  "hindi/mistakes/",
  "hindi/slang/",
  "hindi/formal-informal/",
  "hindi/hinglish/",
  "hindi/name-topic/",
  "hindi/flashcards-topic/",
  "hindi/how-long/",
  "learn-hindi-for-speakers/",
  "learn-hindi-for-english-speakers/",
  "learn-hindi-for-spanish-speakers/",
  "learn-hindi-for-french-speakers/",
  "learn-hindi-for-german-speakers/",
  "learn-hindi-for-japanese-speakers/",
  "learn-hindi-for-portuguese-speakers/",
  "learn-hindi-for-arabic-speakers/",
  "learn-hindi-for-bengali-speakers/",
  "learn-hindi-for-russian-speakers/",
  "learn-hindi-for-chinese-speakers/",
  "learn-hindi-for-urdu-speakers/",
  "learn-hindi-for-tamil-speakers/",
  "learn-hindi-for-korean-speakers/",
  "learn-hindi-for-italian-speakers/",
  "learn-hindi-for-dutch-speakers/",
  "learn-hindi-for-turkish-speakers/",
  "learn-hindi-for-indonesian-speakers/",
  "learn-hindi-for-vietnamese-speakers/",
  "learn-hindi-for-thai-speakers/",
  "learn-hindi-for-polish-speakers/",
  "learn-hindi-for-persian-speakers/",
  "learn-hindi-for-swahili-speakers/",
  "learn-hindi-for-telugu-speakers/",
  "learn-hindi-for-marathi-speakers/",
  "learn-hindi-for-gujarati-speakers/",
  "learn-hindi-for-punjabi-speakers/",
  "learn-hindi-for-nepali-speakers/",
  "learn-hindi-for-malay-speakers/",
  "learn-hindi-for-ukrainian-speakers/",
  "learn-hindi-for-hebrew-speakers/",
  "learn-hindi-for-english-speakers/pronunciation/",
  "learn-hindi-for-english-speakers/grammar/",
  "learn-hindi-for-english-speakers/first-words/",
  "learn-hindi-for-english-speakers/mistakes/",
  "learn-hindi-for-spanish-speakers/pronunciation/",
  "learn-hindi-for-spanish-speakers/grammar/",
  "learn-hindi-for-spanish-speakers/first-words/",
  "learn-hindi-for-spanish-speakers/mistakes/",
  "learn-hindi-for-french-speakers/pronunciation/",
  "learn-hindi-for-french-speakers/grammar/",
  "learn-hindi-for-french-speakers/first-words/",
  "learn-hindi-for-french-speakers/mistakes/",
  "learn-hindi-for-german-speakers/pronunciation/",
  "learn-hindi-for-german-speakers/grammar/",
  "learn-hindi-for-german-speakers/first-words/",
  "learn-hindi-for-german-speakers/mistakes/",
  "learn-hindi-for-japanese-speakers/pronunciation/",
  "learn-hindi-for-japanese-speakers/grammar/",
  "learn-hindi-for-japanese-speakers/first-words/",
  "learn-hindi-for-japanese-speakers/mistakes/",
  "learn-hindi-for-portuguese-speakers/pronunciation/",
  "learn-hindi-for-portuguese-speakers/grammar/",
  "learn-hindi-for-portuguese-speakers/first-words/",
  "learn-hindi-for-portuguese-speakers/mistakes/",
  "learn-hindi-for-arabic-speakers/pronunciation/",
  "learn-hindi-for-arabic-speakers/grammar/",
  "learn-hindi-for-arabic-speakers/first-words/",
  "learn-hindi-for-arabic-speakers/mistakes/",
  "learn-hindi-for-bengali-speakers/pronunciation/",
  "learn-hindi-for-bengali-speakers/grammar/",
  "learn-hindi-for-bengali-speakers/first-words/",
  "learn-hindi-for-bengali-speakers/mistakes/",
  "learn-hindi-for-russian-speakers/pronunciation/",
  "learn-hindi-for-russian-speakers/grammar/",
  "learn-hindi-for-russian-speakers/first-words/",
  "learn-hindi-for-russian-speakers/mistakes/",
  "learn-hindi-for-chinese-speakers/pronunciation/",
  "learn-hindi-for-chinese-speakers/grammar/",
  "learn-hindi-for-chinese-speakers/mistakes/",
  "learn-hindi-for-tamil-speakers/pronunciation/",
  "learn-hindi-for-tamil-speakers/grammar/",
  "learn-hindi-for-tamil-speakers/first-words/",
  "learn-hindi-for-tamil-speakers/mistakes/",
  "learn-hindi-for-korean-speakers/pronunciation/",
  "learn-hindi-for-korean-speakers/grammar/",
  "learn-hindi-for-korean-speakers/first-words/",
  "learn-hindi-for-korean-speakers/mistakes/",
  "learn-hindi-for-italian-speakers/pronunciation/",
  "learn-hindi-for-italian-speakers/grammar/",
  "learn-hindi-for-italian-speakers/first-words/",
  "learn-hindi-for-italian-speakers/mistakes/",
  "learn-hindi-for-dutch-speakers/pronunciation/",
  "learn-hindi-for-dutch-speakers/grammar/",
  "learn-hindi-for-dutch-speakers/mistakes/",
  "learn-hindi-for-turkish-speakers/pronunciation/",
  "learn-hindi-for-turkish-speakers/grammar/",
  "learn-hindi-for-turkish-speakers/first-words/",
  "learn-hindi-for-turkish-speakers/mistakes/",
  "learn-hindi-for-indonesian-speakers/pronunciation/",
  "learn-hindi-for-indonesian-speakers/grammar/",
  "learn-hindi-for-indonesian-speakers/first-words/",
  "learn-hindi-for-indonesian-speakers/mistakes/",
  "learn-hindi-for-vietnamese-speakers/pronunciation/",
  "learn-hindi-for-vietnamese-speakers/grammar/",
  "learn-hindi-for-vietnamese-speakers/mistakes/",
  "learn-hindi-for-thai-speakers/pronunciation/",
  "learn-hindi-for-thai-speakers/grammar/",
  "learn-hindi-for-thai-speakers/first-words/",
  "learn-hindi-for-thai-speakers/mistakes/",
  "learn-hindi-for-polish-speakers/pronunciation/",
  "learn-hindi-for-polish-speakers/grammar/",
  "learn-hindi-for-polish-speakers/mistakes/",
  "learn-hindi-for-persian-speakers/pronunciation/",
  "learn-hindi-for-persian-speakers/grammar/",
  "learn-hindi-for-persian-speakers/first-words/",
  "learn-hindi-for-persian-speakers/mistakes/",
  "learn-hindi-for-swahili-speakers/pronunciation/",
  "learn-hindi-for-swahili-speakers/grammar/",
  "learn-hindi-for-swahili-speakers/first-words/",
  "learn-hindi-for-swahili-speakers/mistakes/",
  "learn-hindi-for-telugu-speakers/pronunciation/",
  "learn-hindi-for-telugu-speakers/grammar/",
  "learn-hindi-for-telugu-speakers/first-words/",
  "learn-hindi-for-telugu-speakers/mistakes/",
  "learn-hindi-for-marathi-speakers/pronunciation/",
  "learn-hindi-for-marathi-speakers/grammar/",
  "learn-hindi-for-marathi-speakers/first-words/",
  "learn-hindi-for-marathi-speakers/mistakes/",
  "learn-hindi-for-gujarati-speakers/pronunciation/",
  "learn-hindi-for-gujarati-speakers/grammar/",
  "learn-hindi-for-gujarati-speakers/first-words/",
  "learn-hindi-for-gujarati-speakers/mistakes/",
  "learn-hindi-for-punjabi-speakers/pronunciation/",
  "learn-hindi-for-punjabi-speakers/grammar/",
  "learn-hindi-for-punjabi-speakers/first-words/",
  "learn-hindi-for-punjabi-speakers/mistakes/",
  "learn-hindi-for-nepali-speakers/pronunciation/",
  "learn-hindi-for-nepali-speakers/grammar/",
  "learn-hindi-for-nepali-speakers/first-words/",
  "learn-hindi-for-nepali-speakers/mistakes/",
  "learn-hindi-for-malay-speakers/pronunciation/",
  "learn-hindi-for-malay-speakers/grammar/",
  "learn-hindi-for-malay-speakers/first-words/",
  "learn-hindi-for-malay-speakers/mistakes/",
  "learn-hindi-for-ukrainian-speakers/pronunciation/",
  "learn-hindi-for-ukrainian-speakers/grammar/",
  "learn-hindi-for-ukrainian-speakers/mistakes/",
  "learn-hindi-for-hebrew-speakers/pronunciation/",
  "learn-hindi-for-hebrew-speakers/grammar/",
  "learn-hindi-for-hebrew-speakers/mistakes/",
  "toolbox/",
  "toolbox/hindi-alphabet/",
  "toolbox/hindi-numbers/",
  "toolbox/hindi-phrasebook/",
  "toolbox/hindi-flashcards/",
  "toolbox/hindi-quiz/",
  "toolbox/hindi-level-test/",
  "toolbox/hindi-typing/",
  "toolbox/hindi-time-planner/",
  "toolbox/hindi-verbs/",
  "toolbox/hindi-date-time/",
  "toolbox/hindi-pronunciation/",
  "toolbox/hindi-vocabulary/",
  "daily-hindi/",
  "daily-hindi/day-1/",
  "daily-hindi/day-2/",
  "daily-hindi/day-3/",
  "daily-hindi/day-4/",
  "daily-hindi/day-5/",
  "daily-hindi/day-6/",
  "daily-hindi/day-7/",
  "daily-hindi/day-8/",
  "daily-hindi/day-9/",
  "daily-hindi/day-10/",
  "daily-hindi/day-11/",
  "daily-hindi/day-12/",
  "daily-hindi/day-13/",
  "daily-hindi/day-14/",
  "daily-hindi/day-15/",
  "daily-hindi/day-16/",
  "daily-hindi/day-17/",
  "daily-hindi/day-18/",
  "daily-hindi/day-19/",
  "daily-hindi/day-20/",
  "daily-hindi/day-21/",
  "daily-hindi/day-22/",
  "daily-hindi/day-23/",
  "daily-hindi/day-24/",
  "daily-hindi/day-25/",
  "daily-hindi/day-26/",
  "daily-hindi/day-27/",
  "daily-hindi/day-28/",
  "daily-hindi/day-29/",
  "daily-hindi/day-30/",
  "learn/",
  "learn/hindi-alphabet-for-beginners/",
  "learn/how-to-say-hello-in-hindi/",
  "learn/hindi-numbers-1-to-100/",
  "learn/learn-hindi-online-guide/",
  "learn/hindi-phrases-for-travel/",
  "learn/write-your-name-in-hindi/",
  "learn/hindi-family-words/",
  "learn/hindi-or-urdu-difference/",
  "learn/hindi-days-months-time/",
  "learn/learn-hindi-from-bollywood/",
  "learn/hindi-gender-masculine-feminine/",
  "learn/hindi-sentence-structure/",
  "learn/aap-tum-tu-hindi/",
  "learn/common-hindi-mistakes/",
  "learn/hindi-verbs-present-past-future/",
  "ask/",
  "ask/how-to-say-sorry-in-hindi-properly/",
  "ask/what-is-the-hardest-part-of-hindi/",
  "ask/can-i-learn-hindi-from-bollywood-alone/",
  "ask/how-many-words-do-i-need-in-hindi/",
  "ask/is-hindi-or-spanish-easier-to-learn/",
  "ask/how-to-practice-hindi-without-a-partner/",
  "ask/what-is-the-best-age-to-learn-hindi/",
  "ask/how-to-remember-hindi-genders/",
  "ask/do-hindi-speakers-mind-mistakes/",
  "ask/what-does-namaste-really-mean/",
  "ask/how-long-to-read-hindi-script/",
  "ask/how-to-say-thank-you-in-hindi/",
  "ask/how-to-say-hello-in-hindi-question/",
  "ask/how-to-say-i-love-you-in-hindi/",
  "ask/is-hindi-hard-to-learn/",
  "ask/how-long-to-learn-hindi/",
  "ask/hindi-alphabet-question/",
  "ask/how-to-write-name-hindi-question/",
  "ask/hindi-family-question/",
  "ask/hindi-or-urdu-question/",
  "ask/cheapest-way-to-learn-hindi/",
  "ask/how-to-say-sorry-in-hindi/",
  "ask/how-much-does-a-hindi-tutor-cost/",
  "ask/how-to-count-1-to-10-in-hindi/",
  "ask/is-italki-or-preply-better-for-hindi/",
  "ask/what-does-acha-mean-in-hindi/",
  "ask/can-i-learn-hindi-in-3-months/",
  "ask/hindi-or-urdu-which-to-learn/",
  "ask/best-way-to-learn-hindi-for-beginners/",
  "ask/how-to-introduce-yourself-in-hindi/",
  "ask/is-duolingo-good-for-hindi/",
  "ask/what-does-yaar-mean-in-hindi/",
  "ask/do-i-need-to-learn-devanagari/",
  "ask/how-to-say-good-morning-in-hindi/",
  "ask/how-to-say-how-are-you-in-hindi/",
  "ask/how-to-say-what-is-your-name-in-hindi/",
  "ask/hindi-words-every-beginner-should-know/",
  "ask/how-to-say-i-dont-understand-in-hindi/",
  "ask/is-hindi-useful-to-learn/",
  "ask/how-to-say-yes-and-no-in-hindi/",
  "ask/hindi-for-kids-how-to-start/",
  "ask/how-to-say-please-in-hindi/",
  "ask/can-i-learn-hindi-by-myself/",
  "answers/",
  "answers/how-to-say-i-am-hungry-in-hindi/",
  "answers/how-to-say-goodbye-in-hindi/",
  "answers/hindi-numbers-1-to-100/",
  "answers/hindi-days-of-the-week/",
  "answers/how-to-tell-the-time-in-hindi/",
  "answers/hindi-months-and-seasons/",
  "answers/hindi-colours-list/",
  "answers/hindi-family-words/",
  "answers/hindi-body-parts-vocabulary/",
  "answers/how-to-ask-for-directions-in-hindi/",
  "answers/how-to-order-food-in-hindi/",
  "answers/hindi-phrases-for-travelling-in-india/",
  "answers/how-to-say-i-am-learning-hindi/",
  "answers/hindi-vs-sanskrit-difference/",
  "answers/what-does-ji-mean-in-hindi/",
  "answers/hindi-postpositions-ka-ki-ke/",
  "answers/hindi-word-order-explained/",
  "answers/best-hindi-movies-to-learn-hindi/",
  "answers/how-to-practice-hindi-speaking-alone/",
  "answers/hindi-vs-punjabi-vs-bengali/",
  "answers/how-to-type-hindi-on-phone/",
  "answers/difference-between-hindi-and-urdu/",
  "answers/hindi-pronouns-explained/",
  "answers/how-to-say-please-and-thank-you-in-hindi/",
  "answers/hindi-verb-hona-to-be/",
  "answers/best-way-to-learn-hindi-as-a-beginner/",
  "answers/hindi-greetings-namaste-and-others/",
  "answers/can-i-learn-hindi-without-learning-the-script/",
  "es/",
  "es/find-tutors.html",
  "es/join.html",
  "fr/",
  "fr/find-tutors.html",
  "fr/join.html",
  "de/",
  "de/find-tutors.html",
  "de/join.html",
  "pt/",
  "pt/find-tutors.html",
  "pt/join.html",
  "ja/",
  "ja/find-tutors.html",
  "ja/join.html",
  "ar/",
  "ar/find-tutors.html",
  "ar/join.html"
 ],
 "release": {
  "commit": "dd8a4a2dc1ce28b9725a89463551db02058faf1a",
  "subject": "Phase 4: Learn Hindi complete structure (hub/levels/topics)",
  "buildTime": "2026-09-12T06:45:10.618Z",
  "dataSourceStatus": "PAUSED_FOR_REUPLOAD",
  "toolQa": {
   "tools": 12,
   "pass": 12,
   "fail": 0,
   "failed": []
  },
  "idleRegression": {
   "refreshRequiredAnywhere": false
  },
  "sections": {
   "totalHtml": 606,
   "tutorProfiles": 4,
   "materials": 0
  }
 },
 "phase3": {
  "remote": {
   "url": "https://github.com/ekgurulearning/EkGuru",
   "mainHead": "ba859a9bb9b5ebd9826b94599179e5a0712f29db",
   "mainSubject": "Initial commit (owner force-push, 2026-09-11)",
   "localAhead": true,
   "note": "Remote main is a squashed PRE-Phase-2 snapshot + the owner's live-sheets/ CSV exports. Local main is ~40 commits ahead; a push is non-fast-forward."
  },
  "live": {
   "url": "https://ekguru.shop/",
   "servesPhase2": false,
   "materials": 404,
   "faq": 404,
   "recoveryJs": 404,
   "swCache": "ekguru-v30-f10d5437",
   "sitemaps": 13,
   "note": "Production serves the pre-Phase-2 build (no /materials/, /faq/, recovery.js). Live-sheets/*.csv ARE publicly reachable on the live site."
  },
  "sheets": {
   "runtime": "PAUSED_FOR_REUPLOAD",
   "publishedUrlsSupplied": false,
   "liveSheetsInRepo": [
    "content.csv",
    "reviews.csv",
    "settings.csv",
    "tutors.csv"
   ],
   "note": "Owner supplied live-sheets/ CSVs in the reset commit; six published Google-Sheet URLs are still required before runtime activation."
  },
  "email": {
   "externalE2E": "BLOCKED_OWNER",
   "tutorEmail": "TUTOR_EMAIL_UNAVAILABLE (blank in tutors.csv — via EkGuru fallback)",
   "localTests": "system/security/routing PASS"
  }
 },
 "phase4": {
  "hub": "/learn/hindi/",
  "levels": [
   "beginner",
   "elementary"
  ],
  "levelsNotBuilt": [
   "intermediate",
   "advanced"
  ],
  "topics": [
   "basics",
   "conversation",
   "daily-life",
   "food",
   "grammar",
   "numbers",
   "pronunciation",
   "shopping",
   "time-dates",
   "travel",
   "vocabulary"
  ],
  "lessons": 15,
  "materials": 15,
  "practice": 13,
  "paths": 7,
  "browser": "108/108",
  "idleProblems": 0,
  "gate": "YELLOW_PARTIAL_VERIFICATION",
  "green": 27,
  "yellow": 2,
  "red": 1
 },
 "phase5": {
  "verdict": "GREEN_INTERACTION_VERIFIED",
  "cardsTotal": 1766,
  "byPattern": {
   "no-link": 113,
   "informational-faq": 1520,
   "nested-actions": 50,
   "whole-anchor": 78,
   "stretched-link": 4,
   "js-wired-action": 1
  },
  "titleOnly": 0,
  "deadLinks": 0,
  "deadButtons": 0,
  "interactions": "19/19",
  "matrix": "146/146",
  "regression": "5/5",
  "gapsBlocking": 0
 }
};
