/* EkGuru — CHINESE COURSE BANK (authored, single source of truth).
   Generated by tools/build-language-course.py — do not hand-edit. */
window.EKGURU_COURSE_ZH = {
 "practice": {
  "vocabulary": [
   {
    "q": "What does “你好” mean?",
    "a": "hello",
    "opts": [
     "thanks",
     "hello",
     "goodbye",
     "sorry"
    ],
    "explain": "Nǐ hǎo — hello (said ní hǎo by sandhi)."
   },
   {
    "q": "“谢谢” means…",
    "a": "thanks",
    "opts": [
     "please",
     "thanks",
     "sorry",
     "hello"
    ],
    "explain": "Xièxie — thanks; answered with 不客气."
   },
   {
    "q": "The reply to 谢谢 is…",
    "a": "不客气",
    "opts": [
     "不客气",
     "没关系",
     "再见",
     "谢谢"
    ],
    "explain": "Bú kèqi — don't be polite."
   },
   {
    "q": "In 王伟, the family name is…",
    "a": "王 (first)",
    "opts": [
     "伟",
     "王 (first)",
     "王伟 together",
     "neither"
    ],
    "explain": "Family name comes first: Mr Wáng."
   },
   {
    "q": "“mǎ” (3rd tone) means…",
    "a": "horse",
    "opts": [
     "mother",
     "hemp",
     "horse",
     "scold"
    ],
    "explain": "mā mother, má hemp, mǎ horse, mà scold."
   },
   {
    "q": "你好 is actually pronounced…",
    "a": "ní hǎo",
    "opts": [
     "nǐ hǎo",
     "ní hǎo",
     "nì hào",
     "nī hāo"
    ],
    "explain": "Third-tone sandhi: first becomes 2nd."
   },
   {
    "q": "“多少钱?” means…",
    "a": "how much?",
    "opts": [
     "what time?",
     "how much?",
     "how old?",
     "how many?"
    ],
    "explain": "Duōshao qián? — the market essential."
   },
   {
    "q": "“很好吃!” means…",
    "a": "very delicious!",
    "opts": [
     "very big!",
     "very hot!",
     "very delicious!",
     "very full!"
    ],
    "explain": "Hěn hǎochī! praises the food."
   },
   {
    "q": "“买单” means…",
    "a": "the bill, please",
    "opts": [
     "the menu",
     "the bill, please",
     "one more",
     "takeaway"
    ],
    "explain": "Mǎidān asks for the bill."
   },
   {
    "q": "“我吃饱了” means…",
    "a": "I am full",
    "opts": [
     "I am hungry",
     "I am full",
     "I am thirsty",
     "I am tired"
    ],
    "explain": "Eaten to fullness."
   },
   {
    "q": "“不” before a 4th tone is said…",
    "a": "bú",
    "opts": [
     "bù",
     "bú",
     "bǔ",
     "bū"
    ],
    "explain": "不对 is bú duì — tone change."
   },
   {
    "q": "Sticking chopsticks upright in rice is…",
    "a": "taboo (funeral-like)",
    "opts": [
     "lucky",
     "taboo (funeral-like)",
     "polite",
     "normal"
    ],
    "explain": "It mirrors funeral incense — never do it."
   }
  ],
  "grammar": [
   {
    "q": "“I am a student” is…",
    "a": "我是学生",
    "opts": [
     "我在学生",
     "我是学生",
     "我有学生",
     "我学生"
    ],
    "explain": "Identity uses 是: wǒ shì xuéshēng."
   },
   {
    "q": "“I am tired” is…",
    "a": "我很累",
    "opts": [
     "我是累",
     "我很累",
     "我在累",
     "我有累"
    ],
    "explain": "Adjectives need no 是: wǒ hěn lèi."
   },
   {
    "q": "“I have a book” is…",
    "a": "我有一本书",
    "opts": [
     "我是书",
     "我有一本书",
     "我在书",
     "我书有"
    ],
    "explain": "Having uses 有 + measure word: yì běn shū."
   },
   {
    "q": "“I am at home” is…",
    "a": "我在家",
    "opts": [
     "我是家",
     "我在家",
     "我有家",
     "家我"
    ],
    "explain": "Location uses 在: wǒ zài jiā."
   },
   {
    "q": "“Two people” is…",
    "a": "两个人",
    "opts": [
     "二个人",
     "两个人",
     "两人们",
     "二人们"
    ],
    "explain": "Things counted with 两: liǎng ge rén."
   },
   {
    "q": "“Three books” is…",
    "a": "三本书",
    "opts": [
     "三书",
     "三本书",
     "三本的书",
     "三个书"
    ],
    "explain": "本 is the measure word for books."
   },
   {
    "q": "“I am 20” is…",
    "a": "我二十岁",
    "opts": [
     "我二十年",
     "我二十岁",
     "我是二十",
     "我有二十"
    ],
    "explain": "Wǒ èrshí suì — 岁 for age."
   },
   {
    "q": "“I go to school at 8” is…",
    "a": "我八点去学校",
    "opts": [
     "我去学校八点",
     "我八点去学校",
     "八点我去学校去",
     "我去八点学校"
    ],
    "explain": "Time slots after the subject."
   },
   {
    "q": "“I don't eat meat” is…",
    "a": "我不吃肉",
    "opts": [
     "我不吃肉",
     "我没吃肉",
     "我不是吃肉",
     "我没有吃肉"
    ],
    "explain": "Habits negate with 不."
   },
   {
    "q": "“I didn't go yesterday” is…",
    "a": "我昨天没去",
    "opts": [
     "我昨天不去",
     "我昨天没去",
     "我没昨天去",
     "昨天我不去"
    ],
    "explain": "Completed past negates with 没."
   },
   {
    "q": "“Where do you work?” is…",
    "a": "你在哪儿工作?",
    "opts": [
     "你在哪儿工作?",
     "在哪儿你工作?",
     "你工作在哪儿吗?",
     "哪儿工作你?"
    ],
    "explain": "Wh-words stay in place."
   },
   {
    "q": "“Are you a teacher?” (choice) is…",
    "a": "你是不是老师?",
    "opts": [
     "你是老师吗?",
     "你是不是老师?",
     "你老师是不是?",
     "是不是你老师?"
    ],
    "explain": "The 是不是 choice pattern; 吗 also works."
   }
  ]
 },
 "quiz": [
  {
   "id": "zh-greet-1",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“你吃了吗?” is used as…",
   "a": "a warm \"how are you\"",
   "opts": [
    "a dinner invitation",
    "a warm \"how are you\"",
    "a complaint",
    "a goodbye"
   ],
   "explain": "Have-you-eaten = how are you."
  },
  {
   "id": "zh-greet-2",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "Introduce yourself as Ravi. You say…",
   "a": "我叫拉维",
   "opts": [
    "我叫拉维",
    "我是叫拉维",
    "我名字拉维",
    "叫我拉维是"
   ],
   "explain": "Wǒ jiào… — I am called…"
  },
  {
   "id": "zh-greet-3",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“您” (nín) is…",
   "a": "respectful \"you\"",
   "opts": [
    "plural you",
    "respectful \"you\"",
    "casual you",
    "\"they\""
   ],
   "explain": "Nín honours elders and clients."
  },
  {
   "id": "zh-greet-4",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“再见” literally means…",
   "a": "again see",
   "opts": [
    "go well",
    "again see",
    "stay safe",
    "long life"
   ],
   "explain": "Zàijiàn — see you again."
  },
  {
   "id": "zh-pin-1",
   "lesson": "pinyin-and-tones",
   "type": "vocab",
   "topic": "tones",
   "level": "beginner",
   "q": "“mà” (4th tone) means…",
   "a": "to scold",
   "opts": [
    "mother",
    "horse",
    "hemp",
    "to scold"
   ],
   "explain": "Mà — to scold; mā is mother."
  },
  {
   "id": "zh-pin-2",
   "lesson": "pinyin-and-tones",
   "type": "vocab",
   "topic": "tones",
   "level": "beginner",
   "q": "Pinyin is best described as…",
   "a": "romanisation scaffolding",
   "opts": [
    "the real script",
    "romanisation scaffolding",
    "a dialect",
    "handwriting"
   ],
   "explain": "Training wheels; characters are the bike."
  },
  {
   "id": "zh-pin-3",
   "lesson": "pinyin-and-tones",
   "type": "meaning",
   "topic": "tones",
   "level": "beginner",
   "q": "“不对” is pronounced…",
   "a": "bú duì",
   "opts": [
    "bù duì",
    "bú duì",
    "bǔ duǐ",
    "bū duī"
   ],
   "explain": "不 turns 2nd before a 4th tone."
  },
  {
   "id": "zh-shi-1",
   "lesson": "shi-you-and-zai",
   "type": "vocab",
   "topic": "grammar",
   "level": "beginner",
   "q": "“There is nobody” is…",
   "a": "没有人",
   "opts": [
    "沒有人",
    "没有人",
    "不有人",
    "没是人"
   ],
   "explain": "Méiyǒu rén (simplified 没有人)."
  },
  {
   "id": "zh-shi-2",
   "lesson": "shi-you-and-zai",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "Say “the doctor is here” (location). You say…",
   "a": "医生在这里",
   "opts": [
    "医生在这里",
    "医生是有这里",
    "这里是医生在",
    "医生是有这里"
   ],
   "explain": "Location → 在: 医生在这里."
  },
  {
   "id": "zh-shi-3",
   "lesson": "shi-you-and-zai",
   "type": "meaning",
   "topic": "grammar",
   "level": "beginner",
   "q": "“我不是老师” means…",
   "a": "I am not a teacher",
   "opts": [
    "I am a teacher",
    "I have no teacher",
    "I am not a teacher",
    "I was a teacher"
   ],
   "explain": "Bú shì negates identity."
  },
  {
   "id": "zh-num-1",
   "lesson": "numbers-and-measure-words",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "“九十九” is the number…",
   "a": "99",
   "opts": [
    "90",
    "99",
    "919",
    "999"
   ],
   "explain": "Nine-ten-nine = 99."
  },
  {
   "id": "zh-num-2",
   "lesson": "numbers-and-measure-words",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "The universal fallback measure word is…",
   "a": "个",
   "opts": [
    "本",
    "个",
    "杯",
    "只"
   ],
   "explain": "个 (ge) rescues every noun."
  },
  {
   "id": "zh-num-3",
   "lesson": "numbers-and-measure-words",
   "type": "usage",
   "topic": "numbers",
   "level": "beginner",
   "q": "Phone numbers and maths use…",
   "a": "二 (èr)",
   "opts": [
    "两",
    "二 (èr)",
    "俩",
    "双"
   ],
   "explain": "Abstract counting keeps èr."
  },
  {
   "id": "zh-food-1",
   "lesson": "food-and-ordering",
   "type": "usage",
   "topic": "food",
   "level": "beginner",
   "q": "Get the waiter's attention. You call…",
   "a": "服务员!",
   "opts": [
    "服务员!",
    "老板!",
    "朋友!",
    "师傅!"
   ],
   "explain": "Fúwùyuán! — waiter!"
  },
  {
   "id": "zh-food-2",
   "lesson": "food-and-ordering",
   "type": "vocab",
   "topic": "food",
   "level": "beginner",
   "q": "Chopsticks are…",
   "a": "筷子",
   "opts": [
    "叉子",
    "筷子",
    "勺子",
    "刀子"
   ],
   "explain": "Kuàizi; 叉子 is a fork."
  },
  {
   "id": "zh-food-3",
   "lesson": "food-and-ordering",
   "type": "meaning",
   "topic": "food",
   "level": "beginner",
   "q": "Tipping on the Mainland is…",
   "a": "not customary",
   "opts": [
    "20% expected",
    "not customary",
    "10% expected",
    "required"
   ],
   "explain": "No tipping culture on the Mainland."
  },
  {
   "id": "zh-sen-1",
   "lesson": "basic-sentences",
   "type": "vocab",
   "topic": "grammar",
   "level": "beginner",
   "q": "了 (le) marks…",
   "a": "completion / new situation",
   "opts": [
    "past tense always",
    "completion / new situation",
    "future",
    "politeness"
   ],
   "explain": "Completion, not past tense."
  },
  {
   "id": "zh-sen-2",
   "lesson": "basic-sentences",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "Say “I eat at home” (place first). You say…",
   "a": "我在家吃饭",
   "opts": [
    "我在家吃饭",
    "我吃饭在家",
    "在家我吃饭",
    "我吃在家饭"
   ],
   "explain": "Place slots before the verb."
  },
  {
   "id": "zh-sen-3",
   "lesson": "basic-sentences",
   "type": "meaning",
   "topic": "grammar",
   "level": "beginner",
   "q": "有 always negates with…",
   "a": "没",
   "opts": [
    "不",
    "没",
    "别",
    "莫"
   ],
   "explain": "没有 — even in the present."
  },
  {
   "id": "zh-greet-5",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "Ask someone's surname politely. You say…",
   "a": "您贵姓?",
   "opts": [
    "你叫什么?",
    "您贵姓?",
    "你姓什么名字?",
    "贵姓你什么?"
   ],
   "explain": "Nín guì xìng? — your honourable surname?"
  }
 ],
 "review": [
  {
   "p": "你好",
   "a": "hello (nǐ hǎo → ní hǎo)"
  },
  {
   "p": "早上好",
   "a": "good morning"
  },
  {
   "p": "谢谢",
   "a": "thanks"
  },
  {
   "p": "不客气",
   "a": "you're welcome"
  },
  {
   "p": "再见",
   "a": "goodbye"
  },
  {
   "p": "我叫…",
   "a": "I am called…"
  },
  {
   "p": "我是印度人",
   "a": "I am an Indian"
  },
  {
   "p": "mā / má / mǎ / mà",
   "a": "mother / hemp / horse / scold"
  },
  {
   "p": "我是学生",
   "a": "I am a student"
  },
  {
   "p": "我很累",
   "a": "I am tired"
  },
  {
   "p": "我有一本书",
   "a": "I have a book"
  },
  {
   "p": "我在家",
   "a": "I am at home"
  },
  {
   "p": "一…十",
   "a": "1–10 (…shí)"
  },
  {
   "p": "二十一",
   "a": "21 (two-ten-one)"
  },
  {
   "p": "两个人",
   "a": "two people (liǎng!)"
  },
  {
   "p": "三本书",
   "a": "three books"
  },
  {
   "p": "我二十岁",
   "a": "I am 20 years old"
  },
  {
   "p": "多少钱?",
   "a": "how much?"
  },
  {
   "p": "我要…",
   "a": "I want… (ordering)"
  },
  {
   "p": "很好吃!",
   "a": "very delicious!"
  },
  {
   "p": "我吃饱了",
   "a": "I am full"
  },
  {
   "p": "买单",
   "a": "the bill, please"
  },
  {
   "p": "我不吃肉",
   "a": "I don't eat meat"
  },
  {
   "p": "你在哪儿工作?",
   "a": "where do you work?"
  }
 ]
};
