/* EkGuru — JAPANESE COURSE BANK (authored, single source of truth).
   Generated by tools/build-language-course.py — do not hand-edit. */
window.EKGURU_COURSE_JA = {
 "practice": {
  "vocabulary": [
   {
    "q": "“こんにちは” is used…",
    "a": "in the daytime",
    "opts": [
     "in the morning",
     "in the daytime",
     "in the evening",
     "at night"
    ],
    "explain": "Konnichiwa — daytime hello (は read wa)."
   },
   {
    "q": "“よろしくおねがいします” means…",
    "a": "please treat me well",
    "opts": [
     "thank you",
     "please treat me well",
     "goodbye",
     "excuse me"
    ],
    "explain": "It closes introductions, handing over the relationship."
   },
   {
    "q": "“すみません” does NOT mean…",
    "a": "goodbye",
    "opts": [
     "excuse me",
     "sorry",
     "thanks for trouble",
     "goodbye"
    ],
    "explain": "Sumimasen covers excuse/sorry/thanks-never goodbye."
   },
   {
    "q": "Foreign words are written in…",
    "a": "katakana",
    "opts": [
     "hiragana",
     "katakana",
     "kanji",
     "romaji"
    ],
    "explain": "Katakana: コーヒー, コンピューター."
   },
   {
    "q": "“いただきます” is said…",
    "a": "before eating",
    "opts": [
     "after eating",
     "before eating",
     "when paying",
     "when cooking"
    ],
    "explain": "Itadakimasu — I humbly receive."
   },
   {
    "q": "“ごちそうさまでした” is said…",
    "a": "after eating",
    "opts": [
     "before eating",
     "after eating",
     "at the door",
     "on the phone"
    ],
    "explain": "Gochisōsama deshita — thanks for the feast."
   },
   {
    "q": "Slurping ramen is…",
    "a": "correct and appreciative",
    "opts": [
     "rude",
     "correct and appreciative",
     "illegal",
     "childish"
    ],
    "explain": "Slurping cools noodles and signals enjoyment."
   },
   {
    "q": "“いくらですか” means…",
    "a": "how much?",
    "opts": [
     "what time?",
     "how much?",
     "how old?",
     "where?"
    ],
    "explain": "Ikura desu ka — how much is it?"
   },
   {
    "q": "Tipping in Japan is…",
    "a": "not done",
    "opts": [
     "20% expected",
     "not done",
     "10% expected",
     "required"
    ],
    "explain": "Tipping confuses and can offend."
   },
   {
    "q": "Passing food chopstick-to-chopstick is…",
    "a": "taboo (funeral-like)",
    "opts": [
     "polite",
     "taboo (funeral-like)",
     "fun",
     "normal"
    ],
    "explain": "Hiroibashi mirrors a funeral bone ritual."
   },
   {
    "q": "“おはようございます” is…",
    "a": "good morning (polite)",
    "opts": [
     "good evening",
     "good morning (polite)",
     "good night",
     "welcome"
    ],
    "explain": "Full polite morning greeting."
   },
   {
    "q": "A 45°+ bow signals…",
    "a": "deep apology",
    "opts": [
     "hello",
     "thanks",
     "deep apology",
     "goodbye"
    ],
    "explain": "Deeper bow, deeper meaning."
   }
  ],
  "grammar": [
   {
    "q": "“I am a teacher” is…",
    "a": "私は先生です",
    "opts": [
     "私は先生です",
     "私が先生です",
     "私は先生が",
     "先生私はです"
    ],
    "explain": "Neutral statement: topic は + です."
   },
   {
    "q": "“I am the one who is a student” stresses with…",
    "a": "私が学生です",
    "opts": [
     "私は学生です",
     "私が学生です",
     "私も学生です",
     "私は学生が"
    ],
    "explain": "が marks the subject emphatically."
   },
   {
    "q": "“Read a book” (object) is…",
    "a": "本を読みます",
    "opts": [
     "本を読みます",
     "本が読みます",
     "本に読みます",
     "本で読みます"
    ],
    "explain": "を marks the direct object."
   },
   {
    "q": "“Study at the library” is…",
    "a": "図書館で勉強します",
    "opts": [
     "図書館に勉強します",
     "図書館で勉強します",
     "図書館へ勉強します",
     "図書館を勉強します"
    ],
    "explain": "で marks where an action happens."
   },
   {
    "q": "“There is a cat” is…",
    "a": "猫がいます",
    "opts": [
     "猫があります",
     "猫がいます",
     "猫はいます",
     "猫をいます"
    ],
    "explain": "Living things take いる."
   },
   {
    "q": "“There is a book” is…",
    "a": "本があります",
    "opts": [
     "本がいます",
     "本があります",
     "本はあります",
     "本をあります"
    ],
    "explain": "Inanimate things take ある."
   },
   {
    "q": "“(I) ate” is…",
    "a": "食べました",
    "opts": [
     "食べます",
     "食べました",
     "食べません",
     "食べましょう"
    ],
    "explain": "ました is the polite past."
   },
   {
    "q": "“(I) don't drink” is…",
    "a": "飲みません",
    "opts": [
     "飲みます",
     "飲みました",
     "飲みません",
     "飲みましょう"
    ],
    "explain": "ません is the polite negative."
   },
   {
    "q": "“Let's go” is…",
    "a": "行きましょう",
    "opts": [
     "行きます",
     "行きました",
     "行きましょう",
     "行きたいです"
    ],
    "explain": "ましょう proposes: let's."
   },
   {
    "q": "“I want to eat” is…",
    "a": "食べたいです",
    "opts": [
     "食べます",
     "食べたいです",
     "食べましょう",
     "食べのです"
    ],
    "explain": "Stem + たいです = want to."
   },
   {
    "q": "“Three people” is…",
    "a": "三人 (さんにん)",
    "opts": [
     "三人 (さんにん)",
     "三人 (みたり)",
     "三つ人",
     "人三"
    ],
    "explain": "Sannin — the counter 人."
   },
   {
    "q": "“一本” is read…",
    "a": "いっぽん",
    "opts": [
     "いちほん",
     "いっぽん",
     "いちぼん",
     "いっほん"
    ],
    "explain": "Euphonic change: ippon."
   }
  ]
 },
 "quiz": [
  {
   "id": "ja-greet-1",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“お疲れ様でした” is said…",
   "a": "to those leaving / after work",
   "opts": [
    "on arrival",
    "to those leaving / after work",
    "at meals",
    "on the phone"
   ],
   "explain": "Otsukaresama — thank you for your work."
  },
  {
   "id": "ja-greet-2",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "Answer “いってきます” (I'm off). You say…",
   "a": "いってらっしゃい",
   "opts": [
    "いってらっしゃい",
    "いってきます",
    "ただいま",
    "おかえり again"
   ],
   "explain": "Itterasshai answers ittekimasu."
  },
  {
   "id": "ja-greet-3",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "Business cards are exchanged…",
   "a": "with both hands, then studied",
   "opts": [
    "one-handed",
    "with both hands, then studied",
    "by throwing",
    "never in person"
   ],
   "explain": "Meishi ritual: both hands, study it."
  },
  {
   "id": "ja-greet-4",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“さようなら” vs “じゃあね”: pick…",
   "a": "sayōnara is final; jā ne is casual",
   "opts": [
    "both casual",
    "sayōnara is final; jā ne is casual",
    "both final",
    "same meaning"
   ],
   "explain": "Sayōnara carries finality."
  },
  {
   "id": "ja-part-1",
   "lesson": "scripts-and-particles",
   "type": "vocab",
   "topic": "particles",
   "level": "beginner",
   "q": "In 私はコーヒーを飲みます, コーヒー is in…",
   "a": "katakana",
   "opts": [
    "hiragana",
    "katakana",
    "kanji",
    "romaji"
   ],
   "explain": "Foreign loanword → katakana."
  },
  {
   "id": "ja-part-2",
   "lesson": "scripts-and-particles",
   "type": "usage",
   "topic": "particles",
   "level": "beginner",
   "q": "Ask “who is coming?”. You say…",
   "a": "誰が来ますか",
   "opts": [
    "誰が来ますか",
    "誰は来ますか",
    "誰を来ますか",
    "誰に来ますか"
   ],
   "explain": "New information takes が."
  },
  {
   "id": "ja-part-3",
   "lesson": "scripts-and-particles",
   "type": "meaning",
   "topic": "particles",
   "level": "beginner",
   "q": "“私も学生です” means…",
   "a": "I too am a student",
   "opts": [
    "I am a student?",
    "I too am a student",
    "only I am a student",
    "I was a student"
   ],
   "explain": "も = also, replacing は."
  },
  {
   "id": "ja-desu-1",
   "lesson": "desu-aru-iru",
   "type": "vocab",
   "topic": "grammar",
   "level": "beginner",
   "q": "“Is expensive” (い-adjective) is…",
   "a": "高いです",
   "opts": [
    "高いです",
    "高です",
    "高います",
    "高いだ"
   ],
   "explain": "Takai desu — い-adjectives keep い."
  },
  {
   "id": "ja-desu-2",
   "lesson": "desu-aru-iru",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "Say “I have a car”. You say…",
   "a": "私は車があります",
   "opts": [
    "私は車があります",
    "私は車がいます",
    "私は車をです",
    "車が私あります"
   ],
   "explain": "Cars are inanimate: ある."
  },
  {
   "id": "ja-desu-3",
   "lesson": "desu-aru-iru",
   "type": "meaning",
   "topic": "grammar",
   "level": "beginner",
   "q": "“学生でした” means…",
   "a": "was a student",
   "opts": [
    "is a student",
    "was a student",
    "will be a student",
    "is not a student"
   ],
   "explain": "でした is the polite past."
  },
  {
   "id": "ja-num-1",
   "lesson": "numbers-and-counters",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "4 is usually read よん because し also means…",
   "a": "death",
   "opts": [
    "four things",
    "death",
    "west",
    "dirt"
   ],
   "explain": "し = death — avoided in counting."
  },
  {
   "id": "ja-num-2",
   "lesson": "numbers-and-counters",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "Flat things (paper, shirts) count with…",
   "a": "枚 (まい)",
   "opts": [
    "本",
    "枚 (まい)",
    "匹",
    "冊"
   ],
   "explain": "Mai — the flat-thing counter."
  },
  {
   "id": "ja-num-3",
   "lesson": "numbers-and-counters",
   "type": "usage",
   "topic": "numbers",
   "level": "beginner",
   "q": "20 years old is specially read…",
   "a": "二十歳 (はたち)",
   "opts": [
    "二十歳 (はたち)",
    "二十歳 (にじゅうさい)",
    "二十年",
    "二十才 (はたし)"
   ],
   "explain": "Hatachi — the famous exception."
  },
  {
   "id": "ja-food-1",
   "lesson": "food-and-ordering",
   "type": "usage",
   "topic": "food",
   "level": "beginner",
   "q": "Order ramen politely. You say…",
   "a": "ラーメンをください",
   "opts": [
    "ラーメンをください",
    "ラーメンがください",
    "ラーメンくださいを",
    "くださいラーメンを"
   ],
   "explain": "…o kudasai — the ordering pattern."
  },
  {
   "id": "ja-food-2",
   "lesson": "food-and-ordering",
   "type": "meaning",
   "topic": "food",
   "level": "beginner",
   "q": "“とりあえずビール!” means…",
   "a": "for now, beer!",
   "opts": [
    "no beer!",
    "for now, beer!",
    "beer forever!",
    "one beer only!"
   ],
   "explain": "The izakaya opening shout."
  },
  {
   "id": "ja-food-3",
   "lesson": "food-and-ordering",
   "type": "vocab",
   "topic": "food",
   "level": "beginner",
   "q": "The bill, please — you say…",
   "a": "お会計をおねがいします",
   "opts": [
    "お会計をください",
    "お会計をおねがいします",
    "お金ください",
    "レジはいくら"
   ],
   "explain": "Okaikei o onegai shimasu."
  },
  {
   "id": "ja-verb-1",
   "lesson": "masu-verbs",
   "type": "vocab",
   "topic": "verbs",
   "level": "beginner",
   "q": "“しました” is the past of…",
   "a": "します (do)",
   "opts": [
    "きます",
    "します (do)",
    "いきます",
    "みます"
   ],
   "explain": "Shimashita — did."
  },
  {
   "id": "ja-verb-2",
   "lesson": "masu-verbs",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "Propose “shall we eat?”. You say…",
   "a": "食べましょうか",
   "opts": [
    "食べましょうか",
    "食べますか",
    "食べたいですか",
    "食べなさいか"
   ],
   "explain": "Mashō ka softens the proposal."
  },
  {
   "id": "ja-verb-3",
   "lesson": "masu-verbs",
   "type": "meaning",
   "topic": "verbs",
   "level": "beginner",
   "q": "“猫が好きです” means…",
   "a": "I like cats",
   "opts": [
    "cats like me",
    "I like cats",
    "the cat is here",
    "cats exist"
   ],
   "explain": "Suki (liked) with が — I like cats."
  },
  {
   "id": "ja-greet-5",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“お先に失礼します” is said when…",
   "a": "leaving before others",
   "opts": [
    "arriving late",
    "leaving before others",
    "entering a shop",
    "answering mail"
   ],
   "explain": "Excuse me for leaving first."
  }
 ],
 "review": [
  {
   "p": "おはようございます",
   "a": "good morning"
  },
  {
   "p": "こんにちは",
   "a": "hello (daytime)"
  },
  {
   "p": "はじめまして",
   "a": "how do you do"
  },
  {
   "p": "よろしくおねがいします",
   "a": "please treat me well"
  },
  {
   "p": "ありがとうございます",
   "a": "thank you"
  },
  {
   "p": "すみません",
   "a": "excuse me / sorry"
  },
  {
   "p": "私は…です",
   "a": "I am…"
  },
  {
   "p": "は / が",
   "a": "topic / subject"
  },
  {
   "p": "〜をください",
   "a": "…please (ordering)"
  },
  {
   "p": "いただきます",
   "a": "before eating"
  },
  {
   "p": "ごちそうさまでした",
   "a": "after eating"
  },
  {
   "p": "猫がいます",
   "a": "there is a cat"
  },
  {
   "p": "本があります",
   "a": "there is a book"
  },
  {
   "p": "三人 (さんにん)",
   "a": "three people"
  },
  {
   "p": "一本 (いっぽん)",
   "a": "one long thing"
  },
  {
   "p": "二十歳 (はたち)",
   "a": "20 years old"
  },
  {
   "p": "いくらですか",
   "a": "how much?"
  },
  {
   "p": "おすすめは何ですか",
   "a": "what do you recommend?"
  },
  {
   "p": "お会計をおねがいします",
   "a": "bill, please"
  },
  {
   "p": "食べました",
   "a": "(I) ate"
  },
  {
   "p": "飲みません",
   "a": "(I) don't drink"
  },
  {
   "p": "行きましょう",
   "a": "let's go"
  },
  {
   "p": "食べたいです",
   "a": "I want to eat"
  },
  {
   "p": "猫が好きです",
   "a": "I like cats"
  }
 ]
};
