/* EkGuru — KOREAN COURSE BANK (authored, single source of truth).
   Generated by tools/build-language-course.py — do not hand-edit. */
window.EKGURU_COURSE_KO = {
 "practice": {
  "vocabulary": [
   {
    "q": "“안녕하세요” literally asks…",
    "a": "are you at peace?",
    "opts": [
     "are you at peace?",
     "have you eaten?",
     "where are you?",
     "who are you?"
    ],
    "explain": "Annyeonghaseyo — are you at peace?"
   },
   {
    "q": "On the phone, Koreans answer…",
    "a": "여보세요",
    "opts": [
     "안녕하세요",
     "여보세요",
     "감사합니다",
     "반갑습니다"
    ],
    "explain": "Yeoboseyo — the phone greeting."
   },
   {
    "q": "The LEAVER says goodbye with…",
    "a": "안녕히 계세요",
    "opts": [
     "안녕히 가세요",
     "안녕히 계세요",
     "안녕히 주무세요",
     "안녕히 드세요"
    ],
    "explain": "Leaver: stay in peace (계세요)."
   },
   {
    "q": "The STAYER says goodbye with…",
    "a": "안녕히 가세요",
    "opts": [
     "안녕히 가세요",
     "안녕히 계세요",
     "안녕히 주무세요",
     "안녕히 드세요"
    ],
    "explain": "Stayer: go in peace (가세요)."
   },
   {
    "q": "“감사합니다” means…",
    "a": "thank you",
    "opts": [
     "sorry",
     "thank you",
     "hello",
     "goodbye"
    ],
    "explain": "Gamsahamnida — full thanks."
   },
   {
    "q": "Hangul was created in…",
    "a": "1443, by scholars",
    "opts": [
     "1900, by missionaries",
     "1443, by scholars",
     "500 BC, by monks",
     "it evolved naturally"
    ],
    "explain": "King Sejong's scholars designed it in 1443."
   },
   {
    "q": "“잘 먹겠습니다” is said…",
    "a": "before eating",
    "opts": [
     "after eating",
     "before eating",
     "when paying",
     "when cooking"
    ],
    "explain": "I will eat well — before the meal."
   },
   {
    "q": "“계산서 주세요” means…",
    "a": "bill, please",
    "opts": [
     "menu, please",
     "bill, please",
     "water, please",
     "one more"
    ],
    "explain": "Gyesanseo juseyo — the bill."
   },
   {
    "q": "Free refillable side dishes are…",
    "a": "반찬",
    "opts": [
     "반찬",
     "쌈",
     "밥",
     "국"
    ],
    "explain": "Banchan — free and refillable."
   },
   {
    "q": "“얼마예요?” means…",
    "a": "how much?",
    "opts": [
     "what time?",
     "how much?",
     "how old?",
     "where?"
    ],
    "explain": "Eolmayeyo — how much is it?"
   },
   {
    "q": "“배불러요” means…",
    "a": "I am full",
    "opts": [
     "I am hungry",
     "I am full",
     "I am thirsty",
     "I am tired"
    ],
    "explain": "My stomach is full."
   },
   {
    "q": "Splitting the bill is called…",
    "a": "더치페이",
    "opts": [
     "반반페이",
     "더치페이",
     "나눔페이",
     "각자페이"
    ],
    "explain": "Deochipei — Dutch pay."
   }
  ],
  "grammar": [
   {
    "q": "“I am a student” (everyday polite) is…",
    "a": "저는 학생이에요",
    "opts": [
     "저는 학생입니다",
     "저는 학생이에요",
     "제가 학생이에요",
     "저는 학생예요"
    ],
    "explain": "Consonant stem → 이에요."
   },
   {
    "q": "“(She) is a doctor” is…",
    "a": "의사예요",
    "opts": [
     "의사이에요",
     "의사예요",
     "의사합니다",
     "의사가요"
    ],
    "explain": "Vowel stem → 예요."
   },
   {
    "q": "“Read a book” (object) is…",
    "a": "책을 읽어요",
    "opts": [
     "책을 읽어요",
     "책이 읽어요",
     "책에 읽어요",
     "책도 읽어요"
    ],
    "explain": "을 marks the object (consonant stem)."
   },
   {
    "q": "“Study at the library” is…",
    "a": "도서관에서 공부해요",
    "opts": [
     "도서관에 공부해요",
     "도서관에서 공부해요",
     "도서관을 공부해요",
     "도서관도 공부해요"
    ],
    "explain": "에서 marks where action happens."
   },
   {
    "q": "“There is no time” is…",
    "a": "시간이 없어요",
    "opts": [
     "시간이 없어요",
     "시간이 있어요",
     "시간을 없어요",
     "시간에 없어요"
    ],
    "explain": "없어요 — the built-in negative of 있어요."
   },
   {
    "q": "“(I) ate” is…",
    "a": "먹었어요",
    "opts": [
     "먹어요",
     "먹었어요",
     "먹을 거예요",
     "먹고 싶어요"
    ],
    "explain": "ㅆ어요 is the polite past."
   },
   {
    "q": "“(I) will eat” is…",
    "a": "먹을 거예요",
    "opts": [
     "먹어요",
     "먹었어요",
     "먹을 거예요",
     "먹었거예요"
    ],
    "explain": "을 거예요 — consonant stem future."
   },
   {
    "q": "“I want to eat” is…",
    "a": "먹고 싶어요",
    "opts": [
     "먹어요 싶다",
     "먹고 싶어요",
     "먹을 싶어요",
     "먹기 싶어요"
    ],
    "explain": "고 싶어요 = want to."
   },
   {
    "q": "“Three people” is…",
    "a": "세 명",
    "opts": [
     "삼 명",
     "세 명",
     "셋 명",
     "세 사람"
    ],
    "explain": "셋 shortens to 세 before counters."
   },
   {
    "q": "“3:15” is…",
    "a": "세 시 십오 분",
    "opts": [
     "삼 시 십오 분",
     "세 시 십오 분",
     "세 시 열다섯 분",
     "삼 시 삼십오 분"
    ],
    "explain": "Native hours + Sino minutes."
   },
   {
    "q": "“I like kimchi” is…",
    "a": "김치를 좋아해요",
    "opts": [
     "김치가 좋아해요",
     "김치를 좋아해요",
     "김치에 좋아해요",
     "김치도 좋아해요"
    ],
    "explain": "좋아해요 takes the object particle."
   },
   {
    "q": "“I can't eat it” (allergy) is…",
    "a": "못 먹어요",
    "opts": [
     "안 먹어요",
     "못 먹어요",
     "먹지요",
     "안 먹지요"
    ],
    "explain": "못 = can't; 안 = won't."
   }
  ]
 },
 "quiz": [
  {
   "id": "ko-greet-1",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "Using 안녕 to a stranger is…",
   "a": "insulting",
   "opts": [
    "polite",
    "insulting",
    "formal",
    "normal"
   ],
   "explain": "안녕 is for friends/juniors only."
  },
  {
   "id": "ko-greet-2",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "You are LEAVING a friend's home. You say…",
   "a": "안녕히 계세요",
   "opts": [
    "안녕히 계세요",
    "안녕히 가세요",
    "안녕히 주무세요",
    "잘 가세요"
   ],
   "explain": "Leaver says: stay in peace."
  },
  {
   "id": "ko-greet-3",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "Business cards are received…",
   "a": "with two hands, then studied",
   "opts": [
    "one-handed",
    "with two hands, then studied",
    "never touched",
    "by bowing only"
   ],
   "explain": "Two hands, study aloud, table it."
  },
  {
   "id": "ko-greet-4",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“성함이 어떻게 되세요?” is…",
   "a": "honorific \"what is your name?\"",
   "opts": [
    "casual hello",
    "honorific \"what is your name?\"",
    "goodbye",
    "thank you"
   ],
   "explain": "Seongham — the honorific word for name."
  },
  {
   "id": "ko-han-1",
   "lesson": "hangul-and-particles",
   "type": "vocab",
   "topic": "script",
   "level": "beginner",
   "q": "ㅇ at a syllable's START is…",
   "a": "silent",
   "opts": [
    "ng",
    "silent",
    "n",
    "m"
   ],
   "explain": "Silent initially (아 = a); ng finally (강 = gang)."
  },
  {
   "id": "ko-han-2",
   "lesson": "hangul-and-particles",
   "type": "usage",
   "topic": "particles",
   "level": "beginner",
   "q": "Answer “누가 와요?” (who's coming?). You say…",
   "a": "제가 와요",
   "opts": [
    "제는 와요",
    "제가 와요",
    "저를 와요",
    "저도 와요"
   ],
   "explain": "Who-answers take 가."
  },
  {
   "id": "ko-han-3",
   "lesson": "hangul-and-particles",
   "type": "meaning",
   "topic": "particles",
   "level": "beginner",
   "q": "“저도 학생이에요” means…",
   "a": "I too am a student",
   "opts": [
    "am I a student?",
    "I too am a student",
    "only I study",
    "I was a student"
   ],
   "explain": "도 = also."
  },
  {
   "id": "ko-ida-1",
   "lesson": "ida-and-isseoyo",
   "type": "vocab",
   "topic": "grammar",
   "level": "beginner",
   "q": "“Is not a student” is…",
   "a": "학생이 아닙니다",
   "opts": [
    "학생이 아닙니다",
    "학생 안이에요",
    "학생이 없어요",
    "안 학생이에요"
   ],
   "explain": "이 아닙니다 negates identity."
  },
  {
   "id": "ko-ida-2",
   "lesson": "ida-and-isseoyo",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "Say “I have a car”. You say…",
   "a": "저는 차가 있어요",
   "opts": [
    "저는 차가 있어요",
    "저는 차를 있어요",
    "저는 차에 있어요",
    "제가 차를 해요"
   ],
   "explain": "Possession via existence: 차가 있어요."
  },
  {
   "id": "ko-ida-3",
   "lesson": "ida-and-isseoyo",
   "type": "meaning",
   "topic": "grammar",
   "level": "beginner",
   "q": "“맛있었어요!” (after the meal) means…",
   "a": "it WAS delicious!",
   "opts": [
    "it is delicious!",
    "it WAS delicious!",
    "it will be tasty!",
    "I am hungry!"
   ],
   "explain": "Past recollection after eating."
  },
  {
   "id": "ko-num-1",
   "lesson": "two-number-systems",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "5,000 won is…",
   "a": "오천 원",
   "opts": [
    "다섯천 원",
    "오천 원",
    "오백 원",
    "만오천 원"
   ],
   "explain": "Money uses Sino-Korean: 오천 원."
  },
  {
   "id": "ko-num-2",
   "lesson": "two-number-systems",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "The universal rescue counter is…",
   "a": "개",
   "opts": [
    "명",
    "개",
    "잔",
    "마리"
   ],
   "explain": "개 (gae) counts generic things."
  },
  {
   "id": "ko-num-3",
   "lesson": "two-number-systems",
   "type": "usage",
   "topic": "numbers",
   "level": "beginner",
   "q": "Say “two (things)” with a counter. You say…",
   "a": "두 개",
   "opts": [
    "둘 개",
    "두 개",
    "이 개",
    "둘의 개"
   ],
   "explain": "둘 shortens to 두 before counters."
  },
  {
   "id": "ko-food-1",
   "lesson": "food-and-ordering",
   "type": "usage",
   "topic": "food",
   "level": "beginner",
   "q": "Order bulgogi politely. You say…",
   "a": "불고기 주세요",
   "opts": [
    "불고기 주세요",
    "불고기가 주세요",
    "불고기를 해요",
    "주세요 불고기를"
   ],
   "explain": "…주세요 — please give me…"
  },
  {
   "id": "ko-food-2",
   "lesson": "food-and-ordering",
   "type": "meaning",
   "topic": "food",
   "level": "beginner",
   "q": "“밥 먹었어요?” doubles as…",
   "a": "\"how are you?\"",
   "opts": [
    "a dinner invite",
    "\"how are you?\"",
    "a complaint",
    "a bill request"
   ],
   "explain": "밥 = rice/meal — have you eaten = how are you."
  },
  {
   "id": "ko-food-3",
   "lesson": "food-and-ordering",
   "type": "vocab",
   "topic": "food",
   "level": "beginner",
   "q": "Ssam (쌈) is eaten…",
   "a": "in one bite",
   "opts": [
    "with a fork",
    "in one bite",
    "in small nibbles",
    "with chopsticks only"
   ],
   "explain": "Wrap it, eat it whole."
  },
  {
   "id": "ko-verb-1",
   "lesson": "present-tense-verbs",
   "type": "vocab",
   "topic": "verbs",
   "level": "beginner",
   "q": "하다 (do) becomes…",
   "a": "해요",
   "opts": [
    "하요",
    "해요",
    "하여요",
    "해어요"
   ],
   "explain": "Hada is special: 해요."
  },
  {
   "id": "ko-verb-2",
   "lesson": "present-tense-verbs",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "Propose “let's eat together”. You say…",
   "a": "같이 먹어요",
   "opts": [
    "같이 먹어요",
    "먹고 싶어요",
    "먹을 거예요",
    "같이 먹었어요"
   ],
   "explain": "같이…요 — let's together."
  },
  {
   "id": "ko-verb-3",
   "lesson": "present-tense-verbs",
   "type": "meaning",
   "topic": "verbs",
   "level": "beginner",
   "q": "“비가 오겠어요” means…",
   "a": "it will probably rain",
   "opts": [
    "it is raining",
    "it will probably rain",
    "it rained",
    "rain please"
   ],
   "explain": "겠 guesses about others."
  },
  {
   "id": "ko-greet-5",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "Receiving a drink from an elder: you…",
   "a": "use two hands, turn aside to sip",
   "opts": [
    "use one hand",
    "use two hands, turn aside to sip",
    "refuse first",
    "drink facing them"
   ],
   "explain": "Two hands to receive, turn aside to sip."
  }
 ],
 "review": [
  {
   "p": "안녕하세요",
   "a": "hello (are you at peace?)"
  },
  {
   "p": "저는…입니다",
   "a": "I am…"
  },
  {
   "p": "만나서 반갑습니다",
   "a": "pleased to meet you"
  },
  {
   "p": "안녕히 가세요 / 계세요",
   "a": "goodbye (stayer / leaver)"
  },
  {
   "p": "감사합니다",
   "a": "thank you"
  },
  {
   "p": "죄송합니다",
   "a": "sorry (formal)"
  },
  {
   "p": "한글",
   "a": "the Korean alphabet"
  },
  {
   "p": "은/는 · 이/가",
   "a": "topic · subject"
  },
  {
   "p": "책을 읽어요",
   "a": "(I) read a book"
  },
  {
   "p": "…주세요",
   "a": "…please (give me)"
  },
  {
   "p": "잘 먹겠습니다",
   "a": "before eating"
  },
  {
   "p": "잘 먹었습니다",
   "a": "after eating"
  },
  {
   "p": "맛있어요!",
   "a": "it's delicious!"
  },
  {
   "p": "계산서 주세요",
   "a": "bill, please"
  },
  {
   "p": "고양이가 있어요",
   "a": "there is a cat"
  },
  {
   "p": "저는 차가 있어요",
   "a": "I have a car"
  },
  {
   "p": "세 명",
   "a": "three people"
  },
  {
   "p": "세 시 십오 분",
   "a": "3:15"
  },
  {
   "p": "얼마예요?",
   "a": "how much?"
  },
  {
   "p": "먹었어요",
   "a": "(I) ate"
  },
  {
   "p": "먹을 거예요",
   "a": "(I) will eat"
  },
  {
   "p": "먹고 싶어요",
   "a": "I want to eat"
  },
  {
   "p": "안 먹어요 / 못 먹어요",
   "a": "won't eat / can't eat"
  },
  {
   "p": "같이 먹어요",
   "a": "let's eat together"
  }
 ]
};
