/* EkGuru — SPANISH COURSE BANK (authored, single source of truth).
   Generated by tools/build-language-course.py — do not hand-edit. */
window.EKGURU_COURSE_ES = {
 "practice": {
  "vocabulary": [
   {
    "q": "What does “hola” mean?",
    "a": "hello",
    "opts": [
     "goodbye",
     "hello",
     "please",
     "thanks"
    ],
    "explain": "Hola is hello — the one word every Spanish speaker knows and uses.",
    "say": "hola"
   },
   {
    "q": "What does “adiós” mean?",
    "a": "goodbye",
    "opts": [
     "hello",
     "goodbye",
     "good night",
     "welcome"
    ],
    "explain": "Adiós is goodbye.",
    "say": "adiós"
   },
   {
    "q": "What does “gracias” mean?",
    "a": "thank you",
    "opts": [
     "please",
     "thank you",
     "sorry",
     "yes"
    ],
    "explain": "Gracias is thank you. The reply is de nada (you're welcome).",
    "say": "gracias"
   },
   {
    "q": "What does “por favor” mean?",
    "a": "please",
    "opts": [
     "please",
     "thank you",
     "excuse me",
     "goodbye"
    ],
    "explain": "Por favor is please.",
    "say": "por favor"
   },
   {
    "q": "What does “agua” mean?",
    "a": "water",
    "opts": [
     "bread",
     "water",
     "wine",
     "milk"
    ],
    "explain": "Agua is water. Note it is feminine but takes el: el agua.",
    "say": "agua"
   },
   {
    "q": "What does “comida” mean?",
    "a": "food",
    "opts": [
     "food",
     "drink",
     "table",
     "kitchen"
    ],
    "explain": "Comida is food (and in Mexico, the midday meal).",
    "say": "comida"
   },
   {
    "q": "What does “casa” mean?",
    "a": "house",
    "opts": [
     "car",
     "house",
     "street",
     "room"
    ],
    "explain": "Casa is house or home.",
    "say": "casa"
   },
   {
    "q": "What does “amigo” mean?",
    "a": "friend",
    "opts": [
     "brother",
     "friend",
     "teacher",
     "neighbour"
    ],
    "explain": "Amigo is friend (masculine); amiga is the feminine form.",
    "say": "amigo"
   },
   {
    "q": "What does “trabajo” mean?",
    "a": "work",
    "opts": [
     "work",
     "holiday",
     "money",
     "time"
    ],
    "explain": "Trabajo is work — also the verb trabajar (to work).",
    "say": "trabajo"
   },
   {
    "q": "What does “tiempo” mean?",
    "a": "time",
    "opts": [
     "weather",
     "time",
     "money",
     "place"
    ],
    "explain": "Tiempo means both time and weather.",
    "say": "tiempo"
   },
   {
    "q": "What does “hoy” mean?",
    "a": "today",
    "opts": [
     "tomorrow",
     "today",
     "yesterday",
     "now"
    ],
    "explain": "Hoy is today; mañana is tomorrow; ayer is yesterday.",
    "say": "hoy"
   },
   {
    "q": "What does “noche” mean?",
    "a": "night",
    "opts": [
     "day",
     "night",
     "morning",
     "week"
    ],
    "explain": "Noche is night — as in buenas noches.",
    "say": "noche"
   }
  ],
  "grammar": [
   {
    "q": "Which verb means “to be” for identity: “Soy de India”?",
    "a": "ser",
    "opts": [
     "ser",
     "estar",
     "tener",
     "hacer"
    ],
    "explain": "Origin and identity use ser: soy de India = I am from India.",
    "say": "soy de India"
   },
   {
    "q": "“Estoy en casa” — which verb is this, and why?",
    "a": "estar — location",
    "opts": [
     "ser — identity",
     "estar — location",
     "ser — time",
     "tener — possession"
    ],
    "explain": "Location always uses estar.",
    "say": "estoy en casa"
   },
   {
    "q": "“El libro” vs “la casa” — why different articles?",
    "a": "libro is masculine, casa is feminine",
    "opts": [
     "libro is masculine, casa is feminine",
     "casa is plural",
     "libro is plural",
     "both are neutral"
    ],
    "explain": "Libro ends in -o (masculine), casa ends in -a (feminine).",
    "say": "el libro"
   },
   {
    "q": "Which is correct: “el día” or “la día”?",
    "a": "el día",
    "opts": [
     "el día",
     "la día",
     "los día",
     "las día"
    ],
    "explain": "Día is a famous exception: it is masculine despite ending in -a.",
    "say": "el día"
   },
   {
    "q": "“Hablamos” means…",
    "a": "we speak",
    "opts": [
     "I speak",
     "we speak",
     "they speak",
     "he speaks"
    ],
    "explain": "-amos is the nosotros (we) ending for -ar verbs.",
    "say": "hablamos"
   },
   {
    "q": "“Como” (from comer) means…",
    "a": "I eat",
    "opts": [
     "I eat",
     "he eats",
     "we eat",
     "they eat"
    ],
    "explain": "-o marks the yo (I) form in every family.",
    "say": "como"
   },
   {
    "q": "How do you say “how are you?” to a friend?",
    "a": "¿Cómo estás?",
    "opts": [
     "¿Cómo está?",
     "¿Cómo estás?",
     "¿Cómo se llama?",
     "¿Qué tal hoy?"
    ],
    "explain": "¿Cómo estás? is the informal (tú) form.",
    "say": "¿cómo estás?"
   },
   {
    "q": "“Me llamo Ana” literally means…",
    "a": "I call myself Ana",
    "opts": [
     "My name is Ana",
     "I call myself Ana",
     "Call me Ana",
     "Ana is my name"
    ],
    "explain": "Llamarse is reflexive: me llamo = I call myself.",
    "say": "me llamo Ana"
   },
   {
    "q": "Which means “the bill, please”?",
    "a": "La cuenta, por favor",
    "opts": [
     "La cuenta, por favor",
     "La comida, por favor",
     "La casa, por favor",
     "El menú, por favor"
    ],
    "explain": "La cuenta is the bill/check.",
    "say": "la cuenta, por favor"
   },
   {
    "q": "“Quisiera un café” means…",
    "a": "I would like a coffee",
    "opts": [
     "I want a coffee now",
     "I would like a coffee",
     "I had a coffee",
     "The coffee is cold"
    ],
    "explain": "Quisiera is the polite conditional — “I would like”.",
    "say": "quisiera un café"
   },
   {
    "q": "Choose the right verb: “Ella ___ alta” (she is tall).",
    "a": "es",
    "opts": [
     "es",
     "está",
     "tiene",
     "hay"
    ],
    "explain": "Height is a characteristic, so ser: ella es alta.",
    "say": "ella es alta"
   },
   {
    "q": "Choose the right verb: “El café ___ caliente” (the coffee is hot).",
    "a": "está",
    "opts": [
     "está",
     "es",
     "tiene",
     "hay"
    ],
    "explain": "Temperature is a temporary state, so estar.",
    "say": "el café está caliente"
   }
  ]
 },
 "quiz": [
  {
   "id": "es-greet-1",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "What does “buenos días” mean?",
   "a": "good morning",
   "opts": [
    "good night",
    "good morning",
    "good afternoon",
    "goodbye"
   ],
   "explain": "Buenos días is good morning — used until midday."
  },
  {
   "id": "es-greet-2",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "When should you use “usted” instead of “tú”?",
   "a": "With strangers and in formal situations",
   "opts": [
    "With friends",
    "With children",
    "With strangers and in formal situations",
    "Never"
   ],
   "explain": "Usted is the formal “you” for strangers, older people and formal settings."
  },
  {
   "id": "es-greet-3",
   "lesson": "greetings-and-introductions",
   "type": "vocab",
   "topic": "greetings",
   "level": "beginner",
   "q": "How do you ask a stranger's name politely?",
   "a": "¿Cómo se llama?",
   "opts": [
    "¿Cómo te llamas?",
    "¿Cómo se llama?",
    "¿Qué es esto?",
    "¿Dónde está?"
   ],
   "explain": "¿Cómo se llama? is the formal (usted) form of “what is your name?”."
  },
  {
   "id": "es-greet-4",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "“Buenas noches” can mean…",
   "a": "both good evening and good night",
   "opts": [
    "only good night",
    "only good evening",
    "both good evening and good night",
    "good morning"
   ],
   "explain": "Buenas noches works as a greeting when arriving late and as “good night” when leaving."
  },
  {
   "id": "es-ser-1",
   "lesson": "ser-and-estar",
   "type": "meaning",
   "topic": "grammar",
   "level": "beginner",
   "q": "“Soy de India” uses ser because…",
   "a": "origin uses ser",
   "opts": [
    "origin uses ser",
    "location uses ser",
    "mood uses ser",
    "it is a temporary state"
   ],
   "explain": "Origin and identity are permanent — they use ser."
  },
  {
   "id": "es-ser-2",
   "lesson": "ser-and-estar",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "“Estoy cansado” (I am tired) uses estar because…",
   "a": "tiredness is a temporary state",
   "opts": [
    "tiredness is a temporary state",
    "it is about identity",
    "it is about origin",
    "it is about profession"
   ],
   "explain": "Mood and condition are temporary states, so estar."
  },
  {
   "id": "es-ser-3",
   "lesson": "ser-and-estar",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "“Estoy listo” vs “Soy listo” — which means “I am ready”?",
   "a": "Estoy listo",
   "opts": [
    "Soy listo",
    "Estoy listo",
    "Both",
    "Neither"
   ],
   "explain": "Estoy listo = I am ready; soy listo = I am clever. The verb changes the meaning."
  },
  {
   "id": "es-gender-1",
   "lesson": "gender-and-articles",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "Which is the correct article for “casa”?",
   "a": "la",
   "opts": [
    "el",
    "la",
    "los",
    "un"
   ],
   "explain": "Casa ends in -a and is feminine: la casa."
  },
  {
   "id": "es-gender-2",
   "lesson": "gender-and-articles",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "Which of these is a famous exception to the -o/-a rule?",
   "a": "el día",
   "opts": [
    "el día",
    "la libro",
    "el casa",
    "la mano y el mapa"
   ],
   "explain": "El día (day) is masculine despite -a; la mano and el mapa are the other classics."
  },
  {
   "id": "es-gender-3",
   "lesson": "gender-and-articles",
   "type": "meaning",
   "topic": "grammar",
   "level": "beginner",
   "q": "Words ending in -ción (like canción) are usually…",
   "a": "feminine",
   "opts": [
    "feminine",
    "masculine",
    "neutral",
    "plural"
   ],
   "explain": "-ción, -sión and -dad nouns are almost always feminine: la canción."
  },
  {
   "id": "es-num-1",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "How do you say 16 in Spanish?",
   "a": "dieciséis",
   "opts": [
    "dieciséis",
    "diez y seis",
    "seis y diez",
    "dieciocho"
   ],
   "explain": "16 is dieciséis — literally “ten and six”."
  },
  {
   "id": "es-num-2",
   "lesson": "numbers-1-to-20",
   "type": "usage",
   "topic": "numbers",
   "level": "beginner",
   "q": "“Uno” shortens to “un” before…",
   "a": "a masculine noun",
   "opts": [
    "a feminine noun",
    "a masculine noun",
    "a plural noun",
    "a verb"
   ],
   "explain": "Un libro (one book), but una casa (one house)."
  },
  {
   "id": "es-num-3",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "“¿Cuánto cuesta?” means…",
   "a": "how much does it cost?",
   "opts": [
    "where is it?",
    "how much does it cost?",
    "what is it?",
    "how many are there?"
   ],
   "explain": "¿Cuánto cuesta? asks the price of one thing."
  },
  {
   "id": "es-food-1",
   "lesson": "food-and-ordering",
   "type": "usage",
   "topic": "food",
   "level": "beginner",
   "q": "The polite way to order in a restaurant is…",
   "a": "Quisiera…",
   "opts": [
    "Quisiera…",
    "Dame…",
    "Quiero ahora…",
    "Me da igual"
   ],
   "explain": "Quisiera (I would like) is polite everywhere."
  },
  {
   "id": "es-food-2",
   "lesson": "food-and-ordering",
   "type": "vocab",
   "topic": "food",
   "level": "beginner",
   "q": "“Agua con gas” is…",
   "a": "sparkling water",
   "opts": [
    "still water",
    "sparkling water",
    "tap water",
    "hot water"
   ],
   "explain": "Con gas = with bubbles (sparkling); sin gas = still."
  },
  {
   "id": "es-food-3",
   "lesson": "food-and-ordering",
   "type": "usage",
   "topic": "food",
   "level": "beginner",
   "q": "How do you ask for the bill?",
   "a": "La cuenta, por favor",
   "opts": [
    "La cuenta, por favor",
    "El menú, por favor",
    "La comida, por favor",
    "El agua, por favor"
   ],
   "explain": "La cuenta is the bill/check."
  },
  {
   "id": "es-verb-1",
   "lesson": "present-tense-regular-verbs",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "The “I” ending for regular -ar verbs is…",
   "a": "-o",
   "opts": [
    "-o",
    "-a",
    "-as",
    "-an"
   ],
   "explain": "Hablo, como, vivo — the yo form always ends in -o."
  },
  {
   "id": "es-verb-2",
   "lesson": "present-tense-regular-verbs",
   "type": "meaning",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Hablamos” means…",
   "a": "we speak",
   "opts": [
    "I speak",
    "we speak",
    "they speak",
    "he speaks"
   ],
   "explain": "-amos is the nosotros ending for -ar verbs."
  },
  {
   "id": "es-verb-3",
   "lesson": "present-tense-regular-verbs",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "Why do native speakers often drop “yo”?",
   "a": "the verb ending already shows the subject",
   "opts": [
    "the verb ending already shows the subject",
    "yo is rude",
    "yo is only for formal speech",
    "yo does not exist"
   ],
   "explain": "Hablo already means “I speak”, so yo is only added for emphasis."
  },
  {
   "id": "es-verb-4",
   "lesson": "present-tense-regular-verbs",
   "type": "vocab",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Comemos” vs “vivimos” — which verb families?",
   "a": "-er and -ir",
   "opts": [
    "-ar and -er",
    "-er and -ir",
    "-ar and -ir",
    "both -ar"
   ],
   "explain": "Comer is -er, vivir is -ir; the difference only shows in we/you-all forms."
  }
 ],
 "review": [
  {
   "p": "hola",
   "a": "hello"
  },
  {
   "p": "adiós",
   "a": "goodbye"
  },
  {
   "p": "gracias",
   "a": "thank you"
  },
  {
   "p": "por favor",
   "a": "please"
  },
  {
   "p": "buenos días",
   "a": "good morning"
  },
  {
   "p": "buenas noches",
   "a": "good evening / night"
  },
  {
   "p": "¿Cómo estás?",
   "a": "how are you? (informal)"
  },
  {
   "p": "Me llamo Ana",
   "a": "my name is Ana"
  },
  {
   "p": "¿Cómo te llamas?",
   "a": "what is your name? (informal)"
  },
  {
   "p": "soy de India",
   "a": "I am from India"
  },
  {
   "p": "estoy en casa",
   "a": "I am at home"
  },
  {
   "p": "el libro",
   "a": "the book"
  },
  {
   "p": "la casa",
   "a": "the house"
  },
  {
   "p": "el agua",
   "a": "the water"
  },
  {
   "p": "uno, dos, tres",
   "a": "one, two, three"
  },
  {
   "p": "dieciséis",
   "a": "sixteen"
  },
  {
   "p": "¿Cuánto cuesta?",
   "a": "how much does it cost?"
  },
  {
   "p": "La cuenta, por favor",
   "a": "the bill, please"
  },
  {
   "p": "Quisiera un café",
   "a": "I would like a coffee"
  },
  {
   "p": "hablo español",
   "a": "I speak Spanish"
  },
  {
   "p": "amigo / amiga",
   "a": "friend (m / f)"
  },
  {
   "p": "hoy",
   "a": "today"
  },
  {
   "p": "comida",
   "a": "food"
  },
  {
   "p": "trabajo",
   "a": "work"
  }
 ]
};
