/* EkGuru — ITALIAN COURSE BANK (authored, single source of truth).
   Generated by tools/build-language-course.py — do not hand-edit. */
window.EKGURU_COURSE_IT = {
 "practice": {
  "vocabulary": [
   {
    "q": "What does “buongiorno” mean?",
    "a": "good morning / good day",
    "opts": [
     "good morning / good day",
     "good evening",
     "good night",
     "goodbye"
    ],
    "explain": "Buongiorno covers morning to early afternoon."
   },
   {
    "q": "“Ciao” is used…",
    "a": "informally, hello and goodbye",
    "opts": [
     "formally only",
     "informally, hello and goodbye",
     "for goodbye only",
     "for hello only"
    ],
    "explain": "Ciao is informal — both hello and goodbye."
   },
   {
    "q": "“Grazie mille” means…",
    "a": "a thousand thanks",
    "opts": [
     "please",
     "a thousand thanks",
     "you're welcome",
     "excuse me"
    ],
    "explain": "Grazie mille adds real warmth to thanks."
   },
   {
    "q": "The reply to “grazie” is…",
    "a": "prego",
    "opts": [
     "prego",
     "per favore",
     "scusi",
     "salute"
    ],
    "explain": "Prego means you're welcome — and much more."
   },
   {
    "q": "What does “il conto” mean?",
    "a": "the bill",
    "opts": [
     "the menu",
     "the bill",
     "the tip",
     "the course"
    ],
    "explain": "Il conto, per favore — the bill, please."
   },
   {
    "q": "“Ho fame” means…",
    "a": "I am hungry",
    "opts": [
     "I am thirsty",
     "I am hungry",
     "I am tired",
     "I am cold"
    ],
    "explain": "Hunger uses avere: Ho fame."
   },
   {
    "q": "“Buon appetito!” is said…",
    "a": "before starting to eat",
    "opts": [
     "after paying",
     "before starting to eat",
     "when ordering",
     "when leaving"
    ],
    "explain": "Buon appetito opens the meal."
   },
   {
    "q": "A cappuccino after lunch is…",
    "a": "a foreigner's mistake",
    "opts": [
     "normal",
     "a foreigner's mistake",
     "required",
     "cheaper"
    ],
    "explain": "Cappuccino is breakfast only in Italy."
   },
   {
    "q": "What does “c'è” mean?",
    "a": "there is",
    "opts": [
     "there is",
     "there are",
     "it is",
     "here is"
    ],
    "explain": "C'è is there is; ci sono is there are."
   },
   {
    "q": "“Mi dispiace” means…",
    "a": "I'm sorry",
    "opts": [
     "I like it",
     "I'm sorry",
     "I don't know",
     "excuse me (passing)"
    ],
    "explain": "Mi dispiace apologises — I'm sorry."
   },
   {
    "q": "“Quanti anni hai?” asks about…",
    "a": "age (informal)",
    "opts": [
     "name",
     "age (informal)",
     "origin",
     "time"
    ],
    "explain": "Quanti anni hai? — how old are you? (informal)."
   },
   {
    "q": "What does “che buono!” mean?",
    "a": "how delicious!",
    "opts": [
     "how much!",
     "how delicious!",
     "how big!",
     "how fast!"
    ],
    "explain": "Che buono! praises the food."
   }
  ],
  "grammar": [
   {
    "q": "“The book” (libro, masculine) is…",
    "a": "il libro",
    "opts": [
     "il libro",
     "lo libro",
     "la libro",
     "l'libro"
    ],
    "explain": "Masculine + consonant takes il: il libro."
   },
   {
    "q": "“The student” (studente, masculine) is…",
    "a": "lo studente",
    "opts": [
     "il studente",
     "lo studente",
     "la studente",
     "l'studente"
    ],
    "explain": "S+consonant takes lo: lo studente."
   },
   {
    "q": "“The friend” (amica, feminine, vowel) is…",
    "a": "l'amica",
    "opts": [
     "la amica",
     "l'amica",
     "una amica",
     "le amica"
    ],
    "explain": "Feminine before a vowel elides: l'amica."
   },
   {
    "q": "The plural of “casa” is…",
    "a": "case",
    "opts": [
     "casi",
     "case",
     "casa",
     "casas"
    ],
    "explain": "-a becomes -e: casa → case."
   },
   {
    "q": "“I am” is…",
    "a": "sono",
    "opts": [
     "sono",
     "sei",
     "è",
     "siamo"
    ],
    "explain": "Essere: io sono, tu sei, lui è."
   },
   {
    "q": "“You (informal) have” is…",
    "a": "hai",
    "opts": [
     "ho",
     "hai",
     "ha",
     "avete"
    ],
    "explain": "Avere: io ho, tu hai, lui ha."
   },
   {
    "q": "“There are two museums” is…",
    "a": "Ci sono due musei",
    "opts": [
     "C'è due musei",
     "Ci sono due musei",
     "Sono due musei",
     "È due musei"
    ],
    "explain": "Plural existence: ci sono."
   },
   {
    "q": "“I don't speak Italian” is…",
    "a": "Non parlo italiano",
    "opts": [
     "Non parlo italiano",
     "No parlo italiano",
     "Parlo non italiano",
     "Io non parli italiano"
    ],
    "explain": "Non before the verb: Non parlo."
   },
   {
    "q": "“You (informal) speak” is…",
    "a": "parli",
    "opts": [
     "parlo",
     "parli",
     "parla",
     "parlate"
    ],
    "explain": "-are verbs: tu takes -i — parli."
   },
   {
    "q": "“I understand” (capire) is…",
    "a": "capisco",
    "opts": [
     "capo",
     "capiro",
     "capisco",
     "capisce"
    ],
    "explain": "Capire takes -isc-: capisco."
   },
   {
    "q": "“Of the” (di + il) fuses to…",
    "a": "del",
    "opts": [
     "dil",
     "del",
     "dal",
     "dei"
    ],
    "explain": "Di + il = del — fusion is mandatory."
   },
   {
    "q": "“I like it” is…",
    "a": "mi piace",
    "opts": [
     "mi piaccio",
     "mi piace",
     "mi piacciono",
     "io piaccio"
    ],
    "explain": "Singular liked thing: mi piace (plural: mi piacciono)."
   }
  ]
 },
 "quiz": [
  {
   "id": "it-greet-1",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "What does “buonasera” mean?",
   "a": "good evening",
   "opts": [
    "good morning",
    "good afternoon",
    "good evening",
    "good night"
   ],
   "explain": "Buonasera is good evening — from mid-afternoon."
  },
  {
   "id": "it-greet-2",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "You greet a shopkeeper at 10 am. You say…",
   "a": "buongiorno",
   "opts": [
    "ciao",
    "buongiorno",
    "buonasera",
    "buonanotte"
   ],
   "explain": "Strangers get buongiorno; ciao is for friends."
  },
  {
   "id": "it-greet-3",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“Mi chiamo Anna” means…",
   "a": "I call myself Anna",
   "opts": [
    "I call myself Anna",
    "I know Anna",
    "call Anna",
    "Anna calls me"
   ],
   "explain": "Mi chiamo… — I call myself…"
  },
  {
   "id": "it-greet-4",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "Ask a stranger's name (formal). You say…",
   "a": "Come si chiama?",
   "opts": [
    "Come ti chiami?",
    "Come si chiama?",
    "Chi sei?",
    "Cosa sei?"
   ],
   "explain": "Strangers get Lei: Come si chiama?"
  },
  {
   "id": "it-noun-1",
   "lesson": "nouns-gender-and-articles",
   "type": "vocab",
   "topic": "grammar",
   "level": "beginner",
   "q": "“The house” (casa, feminine) is…",
   "a": "la casa",
   "opts": [
    "il casa",
    "la casa",
    "lo casa",
    "l'casa"
   ],
   "explain": "Feminine + consonant: la casa."
  },
  {
   "id": "it-noun-2",
   "lesson": "nouns-gender-and-articles",
   "type": "vocab",
   "topic": "grammar",
   "level": "beginner",
   "q": "The plural of “libro” is…",
   "a": "libri",
   "opts": [
    "libri",
    "libre",
    "libros",
    "libra"
   ],
   "explain": "-o becomes -i: libro → libri."
  },
  {
   "id": "it-noun-3",
   "lesson": "nouns-gender-and-articles",
   "type": "meaning",
   "topic": "grammar",
   "level": "beginner",
   "q": "“Un'amica” elides because…",
   "a": "una drops -a before a vowel",
   "opts": [
    "amica is masculine",
    "una drops -a before a vowel",
    "articles are optional",
    "amica is plural"
   ],
   "explain": "Una + vowel → un': un'amica."
  },
  {
   "id": "it-ess-1",
   "lesson": "essere-and-avere",
   "type": "vocab",
   "topic": "verbs",
   "level": "beginner",
   "q": "“We are” is…",
   "a": "siamo",
   "opts": [
    "siamo",
    "siete",
    "sono",
    "sei"
   ],
   "explain": "Essere: noi siamo, voi siete, loro sono."
  },
  {
   "id": "it-ess-2",
   "lesson": "essere-and-avere",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "Say “I am 20” (age). You say…",
   "a": "Ho vent'anni",
   "opts": [
    "Sono vent'anni",
    "Ho vent'anni",
    "Ho venti anni vecchi",
    "Mi sono venti"
   ],
   "explain": "Age uses avere, elided: Ho vent'anni."
  },
  {
   "id": "it-ess-3",
   "lesson": "essere-and-avere",
   "type": "meaning",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Ho paura” means…",
   "a": "I am afraid",
   "opts": [
    "I am afraid",
    "I am hungry",
    "I have fearfulness",
    "I fear having"
   ],
   "explain": "Fear uses avere: Ho paura."
  },
  {
   "id": "it-num-1",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "“Sette” is the number…",
   "a": "7",
   "opts": [
    "6",
    "7",
    "9",
    "17"
   ],
   "explain": "Sei is 6, sette is 7."
  },
  {
   "id": "it-num-2",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "“Diciotto” is…",
   "a": "18",
   "opts": [
    "8",
    "18",
    "80",
    "88"
   ],
   "explain": "Diciotto is 18 — ten-first pattern."
  },
  {
   "id": "it-num-3",
   "lesson": "numbers-1-to-20",
   "type": "usage",
   "topic": "numbers",
   "level": "beginner",
   "q": "Say “it is three o'clock”. You say…",
   "a": "Sono le tre",
   "opts": [
    "È le tre",
    "Sono le tre",
    "Sono tre ore",
    "È tre"
   ],
   "explain": "Hours are feminine plural: Sono le tre (but È l'una)."
  },
  {
   "id": "it-food-1",
   "lesson": "food-and-ordering",
   "type": "usage",
   "topic": "food",
   "level": "beginner",
   "q": "Order a coffee politely. You say…",
   "a": "Vorrei un caffè, per favore",
   "opts": [
    "Vorrei un caffè, per favore",
    "Voglio caffè subito",
    "Dammi un caffè",
    "Caffè per me adesso"
   ],
   "explain": "Vorrei… per favore is the polite ordering phrase."
  },
  {
   "id": "it-food-2",
   "lesson": "food-and-ordering",
   "type": "meaning",
   "topic": "food",
   "level": "beginner",
   "q": "“Il conto, per favore” means…",
   "a": "the bill, please",
   "opts": [
    "the menu, please",
    "the bill, please",
    "one more, please",
    "table for two"
   ],
   "explain": "Il conto is the bill."
  },
  {
   "id": "it-food-3",
   "lesson": "food-and-ordering",
   "type": "vocab",
   "topic": "food",
   "level": "beginner",
   "q": "Still water is…",
   "a": "acqua naturale",
   "opts": [
    "acqua frizzante",
    "acqua naturale",
    "acqua calda",
    "acqua fresca"
   ],
   "explain": "Naturale is still; frizzante is sparkling."
  },
  {
   "id": "it-verb-1",
   "lesson": "present-tense-regular-verbs",
   "type": "vocab",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Parlano” — the ending -no marks…",
   "a": "loro (they)",
   "opts": [
    "io",
    "tu",
    "noi",
    "loro (they)"
   ],
   "explain": "The -no ending always marks loro."
  },
  {
   "id": "it-verb-2",
   "lesson": "present-tense-regular-verbs",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "Ask “where do you live?” (informal). You say…",
   "a": "Dove abiti?",
   "opts": [
    "Dove abiti?",
    "Dove abita?",
    "Dove abitare?",
    "Abiti dove tu?"
   ],
   "explain": "No inversion: Dove abiti?"
  },
  {
   "id": "it-verb-3",
   "lesson": "present-tense-regular-verbs",
   "type": "meaning",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Non capisco” means…",
   "a": "I don't understand",
   "opts": [
    "I don't understand",
    "I don't speak",
    "she doesn't understand",
    "we don't understand"
   ],
   "explain": "Non capisco — the -isc- verb every beginner needs."
  },
  {
   "id": "it-greet-5",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“Arrivederci” is safe with anyone because…",
   "a": "it works in every register",
   "opts": [
    "it works in every register",
    "it is archaic",
    "it is slang",
    "it means please"
   ],
   "explain": "Arrivederci is the neutral goodbye; ciao is informal only."
  }
 ],
 "review": [
  {
   "p": "ciao",
   "a": "hello/bye (informal)"
  },
  {
   "p": "buongiorno",
   "a": "good morning / day"
  },
  {
   "p": "buonasera",
   "a": "good evening"
  },
  {
   "p": "arrivederci",
   "a": "goodbye"
  },
  {
   "p": "grazie",
   "a": "thanks"
  },
  {
   "p": "prego",
   "a": "you're welcome"
  },
  {
   "p": "per favore",
   "a": "please"
  },
  {
   "p": "Mi chiamo…",
   "a": "I call myself…"
  },
  {
   "p": "il / lo / la",
   "a": "the (m / m* / f)"
  },
  {
   "p": "un / uno / una",
   "a": "a (m / m* / f)"
  },
  {
   "p": "sono",
   "a": "I am"
  },
  {
   "p": "sei",
   "a": "you are (informal)"
  },
  {
   "p": "è",
   "a": "he/she/it is"
  },
  {
   "p": "ho",
   "a": "I have"
  },
  {
   "p": "hai",
   "a": "you have (informal)"
  },
  {
   "p": "non",
   "a": "not (before the verb)"
  },
  {
   "p": "uno, due, tre",
   "a": "one, two, three"
  },
  {
   "p": "venti",
   "a": "twenty"
  },
  {
   "p": "Ho vent'anni",
   "a": "I am 20 years old"
  },
  {
   "p": "Vorrei…",
   "a": "I would like…"
  },
  {
   "p": "Il conto, per favore",
   "a": "the bill, please"
  },
  {
   "p": "Buon appetito!",
   "a": "enjoy your meal!"
  },
  {
   "p": "parlo",
   "a": "I speak"
  },
  {
   "p": "Dove abiti?",
   "a": "where do you live?"
  }
 ]
};
