/* EkGuru — ARABIC COURSE BANK (authored, single source of truth).
   Generated by tools/build-language-course.py — do not hand-edit. */
window.EKGURU_COURSE_AR = {
 "practice": {
  "vocabulary": [
   {
    "q": "What does “السلام عليكم” mean?",
    "a": "peace upon you",
    "opts": [
     "good morning",
     "peace upon you",
     "goodbye",
     "thank you"
    ],
    "explain": "As-salāmu ʿalaykum — peace upon you — the universal hello."
   },
   {
    "q": "The required answer is…",
    "a": "وعليكم السلام",
    "opts": [
     "وعليكم السلام",
     "مع السلامة",
     "أهلا وسهلا",
     "مرحبا بك"
    ],
    "explain": "Wa ʿalaykum as-salām — and upon you peace."
   },
   {
    "q": "“شكرا” means…",
    "a": "thanks",
    "opts": [
     "please",
     "thanks",
     "sorry",
     "hello"
    ],
    "explain": "Shukran is thanks; عفوا answers it."
   },
   {
    "q": "The reply to thanks is…",
    "a": "عفوا",
    "opts": [
     "عفوا",
     "شكرا",
     "من فضلك",
     "لو سمحت"
    ],
    "explain": "ʿAfwan — pardon — answers shukran."
   },
   {
    "q": "What does “الحساب” mean?",
    "a": "the bill",
    "opts": [
     "the menu",
     "the bill",
     "the table",
     "the tip"
    ],
    "explain": "Al-ḥisāb law samaḥt — the bill, please."
   },
   {
    "q": "“أنا جائع” (man speaking) means…",
    "a": "I am hungry",
    "opts": [
     "I am thirsty",
     "I am hungry",
     "I am tired",
     "I am full"
    ],
    "explain": "Anā jā'iʿ — I am hungry (man; woman: jā'iʿa)."
   },
   {
    "q": "“لذيذ!” means…",
    "a": "delicious!",
    "opts": [
     "big!",
     "delicious!",
     "hot!",
     "sweet!"
    ],
    "explain": "Ladhīdh! praises the food."
   },
   {
    "q": "“الشمس” is pronounced…",
    "a": "ash-shams",
    "opts": [
     "al-shams",
     "ash-shams",
     "as-shams",
     "el-shams"
    ],
    "explain": "ش is a sun letter: the ل assimilates — ash-shams."
   },
   {
    "q": "“بسم الله” is said…",
    "a": "before eating",
    "opts": [
     "after eating",
     "before eating",
     "when paying",
     "when leaving"
    ],
    "explain": "Bismillāh opens the meal."
   },
   {
    "q": "“أنا اسمي علي” means…",
    "a": "my name is Ali",
    "opts": [
     "my name is Ali",
     "I know Ali",
     "call Ali",
     "Ali knows me"
    ],
    "explain": "Anā ismī… — I, my name is…"
   },
   {
    "q": "“كتب” without vowels shows that…",
    "a": "short vowels are usually unwritten",
    "opts": [
     "Arabic has no vowels",
     "short vowels are usually unwritten",
     "all words look alike",
     "vowels don't matter"
    ],
    "explain": "Kataba/kutub share كتب — context decides."
   },
   {
    "q": "“لا أفهم” means…",
    "a": "I don't understand",
    "opts": [
     "I don't know",
     "I don't understand",
     "I don't speak",
     "I don't hear"
    ],
    "explain": "Lā afham — the beginner's shield."
   }
  ],
  "grammar": [
   {
    "q": "“You” to a woman is…",
    "a": "أنتِ",
    "opts": [
     "أنتَ",
     "أنتِ",
     "هو",
     "نحن"
    ],
    "explain": "Anti — you to a woman; anta to a man."
   },
   {
    "q": "“He is a student” is…",
    "a": "هو طالب",
    "opts": [
     "هو طالب",
     "هو يكون طالب",
     "هو في طالب",
     "طالب هو يكون"
    ],
    "explain": "Present \"is\" is omitted: هو طالب."
   },
   {
    "q": "“I am not a student” is…",
    "a": "لست طالبا",
    "opts": [
     "لا أنا طالب",
     "لست طالبا",
     "أنا مش طالب",
     "ما أنا طالب"
    ],
    "explain": "Laysa negates identity: لست طالبا."
   },
   {
    "q": "“I have a book” is…",
    "a": "عندي كتاب",
    "opts": [
     "أنا عندي كتاب",
     "عندي كتاب",
     "لي كتاب عند",
     "أملك كتابا"
    ],
    "explain": "ʿIndī kitāb — at-me a book."
   },
   {
    "q": "“The student's book” is…",
    "a": "كتاب الطالب",
    "opts": [
     "الكتاب الطالب",
     "كتاب الطالب",
     "كتاب لطالب",
     "الطالب كتاب"
    ],
    "explain": "Iḍāfa: possessed + possessor, no \"of\"."
   },
   {
    "q": "“Three books” (masculine noun) is…",
    "a": "ثلاثة كتب",
    "opts": [
     "ثلاث كتب",
     "ثلاثة كتب",
     "ثلاثة كتاب",
     "ثلث كتب"
    ],
    "explain": "Polarity: masculine noun takes ثلاثة."
   },
   {
    "q": "“Three (female) students” is…",
    "a": "ثلاث طالبات",
    "opts": [
     "ثلاثة طالبات",
     "ثلاث طالبات",
     "ثلاث طالبة",
     "ثالث طالبات"
    ],
    "explain": "Polarity: feminine noun takes bare ثلاث."
   },
   {
    "q": "“I write” is…",
    "a": "أكتب",
    "opts": [
     "أكتب",
     "تكتب",
     "يكتب",
     "نكتب"
    ],
    "explain": "أ prefix marks أنا: أكتب."
   },
   {
    "q": "“She writes” is…",
    "a": "تكتب",
    "opts": [
     "يكتب",
     "تكتب",
     "أكتب",
     "نكتب"
    ],
    "explain": "هي takes ت: تكتب (same as أنتَ)."
   },
   {
    "q": "“I don't know” is…",
    "a": "لا أعرف",
    "opts": [
     "لا أعرف",
     "ما أعرف",
     "لم أعرف",
     "لن أعرف"
    ],
    "explain": "Present negation: لا + verb."
   },
   {
    "q": "“Where do you (m) live?” is…",
    "a": "أين تسكن؟",
    "opts": [
     "أين تسكن؟",
     "أين أسكن؟",
     "أين يسكن؟",
     "أين نسكن؟"
    ],
    "explain": "No inversion: أين تسكن؟"
   },
   {
    "q": "“My age is 20” is…",
    "a": "عمري عشرون سنة",
    "opts": [
     "عمري عشرون سنة",
     "أنا عشرون سنة",
     "عندي عشرون سنة",
     "سني عشرون عام"
    ],
    "explain": "ʿUmrī ʿishrūn sana."
   }
  ]
 },
 "quiz": [
  {
   "id": "ar-greet-1",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "What does “صباح الخير” mean?",
   "a": "good morning",
   "opts": [
    "good morning",
    "good evening",
    "good night",
    "goodbye"
   ],
   "explain": "Ṣabāḥ al-khayr — morning of goodness."
  },
  {
   "id": "ar-greet-2",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "Someone says السلام عليكم. You answer…",
   "a": "وعليكم السلام",
   "opts": [
    "مع السلامة",
    "وعليكم السلام",
    "مرحبا",
    "أهلا"
   ],
   "explain": "The greeting demands its answer."
  },
  {
   "id": "ar-greet-3",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“مع السلامة” means…",
   "a": "goodbye (go with safety)",
   "opts": [
    "good morning",
    "goodbye (go with safety)",
    "welcome",
    "please sit"
   ],
   "explain": "Maʿa as-salāma — go with safety."
  },
  {
   "id": "ar-greet-4",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "Ask a woman's name. You say…",
   "a": "ما اسمك؟ (ismik)",
   "opts": [
    "ما اسمك؟ (ismik)",
    "ما اسمك؟ (ismuk)",
    "ما هو اسمك؟",
    "كيف اسمك؟"
   ],
   "explain": "To a woman: mā ismik?"
  },
  {
   "id": "ar-alpha-1",
   "lesson": "alphabet-and-sounds",
   "type": "vocab",
   "topic": "script",
   "level": "beginner",
   "q": "Arabic is written…",
   "a": "right to left",
   "opts": [
    "left to right",
    "right to left",
    "top to bottom",
    "in columns"
   ],
   "explain": "Right to left, letters joining."
  },
  {
   "id": "ar-alpha-2",
   "lesson": "alphabet-and-sounds",
   "type": "vocab",
   "topic": "script",
   "level": "beginner",
   "q": "“القمر” (the moon) is pronounced…",
   "a": "al-qamar",
   "opts": [
    "al-qamar",
    "aq-qamar",
    "el-qamar",
    "ash-qamar"
   ],
   "explain": "ق is a moon letter: the ل stays — al-qamar."
  },
  {
   "id": "ar-alpha-3",
   "lesson": "alphabet-and-sounds",
   "type": "meaning",
   "topic": "script",
   "level": "beginner",
   "q": "Short vowels are usually…",
   "a": "omitted in writing",
   "opts": [
    "written always",
    "omitted in writing",
    "written in red",
    "spoken only"
   ],
   "explain": "Ḥarakāt appear in learners' texts, rarely elsewhere."
  },
  {
   "id": "ar-pro-1",
   "lesson": "pronouns-and-to-be",
   "type": "vocab",
   "topic": "grammar",
   "level": "beginner",
   "q": "“They (men)” is…",
   "a": "هم",
   "opts": [
    "هن",
    "هم",
    "أنتم",
    "نحن"
   ],
   "explain": "Hum — they (masculine); hunna (هن) feminine."
  },
  {
   "id": "ar-pro-2",
   "lesson": "pronouns-and-to-be",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "Say “the house door's key” (chain). You say…",
   "a": "مفتاح باب البيت",
   "opts": [
    "مفتاح باب البيت",
    "المفتاح الباب البيت",
    "مفتاح لباب لبيت",
    "بيت باب مفتاح"
   ],
   "explain": "Iḍāfa chains: مفتاح باب البيت."
  },
  {
   "id": "ar-pro-3",
   "lesson": "pronouns-and-to-be",
   "type": "meaning",
   "topic": "grammar",
   "level": "beginner",
   "q": "“هو طالب” has no “is” because…",
   "a": "present \"is\" is omitted",
   "opts": [
    "طالب means is",
    "present \"is\" is omitted",
    "هو means is",
    "Arabic has no verbs"
   ],
   "explain": "Zero copula in the present."
  },
  {
   "id": "ar-num-1",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "“سبعة” is the number…",
   "a": "7",
   "opts": [
    "6",
    "7",
    "9",
    "17"
   ],
   "explain": "Sitta is 6, sabʿa is 7."
  },
  {
   "id": "ar-num-2",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "“One car” (feminine) is…",
   "a": "سيارة واحدة",
   "opts": [
    "سيارة واحد",
    "سيارة واحدة",
    "واحدة سيارة",
    "واحد سيارة"
   ],
   "explain": "Feminine one: واحدة, after the noun."
  },
  {
   "id": "ar-num-3",
   "lesson": "numbers-1-to-20",
   "type": "usage",
   "topic": "numbers",
   "level": "beginner",
   "q": "Ask a man's age. You say…",
   "a": "كم عمرك؟ (ʿumruk)",
   "opts": [
    "كم عمرك؟ (ʿumruk)",
    "كم عمرك؟ (ʿumrik)",
    "كم سنة لك؟",
    "ما عمرك أنت؟"
   ],
   "explain": "To a man: kam ʿumruk?"
  },
  {
   "id": "ar-food-1",
   "lesson": "food-and-ordering",
   "type": "usage",
   "topic": "food",
   "level": "beginner",
   "q": "Order tea politely. You say…",
   "a": "أريد شايا، من فضلك",
   "opts": [
    "أريد شايا، من فضلك",
    "أعطني شاي الآن",
    "شاي بسرعة",
    "أبغى شاي حال"
   ],
   "explain": "Urīdu shāyan, min faḍlik."
  },
  {
   "id": "ar-food-2",
   "lesson": "food-and-ordering",
   "type": "meaning",
   "topic": "food",
   "level": "beginner",
   "q": "“الحساب لو سمحت” means…",
   "a": "the bill, please",
   "opts": [
    "the menu, please",
    "the bill, please",
    "one more, please",
    "table for two"
   ],
   "explain": "Al-ḥisāb — the bill."
  },
  {
   "id": "ar-food-3",
   "lesson": "food-and-ordering",
   "type": "vocab",
   "topic": "food",
   "level": "beginner",
   "q": "Bread (the utensil) is…",
   "a": "خبز",
   "opts": [
    "خبز",
    "أرز",
    "لحم",
    "ماء"
   ],
   "explain": "Khubz — tear and scoop with it."
  },
  {
   "id": "ar-verb-1",
   "lesson": "present-tense-verbs",
   "type": "vocab",
   "topic": "verbs",
   "level": "beginner",
   "q": "“نكتب” — the prefix marks…",
   "a": "نحن (we)",
   "opts": [
    "أنا",
    "أنت",
    "نحن (we)",
    "هم"
   ],
   "explain": "The ن prefix always marks نحن."
  },
  {
   "id": "ar-verb-2",
   "lesson": "present-tense-verbs",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "Ask “where do you (m) live?”. You say…",
   "a": "أين تسكن؟",
   "opts": [
    "أين تسكن؟",
    "أين أسكن؟",
    "أين يسكن؟",
    "أين سكنت؟"
   ],
   "explain": "No inversion: أين تسكن؟"
  },
  {
   "id": "ar-verb-3",
   "lesson": "present-tense-verbs",
   "type": "meaning",
   "topic": "verbs",
   "level": "beginner",
   "q": "كتاب، مكتبة and كاتب share…",
   "a": "the root ك-ت-ب (writing)",
   "opts": [
    "the same vowels",
    "the root ك-ت-ب (writing)",
    "the same length",
    "nothing — coincidence"
   ],
   "explain": "One root, one family: writing."
  },
  {
   "id": "ar-greet-5",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“من فضلك” literally means…",
   "a": "from your grace",
   "opts": [
    "from your grace",
    "with sugar",
    "by order",
    "under God"
   ],
   "explain": "Min faḍlik — from your grace."
  }
 ],
 "review": [
  {
   "p": "السلام عليكم",
   "a": "peace upon you (hello)"
  },
  {
   "p": "وعليكم السلام",
   "a": "and upon you peace (answer)"
  },
  {
   "p": "صباح الخير",
   "a": "good morning"
  },
  {
   "p": "مساء الخير",
   "a": "good evening"
  },
  {
   "p": "مع السلامة",
   "a": "goodbye"
  },
  {
   "p": "شكرا",
   "a": "thanks"
  },
  {
   "p": "عفوا",
   "a": "you're welcome"
  },
  {
   "p": "من فضلك",
   "a": "please"
  },
  {
   "p": "أنا اسمي…",
   "a": "my name is…"
  },
  {
   "p": "أنتَ / أنتِ",
   "a": "you (to man / woman)"
  },
  {
   "p": "هو طالب",
   "a": "he is a student"
  },
  {
   "p": "عندي…",
   "a": "I have…"
  },
  {
   "p": "كتاب الطالب",
   "a": "the student's book"
  },
  {
   "p": "واحد، اثنان، ثلاثة",
   "a": "one, two, three"
  },
  {
   "p": "عشرون",
   "a": "twenty"
  },
  {
   "p": "عمري عشرون سنة",
   "a": "I am 20 years old"
  },
  {
   "p": "أريد…",
   "a": "I want…"
  },
  {
   "p": "الحساب لو سمحت",
   "a": "the bill, please"
  },
  {
   "p": "بسم الله",
   "a": "in God's name (before eating)"
  },
  {
   "p": "لذيذ!",
   "a": "delicious!"
  },
  {
   "p": "أكتب",
   "a": "I write"
  },
  {
   "p": "لا أعرف",
   "a": "I don't know"
  },
  {
   "p": "لا أفهم",
   "a": "I don't understand"
  },
  {
   "p": "أين تسكن؟",
   "a": "where do you live?"
  }
 ]
};
