/* EkGuru — PORTUGUESE COURSE BANK (authored, single source of truth).
   Generated by tools/build-language-course.py — do not hand-edit. */
window.EKGURU_COURSE_PT = {
 "practice": {
  "vocabulary": [
   {
    "q": "What does “bom dia” mean?",
    "a": "good morning",
    "opts": [
     "good morning",
     "good afternoon",
     "good evening",
     "good night"
    ],
    "explain": "Bom dia is good morning — boa tarde follows at midday."
   },
   {
    "q": "“Boa noite” covers…",
    "a": "evening greeting and night farewell",
    "opts": [
     "morning only",
     "evening greeting and night farewell",
     "afternoon only",
     "farewells only"
    ],
    "explain": "Boa noite does double duty: good evening and good night."
   },
   {
    "q": "A woman says thank you. She says…",
    "a": "obrigada",
    "opts": [
     "obrigado",
     "obrigada",
     "obrigados",
     "obrigadas"
    ],
    "explain": "The ending matches the speaker: men obrigado, women obrigada."
   },
   {
    "q": "What does “a conta” mean?",
    "a": "the bill",
    "opts": [
     "the menu",
     "the bill",
     "the table",
     "the menu (PT)"
    ],
    "explain": "A conta, por favor — the bill, please."
   },
   {
    "q": "“Tenho fome” means…",
    "a": "I am hungry",
    "opts": [
     "I am thirsty",
     "I am hungry",
     "I am tired",
     "I am full"
    ],
    "explain": "Hunger uses ter: Tenho fome."
   },
   {
    "q": "“Quanto custa?” means…",
    "a": "how much is it?",
    "opts": [
     "what is it?",
     "how much is it?",
     "where is it?",
     "who is it?"
    ],
    "explain": "Quanto custa? — how much is it?"
   },
   {
    "q": "In Brazil, the menu is…",
    "a": "o cardápio",
    "opts": [
     "o cardápio",
     "a ementa",
     "a conta",
     "o prato"
    ],
    "explain": "Brazil: cardápio; Portugal: ementa."
   },
   {
    "q": "“Quatorze / catorze” is the number…",
    "a": "14",
    "opts": [
     "4",
     "13",
     "14",
     "40"
    ],
    "explain": "14 is quatorze (BR) / catorze (PT)."
   },
   {
    "q": "“Duas casas” shows that…",
    "a": "dois has a feminine form",
    "opts": [
     "all numbers agree",
     "dois has a feminine form",
     "casas is masculine",
     "plurals drop -s"
    ],
    "explain": "Only um/uma and dois/duas agree with gender."
   },
   {
    "q": "What does “desculpe” mean?",
    "a": "sorry / excuse me",
    "opts": [
     "please",
     "sorry / excuse me",
     "thanks",
     "hello"
    ],
    "explain": "Desculpe excuses and apologises."
   },
   {
    "q": "“O dia” is surprising because…",
    "a": "it is masculine despite -a",
    "opts": [
     "it is feminine",
     "it is masculine despite -a",
     "it has no plural",
     "it is always plural"
    ],
    "explain": "O dia (the day) breaks the -a = feminine pattern."
   },
   {
    "q": "“De nada” is the reply to…",
    "a": "thanks",
    "opts": [
     "hello",
     "thanks",
     "sorry",
     "goodbye"
    ],
    "explain": "De nada — it's nothing — answers obrigado/a."
   }
  ],
  "grammar": [
   {
    "q": "“The book” (livro, masculine) is…",
    "a": "o livro",
    "opts": [
     "o livro",
     "a livro",
     "um livro",
     "os livro"
    ],
    "explain": "Masculine singular takes o: o livro."
   },
   {
    "q": "“The houses” is…",
    "a": "as casas",
    "opts": [
     "os casas",
     "as casas",
     "a casas",
     "uns casas"
    ],
    "explain": "Feminine plural: as casas."
   },
   {
    "q": "The plural of “homem” is…",
    "a": "homens",
    "opts": [
     "homemes",
     "homens",
     "homenes",
     "homems"
    ],
    "explain": "-m becomes -ns: homem → homens."
   },
   {
    "q": "“I am Ana” (identity) is…",
    "a": "Eu sou a Ana",
    "opts": [
     "Eu sou a Ana",
     "Eu estou a Ana",
     "Eu tenho a Ana",
     "Eu fico a Ana"
    ],
    "explain": "Identity uses ser: Eu sou…"
   },
   {
    "q": "“The book is on the table” is…",
    "a": "O livro está na mesa",
    "opts": [
     "O livro é na mesa",
     "O livro está na mesa",
     "O livro tem na mesa",
     "O livro fica na mesa"
    ],
    "explain": "Location uses estar: está na mesa."
   },
   {
    "q": "“I am twenty years old” is…",
    "a": "Tenho vinte anos",
    "opts": [
     "Sou vinte anos",
     "Estou vinte anos",
     "Tenho vinte anos",
     "Houve vinte anos"
    ],
    "explain": "Age uses ter: Tenho vinte anos."
   },
   {
    "q": "“You (você) speak” is…",
    "a": "você fala",
    "opts": [
     "você falo",
     "você fala",
     "você falas",
     "você falam"
    ],
    "explain": "Você conjugates like ele/ela: fala."
   },
   {
    "q": "“I don't speak Portuguese” is…",
    "a": "Eu não falo português",
    "opts": [
     "Eu não falo português",
     "Eu falo não português",
     "Eu no falo português",
     "Não eu falo português"
    ],
    "explain": "Não goes before the verb: Eu não falo."
   },
   {
    "q": "“Do you speak English?” is…",
    "a": "Você fala inglês?",
    "opts": [
     "Fala você inglês?",
     "Você fala inglês?",
     "Você falas inglês?",
     "É você fala inglês?"
    ],
    "explain": "No inversion needed: Você fala inglês?"
   },
   {
    "q": "“I like coffee” is…",
    "a": "Eu gosto de café",
    "opts": [
     "Eu gosto café",
     "Eu gosto de café",
     "Eu gostar café",
     "Me gusta café"
    ],
    "explain": "Gostar always takes de: gosto de café."
   },
   {
    "q": "“In the house” (contraction) is…",
    "a": "na casa",
    "opts": [
     "em a casa",
     "na casa",
     "da casa",
     "à casa"
    ],
    "explain": "Em + a contracts to na: na casa."
   },
   {
    "q": "“She doesn't eat meat” is…",
    "a": "Ela não come carne",
    "opts": [
     "Ela não come carne",
     "Ela não comes carne",
     "Ela não comem carne",
     "Ela come não carne"
    ],
    "explain": "Ela come → Ela não come carne."
   }
  ]
 },
 "quiz": [
  {
   "id": "pt-greet-1",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "What does “boa tarde” mean?",
   "a": "good afternoon",
   "opts": [
    "good morning",
    "good afternoon",
    "good evening",
    "good night"
   ],
   "explain": "Boa tarde is good afternoon."
  },
  {
   "id": "pt-greet-2",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "You arrive at a party at 9 pm. You say…",
   "a": "boa noite",
   "opts": [
    "bom dia",
    "boa tarde",
    "boa noite",
    "tchau"
   ],
   "explain": "Evening arrivals get boa noite — it greets as well as farewells."
  },
  {
   "id": "pt-greet-3",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“Meu nome é Ana” means…",
   "a": "my name is Ana",
   "opts": [
    "my name is Ana",
    "I know Ana",
    "I see Ana",
    "call me Ana"
   ],
   "explain": "Meu nome é… — my name is…"
  },
  {
   "id": "pt-greet-4",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "A man thanks you. He says…",
   "a": "obrigado",
   "opts": [
    "obrigado",
    "obrigada",
    "por favor",
    "de nada"
   ],
   "explain": "Men say obrigado; women say obrigada."
  },
  {
   "id": "pt-noun-1",
   "lesson": "nouns-gender-and-articles",
   "type": "vocab",
   "topic": "grammar",
   "level": "beginner",
   "q": "“The house” (casa, feminine) is…",
   "a": "a casa",
   "opts": [
    "o casa",
    "a casa",
    "uma casa",
    "as casa"
   ],
   "explain": "Feminine singular takes a: a casa."
  },
  {
   "id": "pt-noun-2",
   "lesson": "nouns-gender-and-articles",
   "type": "vocab",
   "topic": "grammar",
   "level": "beginner",
   "q": "The plural of “coração” is…",
   "a": "corações",
   "opts": [
    "coraçãos",
    "corações",
    "coraçães",
    "coração"
   ],
   "explain": "-ão usually becomes -ões: corações."
  },
  {
   "id": "pt-noun-3",
   "lesson": "nouns-gender-and-articles",
   "type": "meaning",
   "topic": "grammar",
   "level": "beginner",
   "q": "Portugal takes no article because…",
   "a": "it is the named exception",
   "opts": [
    "it is a city",
    "it is the named exception",
    "it is feminine",
    "it is plural"
   ],
   "explain": "Countries take articles (o Brasil, a Índia) — except Portugal."
  },
  {
   "id": "pt-ser-1",
   "lesson": "ser-and-estar",
   "type": "vocab",
   "topic": "verbs",
   "level": "beginner",
   "q": "“They are” (identity) is…",
   "a": "eles são",
   "opts": [
    "eles são",
    "eles estão",
    "eles têm",
    "eles eram"
   ],
   "explain": "Identity uses ser: eles são."
  },
  {
   "id": "pt-ser-2",
   "lesson": "ser-and-estar",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "Say “I am tired” (woman speaking). You say…",
   "a": "Estou cansada",
   "opts": [
    "Sou cansada",
    "Estou cansada",
    "Tenho cansada",
    "Fico cansada"
   ],
   "explain": "States use estar, agreeing feminine: Estou cansada."
  },
  {
   "id": "pt-ser-3",
   "lesson": "ser-and-estar",
   "type": "meaning",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Ele está bom” (after illness) means…",
   "a": "he is well now",
   "opts": [
    "he is a good man",
    "he is well now",
    "he is good-looking",
    "he is tasty"
   ],
   "explain": "Estar + bom = well/recovered; ser + bom = a good person."
  },
  {
   "id": "pt-num-1",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "“Oito” is the number…",
   "a": "8",
   "opts": [
    "7",
    "8",
    "9",
    "18"
   ],
   "explain": "Sete is 7, oito is 8."
  },
  {
   "id": "pt-num-2",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "“Two houses” is…",
   "a": "duas casas",
   "opts": [
    "dois casas",
    "duas casas",
    "dois casa",
    "duas casa"
   ],
   "explain": "Feminine needs duas: duas casas."
  },
  {
   "id": "pt-num-3",
   "lesson": "numbers-1-to-20",
   "type": "usage",
   "topic": "numbers",
   "level": "beginner",
   "q": "Ask someone's age. You say…",
   "a": "Quantos anos você tem?",
   "opts": [
    "Quantos anos você é?",
    "Quantos anos você tem?",
    "Que idade você está?",
    "Quantos anos para você?"
   ],
   "explain": "Quantos anos você tem? — how many years do you have?"
  },
  {
   "id": "pt-food-1",
   "lesson": "food-and-ordering",
   "type": "usage",
   "topic": "food",
   "level": "beginner",
   "q": "Order a coffee politely. You say…",
   "a": "Queria um café, por favor",
   "opts": [
    "Queria um café, por favor",
    "Quero café agora",
    "Me dá café",
    "Café para mim já"
   ],
   "explain": "Queria… por favor is the polite ordering phrase."
  },
  {
   "id": "pt-food-2",
   "lesson": "food-and-ordering",
   "type": "meaning",
   "topic": "food",
   "level": "beginner",
   "q": "“A conta, por favor” means…",
   "a": "the bill, please",
   "opts": [
    "the menu, please",
    "the bill, please",
    "one more, please",
    "table for two"
   ],
   "explain": "A conta is the bill."
  },
  {
   "id": "pt-food-3",
   "lesson": "food-and-ordering",
   "type": "vocab",
   "topic": "food",
   "level": "beginner",
   "q": "Still water is…",
   "a": "água sem gás",
   "opts": [
    "água com gás",
    "água sem gás",
    "água fria",
    "água quente"
   ],
   "explain": "Sem gás is still; com gás is sparkling."
  },
  {
   "id": "pt-verb-1",
   "lesson": "present-tense-regular-verbs",
   "type": "vocab",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Nós falamos” — the ending -mos marks…",
   "a": "nós (we)",
   "opts": [
    "eu",
    "tu",
    "nós (we)",
    "eles"
   ],
   "explain": "The -mos ending always marks nós."
  },
  {
   "id": "pt-verb-2",
   "lesson": "present-tense-regular-verbs",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "Ask “where do you live?”. You say…",
   "a": "Onde você mora?",
   "opts": [
    "Onde você mora?",
    "Onde moras você?",
    "Onde você morar?",
    "Mora onde você?"
   ],
   "explain": "No inversion: Onde você mora?"
  },
  {
   "id": "pt-verb-3",
   "lesson": "present-tense-regular-verbs",
   "type": "meaning",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Eu não como carne” means…",
   "a": "I don't eat meat",
   "opts": [
    "I don't eat meat",
    "I don't cook meat",
    "she doesn't eat meat",
    "we don't eat meat"
   ],
   "explain": "Eu não como carne — não before the verb."
  },
  {
   "id": "pt-greet-5",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“Se faz favor” is heard constantly in…",
   "a": "Portugal",
   "opts": [
    "Brazil",
    "Portugal",
    "Angola only",
    "nowhere — it is archaic"
   ],
   "explain": "Se faz favor is the Portuguese all-purpose please/excuse-me."
  }
 ],
 "review": [
  {
   "p": "olá / oi",
   "a": "hello (neutral / casual)"
  },
  {
   "p": "bom dia",
   "a": "good morning"
  },
  {
   "p": "boa tarde",
   "a": "good afternoon"
  },
  {
   "p": "boa noite",
   "a": "good evening / night"
  },
  {
   "p": "tchau",
   "a": "bye (Brazil)"
  },
  {
   "p": "obrigado / obrigada",
   "a": "thank you (man / woman saying it)"
  },
  {
   "p": "por favor",
   "a": "please"
  },
  {
   "p": "Meu nome é…",
   "a": "my name is…"
  },
  {
   "p": "o / a",
   "a": "the (m / f)"
  },
  {
   "p": "um / uma",
   "a": "a (m / f)"
  },
  {
   "p": "eu sou",
   "a": "I am (identity)"
  },
  {
   "p": "eu estou",
   "a": "I am (state)"
  },
  {
   "p": "eu tenho",
   "a": "I have"
  },
  {
   "p": "Tenho vinte anos",
   "a": "I am 20 years old"
  },
  {
   "p": "não",
   "a": "not (before the verb)"
  },
  {
   "p": "um, dois, três",
   "a": "one, two, three"
  },
  {
   "p": "vinte",
   "a": "twenty"
  },
  {
   "p": "Quanto custa?",
   "a": "how much is it?"
  },
  {
   "p": "Queria…",
   "a": "I would like…"
  },
  {
   "p": "A conta, por favor",
   "a": "the bill, please"
  },
  {
   "p": "Que gostoso!",
   "a": "how tasty!"
  },
  {
   "p": "eu falo",
   "a": "I speak"
  },
  {
   "p": "Onde você mora?",
   "a": "where do you live?"
  },
  {
   "p": "de nada",
   "a": "you're welcome"
  }
 ]
};
