/* EkGuru — FRENCH COURSE BANK (authored, single source of truth).
   Generated by tools/build-language-course.py — do not hand-edit. */
window.EKGURU_COURSE_FR = {
 "practice": {
  "vocabulary": [
   {
    "q": "What does “bonjour” mean?",
    "a": "hello",
    "opts": [
     "goodbye",
     "hello",
     "please",
     "thanks"
    ],
    "explain": "Bonjour is hello/good morning — used all day.",
    "say": "bonjour"
   },
   {
    "q": "What does “merci” mean?",
    "a": "thank you",
    "opts": [
     "please",
     "thank you",
     "sorry",
     "yes"
    ],
    "explain": "Merci is thank you. The reply is de rien (you're welcome).",
    "say": "merci"
   },
   {
    "q": "What does “s'il vous plaît” mean?",
    "a": "please",
    "opts": [
     "please",
     "thank you",
     "excuse me",
     "goodbye"
    ],
    "explain": "S'il vous plaît is please — the formal/polite form.",
    "say": "s'il vous plaît"
   },
   {
    "q": "What does “au revoir” mean?",
    "a": "goodbye",
    "opts": [
     "hello",
     "goodbye",
     "good night",
     "welcome"
    ],
    "explain": "Au revoir is goodbye.",
    "say": "au revoir"
   },
   {
    "q": "What does “oui” mean?",
    "a": "yes",
    "opts": [
     "no",
     "yes",
     "maybe",
     "please"
    ],
    "explain": "Oui is yes; non is no.",
    "say": "oui"
   },
   {
    "q": "What does “l'eau” mean?",
    "a": "water",
    "opts": [
     "bread",
     "water",
     "wine",
     "milk"
    ],
    "explain": "L'eau is water (feminine: la eau → l'eau).",
    "say": "l'eau"
   },
   {
    "q": "What does “la maison” mean?",
    "a": "house",
    "opts": [
     "car",
     "house",
     "street",
     "room"
    ],
    "explain": "La maison is the house or home.",
    "say": "la maison"
   },
   {
    "q": "What does “un ami” mean?",
    "a": "a friend",
    "opts": [
     "a brother",
     "a friend",
     "a teacher",
     "a neighbour"
    ],
    "explain": "Un ami is a friend (masculine); une amie is the feminine form.",
    "say": "un ami"
   },
   {
    "q": "What does “le travail” mean?",
    "a": "work",
    "opts": [
     "work",
     "holiday",
     "money",
     "time"
    ],
    "explain": "Le travail is work; travailler is to work.",
    "say": "le travail"
   },
   {
    "q": "What does “aujourd'hui” mean?",
    "a": "today",
    "opts": [
     "tomorrow",
     "today",
     "yesterday",
     "now"
    ],
    "explain": "Aujourd'hui is today; demain is tomorrow; hier is yesterday.",
    "say": "aujourd'hui"
   },
   {
    "q": "What does “la nuit” mean?",
    "a": "night",
    "opts": [
     "day",
     "night",
     "morning",
     "week"
    ],
    "explain": "La nuit is night — as in bonne nuit.",
    "say": "la nuit"
   },
   {
    "q": "What does “non” mean?",
    "a": "no",
    "opts": [
     "yes",
     "no",
     "maybe",
     "never"
    ],
    "explain": "Non is no — the partner of oui.",
    "say": "non"
   }
  ],
  "grammar": [
   {
    "q": "“Je suis de l'Inde” uses être because…",
    "a": "origin uses être",
    "opts": [
     "origin uses être",
     "location uses être",
     "mood uses être",
     "it is a temporary state"
    ],
    "explain": "Origin and identity are permanent — they use être.",
    "say": "je suis de l'Inde"
   },
   {
    "q": "“J'ai faim” (I am hungry) uses avoir because…",
    "a": "French uses avoir for hunger",
    "opts": [
     "French uses avoir for hunger",
     "it is about identity",
     "it is about origin",
     "faim is a verb"
    ],
    "explain": "Age, hunger, thirst, heat and cold all use avoir in French.",
    "say": "j'ai faim"
   },
   {
    "q": "“J'ai vingt ans” literally means…",
    "a": "I have twenty years",
    "opts": [
     "I am twenty years old",
     "I have twenty years",
     "I want twenty years",
     "I like twenty years"
    ],
    "explain": "French says \"I have 20 years\", not \"I am 20\".",
    "say": "j'ai vingt ans"
   },
   {
    "q": "“Le livre” vs “la table” — why different articles?",
    "a": "livre is masculine, table is feminine",
    "opts": [
     "livre is masculine, table is feminine",
     "table is plural",
     "livre is plural",
     "both are neutral"
    ],
    "explain": "Livre is masculine (le), table is feminine (la) despite ending in -e.",
    "say": "le livre"
   },
   {
    "q": "Which is correct: “l'ami” or “le ami”?",
    "a": "l'ami",
    "opts": [
     "le ami",
     "l'ami",
     "la ami",
     "les ami"
    ],
    "explain": "Le elides to l' before a vowel: l'ami.",
    "say": "l'ami"
   },
   {
    "q": "How do you make a sentence negative: “I don't speak English”?",
    "a": "Je ne parle pas anglais",
    "opts": [
     "Je ne parle pas anglais",
     "Je parle pas anglais jamais",
     "Je non parle anglais",
     "Je parle ne anglais pas"
    ],
    "explain": "Negation wraps the verb with ne … pas.",
    "say": "je ne parle pas anglais"
   },
   {
    "q": "“Je parle” means…",
    "a": "I speak",
    "opts": [
     "I speak",
     "he speaks",
     "we speak",
     "they speak"
    ],
    "explain": "The -e ending (silent) marks the je form of -er verbs.",
    "say": "je parle"
   },
   {
    "q": "“Nous parlons” means…",
    "a": "we speak",
    "opts": [
     "I speak",
     "we speak",
     "they speak",
     "he speaks"
    ],
    "explain": "-ons is the nous (we) ending for -er verbs.",
    "say": "nous parlons"
   },
   {
    "q": "How do you ask a friend's name?",
    "a": "Comment tu t'appelles ?",
    "opts": [
     "Comment vous appelez-vous ?",
     "Comment tu t'appelles ?",
     "Qu'est-ce que c'est ?",
     "Où es-tu ?"
    ],
    "explain": "Comment tu t'appelles ? is the informal (tu) form.",
    "say": "comment tu t'appelles ?"
   },
   {
    "q": "“Je m'appelle Marie” literally means…",
    "a": "I call myself Marie",
    "opts": [
     "My name is Marie",
     "I call myself Marie",
     "Call me Marie",
     "Marie is my name"
    ],
    "explain": "S'appeler is reflexive: je m'appelle = I call myself.",
    "say": "je m'appelle Marie"
   },
   {
    "q": "Which means “the bill, please”?",
    "a": "L'addition, s'il vous plaît",
    "opts": [
     "L'addition, s'il vous plaît",
     "La nourriture, s'il vous plaît",
     "La maison, s'il vous plaît",
     "Le menu, s'il vous plaît"
    ],
    "explain": "L'addition is the bill/check.",
    "say": "l'addition, s'il vous plaît"
   },
   {
    "q": "“Je voudrais un café” means…",
    "a": "I would like a coffee",
    "opts": [
     "I want a coffee now",
     "I would like a coffee",
     "I had a coffee",
     "The coffee is cold"
    ],
    "explain": "Je voudrais is the polite conditional — “I would like”.",
    "say": "je voudrais un café"
   }
  ]
 },
 "quiz": [
  {
   "id": "fr-greet-1",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "What does “bonjour” mean?",
   "a": "hello / good morning",
   "opts": [
    "good night",
    "hello / good morning",
    "good evening",
    "goodbye"
   ],
   "explain": "Bonjour is hello/good morning — used all day until evening."
  },
  {
   "id": "fr-greet-2",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "“Salut” is best used with…",
   "a": "friends and family",
   "opts": [
    "strangers",
    "friends and family",
    "a police officer",
    "your boss"
   ],
   "explain": "Salut is the casual hi — for friends and family, not formal situations."
  },
  {
   "id": "fr-greet-3",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "After about 6pm, “bonjour” becomes…",
   "a": "bonsoir",
   "opts": [
    "bonne nuit",
    "bonsoir",
    "salut",
    "au revoir"
   ],
   "explain": "Bonsoir (good evening) replaces bonjour in the evening."
  },
  {
   "id": "fr-greet-4",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "When should you use “vous” instead of “tu”?",
   "a": "With strangers and in formal situations",
   "opts": [
    "With friends",
    "With children",
    "With strangers and in formal situations",
    "Never"
   ],
   "explain": "Vous is the formal “you” (and the plural) — safer with strangers."
  },
  {
   "id": "fr-etre-1",
   "lesson": "etre-and-avoir",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "“Je suis étudiant” uses être because…",
   "a": "profession uses être",
   "opts": [
    "profession uses être",
    "location uses être",
    "mood uses être",
    "it is temporary"
   ],
   "explain": "Identity and profession are permanent — they use être."
  },
  {
   "id": "fr-etre-2",
   "lesson": "etre-and-avoir",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "How do you say “I am 20 years old” in French?",
   "a": "J'ai vingt ans",
   "opts": [
    "Je suis vingt ans",
    "J'ai vingt ans",
    "Je suis vingt années",
    "J'ai vingt années"
   ],
   "explain": "French uses avoir for age: J'ai vingt ans (I have 20 years)."
  },
  {
   "id": "fr-etre-3",
   "lesson": "etre-and-avoir",
   "type": "meaning",
   "topic": "grammar",
   "level": "beginner",
   "q": "“J'ai soif” means…",
   "a": "I am thirsty",
   "opts": [
    "I am hungry",
    "I am thirsty",
    "I am tired",
    "I am cold"
   ],
   "explain": "J'ai soif = I am thirsty (literally \"I have thirst\")."
  },
  {
   "id": "fr-etre-4",
   "lesson": "etre-and-avoir",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "Why is it “j'ai” and not “je ai”?",
   "a": "je + ai elides to j'ai",
   "opts": [
    "je + ai elides to j'ai",
    "ai is wrong",
    "it is the plural",
    "it is the formal form"
   ],
   "explain": "Je elides to j' before a vowel sound: j'ai, j'habite."
  },
  {
   "id": "fr-gender-1",
   "lesson": "gender-and-articles",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "Which is the correct article for “maison”?",
   "a": "la",
   "opts": [
    "le",
    "la",
    "les",
    "un"
   ],
   "explain": "Maison is feminine: la maison."
  },
  {
   "id": "fr-gender-2",
   "lesson": "gender-and-articles",
   "type": "usage",
   "topic": "grammar",
   "level": "beginner",
   "q": "Words ending in -tion (like nation) are usually…",
   "a": "feminine",
   "opts": [
    "feminine",
    "masculine",
    "neutral",
    "plural"
   ],
   "explain": "-tion, -sion and -té nouns are almost always feminine: la nation."
  },
  {
   "id": "fr-gender-3",
   "lesson": "gender-and-articles",
   "type": "meaning",
   "topic": "grammar",
   "level": "beginner",
   "q": "Before a vowel, “le” and “la” both become…",
   "a": "l'",
   "opts": [
    "les",
    "l'",
    "un",
    "des"
   ],
   "explain": "Le/la elide to l' before a vowel: l'ami, l'eau, l'école."
  },
  {
   "id": "fr-num-1",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "How do you say 16 in French?",
   "a": "seize",
   "opts": [
    "seize",
    "dix-six",
    "six-dix",
    "quinze et un"
   ],
   "explain": "16 is seize — a single word, no pattern."
  },
  {
   "id": "fr-num-2",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "“Dix-sept” is which number?",
   "a": "17",
   "opts": [
    "16",
    "17",
    "18",
    "70"
   ],
   "explain": "Dix-sept = ten-seven = 17; the pattern starts at 17."
  },
  {
   "id": "fr-num-3",
   "lesson": "numbers-1-to-20",
   "type": "meaning",
   "topic": "numbers",
   "level": "beginner",
   "q": "“C'est combien ?” means…",
   "a": "how much is it?",
   "opts": [
    "where is it?",
    "how much is it?",
    "what is it?",
    "how many are there?"
   ],
   "explain": "C'est combien ? asks the price."
  },
  {
   "id": "fr-food-1",
   "lesson": "food-and-ordering",
   "type": "usage",
   "topic": "food",
   "level": "beginner",
   "q": "The polite way to order in a restaurant is…",
   "a": "Je voudrais…",
   "opts": [
    "Je voudrais…",
    "Donne-moi…",
    "Je veux maintenant…",
    "Peu importe"
   ],
   "explain": "Je voudrais (I would like) is polite everywhere."
  },
  {
   "id": "fr-food-2",
   "lesson": "food-and-ordering",
   "type": "vocab",
   "topic": "food",
   "level": "beginner",
   "q": "In France, to ask for free tap water you say…",
   "a": "une carafe d'eau",
   "opts": [
    "une carafe d'eau",
    "l'eau gazeuse",
    "une bouteille d'eau",
    "de l'eau chaude"
   ],
   "explain": "Une carafe d'eau is a jug of tap water — free in French restaurants."
  },
  {
   "id": "fr-food-3",
   "lesson": "food-and-ordering",
   "type": "usage",
   "topic": "food",
   "level": "beginner",
   "q": "How do you ask for the bill in France?",
   "a": "L'addition, s'il vous plaît",
   "opts": [
    "L'addition, s'il vous plaît",
    "Le menu, s'il vous plaît",
    "La nourriture, s'il vous plaît",
    "L'eau, s'il vous plaît"
   ],
   "explain": "L'addition is the bill (la facture in Québec)."
  },
  {
   "id": "fr-verb-1",
   "lesson": "present-tense-regular-verbs",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "The “I” form of parler (to speak) is…",
   "a": "je parle",
   "opts": [
    "je parle",
    "je parles",
    "je parlons",
    "je parlent"
   ],
   "explain": "The je form of -er verbs ends in silent -e: je parle."
  },
  {
   "id": "fr-verb-2",
   "lesson": "present-tense-regular-verbs",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Nous finissons” — which verb group is this?",
   "a": "-ir",
   "opts": [
    "-er",
    "-ir",
    "-re",
    "none"
   ],
   "explain": "Finir is an -ir verb; the -iss- in the plural is the giveaway."
  },
  {
   "id": "fr-verb-3",
   "lesson": "present-tense-regular-verbs",
   "type": "meaning",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Ils vendent” means…",
   "a": "they sell",
   "opts": [
    "they sell",
    "they speak",
    "they finish",
    "we sell"
   ],
   "explain": "Vendre is -re; ils vendent = they sell."
  }
 ],
 "review": [
  {
   "p": "bonjour",
   "a": "hello / good morning"
  },
  {
   "p": "merci",
   "a": "thank you"
  },
  {
   "p": "s'il vous plaît",
   "a": "please"
  },
  {
   "p": "au revoir",
   "a": "goodbye"
  },
  {
   "p": "salut",
   "a": "hi (informal)"
  },
  {
   "p": "bonne nuit",
   "a": "good night"
  },
  {
   "p": "oui / non",
   "a": "yes / no"
  },
  {
   "p": "Comment ça va ?",
   "a": "how's it going?"
  },
  {
   "p": "Je m'appelle Marie",
   "a": "my name is Marie"
  },
  {
   "p": "Comment tu t'appelles ?",
   "a": "what is your name? (informal)"
  },
  {
   "p": "Je suis de l'Inde",
   "a": "I am from India"
  },
  {
   "p": "J'ai faim",
   "a": "I am hungry"
  },
  {
   "p": "J'ai vingt ans",
   "a": "I am twenty years old"
  },
  {
   "p": "le livre",
   "a": "the book"
  },
  {
   "p": "la maison",
   "a": "the house"
  },
  {
   "p": "l'eau",
   "a": "the water"
  },
  {
   "p": "un, deux, trois",
   "a": "one, two, three"
  },
  {
   "p": "seize",
   "a": "sixteen"
  },
  {
   "p": "C'est combien ?",
   "a": "how much is it?"
  },
  {
   "p": "L'addition, s'il vous plaît",
   "a": "the bill, please"
  },
  {
   "p": "Je voudrais un café",
   "a": "I would like a coffee"
  },
  {
   "p": "je parle français",
   "a": "I speak French"
  },
  {
   "p": "un ami",
   "a": "a friend"
  },
  {
   "p": "à bientôt",
   "a": "see you soon"
  }
 ]
};
