/* EkGuru — GERMAN COURSE BANK (authored, single source of truth).
   Generated by tools/build-language-course.py — do not hand-edit. */
window.EKGURU_COURSE_DE = {
 "practice": {
  "vocabulary": [
   {
    "q": "What does “Guten Tag” mean?",
    "a": "good day",
    "opts": [
     "good morning",
     "good day",
     "good evening",
     "good night"
    ],
    "explain": "Guten Tag is good day — used from late morning through the afternoon."
   },
   {
    "q": "What does “Tschüss” mean?",
    "a": "bye (informal)",
    "opts": [
     "hello",
     "bye (informal)",
     "thanks",
     "please"
    ],
    "explain": "Tschüss is the everyday informal goodbye."
   },
   {
    "q": "“Danke” means…",
    "a": "thanks",
    "opts": [
     "please",
     "thanks",
     "sorry",
     "yes"
    ],
    "explain": "Danke is thanks; the reply is Bitte (you're welcome)."
   },
   {
    "q": "“Bitte” does NOT mean…",
    "a": "goodbye",
    "opts": [
     "please",
     "you're welcome",
     "here you are",
     "goodbye"
    ],
    "explain": "Bitte covers please, you're welcome and here you are — but never goodbye."
   },
   {
    "q": "What does “die Rechnung” mean?",
    "a": "the bill",
    "opts": [
     "the menu",
     "the bill",
     "the table",
     "the tip"
    ],
    "explain": "Die Rechnung, bitte — the bill, please."
   },
   {
    "q": "“Ich habe Hunger” means…",
    "a": "I am hungry",
    "opts": [
     "I am thirsty",
     "I am hungry",
     "I am tired",
     "I am cold"
    ],
    "explain": "Hunger uses haben: Ich habe Hunger — literally I have hunger."
   },
   {
    "q": "What does “das Brot” mean?",
    "a": "bread",
    "opts": [
     "bread",
     "cheese",
     "water",
     "apple"
    ],
    "explain": "Das Brot is bread — neuter, like most staple foods is not; just memorise it."
   },
   {
    "q": "“zwölf” is the number…",
    "a": "12",
    "opts": [
     "10",
     "11",
     "12",
     "20"
    ],
    "explain": "Elf is 11, zwölf is 12 — then dreizehn (13)."
   },
   {
    "q": "What does “Guten Appetit” mean?",
    "a": "enjoy your meal",
    "opts": [
     "the bill please",
     "enjoy your meal",
     "table for two",
     "no sugar"
    ],
    "explain": "Guten Appetit is said before starting to eat — wait for it."
   },
   {
    "q": "“Entschuldigung!” is used to…",
    "a": "get attention politely",
    "opts": [
     "order food",
     "get attention politely",
     "say goodbye",
     "ask the price"
    ],
    "explain": "Entschuldigung means excuse me — to call a server or apologise."
   },
   {
    "q": "What does “das Mädchen” show about gender?",
    "a": "gender follows the word, not the thing",
    "opts": [
     "all girls are feminine",
     "gender follows the word, not the thing",
     "all people are masculine",
     "gender is random"
    ],
    "explain": "Das Mädchen (the girl) is neuter because of the -chen ending."
   },
   {
    "q": "“Wie bitte?” means…",
    "a": "pardon? / say again?",
    "opts": [
     "how much?",
     "pardon? / say again?",
     "where?",
     "why?"
    ],
    "explain": "Wie bitte? is the polite pardon? — use it when numbers blur past."
   }
  ],
  "grammar": [
   {
    "q": "The article for a masculine noun (the man) is…",
    "a": "der Mann",
    "opts": [
     "der Mann",
     "die Mann",
     "das Mann",
     "den Mann"
    ],
    "explain": "Masculine takes der: der Mann."
   },
   {
    "q": "The article for a feminine noun (the woman) is…",
    "a": "die Frau",
    "opts": [
     "der Frau",
     "die Frau",
     "das Frau",
     "ein Frau"
    ],
    "explain": "Feminine takes die: die Frau."
   },
   {
    "q": "The article for a neuter noun (the child) is…",
    "a": "das Kind",
    "opts": [
     "der Kind",
     "die Kind",
     "das Kind",
     "dem Kind"
    ],
    "explain": "Neuter takes das: das Kind."
   },
   {
    "q": "“A woman” is…",
    "a": "eine Frau",
    "opts": [
     "ein Frau",
     "eine Frau",
     "einer Frau",
     "einen Frau"
    ],
    "explain": "Feminine indefinite article is eine: eine Frau."
   },
   {
    "q": "The plural of “das Kind” is…",
    "a": "die Kinder",
    "opts": [
     "die Kindes",
     "die Kinder",
     "die Kinden",
     "die Kind"
    ],
    "explain": "Das Kind → die Kinder — the -er plural with umlaut."
   },
   {
    "q": "“I am” is…",
    "a": "ich bin",
    "opts": [
     "ich bin",
     "ich bist",
     "ich ist",
     "ich sind"
    ],
    "explain": "Sein: ich bin, du bist, er ist."
   },
   {
    "q": "“You (informal) have” is…",
    "a": "du hast",
    "opts": [
     "du habe",
     "du hast",
     "du hat",
     "du haben"
    ],
    "explain": "Haben: ich habe, du hast, er hat."
   },
   {
    "q": "“I have no car” is…",
    "a": "Ich habe kein Auto",
    "opts": [
     "Ich habe nicht Auto",
     "Ich habe kein Auto",
     "Ich nicht habe Auto",
     "Ich habe keine Auto"
    ],
    "explain": "Negating a noun with ein/no article uses kein (neuter: kein Auto)."
   },
   {
    "q": "“He learns German” is…",
    "a": "Er lernt Deutsch",
    "opts": [
     "Er lernen Deutsch",
     "Er lernt Deutsch",
     "Er lernst Deutsch",
     "Er lerne Deutsch"
    ],
    "explain": "Regular verbs: er/sie/es take -t — er lernt."
   },
   {
    "q": "“Do you learn German?” is…",
    "a": "Lernst du Deutsch?",
    "opts": [
     "Du lernst Deutsch?",
     "Lernst du Deutsch?",
     "Lernen du Deutsch?",
     "Lernt du Deutsch?"
    ],
    "explain": "Yes-no questions invert: verb first — Lernst du Deutsch?"
   },
   {
    "q": "“You (all) work” is…",
    "a": "ihr arbeitet",
    "opts": [
     "ihr arbeiten",
     "ihr arbeitet",
     "ihr arbeitst",
     "ihr arbeite"
    ],
    "explain": "Arbeiten inserts e: ihr arbeitet — never arbeitst."
   },
   {
    "q": "In “Heute lerne ich Deutsch”, the verb position shows…",
    "a": "the verb always comes second",
    "opts": [
     "the verb comes first",
     "the verb always comes second",
     "the verb comes last",
     "free word order"
    ],
    "explain": "German main clauses are verb-second, whatever starts the sentence."
   }
  ]
 },
 "quiz": [
  {
   "id": "de-greet-1",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "What does “Guten Morgen” mean?",
   "a": "good morning",
   "opts": [
    "good morning",
    "good day",
    "good evening",
    "good night"
   ],
   "explain": "Guten Morgen is good morning — used until about 11."
  },
  {
   "id": "de-greet-2",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "You meet a stranger at 3 pm. You say…",
   "a": "Guten Tag",
   "opts": [
    "Guten Morgen",
    "Guten Tag",
    "Gute Nacht",
    "Moin Moin"
   ],
   "explain": "Afternoon calls for Guten Tag; Gute Nacht is a farewell only."
  },
  {
   "id": "de-greet-3",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“Ich heiße Anna” means…",
   "a": "I am called Anna",
   "opts": [
    "I am called Anna",
    "I know Anna",
    "I see Anna",
    "I help Anna"
   ],
   "explain": "Ich heiße… introduces your name — I am called…"
  },
  {
   "id": "de-greet-4",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "Ask a stranger's name (formal). You say…",
   "a": "Wie heißen Sie?",
   "opts": [
    "Wie heißt du?",
    "Wie heißen Sie?",
    "Wer bist du?",
    "Was bist du?"
   ],
   "explain": "Strangers get Sie: Wie heißen Sie?"
  },
  {
   "id": "de-noun-1",
   "lesson": "nouns-gender-and-articles",
   "type": "vocab",
   "topic": "grammar",
   "level": "beginner",
   "q": "Which article goes with “Tisch” (table, masculine)?",
   "a": "der",
   "opts": [
    "der",
    "die",
    "das",
    "den"
   ],
   "explain": "Der Tisch — masculine takes der."
  },
  {
   "id": "de-noun-2",
   "lesson": "nouns-gender-and-articles",
   "type": "vocab",
   "topic": "grammar",
   "level": "beginner",
   "q": "A word ending in -ung is almost always…",
   "a": "feminine",
   "opts": [
    "masculine",
    "feminine",
    "neuter",
    "plural"
   ],
   "explain": "-ung, -heit, -keit are reliably feminine: die Zeitung."
  },
  {
   "id": "de-noun-3",
   "lesson": "nouns-gender-and-articles",
   "type": "meaning",
   "topic": "grammar",
   "level": "beginner",
   "q": "“Ich bin Lehrer” drops the article because…",
   "a": "professions after sein take no article",
   "opts": [
    "Lehrer is plural",
    "professions after sein take no article",
    "Lehrer is feminine",
    "articles are optional"
   ],
   "explain": "Professions and nationalities after sein drop ein: Ich bin Lehrer."
  },
  {
   "id": "de-sein-1",
   "lesson": "sein-and-haben",
   "type": "vocab",
   "topic": "verbs",
   "level": "beginner",
   "q": "“We are” is…",
   "a": "wir sind",
   "opts": [
    "wir sind",
    "wir seid",
    "wir bin",
    "wir ist"
   ],
   "explain": "Sein: wir sind — same as sie/Sie sind."
  },
  {
   "id": "de-sein-2",
   "lesson": "sein-and-haben",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "Say “I am not tired”. You say…",
   "a": "Ich bin nicht müde",
   "opts": [
    "Ich bin nicht müde",
    "Ich bin kein müde",
    "Ich nicht bin müde",
    "Ich bin müde nicht"
   ],
   "explain": "Adjectives negate with nicht: Ich bin nicht müde."
  },
  {
   "id": "de-sein-3",
   "lesson": "sein-and-haben",
   "type": "meaning",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Ich habe Angst” means…",
   "a": "I am afraid",
   "opts": [
    "I am afraid",
    "I am hungry",
    "I have fearfulness",
    "I fear having"
   ],
   "explain": "Fear, hunger and cold use haben: Ich habe Angst."
  },
  {
   "id": "de-num-1",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "“sieben” is the number…",
   "a": "7",
   "opts": [
    "6",
    "7",
    "9",
    "11"
   ],
   "explain": "Sechs is 6, sieben is 7 — short second syllable."
  },
  {
   "id": "de-num-2",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "“sechzehn” is…",
   "a": "16",
   "opts": [
    "6",
    "16",
    "60",
    "66"
   ],
   "explain": "Sechzehn is 16 — note the shortened sech- stem."
  },
  {
   "id": "de-num-3",
   "lesson": "numbers-1-to-20",
   "type": "usage",
   "topic": "numbers",
   "level": "beginner",
   "q": "Say “I am 20 years old”. You say…",
   "a": "Ich bin zwanzig Jahre alt",
   "opts": [
    "Ich habe zwanzig Jahre",
    "Ich bin zwanzig Jahre alt",
    "Ich bin zwanzig alt Jahre",
    "Ich werde zwanzig"
   ],
   "explain": "Age uses sein: Ich bin zwanzig Jahre alt."
  },
  {
   "id": "de-food-1",
   "lesson": "food-and-ordering",
   "type": "usage",
   "topic": "food",
   "level": "beginner",
   "q": "Order a coffee politely. You say…",
   "a": "Ich möchte einen Kaffee, bitte",
   "opts": [
    "Ich möchte einen Kaffee, bitte",
    "Ich will Kaffee jetzt",
    "Kaffee geben mir",
    "Ich habe Kaffee gern"
   ],
   "explain": "Ich möchte… bitte is the polite ordering phrase."
  },
  {
   "id": "de-food-2",
   "lesson": "food-and-ordering",
   "type": "meaning",
   "topic": "food",
   "level": "beginner",
   "q": "“Die Rechnung, bitte” means…",
   "a": "the bill, please",
   "opts": [
    "the menu, please",
    "the bill, please",
    "table for two",
    "one more, please"
   ],
   "explain": "Die Rechnung is the bill — never rush it."
  },
  {
   "id": "de-food-3",
   "lesson": "food-and-ordering",
   "type": "vocab",
   "topic": "food",
   "level": "beginner",
   "q": "“Still” water is…",
   "a": "stilles Wasser",
   "opts": [
    "stilles Wasser",
    "Sprudel",
    "Leitungswasser",
    "Mineralwasser kalt"
   ],
   "explain": "Stilles Wasser is still water; Sprudel is sparkling."
  },
  {
   "id": "de-verb-1",
   "lesson": "present-tense-regular-verbs",
   "type": "vocab",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Du lernst” — the ending -st marks…",
   "a": "du (you, informal)",
   "opts": [
    "ich",
    "du (you, informal)",
    "er",
    "wir"
   ],
   "explain": "The -st ending always marks du."
  },
  {
   "id": "de-verb-2",
   "lesson": "present-tense-regular-verbs",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "Ask “where do you live?” (informal). You say…",
   "a": "Wo wohnst du?",
   "opts": [
    "Wo wohnst du?",
    "Wo wohnt du?",
    "Wo wohnen du?",
    "Wo wohne du?"
   ],
   "explain": "W-questions keep the verb second: Wo wohnst du?"
  },
  {
   "id": "de-verb-3",
   "lesson": "present-tense-regular-verbs",
   "type": "meaning",
   "topic": "verbs",
   "level": "beginner",
   "q": "In “Ich möchte Deutsch lernen”, “lernen” sits last because…",
   "a": "the main verb goes last with a modal",
   "opts": [
    "German verbs always end sentences",
    "the main verb goes last with a modal",
    "lernen is irregular",
    "möchte is not a verb"
   ],
   "explain": "Modal second, main verb last — the verb bracket."
  },
  {
   "id": "de-greet-5",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“Auf Wiedersehen” literally means…",
   "a": "until seeing again",
   "opts": [
    "until seeing again",
    "go with God",
    "stay well",
    "good luck"
   ],
   "explain": "Auf Wiedersehen — until seeing again — the formal goodbye."
  }
 ],
 "review": [
  {
   "p": "Hallo",
   "a": "hello"
  },
  {
   "p": "Guten Morgen",
   "a": "good morning"
  },
  {
   "p": "Guten Tag",
   "a": "good day"
  },
  {
   "p": "Guten Abend",
   "a": "good evening"
  },
  {
   "p": "Tschüss",
   "a": "bye (informal)"
  },
  {
   "p": "Danke",
   "a": "thanks"
  },
  {
   "p": "Bitte",
   "a": "please / you're welcome"
  },
  {
   "p": "Ich heiße…",
   "a": "I am called…"
  },
  {
   "p": "der / die / das",
   "a": "the (m / f / n)"
  },
  {
   "p": "ein / eine",
   "a": "a (m+n / f)"
  },
  {
   "p": "ich bin",
   "a": "I am"
  },
  {
   "p": "du bist",
   "a": "you are (informal)"
  },
  {
   "p": "er ist",
   "a": "he is"
  },
  {
   "p": "ich habe",
   "a": "I have"
  },
  {
   "p": "du hast",
   "a": "you have (informal)"
  },
  {
   "p": "nicht / kein",
   "a": "not / no, not a"
  },
  {
   "p": "eins, zwei, drei",
   "a": "one, two, three"
  },
  {
   "p": "zwölf",
   "a": "twelve"
  },
  {
   "p": "zwanzig",
   "a": "twenty"
  },
  {
   "p": "Ich möchte…",
   "a": "I would like…"
  },
  {
   "p": "Die Rechnung, bitte",
   "a": "the bill, please"
  },
  {
   "p": "Guten Appetit!",
   "a": "enjoy your meal!"
  },
  {
   "p": "ich lerne",
   "a": "I learn"
  },
  {
   "p": "Wo wohnst du?",
   "a": "where do you live?"
  }
 ]
};
