/* EkGuru — RUSSIAN COURSE BANK (authored, single source of truth).
   Generated by tools/build-language-course.py — do not hand-edit. */
window.EKGURU_COURSE_RU = {
 "practice": {
  "vocabulary": [
   {
    "q": "What does “здравствуйте” mean?",
    "a": "hello (formal)",
    "opts": [
     "hello (formal)",
     "hello (informal)",
     "goodbye",
     "thanks"
    ],
    "explain": "Здравствуйте is the formal hello — the first в is silent."
   },
   {
    "q": "“Добрый день” is used…",
    "a": "in the daytime",
    "opts": [
     "in the morning",
     "in the daytime",
     "in the evening",
     "at night"
    ],
    "explain": "Добрый день is the default daytime greeting."
   },
   {
    "q": "“Пока” means…",
    "a": "bye (informal)",
    "opts": [
     "hello",
     "bye (informal)",
     "please",
     "sorry"
    ],
    "explain": "Пока is informal bye; до свидания is formal."
   },
   {
    "q": "The reply to “спасибо” is…",
    "a": "пожалуйста",
    "opts": [
     "пожалуйста",
     "извините",
     "привет",
     "давай"
    ],
    "explain": "Пожалуйста means please, you're welcome and here-you-are."
   },
   {
    "q": "What does “счёт” mean?",
    "a": "the bill",
    "opts": [
     "the menu",
     "the bill",
     "the table",
     "the tip"
    ],
    "explain": "Счёт, пожалуйста — the bill, please."
   },
   {
    "q": "“Я хочу есть” means…",
    "a": "I am hungry",
    "opts": [
     "I am thirsty",
     "I am hungry",
     "I want to drink",
     "I am full"
    ],
    "explain": "Я хочу есть — I want to eat — is how hunger is said."
   },
   {
    "q": "“Очень вкусно!” means…",
    "a": "very tasty!",
    "opts": [
     "very big!",
     "very tasty!",
     "very fast!",
     "very hot!"
    ],
    "explain": "Очень вкусно! praises the food."
   },
   {
    "q": "“Двенадцать” is the number…",
    "a": "12",
    "opts": [
     "2",
     "12",
     "20",
     "22"
    ],
    "explain": "Двенадцать is 12; двадцать is 20."
   },
   {
    "q": "What does “Приятного аппетита!” mean?",
    "a": "enjoy your meal!",
    "opts": [
     "the bill please",
     "enjoy your meal!",
     "one more!",
     "no sugar"
    ],
    "explain": "Приятного аппетита opens the meal."
   },
   {
    "q": "“Меня зовут Анна” means…",
    "a": "I am called Anna",
    "opts": [
     "I am called Anna",
     "I know Anna",
     "call Anna",
     "Anna knows me"
    ],
    "explain": "Меня зовут… — I am called…"
   },
   {
    "q": "“Кофе” is surprising because…",
    "a": "it is masculine despite -е",
    "opts": [
     "it is feminine",
     "it is masculine despite -е",
     "it is plural",
     "it is indeclinable"
    ],
    "explain": "Кофе breaks the -е = neuter pattern: masculine."
   },
   {
    "q": "“Я не понимаю” means…",
    "a": "I don't understand",
    "opts": [
     "I don't know",
     "I don't understand",
     "I don't speak",
     "I don't remember"
    ],
    "explain": "Я не понимаю — the beginner's shield."
   }
  ],
  "grammar": [
   {
    "q": "“Книга” (book) is…",
    "a": "feminine",
    "opts": [
     "masculine",
     "feminine",
     "neuter",
     "plural"
    ],
    "explain": "-а ending → feminine: книга."
   },
   {
    "q": "“Окно” (window) is…",
    "a": "neuter",
    "opts": [
     "masculine",
     "feminine",
     "neuter",
     "plural"
    ],
    "explain": "-о ending → neuter: окно."
   },
   {
    "q": "The plural of “стол” is…",
    "a": "столы",
    "opts": [
     "столы",
     "столи",
     "стола",
     "столыи"
    ],
    "explain": "Masculine + -ы: стол → столы."
   },
   {
    "q": "“He is a student” is…",
    "a": "Он студент",
    "opts": [
     "Он студент",
     "Он есть студент",
     "Он ест студент",
     "Студент он есть"
    ],
    "explain": "Present \"is\" is omitted: Он студент."
   },
   {
    "q": "“I have a book” is…",
    "a": "У меня есть книга",
    "opts": [
     "Я имею книгу",
     "У меня есть книга",
     "Мне есть книга",
     "Я есть с книгой"
    ],
    "explain": "У меня есть — at me there is."
   },
   {
    "q": "“I have no time” is…",
    "a": "У меня нет времени",
    "opts": [
     "У меня не время",
     "У меня нет времени",
     "Я нет времени",
     "Мне не время"
    ],
    "explain": "У меня нет + genitive: времени."
   },
   {
    "q": "“You (informal) read” is…",
    "a": "ты читаешь",
    "opts": [
     "ты читаю",
     "ты читаешь",
     "ты читает",
     "ты читаем"
    ],
    "explain": "First conjugation: ты читаешь."
   },
   {
    "q": "“They speak” is…",
    "a": "они говорят",
    "opts": [
     "они говорю",
     "они говоришь",
     "они говорят",
     "они говорите"
    ],
    "explain": "Second conjugation: они говорят."
   },
   {
    "q": "“I don't know” is…",
    "a": "Я не знаю",
    "opts": [
     "Я не знаю",
     "Я нет знаю",
     "Не я знаю",
     "Я знаю не"
    ],
    "explain": "Не before the verb: Я не знаю."
   },
   {
    "q": "“Where do you live?” (informal) is…",
    "a": "Где ты живёшь?",
    "opts": [
     "Где ты живёшь?",
     "Где живёшь ты?",
     "Где ты живёт?",
     "Ты где живёшь есть?"
    ],
    "explain": "No inversion: Где ты живёшь?"
   },
   {
    "q": "“Two books” (feminine) is…",
    "a": "две книги",
    "opts": [
     "два книги",
     "две книги",
     "две книга",
     "два книга"
    ],
    "explain": "Feminine two: две книги."
   },
   {
    "q": "“I am 20” (age) is…",
    "a": "Мне двадцать лет",
    "opts": [
     "Я двадцать лет",
     "Мне двадцать лет",
     "Я имею двадцать",
     "Мне двадцать года"
    ],
    "explain": "Dative + лет: Мне двадцать лет."
   }
  ]
 },
 "quiz": [
  {
   "id": "ru-greet-1",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "What does “добрый вечер” mean?",
   "a": "good evening",
   "opts": [
    "good morning",
    "good day",
    "good evening",
    "good night"
   ],
   "explain": "Добрый вечер is good evening."
  },
  {
   "id": "ru-greet-2",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "You greet an official at noon. You say…",
   "a": "здравствуйте",
   "opts": [
    "привет",
    "здравствуйте",
    "пока",
    "давай"
   ],
   "explain": "Officials get здравствуйте, never привет."
  },
  {
   "id": "ru-greet-3",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“До свидания” literally means…",
   "a": "until seeing (again)",
   "opts": [
    "until seeing (again)",
    "go with God",
    "stay well",
    "farewell forever"
   ],
   "explain": "До свидания — until seeing — the formal goodbye."
  },
  {
   "id": "ru-greet-4",
   "lesson": "greetings-and-introductions",
   "type": "usage",
   "topic": "greetings",
   "level": "beginner",
   "q": "Ask a stranger's name (formal). You say…",
   "a": "Как вас зовут?",
   "opts": [
    "Как тебя зовут?",
    "Как вас зовут?",
    "Кто ты?",
    "Что ты?"
   ],
   "explain": "Strangers get вы: Как вас зовут?"
  },
  {
   "id": "ru-noun-1",
   "lesson": "nouns-gender-and-cases",
   "type": "vocab",
   "topic": "grammar",
   "level": "beginner",
   "q": "“Стол” (table) is…",
   "a": "masculine",
   "opts": [
    "masculine",
    "feminine",
    "neuter",
    "plural"
   ],
   "explain": "Consonant ending → masculine: стол."
  },
  {
   "id": "ru-noun-2",
   "lesson": "nouns-gender-and-cases",
   "type": "vocab",
   "topic": "grammar",
   "level": "beginner",
   "q": "The plural of “окно” is…",
   "a": "окна",
   "opts": [
    "окны",
    "окни",
    "окна",
    "окон"
   ],
   "explain": "Neuter -о becomes -а: окно → окна."
  },
  {
   "id": "ru-noun-3",
   "lesson": "nouns-gender-and-cases",
   "type": "meaning",
   "topic": "grammar",
   "level": "beginner",
   "q": "Russian word order is free because…",
   "a": "case endings mark each word's job",
   "opts": [
    "verbs never move",
    "case endings mark each word's job",
    "there are no nouns",
    "adjectives fix positions"
   ],
   "explain": "Cases carry the grammar, so position is flexible."
  },
  {
   "id": "ru-byt-1",
   "lesson": "byt-and-imet",
   "type": "vocab",
   "topic": "verbs",
   "level": "beginner",
   "q": "“There is water here” is…",
   "a": "Здесь есть вода",
   "opts": [
    "Здесь вода есть",
    "Здесь есть вода",
    "Вода здесь есть",
    "Есть здесь вода есть"
   ],
   "explain": "Existence uses есть: Здесь есть вода."
  },
  {
   "id": "ru-byt-2",
   "lesson": "byt-and-imet",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "Say “I don't have time”. You say…",
   "a": "У меня нет времени",
   "opts": [
    "У меня нет времени",
    "Я не время",
    "Мне нет время",
    "У меня не времени"
   ],
   "explain": "У меня нет + genitive."
  },
  {
   "id": "ru-byt-3",
   "lesson": "byt-and-imet",
   "type": "meaning",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Он есть студент” is wrong because…",
   "a": "present \"is\" is omitted",
   "opts": [
    "есть means eats",
    "present \"is\" is omitted",
    "студент is feminine",
    "он needs вы"
   ],
   "explain": "Он студент — no есть for identity."
  },
  {
   "id": "ru-num-1",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "“Восемь” is the number…",
   "a": "8",
   "opts": [
    "7",
    "8",
    "9",
    "18"
   ],
   "explain": "Семь is 7, восемь is 8."
  },
  {
   "id": "ru-num-2",
   "lesson": "numbers-1-to-20",
   "type": "vocab",
   "topic": "numbers",
   "level": "beginner",
   "q": "“Пятнадцать” is…",
   "a": "15",
   "opts": [
    "5",
    "15",
    "50",
    "55"
   ],
   "explain": "Пятнадцать is 15 — stress on -на-."
  },
  {
   "id": "ru-num-3",
   "lesson": "numbers-1-to-20",
   "type": "usage",
   "topic": "numbers",
   "level": "beginner",
   "q": "Ask a friend's age (informal). You say…",
   "a": "Сколько тебе лет?",
   "opts": [
    "Сколько тебе лет?",
    "Сколько вам лет?",
    "Тебе сколько года?",
    "Сколько лет у тебя?"
   ],
   "explain": "Friends get тебе: Сколько тебе лет?"
  },
  {
   "id": "ru-food-1",
   "lesson": "food-and-ordering",
   "type": "usage",
   "topic": "food",
   "level": "beginner",
   "q": "Order tea politely. You say…",
   "a": "Можно мне чай, пожалуйста",
   "opts": [
    "Можно мне чай, пожалуйста",
    "Дай мне чай",
    "Хочу чай сейчас",
    "Чай мне давай"
   ],
   "explain": "Можно мне… пожалуйста is the polite phrase."
  },
  {
   "id": "ru-food-2",
   "lesson": "food-and-ordering",
   "type": "meaning",
   "topic": "food",
   "level": "beginner",
   "q": "“Счёт, пожалуйста” means…",
   "a": "the bill, please",
   "opts": [
    "the menu, please",
    "the bill, please",
    "one more, please",
    "table for two"
   ],
   "explain": "Счёт is the bill."
  },
  {
   "id": "ru-food-3",
   "lesson": "food-and-ordering",
   "type": "vocab",
   "topic": "food",
   "level": "beginner",
   "q": "Still water is…",
   "a": "вода без газа",
   "opts": [
    "вода с газом",
    "вода без газа",
    "горячая вода",
    "холодная вода"
   ],
   "explain": "Без газа is still; с газом is sparkling."
  },
  {
   "id": "ru-verb-1",
   "lesson": "present-tense-verbs",
   "type": "vocab",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Читают” — the ending marks…",
   "a": "они (they)",
   "opts": [
    "я",
    "ты",
    "мы",
    "они (they)"
   ],
   "explain": "The -ют/-ут ending always marks они."
  },
  {
   "id": "ru-verb-2",
   "lesson": "present-tense-verbs",
   "type": "usage",
   "topic": "verbs",
   "level": "beginner",
   "q": "Ask “do you speak Russian?” (informal). You say…",
   "a": "Ты говоришь по-русски?",
   "opts": [
    "Ты говоришь по-русски?",
    "Говоришь ты по-русски?",
    "Ты говорит по-русски?",
    "Ты говорю по-русски?"
   ],
   "explain": "No inversion: Ты говоришь по-русски?"
  },
  {
   "id": "ru-verb-3",
   "lesson": "present-tense-verbs",
   "type": "meaning",
   "topic": "verbs",
   "level": "beginner",
   "q": "“Я пишу” shows…",
   "a": "a с→ш stem mutation",
   "opts": [
    "an irregular ending",
    "a с→ш stem mutation",
    "a borrowed verb",
    "past tense"
   ],
   "explain": "Писать mutates: я пишу."
  },
  {
   "id": "ru-greet-5",
   "lesson": "greetings-and-introductions",
   "type": "meaning",
   "topic": "greetings",
   "level": "beginner",
   "q": "“Давай на ты” means…",
   "a": "let's switch to ты",
   "opts": [
    "let's switch to ты",
    "goodbye, friend",
    "speak louder",
    "write it down"
   ],
   "explain": "Давай на ты — the invitation to informality."
  }
 ],
 "review": [
  {
   "p": "здравствуйте",
   "a": "hello (formal)"
  },
  {
   "p": "привет",
   "a": "hello (informal)"
  },
  {
   "p": "добрый день",
   "a": "good day"
  },
  {
   "p": "до свидания",
   "a": "goodbye (formal)"
  },
  {
   "p": "пока",
   "a": "bye (informal)"
  },
  {
   "p": "спасибо",
   "a": "thanks"
  },
  {
   "p": "пожалуйста",
   "a": "please / you're welcome"
  },
  {
   "p": "Меня зовут…",
   "a": "I am called…"
  },
  {
   "p": "Он студент",
   "a": "he is a student (no \"is\")"
  },
  {
   "p": "У меня есть…",
   "a": "I have…"
  },
  {
   "p": "У меня нет…",
   "a": "I don't have…"
  },
  {
   "p": "есть / нет",
   "a": "there is / there isn't"
  },
  {
   "p": "один, два, три",
   "a": "one, two, three"
  },
  {
   "p": "двадцать",
   "a": "twenty"
  },
  {
   "p": "Мне двадцать лет",
   "a": "I am 20 years old"
  },
  {
   "p": "Можно мне…",
   "a": "may I have…"
  },
  {
   "p": "Счёт, пожалуйста",
   "a": "the bill, please"
  },
  {
   "p": "Приятного аппетита!",
   "a": "enjoy your meal!"
  },
  {
   "p": "Очень вкусно!",
   "a": "very tasty!"
  },
  {
   "p": "я читаю",
   "a": "I read"
  },
  {
   "p": "ты говоришь",
   "a": "you speak (informal)"
  },
  {
   "p": "Я не знаю",
   "a": "I don't know"
  },
  {
   "p": "Я не понимаю",
   "a": "I don't understand"
  },
  {
   "p": "Где ты живёшь?",
   "a": "where do you live?"
  }
 ]
};
