/* =========================================================
   EkGuru — TUTOR ASSEMBLER
   ---------------------------------------------------------
   ⚠️  YOU NORMALLY DO NOT EDIT THIS FILE.

   Each tutor now lives in their own file:

       js/tutors/_registry.js     ← the list of who exists
       js/tutors/sushila-g.js
       js/tutors/hemlata.js
       js/tutors/tara.js
       js/tutors/_TEMPLATE.js     ← copy this for a new tutor

   This file simply collects them in the order given by the
   registry and hands the finished array to the rest of the site.

   ---------------------------------------------------------
   ➕ ADDING A TUTOR — the whole procedure
   ---------------------------------------------------------
     1. Copy   js/tutors/_TEMPLATE.js
        to     js/tutors/newname.js
     2. Fill it in. Every field is commented.
     3. In    js/tutors/_registry.js   add:   "newname",
     4. In EACH html page add one line next to the others:
            <script src="js/tutors/newname.js"></script>
        (index.html, find-tutors.html, tutor.html, join.html)

   Nothing else. Their card, profile, search entry, sitemap and
   Google structured data all appear automatically.
   ========================================================= */

(function () {
  "use strict";

  var order = window.EKGURU_TUTOR_ORDER || [];
  var files = window.EKGURU_TUTOR_FILES || {};
  var list = [];
  var missing = [];

  /* 1. take them in the registry's order */
  order.forEach(function (id) {
    if (files[id]) list.push(files[id]);
    else missing.push(id);
  });

  /* 2. safety net: a tutor file that loaded but was never listed
        in the registry still shows up, rather than vanishing */
  Object.keys(files).forEach(function (id) {
    if (order.indexOf(id) === -1) {
      console.warn('[EkGuru] "' + id + '" is not in _registry.js — adding it to the end.');
      list.push(files[id]);
    }
  });

  /* 3. tell the developer clearly if a file failed to load */
  if (missing.length) {
    console.error('[EkGuru] These tutors are listed in _registry.js but their file did not load: ' +
      missing.join(", ") + '. Check the <script src="js/tutors/NAME.js"> tag in your HTML.');
  }

  window.EKGURU_TUTORS = list;
})();
