/* =========================================================
   EkGuru — TUTOR ASSEMBLER
   ---------------------------------------------------------
   ⚠️  YOU NORMALLY DO NOT EDIT THIS FILE.

   Each tutor now lives in their own file:

       js/tutors/_registry.js     ← the list of who exists
       js/tutors/sushila-g.js
       js/tutors/hemlata.js
       js/tutors/tara.js
       js/tutors/_TEMPLATE.js     ← copy this for a new tutor

   This file simply collects them in the order given by the
   registry and hands the finished array to the rest of the site.

   ---------------------------------------------------------
   ➕ ADDING A TUTOR — the whole procedure
   ---------------------------------------------------------
     1. Copy   js/tutors/_TEMPLATE.js
        to     js/tutors/newname.js
     2. Fill it in. Every field is commented.
     3. In    js/tutors/_registry.js   add:   "newname",
     4. Run:  node tools/langsync.js
        That adds the <script> tags to every page — English AND the
        six translated ones — and rebuilds their tutor cards and
        JSON-LD. Doing it by hand is what made Shikha Dutta invisible
        on every language page until v30.

   Nothing else. Their card, profile, search entry, sitemap and
   Google structured data all appear automatically.
   ========================================================= */

(function () {
  "use strict";

  var order = window.EKGURU_TUTOR_ORDER || [];
  var files = window.EKGURU_TUTOR_FILES || {};
  var list = [];
  var missing = [];

  /* 1. take them in the registry's order */
  order.forEach(function (id) {
    if (files[id]) list.push(files[id]);
    else missing.push(id);
  });

  /* 2. safety net: a tutor file that loaded but was never listed
        in the registry still shows up, rather than vanishing */
  Object.keys(files).forEach(function (id) {
    if (order.indexOf(id) === -1) {
      console.warn('[EkGuru] "' + id + '" is not in _registry.js — adding it to the end.');
      list.push(files[id]);
    }
  });

  /* 3. tell the developer clearly if a file failed to load */
  if (missing.length) {
    console.error('[EkGuru] These tutors are listed in _registry.js but their file did not load: ' +
      missing.join(", ") + '. Check the <script src="js/tutors/NAME.js"> tag in your HTML.');
  }

  /* ---------------------------------------------------------
     4. DEFAULTS — the safety net
     ---------------------------------------------------------
     A tutor file may legitimately leave fields out: a new tutor
     added in a hurry, or one whose details are still coming.
     Without this, a missing field printed the literal word
     "undefined" into the page — it appeared in the meta
     description as "native speaker from undefined", which Google
     would have indexed.

     Every field the rest of the site reads is given a sensible
     empty value here, in ONE place, so no future tutor file can
     break a page by omitting something. Anything the tutor file
     does set is left completely untouched.
     --------------------------------------------------------- */
  var DEFAULTS = {
    /* identity */
    nickname: "", headline: "", subject: "Hindi",
    country: "India", countryFlag: "🇮🇳", city: "", timezone: "IST (Asia/Kolkata)",

    /* media */
    photo: "images/placeholder-tutor.jpg",
    thumb: "images/placeholder-tutor.jpg",
    banner: "", youtubeId: "", videoTitle: "Hindi Tutor Intro",

    /* numbers */
    rating: 0, reviewsCount: 0, lessonsCount: 0,
    priceUSD: 0, lessonLength: "50 min", experienceYears: 0,
    trialAvailable: false, verified: false, superTutor: false,

    /* contact */
    preplyUrl: "", email: "", whatsapp: "", formKey: "", calLink: "",

    /* content */
    tags: [], teaches: [], levels: ["Beginner", "Intermediate", "Advanced"],
    bio: "", reviews: [], availability: {}
  };

  list.forEach(function (t) {
    Object.keys(DEFAULTS).forEach(function (k) {
      if (t[k] === undefined || t[k] === null) {
        var d = DEFAULTS[k];
        /* copy arrays and objects so two tutors never share one */
        t[k] = Array.isArray(d) ? d.slice() : (d && typeof d === "object" ? {} : d);
      }
    });

    /* =========================================================
       PHONE NUMBERS ARE BLOCKED, DELIBERATELY
       ---------------------------------------------------------
       Publishing a tutor's personal mobile on a public website
       means anyone in the world can call or message it at any
       hour, forever. Scrapers harvest numbers from public pages
       within days, and it cannot be undone once indexed.

       Shikha's number was published, and removing it from her
       file was not enough on its own — the value could be put
       back by anyone editing a tutor file, and the same mistake
       would ship again.

       So it is blocked HERE, in the one place every tutor passes
       through. Even if a tutor file sets a number, it is stripped
       and a warning is printed. The site cannot publish a phone
       number by accident any more.

       If a tutor genuinely wants this one day: get it in writing,
       use a separate business number never a personal one, and
       set allowPhone: true on that tutor's file as an explicit,
       visible decision.
       ========================================================= */
    if (t.whatsapp && !t.allowPhone) {
      console.warn('[EkGuru] Phone number removed from "' + t.id +
        '" before publishing. Personal numbers are not published — see ' +
        'js/tutors-data.js. Set allowPhone:true only with the tutor\'s ' +
        'written consent, and only for a business number.');
      t.whatsapp = "";
    }

    /* An email is required for bookings to go anywhere. Falling back
       to the shared address means a request is never simply lost. */
    if (!t.email) {
      t.email = (window.EKGURU_SITE && window.EKGURU_SITE.email) || "";
    }

    /* thumb defaults to the main photo rather than the placeholder */
    if (t.thumb === DEFAULTS.thumb && t.photo !== DEFAULTS.photo) t.thumb = t.photo;

    /* A headline is used as the page subtitle and in search results.
       An empty one leaves a visible gap, so build a plain one. */
    if (!t.headline) {
      t.headline = t.subject + " tutor" + (t.city ? " from " + t.city : "");
    }
  });

  window.EKGURU_TUTORS = list;
  window.EKGURU_TUTOR_DEFAULTS = DEFAULTS;   /* exposed for the tools */
})();
