#!/usr/bin/env python3
"""Audit the rendered root-level topic trees for the nine Indian languages.

Scope is the root topic system generated by tools/build-lang-topics.py, for
example /bengali/greetings/. The separate /learn/<slug>/ course routes are
intentionally not included in this Phase 2 audit.
"""
from __future__ import annotations

import datetime as dt
import hashlib
import html
import importlib.util
import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOPICS_DIR = ROOT / "data/topics"
REPORT_PATH = ROOT / "data/quality/indian-topic-parity.json"
EXPECTED = {
    "bn": "bengali",
    "gu": "gujarati",
    "kn": "kannada",
    "ml": "malayalam",
    "mr": "marathi",
    "pa": "punjabi",
    "ta": "tamil",
    "te": "telugu",
    "ur": "urdu",
}


def load_word_audit():
    path = ROOT / "tools/audit-adsense-readiness.py"
    spec = importlib.util.spec_from_file_location("ekguru_adsense_audit", path)
    if spec is None or spec.loader is None:
        raise RuntimeError("could not load the shared editorial word counter")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


WORDS = load_word_audit()


def visible_text(raw: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", raw))).strip()


def signature(text: str) -> str:
    normalized = re.sub(r"\s+", " ", text.casefold()).strip()
    normalized = re.sub(r"\d+(?: \d+)*", "#", normalized)
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()[:20]


def attributes(raw: str) -> dict[str, str]:
    return {key.lower(): html.unescape(value) for key, _, value in
            re.findall(r"([\w:-]+)\s*=\s*([\"'])(.*?)\2", raw, re.S)}


def page_errors(cfg: dict, topic: dict, path: Path) -> tuple[list[str], dict]:
    errors: list[str] = []
    if not path.is_file():
        return [f"{path.relative_to(ROOT)}: rendered topic page is missing"], {}
    raw = path.read_text(encoding="utf-8", errors="replace")
    core_match = re.search(
        r"<article\b(?=[^>]*\bdata-topic-core=[\"']true[\"'])[^>]*>([\s\S]*?)</article>",
        raw, re.I,
    )
    if not core_match:
        return [f"{path.relative_to(ROOT)}: missing article[data-topic-core=true]"], {}
    core = core_match.group(1)
    body = WORDS.CHROME.sub(" ", core)
    word_count = WORDS.count_words(visible_text(body))

    topic_code = cfg["code"]
    topic_slug = topic["slug"]
    core_open = core_match.group(0).split(">", 1)[0] + ">"
    core_attrs = attributes(core_open)
    if core_attrs.get("data-language") != topic_code:
        errors.append(f"{path.relative_to(ROOT)}: topic article language tag does not match {topic_code}")
    if core_attrs.get("data-topic") != topic_slug:
        errors.append(f"{path.relative_to(ROOT)}: topic article slug does not match {topic_slug}")
    if word_count < 400:
        errors.append(f"{path.relative_to(ROOT)}: {word_count} content words (minimum 400)")

    required = {
        "topic-specific opening": r"<p\b[^>]*class=[\"'][^\"']*\blede\b[^\"']*[\"']",
        "native-script vocabulary and romanisation": r"<table\b[^>]*class=[\"'][^\"']*\bphr\b[^\"']*[\"']",
        "language/culture/common-traps section": r"Language, culture, and common traps",
        "retrieval practice": r"<section\b[^>]*class=[\"'][^\"']*\btopic-practice\b",
        "practice answer key": r"<details\b[^>]*class=[\"'][^\"']*\bpractice-key\b",
        "learner questions": r"Questions learners ask",
    }
    for label, pattern in required.items():
        if not re.search(pattern, core, re.I):
            errors.append(f"{path.relative_to(ROOT)}: missing {label}")
    note = re.search(r'<div class="note">(.*?)</div>', core, re.I | re.S)
    if not note or len(visible_text(note.group(1)).split()) < 20:
        errors.append(f"{path.relative_to(ROOT)}: language/cultural context note is missing or too short")
    practice_context = re.search(
        r'<p class="practice-context"[^>]*>(.*?)</p>', core, re.I | re.S,
    )
    if not practice_context or "common mistake" not in visible_text(practice_context.group(1)).casefold():
        errors.append(f"{path.relative_to(ROOT)}: practice does not call out a common mistake")

    phrase_count = len(topic.get("phrases", []))
    speakers = re.findall(r"<button\b[^>]*\bdata-sb-say=[\"']", core, re.I)
    if len(speakers) != phrase_count:
        errors.append(f"{path.relative_to(ROOT)}: {len(speakers)} phrase speaker buttons for {phrase_count} phrases")
    target_cells = re.findall(
        r"<td\b(?=[^>]*\blang=[\"']" + re.escape(topic_code) + r"[\"'])"
        r"(?=[^>]*\bdir=[\"']auto[\"'])[^>]*>", core, re.I,
    )
    if len(target_cells) != phrase_count:
        errors.append(f"{path.relative_to(ROOT)}: {len(target_cells)} correctly tagged target-script cells for {phrase_count} phrases")
    if not re.search(r"<script\b[^>]*src=[\"'][^\"']*js/storybook\.js", raw, re.I):
        errors.append(f"{path.relative_to(ROOT)}: shared storybook voice runtime is not loaded")
    if not re.search(r"<script\b[^>]*src=[\"'][^\"']*/js/voice\.js", raw, re.I):
        errors.append(f"{path.relative_to(ROOT)}: shared voice provider is not loaded")
    if not re.search(r"<html\b[^>]*\bdata-learning-language=[\"']" + re.escape(topic_code) + r"[\"']", raw, re.I):
        errors.append(f"{path.relative_to(ROOT)}: page language context is not {topic_code}")

    lede = re.search(r"<p\b[^>]*class=[\"'][^\"']*\blede\b[^\"']*[\"'][^>]*>([\s\S]*?)</p>", core, re.I)
    opening = visible_text(lede.group(1)) if lede else ""
    if len(opening.split()) < 8:
        errors.append(f"{path.relative_to(ROOT)}: opening is missing or too short to identify the topic")

    article_text = visible_text(body)
    return errors, {
        "slug": topic_slug,
        "path": path.relative_to(ROOT).as_posix(),
        "content_words": word_count,
        "phrase_count": phrase_count,
        "voice_buttons": len(speakers),
        "opening_signature": signature(opening) if opening else "",
        "article_signature": signature(article_text),
    }


def audit() -> tuple[dict, list[str]]:
    errors: list[str] = []
    language_rows: list[dict] = []
    all_pages: list[dict] = []
    opening_map: dict[str, list[str]] = {}
    article_map: dict[str, list[str]] = {}

    files = sorted(TOPICS_DIR.glob("*.json"))
    configs: dict[str, dict] = {}
    for source in files:
        try:
            cfg = json.loads(source.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            errors.append(f"{source.relative_to(ROOT)}: cannot read topic data ({exc})")
            continue
        if cfg.get("code") not in EXPECTED:
            continue
        configs[cfg["code"]] = cfg

    if set(configs) != set(EXPECTED):
        errors.append("topic data must contain exactly the nine scoped language codes; "
                      f"found {sorted(configs)}")

    for code, slug in EXPECTED.items():
        cfg = configs.get(code)
        if not cfg:
            continue
        if cfg.get("dir") != slug:
            errors.append(f"{code}: expected root directory {slug}, got {cfg.get('dir')!r}")
        topics = cfg.get("topics", [])
        topic_slugs = [row.get("slug", "") for row in topics]
        if len(set(topic_slugs)) != len(topic_slugs):
            errors.append(f"{code}: duplicate topic slugs in source data")
        topic_root = ROOT / slug
        actual_slugs = sorted(p.parent.name for p in topic_root.glob("*/index.html"))
        expected_slugs = sorted(topic_slugs)
        if len(topic_slugs) < 29:
            errors.append(f"{code}: only {len(topic_slugs)} topic directories are configured (minimum 29)")
        if actual_slugs != expected_slugs:
            missing = sorted(set(expected_slugs) - set(actual_slugs))
            extra = sorted(set(actual_slugs) - set(expected_slugs))
            errors.append(f"{code}: rendered topic-directory mismatch; missing={missing}, extra={extra}")
        hub = topic_root / "index.html"
        if not hub.is_file():
            errors.append(f"{code}: root topic hub is missing: {hub.relative_to(ROOT)}")

        rows: list[dict] = []
        for topic in topics:
            path = topic_root / topic.get("slug", "") / "index.html"
            page_errs, row = page_errors(cfg, topic, path)
            errors.extend(page_errs)
            if row:
                rows.append(row)
                all_pages.append(row)
                opening_map.setdefault(row["opening_signature"], []).append(row["path"])
                article_map.setdefault(row["article_signature"], []).append(row["path"])
        counts = [row["content_words"] for row in rows]
        language_rows.append({
            "code": code,
            "slug": slug,
            "name": cfg.get("title", slug),
            "topic_directories": len(topic_slugs),
            "rendered_topic_pages": len(rows),
            "min_content_words": min(counts) if counts else 0,
            "max_content_words": max(counts) if counts else 0,
            "phrase_speaker_buttons": sum(row["voice_buttons"] for row in rows),
            "topics": rows,
        })

    for sig, paths in opening_map.items():
        if sig and len(paths) > 1:
            errors.append("duplicate language/topic opening: " + ", ".join(paths))
    for sig, paths in article_map.items():
        if sig and len(paths) > 1:
            errors.append("duplicate topic article: " + ", ".join(paths))

    word_counts = [row["content_words"] for row in all_pages]
    report = {
        "schema_version": 1,
        "generated_on": dt.date.today().isoformat(),
        "scope": "Root-level topic trees generated by tools/build-lang-topics.py; separate /learn/<language>/ routes are excluded.",
        "criteria": {
            "languages": 9,
            "minimum_topic_directories_per_language": 29,
            "minimum_rendered_topic_words": 400,
            "unique_language_topic_openings": True,
            "target_script_lang_and_voice_buttons": True,
            "practice_and_context_sections": True,
        },
        "summary": {
            "languages": len(language_rows),
            "topic_directories_min": min((r["topic_directories"] for r in language_rows), default=0),
            "rendered_topic_pages": len(all_pages),
            "pages_at_or_above_400_words": sum(1 for n in word_counts if n >= 400),
            "minimum_content_words": min(word_counts) if word_counts else 0,
            "maximum_content_words": max(word_counts) if word_counts else 0,
            "phrase_speaker_buttons": sum(row["voice_buttons"] for row in all_pages),
            "unique_openings": len(opening_map),
            "unique_article_signatures": len(article_map),
        },
        "languages_detail": language_rows,
        "failures": errors,
    }
    return report, errors


def main() -> int:
    args = set(sys.argv[1:])
    unknown = args - {"--check", "--write-report"}
    if unknown or len(args) > 1:
        print("Usage: python3 tools/audit-indian-topic-parity.py [--check|--write-report]")
        return 2
    report, errors = audit()
    if errors:
        print(f"FAIL root Indian topic parity: {len(errors)} issue(s)")
        for issue in errors:
            print(" - " + issue)
        return 1
    summary = report["summary"]
    print(
        "PASS root Indian topic parity: %d languages, %d rendered topic pages, "
        "%d directories per language (%d required), %d+ words minimum, "
        "%d explicit phrase speakers, %d unique openings."
        % (summary["languages"], summary["rendered_topic_pages"],
           summary["topic_directories_min"],
           report["criteria"]["minimum_topic_directories_per_language"],
           summary["minimum_content_words"], summary["phrase_speaker_buttons"],
           summary["unique_openings"])
    )
    if "--write-report" in args:
        REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
        REPORT_PATH.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
