# -*- coding: utf-8 -*-
"""194-country program, batch C3 — Madagascar, Rwanda, Burundi, Zimbabwe, Somalia (authored, not MT).

24 words + 12 phrases + 4 grammar concepts per pack, BETA starter reference.
Hindi stays the only PRODUCTION language.
"""

EXTRA_PACKS_194_AF1 = {
    "mg": {
        "name": "Malagasy", "native": "Malagasy",
        "about": ("Malagasy is spoken by about 25 million people in Madagascar. This starter pack covers greetings, "
                  "essentials and core grammar — a first taste, not a full course. It is the English-medium "
                  "starting point for Madagascar."),
        "words": [
            ("izaho", "ee-ZAH-oo", "I", "pronoun", "people"),
            ("ianao", "ee-ah-NOW", "you", "pronoun", "people"),
            ("izy", "EE-zee", "he / she", "pronoun", "people"),
            ("isika", "ee-SEE-kah", "we", "pronoun", "people"),
            ("ianareo", "ee-ah-nah-REH-oo", "you (plural)", "pronoun", "people"),
            ("rano", "RAH-noo", "water", "noun", "essentials"),
            ("sakafo", "sah-KAH-foo", "food", "noun", "essentials"),
            ("trano", "TRAH-noo", "house", "noun", "home"),
            ("mofo", "MOO-foo", "bread", "noun", "food"),
            ("fotoana", "foo-too-AH-nah", "time", "noun", "time"),
            ("andro", "AHN-droo", "day", "noun", "time"),
            ("alina", "ah-LEE-nah", "night", "noun", "time"),
            ("sakaiza", "sah-KAH-ee-zah", "friend", "noun", "people"),
            ("fianakaviana", "fee-ah-nah-kah-vee-AH-nah", "family", "noun", "people"),
            ("olona", "oo-LOO-nah", "person", "noun", "people"),
            ("tsara", "TSAH-rah", "good", "adjective", "basics"),
            ("ratsy", "RAH-tsee", "bad", "adjective", "basics"),
            ("lehibe", "leh-HEE-beh", "big", "adjective", "basics"),
            ("kely", "KEH-lee", "small", "adjective", "basics"),
            ("eny", "EH-nee", "yes", "particle", "essentials"),
            ("tsia", "TSEE-ah", "no", "particle", "essentials"),
            ("vola", "VOO-lah", "money", "noun", "daily"),
            ("boky", "BOO-kee", "book", "noun", "objects"),
            ("misaotra", "mee-SOW-trah", "thanks", "verb", "essentials"),
        ],
        "phrases": [
            ("Salama", "sah-LAH-mah", "hello", "greetings", "neutral"),
            ("Manao ahoana ny maraina", "mah-NOW ah-OO-ah-nah nee mah-RAH-ee-nah", "good morning", "greetings", "neutral"),
            ("Misaotra betsaka", "mee-SOW-trah beh-TSAH-kah", "thanks very much", "essentials", "neutral"),
            ("Manao ahoana ianao?", "mah-NOW ah-OO-ah-nah ee-ah-NOW", "How are you?", "greetings", "informal"),
            ("Iza no anaranao?", "EE-zah noh ah-nah-rah-NOW", "What's your name?", "greetings", "informal"),
            ("Ny anarako dia …", "nee ah-nah-RAH-koo dee-ah", "My name is …", "introductions", "neutral"),
            ("Inona ity?", "ee-NOO-nah EE-tee", "What is this?", "basics", "neutral"),
            ("Tsy azoko", "tsee ah-ZOO-koo", "I don't understand", "problems", "neutral"),
            ("Veloma", "veh-LOO-mah", "goodbye", "greetings", "neutral"),
            ("Miteny anglisy ve ianao?", "mee-TEH-nee ahn-GLEE-see veh ee-ah-NOW", "Do you speak English?", "survival", "informal"),
            ("Ohatrinona?", "oo-ah-TREE-noo-nah", "How much is it?", "shopping", "neutral"),
            ("… aiza?", "ah-EE-zah", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns (no gender)",
             "pattern": "izaho · ianao · izy · isika · ianareo",
             "examples": [
                 {"target": "Izaho miteny", "roman": "ee-ZAH-oo mee-TEH-nee", "gloss": "I speak"},
                 {"target": "Ianao miteny", "roman": "ee-ah-NOW mee-TEH-nee", "gloss": "you speak"},
                 {"target": "Isika miteny", "roman": "ee-SEE-kah mee-TEH-nee", "gloss": "we speak"}],
             "exceptions": ["Izy covers he and she — no gender."],
             "learnerNote": "Short forms (aho, anao) exist — long forms are always safe.",
             "commonMistakes": ["ianao with elders (soften it)", "Short/long forms mixed up"]},
            {"concept": "Negation with tsy",
             "pattern": "tsy + verb",
             "examples": [
                 {"target": "Tsy azoko", "roman": "tsee ah-ZOO-koo", "gloss": "I don't understand"},
                 {"target": "Tsy misy!", "roman": "tsee MEE-see", "gloss": "there is nothing!"},
                 {"target": "Tsy miteny", "roman": "tsee mee-TEH-nee", "gloss": "don't speak / not speaking"}],
             "exceptions": ["Tsia (no) answers; tsy negates phrases."],
             "learnerNote": "Tsy before anything flips it negative — verbs, existence, whole replies.",
             "commonMistakes": ["tsia to negate verbs (use tsy)", "Post-verb tsy"]},
            {"concept": "Manao-ahoana greetings",
             "pattern": "manao ahoana (how?) + ianao / ny maraina / …",
             "examples": [
                 {"target": "Manao ahoana ianao?", "roman": "mah-NOW ah-OO-ah-nah ee-ah-NOW", "gloss": "how are you?"},
                 {"target": "Manao ahoana ny maraina", "roman": "mah-NOW ah-OO-ah-nah nee mah-RAH-ee-nah", "gloss": "good morning (how the morning?)"},
                 {"target": "Tsara fa misaotra", "roman": "TSAH-rah fah mee-SOW-trah", "gloss": "fine, thanks (good, thanks)"}],
             "exceptions": ["Salama opens everything; manao-ahoana carries the question."],
             "learnerNote": "Manao ahoana (how?) scales from hello to morning to evening.",
             "commonMistakes": ["Skipping ianao (sounds abrupt)", "Tsara skipped in replies"]},
            {"concept": "Question words",
             "pattern": "iza (who) · inona (what) · aiza (where) · ohatrinona (how much)",
             "examples": [
                 {"target": "Iza no anaranao?", "roman": "EE-zah noh ah-nah-rah-NOW", "gloss": "what is your name? (who your name?)"},
                 {"target": "… aiza?", "roman": "ah-EE-zah", "gloss": "where is …?"},
                 {"target": "Ohatrinona?", "roman": "oo-ah-TREE-noo-nah", "gloss": "how much is it?"}],
             "exceptions": ["-ko (my) vs -nao (your) endings: anarako vs anaranao."],
             "learnerNote": "Iza asks who, inona what, aiza where — one root, three questions.",
             "commonMistakes": ["iza/inona swaps", "aiza/ohatrinona swaps"]},
        ],
    },
    "rw": {
        "name": "Kinyarwanda", "native": "Ikinyarwanda",
        "about": ("Kinyarwanda (Ikinyarwanda) is spoken by about 12 million people in Rwanda. This starter pack covers "
                  "greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Rwanda."),
        "words": [
            ("njye", "njeh", "I", "pronoun", "people"),
            ("wowe", "WOH-weh", "you", "pronoun", "people"),
            ("we", "weh", "he / she", "pronoun", "people"),
            ("twebwe", "tweh-BWEH", "we", "pronoun", "people"),
            ("mwebwe", "mweh-BWEH", "you (plural)", "pronoun", "people"),
            ("amazi", "ah-MAH-zee", "water", "noun", "essentials"),
            ("ibiryo", "ee-bee-RYOH", "food", "noun", "essentials"),
            ("inzu", "ee-NZOO", "house", "noun", "home"),
            ("umugati", "oo-moo-GAH-tee", "bread", "noun", "food"),
            ("igihe", "ee-gee-HEH", "time", "noun", "time"),
            ("umunsi", "oo-moon-SEE", "day", "noun", "time"),
            ("ijoro", "ee-joh-ROH", "night", "noun", "time"),
            ("inshuti", "ee-nshoo-TEE", "friend", "noun", "people"),
            ("umuryango", "oo-moo-ryahn-GOH", "family", "noun", "people"),
            ("umuntu", "oo-moon-TOO", "person", "noun", "people"),
            ("meza", "meh-ZAH", "good / fine", "adjective", "basics"),
            ("mbi", "mbee", "bad", "adjective", "basics"),
            ("nini", "nee-NEE", "big", "adjective", "basics"),
            ("to", "toh", "small", "adjective", "basics"),
            ("yego", "yeh-GOH", "yes", "particle", "essentials"),
            ("oya", "oh-YAH", "no", "particle", "essentials"),
            ("amafaranga", "ah-mah-fah-RAHN-gah", "money", "noun", "daily"),
            ("igitabo", "ee-gee-tah-BOH", "book", "noun", "objects"),
            ("murakoze", "moo-rah-KOH-zeh", "thanks", "verb", "essentials"),
        ],
        "phrases": [
            ("Muraho", "moo-rah-HOH", "hello", "greetings", "neutral"),
            ("Mwaramutse", "mwah-rah-moot-SEH", "good morning", "greetings", "neutral"),
            ("Murakoze cyane", "moo-rah-KOH-zeh chah-NEH", "thanks very much", "essentials", "neutral"),
            ("Amakuru?", "ah-mah-koo-ROO", "How are you?", "greetings", "informal"),
            ("Witwa nde?", "weet-wah ndeh", "What's your name?", "greetings", "informal"),
            ("Nitwa …", "neet-wah", "My name is …", "introductions", "neutral"),
            ("Iki ni igiki?", "ee-kee nee ee-gee-KEE", "What is this?", "basics", "neutral"),
            ("Sinumva", "see-noom-VAH", "I don't understand", "problems", "neutral"),
            ("Murabeho", "moo-rah-beh-HOH", "goodbye", "greetings", "neutral"),
            ("Uravuga Icyongereza?", "oo-rah-voo-GAH ee-chohn-geh-reh-ZAH", "Do you speak English?", "survival", "informal"),
            ("Ni angahe?", "nee ahn-gah-HEH", "How much is it?", "shopping", "neutral"),
            ("… iri he?", "ee-ree heh", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "njye · wowe · we · twebwe · mwebwe",
             "examples": [
                 {"target": "Njye ndavuga", "roman": "njeh ndah-voo-GAH", "gloss": "I speak"},
                 {"target": "Wowe uravuga", "roman": "WOH-weh oo-rah-voo-GAH", "gloss": "you speak"},
                 {"target": "Twebwe turavuga", "roman": "tweh-BWEH too-rah-voo-GAH", "gloss": "we speak"}],
             "exceptions": ["We covers he and she — no gender in pronouns."],
             "learnerNote": "Verb prefixes (n-/u-/tu-) echo the pronoun — learn them as pairs.",
             "commonMistakes": ["wowe with elders (soften it)", "Wrong verb prefix for the pronoun"]},
            {"concept": "Ni-answers: meza, angahe, igeze",
             "pattern": "ni + word (it is …)",
             "examples": [
                 {"target": "Ni meza", "roman": "nee meh-ZAH", "gloss": "I am fine (it is good)"},
                 {"target": "Ni angahe?", "roman": "nee ahn-gah-HEH", "gloss": "how much is it?"},
                 {"target": "Ni meza, murakoze", "roman": "nee meh-ZAH moo-rah-KOH-zeh", "gloss": "fine, thank you"}],
             "exceptions": ["Amakuru? (news?) always expects Ni meza first."],
             "learnerNote": "Ni (it is) answers everything — fine, prices, and introductions.",
             "commonMistakes": ["Skipping ni", "Meza without ni (sounds bare)"]},
            {"concept": "Nsh-wants: nshaka, nshobora",
             "pattern": "nsh- + verb (I …)",
             "examples": [
                 {"target": "Nshaka …", "roman": "nshah-KAH", "gloss": "I would like …"},
                 {"target": "Nshobora kwishyura?", "roman": "nshoh-boh-RAH kwee-shyoo-RAH", "gloss": "can I pay?"},
                 {"target": "Nitwa …", "roman": "neet-wah", "gloss": "my name is … (I am called)"}],
             "exceptions": ["Nitwa (I am called) is the introduction verb — never drop it."],
             "learnerNote": "Nsh- starts I-statements: wanting, asking, and naming yourself.",
             "commonMistakes": ["Njye nshaka (don't double the I)", "Nitwa skipped in introductions"]},
            {"concept": "Questions: he, angahe, iki",
             "pattern": "he (where) · angahe (how much) · iki (this/what)",
             "examples": [
                 {"target": "… iri he?", "roman": "ee-ree heh", "gloss": "where is …?"},
                 {"target": "Ni angahe?", "roman": "nee ahn-gah-HEH", "gloss": "how much is it?"},
                 {"target": "Iki ni igiki?", "roman": "ee-kee nee ee-gee-KEE", "gloss": "what is this?"}],
             "exceptions": ["Iri he (it-is where) never splits — say it as one chunk."],
             "learnerNote": "He points at places, angahe at prices, iki at things.",
             "commonMistakes": ["he/angahe swaps", "Splitting iri he"]},
        ],
    },
    "rn": {
        "name": "Kirundi", "native": "Ikirundi",
        "about": ("Kirundi (Ikirundi) is spoken by about 12 million people in Burundi. This starter pack covers "
                  "greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Burundi."),
        "words": [
            ("jewe", "jeh-WEH", "I", "pronoun", "people"),
            ("wewe", "weh-WEH", "you", "pronoun", "people"),
            ("uwe", "oo-WEH", "he / she", "pronoun", "people"),
            ("twebwe", "tweh-BWEH", "we", "pronoun", "people"),
            ("mwebwe", "mweh-BWEH", "you (plural)", "pronoun", "people"),
            ("amazi", "ah-MAH-zee", "water", "noun", "essentials"),
            ("ibiryo", "ee-bee-RYOH", "food", "noun", "essentials"),
            ("inzu", "ee-NZOO", "house", "noun", "home"),
            ("umugati", "oo-moo-GAH-tee", "bread", "noun", "food"),
            ("igihe", "ee-gee-HEH", "time", "noun", "time"),
            ("umunsi", "oo-moon-SEE", "day", "noun", "time"),
            ("ijoro", "ee-joh-ROH", "night", "noun", "time"),
            ("mugenzi", "moo-gehn-ZEE", "friend", "noun", "people"),
            ("umuryango", "oo-moo-ryahn-GOH", "family", "noun", "people"),
            ("umuntu", "oo-moon-TOO", "person", "noun", "people"),
            ("meza", "meh-ZAH", "good / fine", "adjective", "basics"),
            ("mbi", "mbee", "bad", "adjective", "basics"),
            ("nini", "nee-NEE", "big", "adjective", "basics"),
            ("to", "toh", "small", "adjective", "basics"),
            ("ego", "eh-GOH", "yes", "particle", "essentials"),
            ("oya", "oh-YAH", "no", "particle", "essentials"),
            ("amafaranga", "ah-mah-fah-RAHN-gah", "money", "noun", "daily"),
            ("igitabo", "ee-gee-tah-BOH", "book", "noun", "objects"),
            ("murakoze", "moo-rah-KOH-zeh", "thanks", "verb", "essentials"),
        ],
        "phrases": [
            ("Muraho", "moo-rah-HOH", "hello", "greetings", "neutral"),
            ("Bwakeye", "bwah-keh-YEH", "good morning", "greetings", "neutral"),
            ("Murakoze cane", "moo-rah-KOH-zeh chah-NEH", "thanks a lot", "essentials", "neutral"),
            ("Amakuru?", "ah-mah-koo-ROO", "How are you?", "greetings", "informal"),
            ("Witwa nde?", "weet-wah ndeh", "What's your name?", "greetings", "informal"),
            ("Nitwa …", "neet-wah", "My name is …", "introductions", "neutral"),
            ("Iki n'igiki?", "ee-kee nee-gee-KEE", "What is this?", "basics", "neutral"),
            ("Sinumva", "see-noom-VAH", "I don't understand", "problems", "neutral"),
            ("Murabeho", "moo-rah-beh-HOH", "goodbye", "greetings", "neutral"),
            ("Uravuga Icongereza?", "oo-rah-voo-GAH ee-kohn-geh-reh-ZAH", "Do you speak English?", "survival", "informal"),
            ("Bingana iki?", "bee-ngah-NAH ee-kee", "How much is this?", "shopping", "neutral"),
            ("Iri he?", "ee-ree heh", "Where is it?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "jewe · wewe · uwe · twebwe · mwebwe",
             "examples": [
                 {"target": "Jewe ndavuga", "roman": "jeh-WEH ndah-voo-GAH", "gloss": "I speak"},
                 {"target": "Wewe uravuga", "roman": "weh-WEH oo-rah-voo-GAH", "gloss": "you speak"},
                 {"target": "Twebwe turavuga", "roman": "tweh-BWEH too-rah-voo-GAH", "gloss": "we speak"}],
             "exceptions": ["Uwe covers he and she — no gender in pronouns."],
             "learnerNote": "Verb prefixes (n-/u-/tu-) echo the pronoun — learn them as pairs.",
             "commonMistakes": ["wewe with elders (soften it)", "Wrong verb prefix for the pronoun"]},
            {"concept": "Greetings by time of day",
             "pattern": "Bwakeye (morning) · Mwiriwe (afternoon) · Ijoro ryiza (night)",
             "examples": [
                 {"target": "Bwakeye", "roman": "bwah-keh-YEH", "gloss": "good morning"},
                 {"target": "Mwiriwe", "roman": "mwee-ree-WEH", "gloss": "good afternoon"},
                 {"target": "Ijoro ryiza", "roman": "ee-joh-ROH ryee-ZAH", "gloss": "good night"}],
             "exceptions": ["Muraho works any time — time-greetings are warmer."],
             "learnerNote": "Greet the clock: morning, afternoon, and night each have their word.",
             "commonMistakes": ["Bwakeye after noon (use Mwiriwe)", "Muraho skipped (greet first!)"]},
            {"concept": "Kuvuga: to speak",
             "pattern": "ku- + vuga (to speak) — uravuga (you speak)",
             "examples": [
                 {"target": "Uravuga Icongereza?", "roman": "oo-rah-voo-GAH ee-kohn-geh-reh-ZAH", "gloss": "do you speak English?"},
                 {"target": "Tugende!", "roman": "too-gehn-DEH", "gloss": "let's go!"},
                 {"target": "Ndagusaba", "roman": "ndah-goo-SAH-bah", "gloss": "please (I request)"}],
             "exceptions": ["Vuga! (speak!) is the command — sharp, use with care."],
             "learnerNote": "Ku- marks the infinitive: kuvuga (to speak), kugenda (to go).",
             "commonMistakes": ["Vuga as please (use ndagusaba)", "Ku- dropped (changes meaning)"]},
            {"concept": "Questions: he, iki, gute",
             "pattern": "he (where) · iki (this/what) · gute (how)",
             "examples": [
                 {"target": "Iri he?", "roman": "ee-ree heh", "gloss": "where is it?"},
                 {"target": "Iki n'igiki?", "roman": "ee-kee nee-gee-KEE", "gloss": "what is this?"},
                 {"target": "Witwa gute?", "roman": "weet-wah GOO-teh", "gloss": "what is your name? (called how?)"}],
             "exceptions": ["Hehe? (where?) doubles the he for emphasis."],
             "learnerNote": "He points at places, iki at things, gute at names and ways.",
             "commonMistakes": ["he/iki swaps", "Splitting iri he"]},
        ],
    },
    "sn": {
        "name": "Shona", "native": "chiShona",
        "about": ("Shona (chiShona) is spoken by about 14 million people in Zimbabwe. This starter pack covers "
                  "greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Zimbabwe."),
        "words": [
            ("ini", "EE-nee", "I", "pronoun", "people"),
            ("iwe", "EE-weh", "you", "pronoun", "people"),
            ("iye", "EE-yeh", "he / she", "pronoun", "people"),
            ("isu", "EE-soo", "we", "pronoun", "people"),
            ("imi", "EE-mee", "you (plural)", "pronoun", "people"),
            ("mvura", "mvoo-RAH", "water", "noun", "essentials"),
            ("chikafu", "chee-kah-FOO", "food", "noun", "essentials"),
            ("imba", "eem-BAH", "house", "noun", "home"),
            ("chingwa", "cheen-GWAH", "bread", "noun", "food"),
            ("nguva", "ngoo-VAH", "time", "noun", "time"),
            ("zuva", "zoo-VAH", "day", "noun", "time"),
            ("usiku", "oo-see-KOO", "night", "noun", "time"),
            ("shamwari", "shah-mwah-REE", "friend", "noun", "people"),
            ("mhuri", "mhoo-REE", "family", "noun", "people"),
            ("munhu", "moon-HOO", "person", "noun", "people"),
            ("zvakanaka", "zvah-kah-NAH-kah", "good", "adjective", "basics"),
            ("zvakaipa", "zvah-kah-EE-pah", "bad", "adjective", "basics"),
            ("hombe", "hohm-BEH", "big", "adjective", "basics"),
            ("diki", "dee-KEE", "small", "adjective", "basics"),
            ("hongu", "hohn-GOO", "yes", "particle", "essentials"),
            ("kwete", "kweh-TEH", "no", "particle", "essentials"),
            ("mari", "mah-REE", "money", "noun", "daily"),
            ("bhuku", "bhoo-KOO", "book", "noun", "objects"),
            ("ndatenda", "ndah-teh-NDAH", "thanks (I thank)", "verb", "essentials"),
        ],
        "phrases": [
            ("Mhoro", "mhoh-ROH", "hello", "greetings", "neutral"),
            ("Mangwanani", "mahn-gwah-NAH-nee", "good morning", "greetings", "neutral"),
            ("Ndatenda chaizvo", "ndah-teh-NDAH chah-eez-VOH", "thanks very much", "essentials", "neutral"),
            ("Makadii?", "mah-kah-DEE", "How are you? (plural/respectful)", "greetings", "informal"),
            ("Unonzi ani?", "oo-nohn-ZEE AH-nee", "What's your name?", "greetings", "informal"),
            ("Ndinonzi …", "ndee-nohn-ZEE", "My name is …", "introductions", "neutral"),
            ("Chii ichi?", "chee ee-chee", "What is this?", "basics", "neutral"),
            ("Handisi kunzwisisa", "hahn-dee-see koon-zwee-SEE-sah", "I don't understand", "problems", "neutral"),
            ("Sara zvakanaka", "sah-rah zvah-kah-NAH-kah", "goodbye (stay well)", "greetings", "neutral"),
            ("Unotaura Chirungu?", "oo-noh-tah-OO-rah chee-roon-GOO", "Do you speak English?", "survival", "informal"),
            ("Zvinodhura zvakadii?", "zvee-noh-DHOO-rah zvah-kah-DEE", "How much is this?", "shopping", "neutral"),
            ("… kupi?", "koo-PEE", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "ini · iwe · iye · isu · imi",
             "examples": [
                 {"target": "Ini ndinotaura", "roman": "EE-nee ndee-noh-tah-OO-rah", "gloss": "I speak"},
                 {"target": "Iwe unotaura", "roman": "EE-weh oo-noh-tah-OO-rah", "gloss": "you speak"},
                 {"target": "Ndiripo, kana iwe?", "roman": "ndee-ree-POH kah-nah EE-weh", "gloss": "I'm fine, and you?"}],
             "exceptions": ["Iye covers he and she — no gender in pronouns."],
             "learnerNote": "Verb prefixes (ndi-/u-) echo the pronoun — learn them as pairs.",
             "commonMistakes": ["iwe with elders (use plural respect)", "Wrong verb prefix for the pronoun"]},
            {"concept": "Noun classes: mu-, chi-, zi-",
             "pattern": "mu-nhu (person) · chi-kafu (food) · zi-nhu (things)",
             "examples": [
                 {"target": "munhu", "roman": "moon-HOO", "gloss": "person (mu- class)"},
                 {"target": "chikafu", "roman": "chee-kah-FOO", "gloss": "food (chi- class)"},
                 {"target": "zvakanaka", "roman": "zvah-kah-NAH-kah", "gloss": "good (zva- agreement)"}],
             "exceptions": ["Adjectives agree with the noun's class — -naka wears many prefixes."],
             "learnerNote": "Every noun wears a class prefix — adjectives dress to match it.",
             "commonMistakes": ["Adjective without agreement", "mu-/va- singular/plural swaps"]},
            {"concept": "Negation with ha-",
             "pattern": "ha- + verb",
             "examples": [
                 {"target": "Handisi kunzwisisa", "roman": "hahn-dee-see koon-zwee-SEE-sah", "gloss": "I don't understand"},
                 {"target": "Handizivi", "roman": "hahn-dee-zee-VEE", "gloss": "I don't know"},
                 {"target": "Hapana", "roman": "hah-PAH-nah", "gloss": "there is none / no"}],
             "exceptions": ["Kwete (no) answers; ha- negates verbs."],
             "learnerNote": "Ha- opens the negative — speakers hear it coming from the first syllable.",
             "commonMistakes": ["kwete to negate verbs (use ha-)", "Post-verb ha-"]},
            {"concept": "Questions: ani, kupi, chii",
             "pattern": "ani (who) · kupi (where) · chii (what)",
             "examples": [
                 {"target": "Unonzi ani?", "roman": "oo-nohn-ZEE AH-nee", "gloss": "what is your name? (you-called who?)"},
                 {"target": "… kupi?", "roman": "koo-PEE", "gloss": "where is …?"},
                 {"target": "Chii ichi?", "roman": "chee ee-chee", "gloss": "what is this?"}],
             "exceptions": ["Uri ani? (who are you?) opens identity questions."],
             "learnerNote": "Ani points at people, kupi at places, chii at things.",
             "commonMistakes": ["ani/kupi swaps", "English word order"]},
        ],
    },
    "so": {
        "name": "Somali", "native": "Soomaali",
        "about": ("Somali (Soomaali) is spoken by about 18 million people in Somalia and neighbours. This starter pack "
                  "covers greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Somalia."),
        "words": [
            ("aniga", "ah-NEE-gah", "I", "pronoun", "people"),
            ("adiga", "ah-DEE-gah", "you (male)", "pronoun", "people"),
            ("isaga", "ee-SAH-gah", "he", "pronoun", "people"),
            ("iyada", "ee-YAH-dah", "she", "pronoun", "people"),
            ("annaga", "ahn-NAH-gah", "we", "pronoun", "people"),
            ("biyo", "BEE-yoh", "water", "noun", "essentials"),
            ("cunto", "OON-toh", "food", "noun", "essentials"),
            ("guri", "GOO-ree", "house", "noun", "home"),
            ("rooti", "ROH-tee", "bread", "noun", "food"),
            ("wakhti", "wahkh-TEE", "time", "noun", "time"),
            ("maalin", "mah-AH-leen", "day", "noun", "time"),
            ("habeen", "hah-BEHN", "night", "noun", "time"),
            ("saaxiib", "sah-HEEB", "friend", "noun", "people"),
            ("qoys", "koys", "family", "noun", "people"),
            ("qof", "kof", "person", "noun", "people"),
            ("wanaagsan", "wah-NAHG-sahn", "good", "adjective", "basics"),
            ("xun", "hoon", "bad", "adjective", "basics"),
            ("weyn", "wayn", "big", "adjective", "basics"),
            ("yar", "yahr", "small", "adjective", "basics"),
            ("haa", "hah", "yes", "particle", "essentials"),
            ("maya", "MAH-yah", "no", "particle", "essentials"),
            ("lacag", "lah-AHG", "money", "noun", "daily"),
            ("buug", "boog", "book", "noun", "objects"),
            ("mahadsanid", "mah-hahd-SAH-need", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Salaan", "sah-LAHN", "hello", "greetings", "neutral"),
            ("Subax wanaagsan", "soo-BAHH wah-NAHG-sahn", "good morning", "greetings", "neutral"),
            ("Mahadsanid badan", "mah-hahd-SAH-need bah-DAHN", "many thanks", "essentials", "neutral"),
            ("Sidee tahay?", "see-DEH tah-HAH-ee", "How are you?", "greetings", "informal"),
            ("Magacaa?", "mah-gah-AH", "What's your name?", "greetings", "informal"),
            ("Magacaygu waa …", "mah-gah-AH-ee-goo wah", "My name is …", "introductions", "neutral"),
            ("Waa maxay?", "wah mah-HAH-ee", "What is this?", "basics", "neutral"),
            ("Ma fahmin", "mah FAH-meen", "I don't understand", "problems", "neutral"),
            ("Nabad gelyo", "nah-BAHD geh-LYOH", "goodbye (see you later)", "greetings", "neutral"),
            ("Ma Ingiriisi ku hadashaa?", "mah een-gee-REE-see koo hah-dah-SHAH", "Do you speak English?", "survival", "informal"),
            ("Waa imisa?", "wah ee-mee-SAH", "How much is it?", "shopping", "neutral"),
            ("… xaggee?", "hhah-GEH", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Gendered pronouns",
             "pattern": "aniga · adiga/iyadha (you m/f) · isaga/iyada (he/she) · annaga",
             "examples": [
                 {"target": "Aniga waan hadlaa", "roman": "ah-NEE-gah wahn hahd-LAH", "gloss": "I speak"},
                 {"target": "Adiga waad hadashaa", "roman": "ah-DEE-gah wahd hah-dah-SHAH", "gloss": "you speak (male)"},
                 {"target": "Annaga waan hadalnaa", "roman": "ahn-NAH-gah wahn hah-dahl-NAH", "gloss": "we speak"}],
             "exceptions": ["You and he/she split by gender — pick adiga/iyada and isaga/iyada carefully."],
             "learnerNote": "Somali pronouns know gender: male and female you/he/she differ.",
             "commonMistakes": ["adiga to a woman (use iyadha)", "isaga for she (use iyada)"]},
            {"concept": "Waa-focus: what the sentence is about",
             "pattern": "… waa … (as for …)",
             "examples": [
                 {"target": "Magacaygu waa …", "roman": "mah-gah-AH-ee-goo wah", "gloss": "my name is … (my-name waa …)"},
                 {"target": "Waa maxay?", "roman": "wah mah-HAH-ee", "gloss": "what is this? (waa what?)"},
                 {"target": "Waa imisa?", "roman": "wah ee-mee-SAH", "gloss": "how much is it? (waa how-much?)"}],
             "exceptions": ["Waa spotlights the topic — verbs agree with what follows it."],
             "learnerNote": "Waa spotlights the sentence's star — names, prices, and questions.",
             "commonMistakes": ["Skipping waa (sounds bare)", "Waa in the wrong slot"]},
            {"concept": "Negation with ma",
             "pattern": "ma + verb",
             "examples": [
                 {"target": "Ma fahmin", "roman": "mah FAH-meen", "gloss": "I don't understand"},
                 {"target": "Ma i caawin kartaa?", "roman": "mah ee ah-WEEN kahr-TAH", "gloss": "can you help me?"},
                 {"target": "Maya", "roman": "MAH-yah", "gloss": "no"}],
             "exceptions": ["Maya (no) answers; ma negates verbs."],
             "learnerNote": "Ma directly before the verb — the whole negative system in one word.",
             "commonMistakes": ["maya to negate verbs (use ma)", "Post-verb ma"]},
            {"concept": "Questions: maxaa, xaggee, imisa",
             "pattern": "maxaa (what) · xaggee (where) · imisa (how much)",
             "examples": [
                 {"target": "Waa maxay?", "roman": "wah mah-HAH-ee", "gloss": "what is this?"},
                 {"target": "… xaggee?", "roman": "hhah-GEH", "gloss": "where is …?"},
                 {"target": "Waa imisa?", "roman": "wah ee-mee-SAH", "gloss": "how much is it?"}],
             "exceptions": ["Maxaa cusub? (what's new?) opens small talk."],
             "learnerNote": "Maxaa points at things, xaggee at places, imisa at prices.",
             "commonMistakes": ["maxaa/xaggee swaps", "English word order"]},
        ],
    },
}
