# -*- coding: utf-8 -*-
"""194-country program, batch C1b — Marshall Islands, Kiribati, Tuvalu (authored, not MT).

24 words + 12 phrases + 4 grammar concepts per pack, BETA starter reference.
Hindi stays the only PRODUCTION language. Spellings simplified to plain Latin
(Marshallese/Kiribati special letters shown in standard form in romance notes).
"""

EXTRA_PACKS_194_OC1B = {
    "mh": {
        "name": "Marshallese", "native": "Kajin Majel",
        "about": ("Marshallese (Kajin Majel) is spoken by about 60,000 people in the Marshall Islands. This starter "
                  "pack covers greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for the Marshall Islands. Spelling here is simplified plain Latin."),
        "words": [
            ("na", "nah", "I", "pronoun", "people"),
            ("kwe", "kweh", "you", "pronoun", "people"),
            ("e", "eh", "he / she", "pronoun", "people"),
            ("eta", "EH-tah", "name", "noun", "people"),
            ("kora", "KOH-rah", "woman", "noun", "people"),
            ("dren", "dehrn", "water", "noun", "essentials"),
            ("mone", "MOH-neh", "food", "noun", "essentials"),
            ("mweo", "mweh-OH", "house", "noun", "home"),
            ("bilawa", "bee-LAH-wah", "bread", "noun", "food"),
            ("awa", "AH-wah", "time / hour", "noun", "time"),
            ("ran", "rahn", "day", "noun", "time"),
            ("bon", "bohng", "night", "noun", "time"),
            ("yokwe", "yoh-KWEH", "love", "noun", "people"),
            ("armij", "ahr-MEEJ", "person", "noun", "people"),
            ("emmon", "ehm-MOHN", "good", "adjective", "basics"),
            ("enana", "eh-nah-NAH", "bad (no good)", "adjective", "basics"),
            ("elap", "eh-LAHP", "big", "adjective", "basics"),
            ("dik", "deek", "small", "adjective", "basics"),
            ("aet", "ah-et", "yes", "particle", "essentials"),
            ("jab", "jahb", "no", "particle", "essentials"),
            ("tala", "TAH-lah", "money (dollar)", "noun", "daily"),
            ("buk", "book", "book", "noun", "objects"),
            ("juon", "joo-OHN", "one", "numeral", "basics"),
            ("kommol", "kohm-MOHL", "thanks", "verb", "essentials"),
        ],
        "phrases": [
            ("Yokwe", "yoh-KWEH", "hello", "greetings", "neutral"),
            ("Jibbon", "jeeb-BOHN", "morning", "greetings", "neutral"),
            ("Kommol tata", "kohm-MOHL TAH-tah", "thanks very much", "essentials", "neutral"),
            ("E j et am mour?", "ehj eht ahm moh-oor", "How are you?", "greetings", "informal"),
            ("Etam?", "eh-TAHM", "What's your name?", "greetings", "informal"),
            ("Eta in …", "eh-TAH een", "My name is …", "introductions", "neutral"),
            ("Ta in?", "tah een", "What is this?", "basics", "neutral"),
            ("Jolok ao bwir", "joh-LOHK ah-oh bweer", "excuse me", "problems", "neutral"),
            ("Yokwe", "yoh-KWEH", "goodbye (same word as hello)", "greetings", "neutral"),
            ("Jouj im letok …", "joh-eej eem leh-ee-TOHK", "Please give me …", "survival", "neutral"),
            ("Jete wonan?", "JEH-teh woh-NAHN", "How much is it?", "shopping", "neutral"),
            ("… ewi?", "EH-wee", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns + eta (name)",
             "pattern": "na · kwe · e — introductions built on eta (name)",
             "examples": [
                 {"target": "Eta in …", "roman": "eh-TAH een", "gloss": "my name is …"},
                 {"target": "Etam?", "roman": "eh-TAHM", "gloss": "what is your name? (name-your?)"},
                 {"target": "E j et am mour?", "roman": "ehj eht ahm moh-oor", "gloss": "how are you?"}],
             "exceptions": ["E covers he and she — no gender."],
             "learnerNote": "Eta (name) plus in/am builds introductions — possessives included free.",
             "commonMistakes": ["kwe with elders (soften with jouj)", "Skipping in/am in my/your"]},
            {"concept": "Question roots: won, ewi, ta, naat",
             "pattern": "won (who) · ewi (where) · ta (what) · naat (when)",
             "examples": [
                 {"target": "… ewi?", "roman": "EH-wee", "gloss": "where is …?"},
                 {"target": "Ta in?", "roman": "tah een", "gloss": "what is this?"},
                 {"target": "Jete awa kio?", "roman": "JEH-teh AH-wah kee-oh", "gloss": "what time is it?"}],
             "exceptions": ["Jete (how much/many) pairs with wonan (price) for shopping."],
             "learnerNote": "Won/ewi/ta/naat — four question roots covering who/where/what/when.",
             "commonMistakes": ["ewi/naat swaps", "English word order"]},
            {"concept": "Emmon, enana, ejab-nana",
             "pattern": "emmon (it's good) · enana (it's no good) · ejab nana (not bad)",
             "examples": [
                 {"target": "Emmon", "roman": "ehm-MOHN", "gloss": "it's good"},
                 {"target": "Enana", "roman": "eh-nah-NAH", "gloss": "it's no good"},
                 {"target": "Ejab nana", "roman": "eh-JAHB nah-NAH", "gloss": "it's not bad"}],
             "exceptions": ["Jab (no) answers; ejab negates inside phrases."],
             "learnerNote": "Ejab (not) plus nana (bad) builds 'not bad' — negation by prefix.",
             "commonMistakes": ["jab to negate phrases (use ejab)", "enana for 'no' (use jab)"]},
            {"concept": "Jouj-politeness",
             "pattern": "jouj (please) · ken jouj (welcome) · jouj im letok (give me)",
             "examples": [
                 {"target": "Jouj im letok …", "roman": "joh-eej eem leh-ee-TOHK", "gloss": "please give me …"},
                 {"target": "Ken jouj", "roman": "kehn joh-eej", "gloss": "you're welcome"},
                 {"target": "Jouj", "roman": "joh-eej", "gloss": "please"}],
             "exceptions": ["Jouj softens any request — use it liberally as a learner."],
             "learnerNote": "Jouj opens doors: please, welcome, and give-me all grow from it.",
             "commonMistakes": ["Bare commands (add jouj)", "Ken jouj as please (it means welcome)"]},
        ],
    },
    "gil": {
        "name": "Kiribati", "native": "Te taetae ni Kiribati",
        "about": ("Kiribati (Te taetae ni Kiribati) is spoken by about 120,000 people in Kiribati. This starter pack "
                  "covers greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Kiribati."),
        "words": [
            ("ngai", "ngah-ee", "I", "pronoun", "people"),
            ("ngkoe", "ngoh-eh", "you", "pronoun", "people"),
            ("ngaia", "ngah-ee-ah", "he / she", "pronoun", "people"),
            ("ti", "tee", "we", "pronoun", "people"),
            ("ara", "AH-rah", "name", "noun", "people"),
            ("ran", "rahn", "water", "noun", "essentials"),
            ("kai", "kah-ee", "food", "noun", "essentials"),
            ("auti", "ah-OO-tee", "house", "noun", "home"),
            ("berena", "beh-REH-nah", "bread", "noun", "food"),
            ("tai", "tah-ee", "time", "noun", "time"),
            ("bong", "bohng", "day", "noun", "time"),
            ("bongi", "boh-NGEE", "night", "noun", "time"),
            ("rao", "rah-oh", "friend", "noun", "people"),
            ("kaainga", "kah-ah-ee-NGah", "family", "noun", "people"),
            ("raoiroi", "rah-oy-ROY", "good", "adjective", "basics"),
            ("buakaka", "boo-ah-KAH-kah", "bad", "adjective", "basics"),
            ("bati", "BAH-tee", "big / much", "adjective", "basics"),
            ("kikino", "kee-KEE-noh", "small", "adjective", "basics"),
            ("eng", "ehng", "yes", "particle", "essentials"),
            ("tiaki", "tee-AH-kee", "no", "particle", "essentials"),
            ("mane", "MAH-neh", "money", "noun", "daily"),
            ("boki", "BOH-kee", "book", "noun", "objects"),
            ("aomata", "ah-oh-MAH-tah", "person", "noun", "people"),
            ("ko rabwa", "koh rah-BWAH", "thanks", "verb", "essentials"),
        ],
        "phrases": [
            ("Mauri", "mow-REE", "hello", "greetings", "neutral"),
            ("Mauri", "mow-REE", "good morning (mauri is the all-day greeting)", "greetings", "neutral"),
            ("Ko bati n rab'a", "koh BAH-tee n rah-BAH", "thanks very much", "essentials", "neutral"),
            ("Ko uara?", "koh oo-AH-rah", "How are you?", "greetings", "informal"),
            ("Antai aram?", "ahn-TAH-ee ah-RAHM", "What's your name?", "greetings", "informal"),
            ("Arau …", "ah-RAH-oo", "My name is …", "introductions", "neutral"),
            ("Antai aei?", "ahn-TAH-ee ah-AY-ee", "What is this?", "basics", "neutral"),
            ("I aki ata", "ee AH-kee AH-tah", "I don't understand", "problems", "neutral"),
            ("Ti a bo", "tee ah boh", "goodbye", "greetings", "neutral"),
            ("I tangiria te ran", "ee tah-ngee-REE-ah teh rahn", "I want water", "survival", "neutral"),
            ("Bon te baka", "bohn teh BAH-kah", "It's delicious!", "food", "neutral"),
            ("… ia?", "EE-ah", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "ngai · ngkoe · ngaia · ti",
             "examples": [
                 {"target": "I tangiria te ran", "roman": "ee tah-ngee-REE-ah teh rahn", "gloss": "I want water"},
                 {"target": "Ko uara?", "roman": "koh oo-AH-rah", "gloss": "how are you? (you how?)"},
                 {"target": "Ti a bo", "roman": "tee ah boh", "gloss": "goodbye (we will …)"}],
             "exceptions": ["Ngaia covers he and she — no gender."],
             "learnerNote": "Ko marks 'you' in questions; ti (we) does the farewelling.",
             "commonMistakes": ["ngkoe with elders (soften it)", "Skipping ko in ko-uara"]},
            {"concept": "Te works like 'the'",
             "pattern": "te + noun: te ran · te kai · te ika",
             "examples": [
                 {"target": "Te ran", "roman": "teh rahn", "gloss": "water / the water"},
                 {"target": "Te kai", "roman": "teh kah-ee", "gloss": "food / the food"},
                 {"target": "I tangiria te ran", "roman": "ee tah-ngee-REE-ah teh rahn", "gloss": "I want water"}],
             "exceptions": ["Te ika (fish) and te ni (coconut) complete the food set."],
             "learnerNote": "Te sits before nouns like English 'the' — te ran, te kai, te ika.",
             "commonMistakes": ["Dropping te (sounds bare)", "Te on names"]},
            {"concept": "Tangira: want and love",
             "pattern": "I tangiria + te-noun (I want …)",
             "examples": [
                 {"target": "I tangiria te ran", "roman": "ee tah-ngee-REE-ah teh rahn", "gloss": "I want water"},
                 {"target": "I tangiria te kai", "roman": "ee tah-ngee-REE-ah teh kah-ee", "gloss": "I want food"},
                 {"target": "Tangira", "roman": "tah-ngee-RAH", "gloss": "love"}],
             "exceptions": ["Tangiria (want) grows from tangira (love) — wanting is loving-to-have."],
             "learnerNote": "One root for want and love — I tangiria opens every request.",
             "commonMistakes": ["Tangira for want (use tangiria)", "Skipping te after tangiria"]},
            {"concept": "Questions: uara, antai, ia",
             "pattern": "ko uara? (how?) · antai (what?) · ia (where?)",
             "examples": [
                 {"target": "Ko uara?", "roman": "koh oo-AH-rah", "gloss": "how are you?"},
                 {"target": "Antai aram?", "roman": "ahn-TAH-ee ah-RAHM", "gloss": "what is your name?"},
                 {"target": "… ia?", "roman": "EE-ah", "gloss": "where is …?"}],
             "exceptions": ["Antai pairs with ara (name) for introductions."],
             "learnerNote": "Ko opens how-are-you; antai asks what; ia asks where.",
             "commonMistakes": ["antai/ia swaps", "English word order"]},
        ],
    },
    "tvl": {
        "name": "Tuvaluan", "native": "Te tagana Tuvalu",
        "about": ("Tuvaluan is spoken by about 11,000 people in Tuvalu. This starter pack covers greetings, essentials "
                  "and core grammar — a first taste, not a full course. It is the English-medium starting point "
                  "for Tuvalu."),
        "words": [
            ("au", "ah-OO", "I", "pronoun", "people"),
            ("koe", "koh-EH", "you", "pronoun", "people"),
            ("ia", "EE-ah", "he / she", "pronoun", "people"),
            ("tatou", "tah-TOH-oo", "we", "pronoun", "people"),
            ("koutou", "koh-oh-TOH-oo", "you (plural)", "pronoun", "people"),
            ("vai", "vah-ee", "water", "noun", "essentials"),
            ("meakai", "meh-ah-KAH-ee", "food", "noun", "essentials"),
            ("fale", "FAH-leh", "house", "noun", "home"),
            ("falaoa", "fah-lah-OH-ah", "bread", "noun", "food"),
            ("taimi", "tah-ee-MEE", "time", "noun", "time"),
            ("aso", "AH-soh", "day", "noun", "time"),
            ("po", "poh", "night", "noun", "time"),
            ("soa", "SOH-ah", "friend", "noun", "people"),
            ("kaiga", "kah-ee-NGAH", "family", "noun", "people"),
            ("lei", "LAY-ee", "good / fine", "adjective", "basics"),
            ("masei", "mah-SAY-ee", "bad", "adjective", "basics"),
            ("lasi", "LAH-see", "big", "adjective", "basics"),
            ("foliki", "foh-LEE-kee", "small", "adjective", "basics"),
            ("ao", "AH-oh", "yes", "particle", "essentials"),
            ("ikai", "ee-KAH-ee", "no", "particle", "essentials"),
            ("tupe", "TOO-peh", "money", "noun", "daily"),
            ("tusi", "TOO-see", "book", "noun", "objects"),
            ("tagata", "tah-ngah-TAH", "person", "noun", "people"),
            ("fakafetai", "fah-kah-feh-TAH-ee", "thanks", "verb", "essentials"),
        ],
        "phrases": [
            ("Tālofa", "tah-loh-FAH", "hello", "greetings", "neutral"),
            ("Tālofa", "tah-loh-FAH", "good morning (talofa is the all-day greeting)", "greetings", "neutral"),
            ("Fakafetai lasi", "fah-kah-feh-TAH-ee LAH-see", "thanks very much", "essentials", "neutral"),
            ("E ā koe?", "eh ah koh-EH", "How are you?", "greetings", "informal"),
            ("Ko oi tou igoa?", "koh oy toh-oo ee-NGOH-ah", "What's your name?", "greetings", "informal"),
            ("Toku igoa ko …", "TOH-koo ee-NGOH-ah koh", "My name is …", "introductions", "neutral"),
            ("Ko te aa …?", "koh teh AH-ah", "What is …?", "basics", "neutral"),
            ("Tulou", "too-LOH-oo", "sorry / excuse me", "problems", "neutral"),
            ("Tofa", "toh-FAH", "goodbye", "greetings", "neutral"),
            ("Fesoasoani mai!", "feh-soh-ah-soh-AH-nee mah-ee", "Help me!", "survival", "neutral"),
            ("Fakamolemole", "fah-kah-moh-leh-MOH-leh", "please", "shopping", "neutral"),
            ("… i fea?", "ee FEH-ah", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Counting 'you': koe, koulua, koutou",
             "pattern": "koe (one you) · koulua (two) · koutou (many)",
             "examples": [
                 {"target": "E ā koe?", "roman": "eh ah koh-EH", "gloss": "how are you? (one person)"},
                 {"target": "E a koulua?", "roman": "eh ah koh-oh-LOO-ah", "gloss": "how are you two?"},
                 {"target": "E a koutou?", "roman": "eh ah koh-oh-TOH-oo", "gloss": "how are you all?"}],
             "exceptions": ["Au (I) and ia (he/she) complete the pronoun set."],
             "learnerNote": "Tuvaluan counts its yous: one, two, many — greet the group right.",
             "commonMistakes": ["koe to a group (use koutou)", "koutou to one person"]},
            {"concept": "Toku (my) vs tou (your)",
             "pattern": "toku + noun (my) · tou + noun (your)",
             "examples": [
                 {"target": "Toku igoa ko …", "roman": "TOH-koo ee-NGOH-ah koh", "gloss": "my name is …"},
                 {"target": "Ko oi tou igoa?", "roman": "koh oy toh-oo ee-NGOH-ah", "gloss": "what is your name?"},
                 {"target": "Toku fale", "roman": "TOH-koo FAH-leh", "gloss": "my house"}],
             "exceptions": ["Possessives sit BEFORE the noun — toku igoa, never igoa toku."],
             "learnerNote": "Toku (my) vs tou (your) — possessives lead, nouns follow.",
             "commonMistakes": ["toku/tou swaps", "Noun before possessive"]},
            {"concept": "E-questions and E 'lei",
             "pattern": "E ā …? (how?) · E 'lei (fine/well)",
             "examples": [
                 {"target": "E ā koe?", "roman": "eh ah koh-EH", "gloss": "how are you?"},
                 {"target": "E a koutou?", "roman": "eh ah koh-oh-TOH-oo", "gloss": "how are you all?"},
                 {"target": "E 'lei, fakafetai", "roman": "eh LAY-ee fah-kah-feh-TAH-ee", "gloss": "fine, thanks"}],
             "exceptions": ["E 'lei also means 'you're welcome' — fine does double duty."],
             "learnerNote": "E opens how-questions; E 'lei (fine) answers them and welcomes thanks.",
             "commonMistakes": ["Skipping E", "lei for bad (use masei)"]},
            {"concept": "Fakafetai, tulou, fakamolemole",
             "pattern": "fakafetai (thanks) · tulou (sorry) · fakamolemole (please)",
             "examples": [
                 {"target": "Fakafetai lasi", "roman": "fah-kah-feh-TAH-ee LAH-see", "gloss": "thanks very much"},
                 {"target": "Tulou", "roman": "too-LOH-oo", "gloss": "sorry / excuse me"},
                 {"target": "Fakamolemole", "roman": "fah-kah-moh-leh-MOH-leh", "gloss": "please"}],
             "exceptions": ["Lasi (big) intensifies thanks — fakafetai lasi, never lasi fakafetai."],
             "learnerNote": "Thanks, sorry, please — the politeness trio that carries every visit.",
             "commonMistakes": ["fakafetai as please (use fakamolemole)", "Lasi before fakafetai"]},
        ],
    },
}
