# -*- coding: utf-8 -*-
"""194-country program, batch C5 — Eritrea, Ethiopia, Haiti (authored, not MT).

24 words + 12 phrases + 4 grammar concepts per pack, BETA starter reference.
Hindi stays the only PRODUCTION language.
"""

EXTRA_PACKS_194_AF3 = {
    "ti": {
        "name": "Tigrinya", "native": "ትግርኛ",
        "about": ("Tigrinya (ትግርኛ) is spoken by about 9 million people in Eritrea and Ethiopia. This starter pack "
                  "covers greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Eritrea."),
        "words": [
            ("አነ", "ane", "I", "pronoun", "people"),
            ("ንስኻ", "nis'kha", "you (male)", "pronoun", "people"),
            ("ንሱ", "nisu", "he", "pronoun", "people"),
            ("ንሳ", "nisa", "she", "pronoun", "people"),
            ("ንሕና", "nihna", "we", "pronoun", "people"),
            ("ማይ", "may", "water", "noun", "essentials"),
            ("መግቢ", "megbi", "food", "noun", "essentials"),
            ("ቤት", "bet", "house", "noun", "home"),
            ("ባኒ", "bani", "bread", "noun", "food"),
            ("ጊዜ", "gize", "time", "noun", "time"),
            ("መዓልቲ", "me'alti", "day", "noun", "time"),
            ("ለይቲ", "leyti", "night", "noun", "time"),
            ("ፈታዊ", "fetawi", "friend", "noun", "people"),
            ("ስድራቤት", "sidrabet", "family", "noun", "people"),
            ("ሰብ", "seb", "person", "noun", "people"),
            ("ጽቡቕ", "tsubuq", "good", "adjective", "basics"),
            ("ሕሙቕ", "himuq", "bad", "adjective", "basics"),
            ("ብዙሕ", "bizuh", "much / many", "adjective", "basics"),
            ("ንእሽተይ", "ni'ushtey", "small", "adjective", "basics"),
            ("እወ", "ewe", "yes", "particle", "essentials"),
            ("ኣይኮነን", "aykonen", "no (it is not)", "particle", "essentials"),
            ("ገንዘብ", "genzeb", "money", "noun", "daily"),
            ("መጽሓፍ", "metshaf", "book", "noun", "objects"),
            ("የቕንየለይ", "yeqenyeley", "thanks", "verb", "essentials"),
        ],
        "phrases": [
            ("ሰላም", "selam", "hello (peace)", "greetings", "neutral"),
            ("ድሓን ሓዲርካ?", "dhan hadirakha", "good morning (did you wake well?)", "greetings", "neutral"),
            ("የቕንየለይ ብጣዕሚ", "yeqenyeley bta'mi", "thanks very much", "essentials", "neutral"),
            ("ከመይ አለኻ?", "kemey alekha", "How are you? (to a man)", "greetings", "informal"),
            ("ስምካ እንታይ ይበሃል?", "simkha intay yibehal", "What's your name?", "greetings", "informal"),
            ("ስመይ … ይበሃል", "simey … yibehal", "My name is …", "introductions", "neutral"),
            ("እዚ እንታይ እዩ?", "izi intay iyu", "What is this?", "basics", "neutral"),
            ("ኣይርድእን", "ayrid'in", "I don't understand", "problems", "neutral"),
            ("ሰላም ኩን", "selam kun", "goodbye (stay in peace)", "greetings", "neutral"),
            ("እንግሊዝኛ ትዛረብ ዶ?", "Inglizña tizarab do", "Do you speak English?", "survival", "informal"),
            ("ክንደይ?", "kindey", "How much is it?", "shopping", "neutral"),
            ("… ኣበይ?", "abey", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Gendered pronouns",
             "pattern": "ane · nis'kha/nis'khi (you m/f) · nisu/nisa (he/she) · nihna",
             "examples": [
                 {"target": "አነ እዛረብ", "roman": "ane izarab", "gloss": "I speak"},
                 {"target": "ንስኻ ትዛረብ", "roman": "nis'kha tizarab", "gloss": "you speak (male)"},
                 {"target": "ንሕና ንዛረብ", "roman": "nihna nizharab", "gloss": "we speak"}],
             "exceptions": ["You and he/she split by gender — pick m/f forms carefully."],
             "learnerNote": "Pronouns know gender: male and female you/he/she differ.",
             "commonMistakes": ["nis'kha to a woman (use nis'khi)", "nisu for she (use nisa)"]},
            {"concept": "Negation wraps the verb (ay-…-n)",
             "pattern": "ay- + verb + -n",
             "examples": [
                 {"target": "ኣይርድእን", "roman": "ayrid'in", "gloss": "I don't understand"},
                 {"target": "ኣይፈልጥን", "roman": "ayfeltn", "gloss": "I don't know"},
                 {"target": "ኣይኮነን", "roman": "aykonen", "gloss": "it is not / no"}],
             "exceptions": ["Ay- opens and -n closes — both halves are required."],
             "learnerNote": "Negation hugs the verb: ay- in front, -n at the back.",
             "commonMistakes": ["-n dropped (half a negative)", "ay- after the verb"]},
            {"concept": "Kemey-greetings (how?)",
             "pattern": "kemey + alekha/alekhi (how are you m/f)",
             "examples": [
                 {"target": "ከመይ አለኻ?", "roman": "kemey alekha", "gloss": "how are you? (to a man)"},
                 {"target": "ከመይ አለኺ?", "roman": "kemey alekhi", "gloss": "how are you? (to a woman)"},
                 {"target": "ጽቡቕ አለኹ", "roman": "tsubuq alekhu", "gloss": "I'm fine (good I-am)"}],
             "exceptions": ["Selam opens; kemey asks; tsubuq alekhu answers."],
             "learnerNote": "Kemey (how?) greets everyone — match m/f, answer with tsubuq.",
             "commonMistakes": ["alekha to a woman (use alekhi)", "Reply skipped (answer tsubuq alekhu)"]},
            {"concept": "Questions: intay, abey, kindey",
             "pattern": "intay (what) · abey (where) · kindey (how much)",
             "examples": [
                 {"target": "እዚ እንታይ እዩ?", "roman": "izi intay iyu", "gloss": "what is this?"},
                 {"target": "… ኣበይ?", "roman": "abey", "gloss": "where is …?"},
                 {"target": "ክንደይ?", "roman": "kindey", "gloss": "how much is it?"}],
             "exceptions": ["Intay asks what; simkha intay asks your name."],
             "learnerNote": "Intay points at things, abey at places, kindey at prices.",
             "commonMistakes": ["intay/abey swaps", "English word order"]},
        ],
    },
    "am": {
        "name": "Amharic", "native": "አማርኛ",
        "about": ("Amharic (አማርኛ) is spoken by about 30 million people in Ethiopia. This starter pack covers "
                  "greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Ethiopia."),
        "words": [
            ("እኔ", "ine", "I", "pronoun", "people"),
            ("አንተ", "ante", "you (male)", "pronoun", "people"),
            ("እሱ", "isu", "he", "pronoun", "people"),
            ("እሷ", "iswa", "she", "pronoun", "people"),
            ("እኛ", "iña", "we", "pronoun", "people"),
            ("ውሃ", "wuha", "water", "noun", "essentials"),
            ("ምግብ", "migib", "food", "noun", "essentials"),
            ("ቤት", "bet", "house", "noun", "home"),
            ("ዳቦ", "dabo", "bread", "noun", "food"),
            ("ጊዜ", "gize", "time", "noun", "time"),
            ("ቀን", "qen", "day", "noun", "time"),
            ("ሌሊት", "lelit", "night", "noun", "time"),
            ("ጓደኛ", "gwadegna", "friend", "noun", "people"),
            ("ቤተሰብ", "beteseb", "family", "noun", "people"),
            ("ሰው", "sew", "person", "noun", "people"),
            ("ጥሩ", "tiru", "good", "adjective", "basics"),
            ("መጥፎ", "metfo", "bad", "adjective", "basics"),
            ("ትልቅ", "tilq", "big", "adjective", "basics"),
            ("ትንሽ", "tinish", "small", "adjective", "basics"),
            ("አዎ", "awo", "yes", "particle", "essentials"),
            ("አይ", "ay", "no", "particle", "essentials"),
            ("ገንዘብ", "genzeb", "money", "noun", "daily"),
            ("መጽሐፍ", "metshaf", "book", "noun", "objects"),
            ("አመሰግናለሁ", "amesegnalehu", "thanks (I thank)", "verb", "essentials"),
        ],
        "phrases": [
            ("ሰላም", "selam", "hello (peace)", "greetings", "neutral"),
            ("እንደምን አደሩ", "endemin aderu", "good morning", "greetings", "neutral"),
            ("በጣም አመሰግናለሁ", "betam amesegnalehu", "thanks very much", "essentials", "neutral"),
            ("እንደምን ነህ?", "endemin neh", "How are you? (to a man)", "greetings", "informal"),
            ("ስምህ ማን ነው?", "simh man new", "What's your name?", "greetings", "informal"),
            ("ስሜ … ነው", "sime … new", "My name is …", "introductions", "neutral"),
            ("ይህ ምንድን ነው?", "yih mindin new", "What is this?", "basics", "neutral"),
            ("አልገባኝም", "algebagnim", "I don't understand", "problems", "neutral"),
            ("ደህና ሁን", "dehna hun", "goodbye (stay well)", "greetings", "neutral"),
            ("እንግሊዝኛ ትችላለህ?", "Inglizña tichilaleh", "Do you speak English?", "survival", "informal"),
            ("ስንት ነው?", "sint new", "How much is it?", "shopping", "neutral"),
            ("… የት ነው?", "yet new", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Gendered pronouns + verb agreement",
             "pattern": "ine · ante/anchi (you m/f) · isu/iswa (he/she) · iña",
             "examples": [
                 {"target": "እኔ እላለሁ", "roman": "ine ilalehu", "gloss": "I speak (I say)"},
                 {"target": "አንተ ትላለህ", "roman": "ante tilaleh", "gloss": "you speak (male)"},
                 {"target": "እኛ እንላለን", "roman": "iña inilalen", "gloss": "we speak"}],
             "exceptions": ["Verbs agree in gender too — tilaleh (m) vs tilalesh (f)."],
             "learnerNote": "Gender runs through pronouns AND verbs — learn m/f pairs together.",
             "commonMistakes": ["ante to a woman (use anchi)", "isu for she (use iswa)"]},
            {"concept": "Negation wraps the verb (al-…-m)",
             "pattern": "al- + verb + -m",
             "examples": [
                 {"target": "አልገባኝም", "roman": "algebagnim", "gloss": "I don't understand"},
                 {"target": "አላውቅም", "roman": "alawqim", "gloss": "I don't know"},
                 {"target": "አይደለም", "roman": "aydelem", "gloss": "it is not / no"}],
             "exceptions": ["Ay- opens and -m closes — both halves are required."],
             "learnerNote": "Negation hugs the verb: al- in front, -m at the back.",
             "commonMistakes": ["-m dropped (half a negative)", "al- after the verb"]},
            {"concept": "Endemin-greetings (how?)",
             "pattern": "endemin + neh/nesh (how are you m/f)",
             "examples": [
                 {"target": "እንደምን ነህ?", "roman": "endemin neh", "gloss": "how are you? (to a man)"},
                 {"target": "እንደምን ነሽ?", "roman": "endemin nesh", "gloss": "how are you? (to a woman)"},
                 {"target": "ደህና ነኝ", "roman": "dehna negn", "gloss": "I'm fine (well I-am)"}],
             "exceptions": ["Selam opens; endemin asks; dehna negn answers."],
             "learnerNote": "Endemin (how?) greets everyone — match m/f, answer dehna negn.",
             "commonMistakes": ["neh to a woman (use nesh)", "Reply skipped (answer dehna negn)"]},
            {"concept": "Questions: man, mindin, yet, sint",
             "pattern": "man (who) · mindin (what) · yet (where) · sint (how much)",
             "examples": [
                 {"target": "ይህ ምንድን ነው?", "roman": "yih mindin new", "gloss": "what is this?"},
                 {"target": "… የት ነው?", "roman": "yet new", "gloss": "where is …?"},
                 {"target": "ስንት ነው?", "roman": "sint new", "gloss": "how much is it?"}],
             "exceptions": ["New? (is?) closes questions — verbs come last."],
             "learnerNote": "Mindin points at things, yet at places, sint at prices — new? closes.",
             "commonMistakes": ["mindin/yet swaps", "English word order (verb last!)"]},
        ],
    },
    "ht": {
        "name": "Haitian Creole", "native": "Kreyòl Ayisyen",
        "about": ("Haitian Creole (Kreyòl Ayisyen) is spoken by about 12 million people in Haiti. This starter pack "
                  "covers greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Haiti."),
        "words": [
            ("mwen", "mwen", "I", "pronoun", "people"),
            ("ou", "oo", "you", "pronoun", "people"),
            ("li", "lee", "he / she", "pronoun", "people"),
            ("nou", "noo", "we", "pronoun", "people"),
            ("yo", "yoh", "they", "pronoun", "people"),
            ("dlo", "dloh", "water", "noun", "essentials"),
            ("manje", "mahn-JEH", "food", "noun", "essentials"),
            ("kay", "kah-ee", "house", "noun", "home"),
            ("pen", "pehn", "bread", "noun", "food"),
            ("lè", "leh", "time", "noun", "time"),
            ("jou", "zhoo", "day", "noun", "time"),
            ("lanuit", "lah-NWEE", "night", "noun", "time"),
            ("zanmi", "zahn-MEE", "friend", "noun", "people"),
            ("fanmi", "fahn-MEE", "family", "noun", "people"),
            ("moun", "moon", "person", "noun", "people"),
            ("bon", "bohn", "good", "adjective", "basics"),
            ("move", "moh-VEH", "bad", "adjective", "basics"),
            ("gwo", "gwoh", "big", "adjective", "basics"),
            ("piti", "pee-TEE", "small", "adjective", "basics"),
            ("wi", "wee", "yes", "particle", "essentials"),
            ("non", "nohn", "no", "particle", "essentials"),
            ("lajan", "lah-ZHAHN", "money", "noun", "daily"),
            ("liv", "leev", "book", "noun", "objects"),
            ("mèsi", "meh-SEE", "thanks", "verb", "essentials"),
        ],
        "phrases": [
            ("Bonjou", "bohn-ZHOO", "hello", "greetings", "neutral"),
            ("Bonjou", "bohn-ZHOO", "good morning", "greetings", "neutral"),
            ("Mèsi anpil", "meh-SEE ahn-PEEL", "thanks very much", "essentials", "neutral"),
            ("Kijan ou ye?", "kee-ZHAHN oo yeh", "How are you?", "greetings", "informal"),
            ("Kijan ou rele?", "kee-ZHAHN oo reh-LEH", "What's your name?", "greetings", "informal"),
            ("Mwen rele …", "mwen reh-LEH", "My name is …", "introductions", "neutral"),
            ("Kisa sa ye?", "kee-SAH sah yeh", "What is this?", "basics", "neutral"),
            ("Mwen pa konprann", "mwen pah kohn-PRAHN", "I don't understand", "problems", "neutral"),
            ("Orevwa", "oh-reh-VWAH", "goodbye", "greetings", "neutral"),
            ("Èske ou pale anglè?", "ehs-KEH oo pah-LEH ahn-GLEH", "Do you speak English?", "survival", "informal"),
            ("Konbyen?", "kohn-BYEHN", "How much is it?", "shopping", "neutral"),
            ("Kibò … ye?", "kee-BOH yeh", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Pronouns never change",
             "pattern": "mwen · ou · li · nou · yo",
             "examples": [
                 {"target": "Mwen pale", "roman": "mwen pah-LEH", "gloss": "I speak"},
                 {"target": "Ou pale", "roman": "oo pah-LEH", "gloss": "you speak"},
                 {"target": "Yo pale", "roman": "yoh pah-LEH", "gloss": "they speak"}],
             "exceptions": ["Li covers he, she and it — no gender anywhere."],
             "learnerNote": "One pronoun set does everything — no cases, no gender, no conjugation.",
             "commonMistakes": ["French je/tu (use mwen/ou)", "Li split by gender (don't)"]},
            {"concept": "Negation with pa",
             "pattern": "pa + verb",
             "examples": [
                 {"target": "Mwen pa konprann", "roman": "mwen pah kohn-PRAHN", "gloss": "I don't understand"},
                 {"target": "Mwen pa pale", "roman": "mwen pah pah-LEH", "gloss": "I don't speak"},
                 {"target": "Non", "roman": "nohn", "gloss": "no"}],
             "exceptions": ["Non (no) answers; pa negates verbs."],
             "learnerNote": "Pa sits right before the verb — the whole negative system in one word.",
             "commonMistakes": ["non to negate verbs (use pa)", "Post-verb pa"]},
            {"concept": "Tense markers: ap, te, a",
             "pattern": "ap (doing) · te (did) · a (will)",
             "examples": [
                 {"target": "Mwen ap pale", "roman": "mwen ahp pah-LEH", "gloss": "I am speaking"},
                 {"target": "Mwen te pale", "roman": "mwen teh pah-LEH", "gloss": "I spoke"},
                 {"target": "Mwen a pale", "roman": "mwen ah pah-LEH", "gloss": "I will speak"}],
             "exceptions": ["Bare verb = present habit or completed past — markers add precision."],
             "learnerNote": "Verbs never change — little markers carry past, present and future.",
             "commonMistakes": ["Conjugating verbs (never!)", "te/ap swaps (past vs now)"]},
            {"concept": "Questions: kisa, kibò, konbyen, kijan",
             "pattern": "kisa (what) · kibò (where) · konbyen (how much) · kijan (how)",
             "examples": [
                 {"target": "Kisa sa ye?", "roman": "kee-SAH sah yeh", "gloss": "what is this?"},
                 {"target": "Kibò … ye?", "roman": "kee-BOH yeh", "gloss": "where is …?"},
                 {"target": "Konbyen?", "roman": "kohn-BYEHN", "gloss": "how much is it?"}],
             "exceptions": ["Èske opens yes/no questions: Èske ou pale anglè?"],
             "learnerNote": "All question words start with ki- — one sound, every question.",
             "commonMistakes": ["kisa/kibò swaps", "Èske skipped in yes/no questions"]},
        ],
    },
}
