# -*- coding: utf-8 -*-
"""194-country program, batch A3 — Balkans + Baltics (authored, not MT).

24 words + 12 phrases + 4 grammar concepts per pack, BETA starter reference.
Hindi stays the only PRODUCTION language.
"""

EXTRA_PACKS_194_EU3 = {
    "mk": {
        "name": "Macedonian", "native": "македонски",
        "about": ("Macedonian (македонски) is spoken by about 2 million people in North Macedonia. This starter pack "
                  "covers greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for North Macedonia."),
        "words": [
            ("јас", "yahs", "I", "pronoun", "people"),
            ("ти", "tee", "you (informal)", "pronoun", "people"),
            ("тој", "toy", "he", "pronoun", "people"),
            ("таа", "tah", "she", "pronoun", "people"),
            ("ние", "NEE-eh", "we", "pronoun", "people"),
            ("вода", "VOH-dah", "water", "noun", "essentials"),
            ("храна", "KHRAH-nah", "food", "noun", "essentials"),
            ("куќа", "KOO-kyah", "house", "noun", "home"),
            ("леб", "lehp", "bread", "noun", "food"),
            ("време", "VREH-meh", "time", "noun", "time"),
            ("ден", "dehn", "day", "noun", "time"),
            ("ноќ", "nohky", "night", "noun", "time"),
            ("пријател", "pree-YAH-tehl", "friend", "noun", "people"),
            ("семејство", "seh-MAY-stvoh", "family", "noun", "people"),
            ("добар", "DOH-bahr", "good", "adjective", "basics"),
            ("лош", "lohsh", "bad", "adjective", "basics"),
            ("голем", "goh-LEHM", "big", "adjective", "basics"),
            ("мал", "mahl", "small", "adjective", "basics"),
            ("да", "dah", "yes", "particle", "essentials"),
            ("не", "neh", "no", "particle", "essentials"),
            ("пари", "PAH-ree", "money", "noun", "daily"),
            ("книга", "KNEE-gah", "book", "noun", "objects"),
            ("човек", "CHOH-vehk", "person", "noun", "people"),
            ("благодарам", "blah-goh-DAH-rahm", "thank you", "verb", "essentials"),
        ],
        "phrases": [
            ("Здраво", "ZDRAH-voh", "hello (informal)", "greetings", "informal"),
            ("Добар ден", "DOH-bahr dehn", "good day", "greetings", "neutral"),
            ("Благодарам многу", "blah-goh-DAH-rahm MNOH-goo", "thanks a lot", "essentials", "neutral"),
            ("Како си?", "KAH-koh see", "How are you? (informal)", "greetings", "informal"),
            ("Како се викаш?", "KAH-koh seh VEE-kahsh", "What's your name? (informal)", "greetings", "informal"),
            ("Се викам …", "seh VEE-kahm", "My name is …", "introductions", "neutral"),
            ("Што е ова?", "shtoh eh OH-vah", "What is this?", "basics", "neutral"),
            ("Не разбирам", "neh rahz-BEE-rahm", "I don't understand", "problems", "neutral"),
            ("Довидување", "doh-vee-DOO-vah-nyeh", "goodbye", "greetings", "neutral"),
            ("Зборувате ли англиски?", "zboh-ROO-vah-teh lee AHN-glee-skee", "Do you speak English? (formal)", "survival", "formal"),
            ("Колку чини?", "KOHL-koo CHEE-nee", "How much is it?", "shopping", "neutral"),
            ("Каде е …?", "KAH-deh eh", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "јас · ти · тој/таа · ние · вие · тие",
             "examples": [
                 {"target": "јас зборувам", "roman": "yahs zboh-ROO-vahm", "gloss": "I speak"},
                 {"target": "ти зборуваш", "roman": "tee zboh-ROO-vahsh", "gloss": "you speak"},
                 {"target": "ние зборуваме", "roman": "NEE-eh zboh-roo-VAH-meh", "gloss": "we speak"}],
             "exceptions": ["Pronouns drop: зборувам alone means I speak."],
             "learnerNote": "Endings carry the subject, so pronouns are optional — use them for emphasis.",
             "commonMistakes": ["Overusing јас", "ти with strangers (use вие)"]},
            {"concept": "Three-way attached articles",
             "pattern": "човекот (this man) · човеков · човекон (that far man)",
             "examples": [
                 {"target": "човекот", "roman": "choh-VEH-koht", "gloss": "the man (near)"},
                 {"target": "жената", "roman": "ZHEH-nah-tah", "gloss": "the woman"},
                 {"target": "детето", "roman": "deh-TEH-toh", "gloss": "the child"}],
             "exceptions": ["Macedonian articles mark distance: -от near, -он far — unique in Slavic."],
             "learnerNote": "Articles attach to the end AND point near/far — start with -от/-та/-то forms.",
             "commonMistakes": ["Articles before nouns", "Ignoring the distance distinction"]},
            {"concept": "Negation with не",
             "pattern": "не + verb",
             "examples": [
                 {"target": "не разбирам", "roman": "neh rahz-BEE-rahm", "gloss": "I don't understand"},
                 {"target": "не знам", "roman": "neh znahm", "gloss": "I don't know"},
                 {"target": "не зборувам", "roman": "neh zboh-ROO-vahm", "gloss": "I don't speak"}],
             "exceptions": ["'There is no' is нема."],
             "learnerNote": "Не directly before the verb — the same simple pattern as Bulgarian.",
             "commonMistakes": ["Post-verb не", "Confusing не with ниту (neither)"]},
            {"concept": "Question words",
             "pattern": "што (what) · каде (where) · кога (when) · зошто (why) · кој (who)",
             "examples": [
                 {"target": "Каде е станицата?", "roman": "KAH-deh eh stah-NEE-tsah-tah", "gloss": "Where is the station?"},
                 {"target": "Колку чини?", "roman": "KOHL-koo CHEE-nee", "gloss": "How much is it?"},
                 {"target": "Што е ова?", "roman": "shtoh eh OH-vah", "gloss": "What is this?"}],
             "exceptions": ["Ли turns statements into yes/no questions: Зборувате ли?"],
             "learnerNote": "Каде (where) is the famous Macedonian marker — neighbours say gdje/gde/kъде.",
             "commonMistakes": ["Forgetting ли", "Што/каде swaps"]},
        ],
    },
    "sq": {
        "name": "Albanian", "native": "shqip",
        "about": ("Albanian (shqip) is spoken by about 7 million people in Albania, Kosovo and North Macedonia. "
                  "This starter pack covers greetings, essentials and core grammar — a first taste, not a full "
                  "course. It is the English-medium starting point for Albania."),
        "words": [
            ("unë", "OO-nuh", "I", "pronoun", "people"),
            ("ti", "tee", "you (informal)", "pronoun", "people"),
            ("ai", "ahy", "he", "pronoun", "people"),
            ("ajo", "AH-yoh", "she", "pronoun", "people"),
            ("ne", "neh", "we", "pronoun", "people"),
            ("ujë", "OO-yuh", "water", "noun", "essentials"),
            ("ushqim", "oosh-KEEM", "food", "noun", "essentials"),
            ("shtëpi", "shtuh-PEE", "house / home", "noun", "home"),
            ("bukë", "BOO-kuh", "bread", "noun", "food"),
            ("kohë", "KOH-huh", "time", "noun", "time"),
            ("ditë", "DEE-tuh", "day", "noun", "time"),
            ("natë", "NAH-tuh", "night", "noun", "time"),
            ("mik", "meek", "friend", "noun", "people"),
            ("familje", "fah-MEEL-yeh", "family", "noun", "people"),
            ("mirë", "MEE-ruh", "good", "adjective", "basics"),
            ("keq", "kehk", "bad", "adjective", "basics"),
            ("madh", "mahdh", "big", "adjective", "basics"),
            ("vogël", "VOH-guhl", "small", "adjective", "basics"),
            ("po", "poh", "yes", "particle", "essentials"),
            ("jo", "yoh", "no", "particle", "essentials"),
            ("para", "pah-RAH", "money", "noun", "daily"),
            ("libër", "lee-BUHR", "book", "noun", "objects"),
            ("njeri", "NYEH-ree", "person", "noun", "people"),
            ("faleminderit", "fah-leh-meen-DEH-reet", "thank you", "verb", "essentials"),
        ],
        "phrases": [
            ("Përshëndetje", "puhr-shuhn-DEHT-yeh", "hello (formal)", "greetings", "formal"),
            ("Mirëdita", "mee-ruh-DEE-tah", "good day", "greetings", "neutral"),
            ("Faleminderit shumë", "fah-leh-meen-DEH-reet SHOO-muh", "thank you very much", "essentials", "neutral"),
            ("Si je?", "see yeh", "How are you? (informal)", "greetings", "informal"),
            ("Si quhesh?", "see KOO-hehsh", "What's your name? (informal)", "greetings", "informal"),
            ("Quhem …", "KOO-hehm", "My name is … (I call myself)", "introductions", "neutral"),
            ("Çfarë është kjo?", "chfahr uhsh-TUH kyoh", "What is this?", "basics", "neutral"),
            ("Nuk kuptoj", "nook KOOP-toy", "I don't understand", "problems", "neutral"),
            ("Mirupafshim", "mee-roo-PAHF-sheem", "goodbye (see you again)", "greetings", "neutral"),
            ("Flisni anglisht?", "FLEES-nee ahn-GLEESHT", "Do you speak English? (formal)", "survival", "formal"),
            ("Sa kushton?", "sah KOOSH-tohn", "How much is it?", "shopping", "neutral"),
            ("Ku është …?", "koo uhsh-TUH", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "unë · ti · ai/ajo · ne · ju · ata/ato",
             "examples": [
                 {"target": "unë flas", "roman": "OO-nuh flahs", "gloss": "I speak"},
                 {"target": "ti flet", "roman": "tee fleht", "gloss": "you speak"},
                 {"target": "ne flasim", "roman": "neh flah-SEEM", "gloss": "we speak"}],
             "exceptions": ["Ju is formal singular and plural."],
             "learnerNote": "Endings carry person, so pronouns drop — Albanian verbs do heavy lifting.",
             "commonMistakes": ["Overusing unë", "ti with strangers"]},
            {"concept": "Definite articles attach",
             "pattern": "mik → miku · shtëpi → shtëpia · ujë → uji",
             "examples": [
                 {"target": "miku", "roman": "MEE-koo", "gloss": "the friend"},
                 {"target": "shtëpia", "roman": "shtuh-PEE-ah", "gloss": "the house"},
                 {"target": "uji", "roman": "OO-yee", "gloss": "the water"}],
             "exceptions": ["Masculine takes -i/-u, feminine -a/-ja — learn with each noun."],
             "learnerNote": "Like Romanian and Bulgarian, Albanian glues the article to the END of the noun.",
             "commonMistakes": ["Articles before nouns", "Miku vs mik (indefinite) mix-ups"]},
            {"concept": "Negation with nuk / s-",
             "pattern": "nuk + verb (present) · s- + verb (some forms)",
             "examples": [
                 {"target": "nuk kuptoj", "roman": "nook KOOP-toy", "gloss": "I don't understand"},
                 {"target": "nuk e di", "roman": "nook eh dee", "gloss": "I/he doesn't know"},
                 {"target": "nuk flas", "roman": "nook flahs", "gloss": "I don't speak"}],
             "exceptions": ["Commands forbid with mos: mos u shqetëso (don't worry)."],
             "learnerNote": "Nuk before the verb negates the present — the form you'll use most.",
             "commonMistakes": ["Jo flas (jo answers, nuk negates)", "Post-verb nuk"]},
            {"concept": "Question words",
             "pattern": "çfarë (what) · ku (where) · kur (when) · pse (why) · kush (who)",
             "examples": [
                 {"target": "Ku është stacioni?", "roman": "koo uhsh-TUH stah-tsyOH-nee", "gloss": "Where is the station?"},
                 {"target": "Sa kushton?", "roman": "sah KOOSH-tohn", "gloss": "How much is it?"},
                 {"target": "Kush je ti?", "roman": "koosh yeh tee", "gloss": "Who are you?"}],
             "exceptions": ["A (really?) can open yes/no questions: A flet…?"],
             "learnerNote": "Question words lead, order stays — intonation does the rest.",
             "commonMistakes": ["Ku/kur swaps", "English helpers"]},
        ],
    },
    "bs": {
        "name": "Bosnian", "native": "bosanski",
        "about": ("Bosnian (bosanski) is spoken by about 2.5 million people in Bosnia and Herzegovina. This starter "
                  "pack covers greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Bosnia and Herzegovina."),
        "words": [
            ("ja", "yah", "I", "pronoun", "people"),
            ("ti", "tee", "you (informal)", "pronoun", "people"),
            ("on", "ohn", "he", "pronoun", "people"),
            ("ona", "OH-nah", "she", "pronoun", "people"),
            ("mi", "mee", "we", "pronoun", "people"),
            ("voda", "VOH-dah", "water", "noun", "essentials"),
            ("hrana", "KHRAH-nah", "food", "noun", "essentials"),
            ("kuća", "KOO-chah", "house", "noun", "home"),
            ("hljeb", "khlyehb", "bread", "noun", "food"),
            ("vrijeme", "VREE-yeh-meh", "time", "noun", "time"),
            ("dan", "dahn", "day", "noun", "time"),
            ("noć", "nohch", "night", "noun", "time"),
            ("prijatelj", "pree-YAH-tehly", "friend", "noun", "people"),
            ("porodica", "poh-ROH-dee-tsah", "family", "noun", "people"),
            ("dobar", "DOH-bahr", "good", "adjective", "basics"),
            ("loš", "lohsh", "bad", "adjective", "basics"),
            ("velik", "veh-LEEK", "big", "adjective", "basics"),
            ("mali", "MAH-lee", "small", "adjective", "basics"),
            ("da", "dah", "yes", "particle", "essentials"),
            ("ne", "neh", "no", "particle", "essentials"),
            ("novac", "NOH-vahts", "money", "noun", "daily"),
            ("knjiga", "KNYEE-gah", "book", "noun", "objects"),
            ("čovjek", "CHOH-vyehk", "person", "noun", "people"),
            ("hvala", "KHVAH-lah", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Zdravo", "ZDRAH-voh", "hello (informal)", "greetings", "informal"),
            ("Dobar dan", "DOH-bahr dahn", "good day", "greetings", "neutral"),
            ("Hvala lijepo", "KHVAH-lah LYEH-poh", "thanks kindly", "essentials", "neutral"),
            ("Kako si?", "KAH-koh see", "How are you? (informal)", "greetings", "informal"),
            ("Kako se zoveš?", "KAH-koh seh ZOH-vehsh", "What's your name? (informal)", "greetings", "informal"),
            ("Zovem se …", "ZOH-vehm seh", "My name is …", "introductions", "neutral"),
            ("Šta je ovo?", "shtah yeh OH-voh", "What is this?", "basics", "neutral"),
            ("Ne razumijem", "neh rah-ZOO-mee-yehm", "I don't understand", "problems", "neutral"),
            ("Doviđenja", "doh-vee-JEH-nyah", "goodbye", "greetings", "neutral"),
            ("Govorite li engleski?", "goh-VOH-ree-teh lee EHN-glehs-kee", "Do you speak English? (formal)", "survival", "formal"),
            ("Koliko košta?", "koh-LEE-koh KOHSH-tah", "How much is it?", "shopping", "neutral"),
            ("Gdje je …?", "gdyeh yeh", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "ja · ti · on/ona · mi · vi · oni/one/ona",
             "examples": [
                 {"target": "ja govorim", "roman": "yah goh-VOH-reem", "gloss": "I speak"},
                 {"target": "ti govoriš", "roman": "tee goh-VOH-reesh", "gloss": "you speak"},
                 {"target": "mi govorimo", "roman": "mee goh-voh-REE-moh", "gloss": "we speak"}],
             "exceptions": ["Vi is formal singular and plural."],
             "learnerNote": "Pronouns drop freely; Bosnian is mutually intelligible with Croatian/Serbian/Montenegrin.",
             "commonMistakes": ["Overusing ja", "ti with strangers"]},
            {"concept": "Ijekavian pronunciation",
             "pattern": "mlijeko · čovjek · vrijeme (ije where Serbian has e)",
             "examples": [
                 {"target": "mlijeko", "roman": "MLEE-yeh-koh", "gloss": "milk (Serbian: mleko)"},
                 {"target": "čovjek", "roman": "CHOH-vyehk", "gloss": "person (Serbian: čovek)"},
                 {"target": "vrijeme", "roman": "VREE-yeh-meh", "gloss": "time (Serbian: vreme)"}],
             "exceptions": ["Not every e becomes ije — learn words as they come."],
             "learnerNote": "The ije sound is Bosnian's audible signature — same words, softer middle.",
             "commonMistakes": ["Forcing ije into every word", "Mixing ekavian and ijekavian randomly"]},
            {"concept": "Negation with ne",
             "pattern": "ne + verb",
             "examples": [
                 {"target": "ne razumijem", "roman": "neh rah-ZOO-mee-yehm", "gloss": "I don't understand"},
                 {"target": "ne znam", "roman": "neh znahm", "gloss": "I don't know"},
                 {"target": "ne govorim", "roman": "neh goh-VOH-reem", "gloss": "I don't speak"}],
             "exceptions": ["Fused: neću (I don't want), nema (there is no), nisam (I am not)."],
             "learnerNote": "Не before the verb, plus the famous fused negatives shared across the region.",
             "commonMistakes": ["Ne sam (say nisam)", "Post-verb ne"]},
            {"concept": "Question words",
             "pattern": "šta (what) · gdje (where) · kada (when) · zašto (why) · ko (who)",
             "examples": [
                 {"target": "Gdje je stanica?", "roman": "gdyeh yeh STAH-nee-tsah", "gloss": "Where is the station?"},
                 {"target": "Koliko košta?", "roman": "koh-LEE-koh KOHSH-tah", "gloss": "How much is it?"},
                 {"target": "Ko je to?", "roman": "koh yeh toh", "gloss": "Who is it?"}],
             "exceptions": ["Li builds yes/no questions: Govorite li?"],
             "learnerNote": "Šta (what) + ijekavian vowels = the Bosnian sound in two details.",
             "commonMistakes": ["Šta/gdje swaps", "Forgetting li"]},
        ],
    },
    "cnr": {
        "name": "Montenegrin", "native": "crnogorski",
        "about": ("Montenegrin (crnogorski) is spoken by about 250,000 people in Montenegro. This starter pack covers "
                  "greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Montenegro."),
        "words": [
            ("ja", "yah", "I", "pronoun", "people"),
            ("ti", "tee", "you (informal)", "pronoun", "people"),
            ("on", "ohn", "he", "pronoun", "people"),
            ("ona", "OH-nah", "she", "pronoun", "people"),
            ("mi", "mee", "we", "pronoun", "people"),
            ("voda", "VOH-dah", "water", "noun", "essentials"),
            ("hrana", "KHRAH-nah", "food", "noun", "essentials"),
            ("kuća", "KOO-chah", "house", "noun", "home"),
            ("hljeb", "khlyehb", "bread", "noun", "food"),
            ("vrijeme", "VREE-yeh-meh", "time", "noun", "time"),
            ("dan", "dahn", "day", "noun", "time"),
            ("noć", "nohch", "night", "noun", "time"),
            ("prijatelj", "pree-YAH-tehly", "friend", "noun", "people"),
            ("porodica", "poh-ROH-dee-tsah", "family", "noun", "people"),
            ("dobar", "DOH-bahr", "good", "adjective", "basics"),
            ("loš", "lohsh", "bad", "adjective", "basics"),
            ("veliki", "veh-LEE-kee", "big", "adjective", "basics"),
            ("mali", "MAH-lee", "small", "adjective", "basics"),
            ("da", "dah", "yes", "particle", "essentials"),
            ("ne", "neh", "no", "particle", "essentials"),
            ("novac", "NOH-vahts", "money", "noun", "daily"),
            ("knjiga", "KNYEE-gah", "book", "noun", "objects"),
            ("čovjek", "CHOH-vyehk", "person", "noun", "people"),
            ("hvala", "KHVAH-lah", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Zdravo", "ZDRAH-voh", "hello (informal)", "greetings", "informal"),
            ("Dobar dan", "DOH-bahr dahn", "good day", "greetings", "neutral"),
            ("Hvala lijepo", "KHVAH-lah LYEH-poh", "thanks kindly", "essentials", "neutral"),
            ("Kako si?", "KAH-koh see", "How are you? (informal)", "greetings", "informal"),
            ("Kako se zoveš?", "KAH-koh seh ZOH-vehsh", "What's your name? (informal)", "greetings", "informal"),
            ("Zovem se …", "ZOH-vehm seh", "My name is …", "introductions", "neutral"),
            ("Što je ovo?", "shtoh yeh OH-voh", "What is this?", "basics", "neutral"),
            ("Ne razumijem", "neh rah-ZOO-mee-yehm", "I don't understand", "problems", "neutral"),
            ("Doviđenja", "doh-vee-JEH-nyah", "goodbye", "greetings", "neutral"),
            ("Govorite li engleski?", "goh-VOH-ree-teh lee EHN-glehs-kee", "Do you speak English? (formal)", "survival", "formal"),
            ("Koliko košta?", "koh-LEE-koh KOHSH-tah", "How much is it?", "shopping", "neutral"),
            ("Gdje je …?", "gdyeh yeh", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "ja · ti · on/ona · mi · vi · oni/one/ona",
             "examples": [
                 {"target": "ja govorim", "roman": "yah goh-VOH-reem", "gloss": "I speak"},
                 {"target": "ti govoriš", "roman": "tee goh-VOH-reesh", "gloss": "you speak"},
                 {"target": "mi govorimo", "roman": "mee goh-voh-REE-moh", "gloss": "we speak"}],
             "exceptions": ["Vi is formal singular and plural."],
             "learnerNote": "Pronouns drop; Montenegrin shares its grammar with Bosnian/Croatian/Serbian.",
             "commonMistakes": ["Overusing ja", "ti with strangers"]},
            {"concept": "Ijekavian + two extra letters",
             "pattern": "ś (soft sh) · ź (soft zh) — ćera → śera (daughter)",
             "examples": [
                 {"target": "śever", "roman": "SYEH-vehr", "gloss": "north (with ś)"},
                 {"target": "iźutra", "roman": "ee-ZYOO-trah", "gloss": "morning (with ź)"},
                 {"target": "čovjek", "roman": "CHOH-vyehk", "gloss": "person (ijekavian)"}],
             "exceptions": ["ś/ź appear mainly in traditional speech; many write sj/zj instead."],
             "learnerNote": "Montenegrin's official alphabet adds ś and ź — the visible badge of the standard.",
             "commonMistakes": ["Ignoring ś/ź in reading", "Overusing them in every word"]},
            {"concept": "Negation with ne",
             "pattern": "ne + verb",
             "examples": [
                 {"target": "ne razumijem", "roman": "neh rah-ZOO-mee-yehm", "gloss": "I don't understand"},
                 {"target": "ne znam", "roman": "neh znahm", "gloss": "I don't know"},
                 {"target": "ne govorim", "roman": "neh goh-VOH-reem", "gloss": "I don't speak"}],
             "exceptions": ["Fused: neću, nema, nijesam (I am not — ijekavian form!)."],
             "learnerNote": "Note nijesam (not nisam) — the ijekavian fingerprint inside grammar itself.",
             "commonMistakes": ["Ne sam (say nijesam)", "Post-verb ne"]},
            {"concept": "Question words",
             "pattern": "što (what) · đe/gdje (where) · kada (when) · zašto (why) · ko (who)",
             "examples": [
                 {"target": "Đe je stanica?", "roman": "dyeh yeh STAH-nee-tsah", "gloss": "Where is the station?"},
                 {"target": "Koliko košta?", "roman": "koh-LEE-koh KOHSH-tah", "gloss": "How much is it?"},
                 {"target": "Ko je to?", "roman": "koh yeh toh", "gloss": "Who is it?"}],
             "exceptions": ["Đe (where) is the Montenegrin shibboleth — neighbours say gdje/gde."],
             "learnerNote": "One word — đe — instantly places a speaker in Montenegro.",
             "commonMistakes": ["Forgetting li in yes/no questions", "Što/đe swaps"]},
        ],
    },
    "lv": {
        "name": "Latvian", "native": "latviešu",
        "about": ("Latvian (latviešu) is spoken by about 1.5 million people in Latvia. This starter pack covers "
                  "greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Latvia."),
        "words": [
            ("es", "ehs", "I", "pronoun", "people"),
            ("tu", "too", "you (informal)", "pronoun", "people"),
            ("viņš", "veensh", "he", "pronoun", "people"),
            ("viņa", "VEE-nyah", "she", "pronoun", "people"),
            ("mēs", "mehs", "we", "pronoun", "people"),
            ("ūdens", "OO-dehns", "water", "noun", "essentials"),
            ("ēdiens", "EH-dee-ehns", "food", "noun", "essentials"),
            ("māja", "MAH-yah", "house / home", "noun", "home"),
            ("maize", "MAH-ee-zeh", "bread", "noun", "food"),
            ("laiks", "lah-eeks", "time", "noun", "time"),
            ("diena", "DEE-eh-nah", "day", "noun", "time"),
            ("nakts", "nahkts", "night", "noun", "time"),
            ("draugs", "drah-oogs", "friend", "noun", "people"),
            ("ģimene", "gee-MEH-neh", "family", "noun", "people"),
            ("labs", "lahbs", "good", "adjective", "basics"),
            ("slikts", "sleekts", "bad", "adjective", "basics"),
            ("liels", "lee-ehls", "big", "adjective", "basics"),
            ("mazs", "mahzs", "small", "adjective", "basics"),
            ("jā", "yah", "yes", "particle", "essentials"),
            ("nē", "neh", "no", "particle", "essentials"),
            ("nauda", "NAH-oo-dah", "money", "noun", "daily"),
            ("grāmata", "grah-MAH-tah", "book", "noun", "objects"),
            ("cilvēks", "TSEEL-vayks", "person", "noun", "people"),
            ("paldies", "pahl-DEE-ehs", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Sveiki", "SVAY-kee", "hello", "greetings", "neutral"),
            ("Labdien", "lahb-DEE-ehn", "good day", "greetings", "neutral"),
            ("Liels paldies", "lee-ehls pahl-DEE-ehs", "big thanks", "essentials", "neutral"),
            ("Kā tev iet?", "kah tew ee-eht", "How are you? (informal)", "greetings", "informal"),
            ("Kā tevi sauc?", "kah TEH-vee sah-oots", "What's your name? (informal)", "greetings", "informal"),
            ("Mani sauc …", "MAH-nee sah-oots", "My name is … (they call me)", "introductions", "neutral"),
            ("Kas tas ir?", "kahs tahs eer", "What is this?", "basics", "neutral"),
            ("Es nesaprotu", "ehs neh-sah-PROH-too", "I don't understand", "problems", "neutral"),
            ("Uz redzēšanos", "ooz rehd-ZEH-shah-nohs", "goodbye (until seeing)", "greetings", "neutral"),
            ("Vai jūs runājat angliski?", "vai yoos ROO-nah-yaht ahng-LEES-kee", "Do you speak English? (formal)", "survival", "formal"),
            ("Cik tas maksā?", "tseeck tahs mahk-SAH", "How much is it?", "shopping", "neutral"),
            ("Kur ir …?", "koor eer", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "es · tu · viņš/viņa · mēs · jūs · viņi/viņas",
             "examples": [
                 {"target": "es runāju", "roman": "ehs ROO-nah-yoo", "gloss": "I speak"},
                 {"target": "tu runā", "roman": "too ROO-nah", "gloss": "you speak"},
                 {"target": "mēs runājam", "roman": "mehs ROO-nah-yahm", "gloss": "we speak"}],
             "exceptions": ["Jūs is formal singular and plural."],
             "learnerNote": "Pronouns drop (runāju = I speak); endings do the work.",
             "commonMistakes": ["Overusing es", "tu with strangers"]},
            {"concept": "Two genders, long vowels matter",
             "pattern": "labs (m) · laba (f) — ā/ē/ī/ū change meaning",
             "examples": [
                 {"target": "labs draugs", "roman": "lahbs drah-oogs", "gloss": "good friend (male)"},
                 {"target": "laba diena", "roman": "LAH-bah DEE-eh-nah", "gloss": "good day (feminine)"},
                 {"target": "liels paldies", "roman": "lee-ehls pahl-DEE-ehs", "gloss": "big thanks"}],
             "exceptions": ["Six cases reshape endings — nominative first."],
             "learnerNote": "Latvian vowels come short and LONG (a vs ā) — length is part of the word.",
             "commonMistakes": ["Ignoring macrons (ā)", "Labs diena (must be laba)"]},
            {"concept": "Negation with ne-",
             "pattern": "ne- prefix on the verb",
             "examples": [
                 {"target": "es nesaprotu", "roman": "ehs neh-sah-PROH-too", "gloss": "I don't understand"},
                 {"target": "es nezinu", "roman": "ehs neh-ZEE-noo", "gloss": "I don't know"},
                 {"target": "es nerunāju", "roman": "ehs neh-ROO-nah-yoo", "gloss": "I don't speak"}],
             "exceptions": ["'It is not' is nav (ne + ir fused)."],
             "learnerNote": "Negation is a prefix: ne- glues onto the verb.",
             "commonMistakes": ["Ne saprotu split in two", "Using nē (no) to negate verbs"]},
            {"concept": "Question words + vai",
             "pattern": "kas (what) · kur (where) · kad (when) · kāpēc (why) · kas (who)",
             "examples": [
                 {"target": "Kur ir stacija?", "roman": "koor eer STAH-tsee-yah", "gloss": "Where is the station?"},
                 {"target": "Cik tas maksā?", "roman": "tseeck tahs mahk-SAH", "gloss": "How much is it?"},
                 {"target": "Vai jūs runājat?", "roman": "vai yoos ROO-nah-yaht", "gloss": "Do you speak?"}],
             "exceptions": ["Vai opens yes/no questions — Latvian's question particle."],
             "learnerNote": "Start yes/no questions with vai; use question words for the rest.",
             "commonMistakes": ["Skipping vai", "Kur/kad swaps"]},
        ],
    },
    "lt": {
        "name": "Lithuanian", "native": "lietuvių",
        "about": ("Lithuanian (lietuvių) is spoken by about 3 million people in Lithuania. This starter pack covers "
                  "greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Lithuania."),
        "words": [
            ("aš", "ahsh", "I", "pronoun", "people"),
            ("tu", "too", "you (informal)", "pronoun", "people"),
            ("jis", "yees", "he", "pronoun", "people"),
            ("ji", "yee", "she", "pronoun", "people"),
            ("mes", "mehs", "we", "pronoun", "people"),
            ("vanduo", "vahn-DWOH", "water", "noun", "essentials"),
            ("maistas", "mah-ees-TAHS", "food", "noun", "essentials"),
            ("namas", "nah-MAHS", "house / home", "noun", "home"),
            ("duona", "DWOH-nah", "bread", "noun", "food"),
            ("laikas", "lah-ee-KAHS", "time", "noun", "time"),
            ("diena", "dee-eh-NAH", "day", "noun", "time"),
            ("naktis", "nahk-TEES", "night", "noun", "time"),
            ("draugas", "drah-oo-GAHS", "friend", "noun", "people"),
            ("šeima", "shay-MAH", "family", "noun", "people"),
            ("geras", "geh-RAHS", "good", "adjective", "basics"),
            ("blogas", "bloh-GAHS", "bad", "adjective", "basics"),
            ("didelis", "dee-deh-LEES", "big", "adjective", "basics"),
            ("mažas", "mah-ZHAHS", "small", "adjective", "basics"),
            ("taip", "tah-eep", "yes", "particle", "essentials"),
            ("ne", "neh", "no", "particle", "essentials"),
            ("pinigai", "pee-nee-GAH-ee", "money", "noun", "daily"),
            ("knyga", "kneeh-GAH", "book", "noun", "objects"),
            ("žmogus", "zh-moh-GOOS", "person", "noun", "people"),
            ("ačiū", "AH-choo", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Sveiki", "SVAY-kee", "hello", "greetings", "neutral"),
            ("Laba diena", "LAH-bah dee-eh-NAH", "good day", "greetings", "neutral"),
            ("Labai ačiū", "lah-BAH-ee AH-choo", "thanks very much", "essentials", "neutral"),
            ("Kaip sekasi?", "kah-eep seh-KAH-see", "How are you? (informal)", "greetings", "informal"),
            ("Kuo vardu?", "kwoh VAHR-doo", "What's (your) name?", "greetings", "informal"),
            ("Mano vardas …", "MAH-noh VAHR-dahs", "My name is …", "introductions", "neutral"),
            ("Kas tai yra?", "kahs tah-ee EE-rah", "What is this?", "basics", "neutral"),
            ("Aš nesuprantu", "ahsh neh-soo-PRAHN-too", "I don't understand", "problems", "neutral"),
            ("Viso gero", "VEE-soh geh-ROH", "goodbye (all good)", "greetings", "neutral"),
            ("Ar kalbate angliškai?", "ahr kahl-BAH-teh ahn-GLEESH-kah-ee", "Do you speak English? (formal)", "survival", "formal"),
            ("Kiek tai kainuoja?", "kee-ehk tah-ee kah-ee-NWOH-yah", "How much is it?", "shopping", "neutral"),
            ("Kur yra …?", "koor EE-rah", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "aš · tu · jis/ji · mes · jūs · jie/jos",
             "examples": [
                 {"target": "aš kalbu", "roman": "ahsh kahl-BOO", "gloss": "I speak"},
                 {"target": "tu kalbi", "roman": "too kahl-BEE", "gloss": "you speak"},
                 {"target": "mes kalbame", "roman": "mehs kahl-BAH-meh", "gloss": "we speak"}],
             "exceptions": ["Jūs is formal singular and plural."],
             "learnerNote": "Lithuanian is famously conservative — its forms echo ancient Indo-European.",
             "commonMistakes": ["Overusing aš", "tu with strangers"]},
            {"concept": "Two genders, seven cases",
             "pattern": "geras (m) · gera (f) — endings shift by case",
             "examples": [
                 {"target": "labas rytas", "roman": "LAH-bahs REE-tahs", "gloss": "good morning (masculine)"},
                 {"target": "laba diena", "roman": "LAH-bah dee-eh-NAH", "gloss": "good day (feminine)"},
                 {"target": "laba naktis", "roman": "LAH-bah nahk-TEES", "gloss": "good night (feminine)"}],
             "exceptions": ["Seven cases — beginners live in nominative + accusative."],
             "learnerNote": "Nouns decline richly; adjectives (-as/-a) agree — patterns first, cases later.",
             "commonMistakes": ["Geras diena (must be gera)", "Ignoring cases in set phrases"]},
            {"concept": "Negation with ne-",
             "pattern": "ne- prefix on the verb",
             "examples": [
                 {"target": "aš nesuprantu", "roman": "ahsh neh-soo-PRAHN-too", "gloss": "I don't understand"},
                 {"target": "aš nežinau", "roman": "ahsh neh-zhee-NAH-oo", "gloss": "I don't know"},
                 {"target": "aš nekalbu", "roman": "ahsh neh-kahl-BOO", "gloss": "I don't speak"}],
             "exceptions": ["'It is not' is nėra (ne + yra fused)."],
             "learnerNote": "Negation is a prefix glued to the verb — one piece, always.",
             "commonMistakes": ["Ne suprantu split", "Using ne like English not"]},
            {"concept": "Question words + ar",
             "pattern": "kas (what) · kur (where) · kada (when) · kodėl (why) · kas (who)",
             "examples": [
                 {"target": "Kur yra stotis?", "roman": "koor EE-rah stoh-TEES", "gloss": "Where is the station?"},
                 {"target": "Kiek tai kainuoja?", "roman": "kee-ehk tah-ee kah-ee-NWOH-yah", "gloss": "How much is it?"},
                 {"target": "Ar kalbate?", "roman": "ahr kahl-BAH-teh", "gloss": "Do you speak?"}],
             "exceptions": ["Ar opens yes/no questions — Lithuanian's question particle."],
             "learnerNote": "Ar at the start signals a yes/no question; question words handle the rest.",
             "commonMistakes": ["Skipping ar", "Kur/kada swaps"]},
        ],
    },
    "et": {
        "name": "Estonian", "native": "eesti",
        "about": ("Estonian (eesti) is spoken by about 1 million people in Estonia. This starter pack covers greetings, "
                  "essentials and core grammar — a first taste, not a full course. It is the English-medium "
                  "starting point for Estonia."),
        "words": [
            ("mina", "MEE-nah", "I", "pronoun", "people"),
            ("sina", "SEE-nah", "you (informal)", "pronoun", "people"),
            ("tema", "TEH-mah", "he / she", "pronoun", "people"),
            ("meie", "MAY-yeh", "we", "pronoun", "people"),
            ("teie", "TAY-yeh", "you (plural/formal)", "pronoun", "people"),
            ("vesi", "VEH-see", "water", "noun", "essentials"),
            ("toit", "toyt", "food", "noun", "essentials"),
            ("maja", "MAH-yah", "house", "noun", "home"),
            ("leib", "layb", "bread", "noun", "food"),
            ("aeg", "ah-eeg", "time", "noun", "time"),
            ("päev", "PAH-ev", "day", "noun", "time"),
            ("öö", "ur", "night", "noun", "time"),
            ("sõber", "SUHR-behr", "friend", "noun", "people"),
            ("perekond", "PEH-reh-kohnd", "family", "noun", "people"),
            ("hea", "HEH-ah", "good", "adjective", "basics"),
            ("halb", "hahlb", "bad", "adjective", "basics"),
            ("suur", "soor", "big", "adjective", "basics"),
            ("väike", "VAH-ee-keh", "small", "adjective", "basics"),
            ("jah", "yah", "yes", "particle", "essentials"),
            ("ei", "ay", "no", "particle", "essentials"),
            ("raha", "RAH-hah", "money", "noun", "daily"),
            ("raamat", "RAH-mahht", "book", "noun", "objects"),
            ("inimene", "EE-nee-meh-neh", "person", "noun", "people"),
            ("aitäh", "ah-ee-TAH", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Tere", "TEH-reh", "hello", "greetings", "neutral"),
            ("Tere hommikust", "TEH-reh HOHM-mee-koost", "good morning", "greetings", "neutral"),
            ("Suur aitäh", "soor ah-ee-TAH", "big thanks", "essentials", "neutral"),
            ("Kuidas läheb?", "KOO-ee-dahs LAH-hehb", "How are you? / How goes it?", "greetings", "informal"),
            ("Mis su nimi on?", "mees soo NEE-mee ohn", "What's your name? (informal)", "greetings", "informal"),
            ("Minu nimi on …", "MEE-noo NEE-mee ohn", "My name is …", "introductions", "neutral"),
            ("Mis see on?", "mees seh ohn", "What is this?", "basics", "neutral"),
            ("Ma ei saa aru", "mah ay sah AH-roo", "I don't understand", "problems", "neutral"),
            ("Nägemist", "NAH-geh-meest", "goodbye (until seeing)", "greetings", "neutral"),
            ("Kas te räägite inglise keelt?", "kahs teh RAH-geh-teh EENG-lee-seh kaylt", "Do you speak English? (formal)", "survival", "formal"),
            ("Kui palju see maksab?", "koo-ee PAHL-yoo seh MAHK-sahb", "How much is this?", "shopping", "neutral"),
            ("Kus on …?", "koos ohn", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns (one he/she)",
             "pattern": "mina · sina · tema · meie · teie · nemad",
             "examples": [
                 {"target": "mina räägin", "roman": "MEE-nah RAH-geen", "gloss": "I speak"},
                 {"target": "sina räägid", "roman": "SEE-nah RAH-geed", "gloss": "you speak"},
                 {"target": "meie räägime", "roman": "MAY-yeh RAH-gee-meh", "gloss": "we speak"}],
             "exceptions": ["Spoken Estonian shortens: ma (I), sa (you) — mina/sina always correct."],
             "learnerNote": "Tema covers he and she — no gender, like Finnish.",
             "commonMistakes": ["Hunting for she (none)", "Spoken ma/sa in formal writing"]},
            {"concept": "Fourteen cases, three lengths",
             "pattern": "maja → majas (in) → majast (from) — consonants come short/long/overlong",
             "examples": [
                 {"target": "majas", "roman": "MAH-yahs", "gloss": "in the house (-s = in)"},
                 {"target": "vees", "roman": "vays", "gloss": "in the water"},
                 {"target": "Tallinnas", "roman": "TAHL-leen-nahs", "gloss": "in Tallinn"}],
             "exceptions": ["Quantity (length) changes meaning: koli/kolli/kooli are three words."],
             "learnerNote": "Endings replace prepositions; start with -s (in) and -st (from).",
             "commonMistakes": ["in majas (double marking)", "Ignoring consonant length"]},
            {"concept": "Negation with ei",
             "pattern": "ei + verb stem (all persons)",
             "examples": [
                 {"target": "ma ei saa aru", "roman": "mah ay sah AH-roo", "gloss": "I don't understand"},
                 {"target": "ma ei tea", "roman": "mah ay TEH-ah", "gloss": "I don't know"},
                 {"target": "ta ei räägi", "roman": "tah ay RAH-gee", "gloss": "he/she doesn't speak"}],
             "exceptions": ["Unlike Finnish, ei never conjugates — one form for everyone."],
             "learnerNote": "Ei is frozen: same word for I/you/he/we — simpler than Finnish negation.",
             "commonMistakes": ["Conjugating ei (don't)", "Finnish-style en/et forms"]},
            {"concept": "Questions with kas + question words",
             "pattern": "mis (what) · kus (where) · millal (when) · miks (why) · kes (who)",
             "examples": [
                 {"target": "Kus on jaam?", "roman": "koos ohn YAHM", "gloss": "Where is the station?"},
                 {"target": "Kui palju?", "roman": "koo-ee PAHL-yoo", "gloss": "How much?"},
                 {"target": "Kas te räägite?", "roman": "kahs teh RAH-gee-teh", "gloss": "Do you speak?"}],
             "exceptions": ["Kas opens yes/no questions — Estonian's question particle."],
             "learnerNote": "Kas first for yes/no; question words otherwise; order stays flat.",
             "commonMistakes": ["Skipping kas", "Kus/millal swaps"]},
        ],
    },
}
