# -*- coding: utf-8 -*-
"""194-country program, batch B1 — Central Asia + Mongolia + Myanmar + Cambodia (authored, not MT).

24 words + 12 phrases + 4 grammar concepts per pack, BETA starter reference.
Hindi stays the only PRODUCTION language.
"""

EXTRA_PACKS_194_AS1 = {
    "kk": {
        "name": "Kazakh", "native": "қазақша",
        "about": ("Kazakh (қазақша) is spoken by about 13 million people in Kazakhstan. This starter pack covers "
                  "greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Kazakhstan."),
        "words": [
            ("мен", "mehn", "I", "pronoun", "people"),
            ("сен", "sehn", "you (informal)", "pronoun", "people"),
            ("ол", "ohl", "he / she", "pronoun", "people"),
            ("біз", "beez", "we", "pronoun", "people"),
            ("сендер", "sehn-DEHR", "you (plural)", "pronoun", "people"),
            ("су", "soo", "water", "noun", "essentials"),
            ("тамақ", "tah-MAHK", "food", "noun", "essentials"),
            ("үй", "ooy", "house / home", "noun", "home"),
            ("нан", "nahn", "bread", "noun", "food"),
            ("уақыт", "oo-ah-KHUHT", "time", "noun", "time"),
            ("күн", "koon", "day", "noun", "time"),
            ("түн", "toon", "night", "noun", "time"),
            ("дос", "dohs", "friend", "noun", "people"),
            ("отбасы", "oht-bah-SEE", "family", "noun", "people"),
            ("жақсы", "zhahk-SEE", "good", "adjective", "basics"),
            ("жаман", "zhah-MAHN", "bad", "adjective", "basics"),
            ("үлкен", "ool-KEHN", "big", "adjective", "basics"),
            ("кішкентай", "keesh-kehn-TAH-ee", "small", "adjective", "basics"),
            ("иә", "ee-YAH", "yes", "particle", "essentials"),
            ("жоқ", "zhohk", "no", "particle", "essentials"),
            ("ақша", "ahk-SHAH", "money", "noun", "daily"),
            ("кітап", "kee-TAHP", "book", "noun", "objects"),
            ("адам", "ah-DAHM", "person", "noun", "people"),
            ("рақмет", "rahkh-MEHT", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Сәлем", "sah-LEHM", "hello", "greetings", "neutral"),
            ("Қайырлы күн", "kah-yuhr-LEE koon", "good day", "greetings", "neutral"),
            ("Рақмет көп", "rahkh-MEHT kurp", "thanks a lot", "essentials", "neutral"),
            ("Қалың қалай?", "kah-LEENG kah-LAH-ee", "How are you? (informal)", "greetings", "informal"),
            ("Атың кім?", "ah-TEENG keem", "What's your name? (informal)", "greetings", "informal"),
            ("Менің атым …", "meh-NEENG ah-TEEM", "My name is …", "introductions", "neutral"),
            ("Бұл не?", "bool neh", "What is this?", "basics", "neutral"),
            ("Мен түсінбеймін", "mehn too-soon-BAY-meen", "I don't understand", "problems", "neutral"),
            ("Сау бол", "sah-OO bohl", "goodbye (stay well)", "greetings", "neutral"),
            ("Сіз ағылшынша сөйлейсіз бе?", "seez ah-ghuhl-SHEEN-shah soy-lay-SEEZ beh", "Do you speak English? (formal)", "survival", "formal"),
            ("Бұл қанша тұрады?", "bool kahn-SHAH too-rah-DEE", "How much is this?", "shopping", "neutral"),
            ("… қайда?", "kahy-DAH", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns (no gender)",
             "pattern": "мен · сен · ол · біз · сендер · олар",
             "examples": [
                 {"target": "мен сөйлеймін", "roman": "mehn soy-lay-MEEN", "gloss": "I speak"},
                 {"target": "сен сөйлейсің", "roman": "sehn soy-lay-SEENG", "gloss": "you speak"},
                 {"target": "біз сөйлейміз", "roman": "beez soy-lay-MEEZ", "gloss": "we speak"}],
             "exceptions": ["Сіз is formal you (singular and plural)."],
             "learnerNote": "Ол covers he/she/it — Turkic languages have no grammatical gender.",
             "commonMistakes": ["Hunting for gender (none)", "сен with strangers (use сіз)"]},
            {"concept": "Vowel harmony + agglutination",
             "pattern": "үй → үйде (at home) · кітап → кітапта (in the book)",
             "examples": [
                 {"target": "үйде", "roman": "ooy-DEH", "gloss": "at home (front vowels → -de)"},
                 {"target": "кітапта", "roman": "kee-tahp-TAH", "gloss": "in the book (back → -ta)"},
                 {"target": "суда", "roman": "soo-DAH", "gloss": "in the water"}],
             "exceptions": ["Consonant harmony too: -da/-de/-ta/-te by voicing."],
             "learnerNote": "Suffixes harmonise with the word's vowels — endings come in back/front pairs.",
             "commonMistakes": ["Үйда (wrong harmony)", "Ignoring rounded/unrounded pairs"]},
            {"concept": "Negation inside the verb",
             "pattern": "verb stem + ma/me + personal ending",
             "examples": [
                 {"target": "мен түсінбеймін", "roman": "mehn too-soon-BAY-meen", "gloss": "I don't understand"},
                 {"target": "мен білмеймін", "roman": "mehn beel-may-MEEN", "gloss": "I don't know"},
                 {"target": "мен сөйлемеймін", "roman": "mehn soy-leh-may-MEEN", "gloss": "I don't speak"}],
             "exceptions": ["Жоқ (no) answers questions; -ma- negates verbs."],
             "learnerNote": "Negation lives INSIDE the verb as -ma-/-me- — no separate word needed.",
             "commonMistakes": ["Жоқ сөйлеймін (wrong)", "Wrong harmony in -ma/-me"]},
            {"concept": "Question words + ма/ме",
             "pattern": "не (what) · қайда (where) · қашан (when) · неге (why) · кім (who)",
             "examples": [
                 {"target": "Вокзал қайда?", "roman": "vohk-ZAHL kahy-DAH", "gloss": "Where is the station?"},
                 {"target": "Бұл қанша тұрады?", "roman": "bool kahn-SHAH too-rah-DEE", "gloss": "How much is this?"},
                 {"target": "Сіз бе?", "roman": "seez beh", "gloss": "You? (formal, with question particle)"}],
             "exceptions": ["Ма/ме/ба/бе particle turns statements into yes/no questions."],
             "learnerNote": "Question words lead; the little ма/ме particle handles yes/no questions.",
             "commonMistakes": ["Skipping ма/ме", "Қайда/қашан swaps"]},
        ],
    },
    "ky": {
        "name": "Kyrgyz", "native": "кыргызча",
        "about": ("Kyrgyz (кыргызча) is spoken by about 5 million people in Kyrgyzstan. This starter pack covers "
                  "greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Kyrgyzstan."),
        "words": [
            ("мен", "mehn", "I", "pronoun", "people"),
            ("сен", "sehn", "you (informal)", "pronoun", "people"),
            ("ал", "ahl", "he / she", "pronoun", "people"),
            ("биз", "beez", "we", "pronoun", "people"),
            ("силер", "see-LEHR", "you (plural)", "pronoun", "people"),
            ("суу", "soo", "water", "noun", "essentials"),
            ("тамак", "tah-MAHK", "food", "noun", "essentials"),
            ("үй", "ooy", "house / home", "noun", "home"),
            ("нан", "nahn", "bread", "noun", "food"),
            ("убакыт", "oo-bah-KHUHT", "time", "noun", "time"),
            ("күн", "koon", "day", "noun", "time"),
            ("түн", "toon", "night", "noun", "time"),
            ("дос", "dohs", "friend", "noun", "people"),
            ("үй-бүлө", "ooy boo-LUR", "family", "noun", "people"),
            ("жакшы", "zhahk-SHEE", "good", "adjective", "basics"),
            ("жаман", "zhah-MAHN", "bad", "adjective", "basics"),
            ("чоң", "chohng", "big", "adjective", "basics"),
            ("кичинекей", "kee-chee-neh-KAY", "small", "adjective", "basics"),
            ("ооба", "oh-BAH", "yes", "particle", "essentials"),
            ("жок", "zhohk", "no", "particle", "essentials"),
            ("акча", "ahk-CHAH", "money", "noun", "daily"),
            ("китеп", "kee-TEHP", "book", "noun", "objects"),
            ("адам", "ah-DAHM", "person", "noun", "people"),
            ("рахмат", "rahkh-MAHT", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Салам", "sah-LAHM", "hello", "greetings", "neutral"),
            ("Кайырлуу күн", "kah-yuhr-LOO koon", "good day", "greetings", "neutral"),
            ("Чоң рахмат", "chohng rahkh-MAHT", "big thanks", "essentials", "neutral"),
            ("Кандайсың?", "kahn-dah-EE-seeng", "How are you? (informal)", "greetings", "informal"),
            ("Атың ким?", "ah-TEENG keem", "What's your name? (informal)", "greetings", "informal"),
            ("Менин атым …", "meh-NEEN ah-TEEM", "My name is …", "introductions", "neutral"),
            ("Бул эмне?", "bool ehm-NEH", "What is this?", "basics", "neutral"),
            ("Мен түшүнбөймүн", "mehn too-shoon-BOY-moon", "I don't understand", "problems", "neutral"),
            ("Кош бол", "kohsh bohl", "goodbye (stay well)", "greetings", "neutral"),
            ("Сиз англисче сүйлөйсүзбү?", "seez ahn-glees-CHEH soo-ee-loy-sooz-BOO", "Do you speak English? (formal)", "survival", "formal"),
            ("Бул канча турат?", "bool kahn-CHAH too-RAHT", "How much is this?", "shopping", "neutral"),
            ("… кайда?", "kahy-DAH", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns (no gender)",
             "pattern": "мен · сен · ал · биз · силер · алар",
             "examples": [
                 {"target": "мен сүйлөймүн", "roman": "mehn soo-ee-loy-MOON", "gloss": "I speak"},
                 {"target": "сен сүйлөйсүң", "roman": "sehn soo-ee-loy-SOONG", "gloss": "you speak"},
                 {"target": "биз сүйлөйбүз", "roman": "beez soo-ee-loy-BOOZ", "gloss": "we speak"}],
             "exceptions": ["Сиз is formal you (singular and plural)."],
             "learnerNote": "Ал covers he/she/it — no gender, classic Turkic pattern shared with Kazakh.",
             "commonMistakes": ["Gender hunting (none)", "сен with elders (use сиз)"]},
            {"concept": "Vowel harmony + agglutination",
             "pattern": "үй → үйдө (at home) · китеп → китепте (in the book)",
             "examples": [
                 {"target": "үйдө", "roman": "ooy-DUR", "gloss": "at home (rounded harmony → -dө)"},
                 {"target": "китепте", "roman": "kee-tehp-TEH", "gloss": "in the book"},
                 {"target": "сууда", "roman": "soo-DAH", "gloss": "in the water"}],
             "exceptions": ["Kyrgyz harmony is famously thorough — roundedness counts too."],
             "learnerNote": "Suffix vowels copy the word's vowels (back/front AND rounded) — endings come in fours.",
             "commonMistakes": ["Үйдө vs үйда", "Forgetting rounded harmony"]},
            {"concept": "Negation inside the verb",
             "pattern": "stem + ba/be/bo/bö + ending",
             "examples": [
                 {"target": "мен түшүнбөймүн", "roman": "mehn too-shoon-BOY-moon", "gloss": "I don't understand"},
                 {"target": "мен билбейм", "roman": "mehn beel-BAYM", "gloss": "I don't know"},
                 {"target": "мен сүйлөбөйм", "roman": "mehn soo-ee-loh-BOYM", "gloss": "I don't speak"}],
             "exceptions": ["Жок answers questions; -ba- negates inside verbs."],
             "learnerNote": "The negative suffix sits inside the verb and harmonises four ways.",
             "commonMistakes": ["Жок сүйлөймүн (wrong)", "Wrong harmony variant"]},
            {"concept": "Question words + бы/би",
             "pattern": "эмне (what) · кайда (where) · качан (when) · эмне үчүн (why) · ким (who)",
             "examples": [
                 {"target": "Вокзал кайда?", "roman": "vohk-ZAHL kahy-DAH", "gloss": "Where is the station?"},
                 {"target": "Бул канча турат?", "roman": "bool kahn-CHAH too-RAHT", "gloss": "How much is this?"},
                 {"target": "Сизби?", "roman": "seez-BEE", "gloss": "You? (formal, with particle)"}],
             "exceptions": ["Бы/би/бу/бү particle marks yes/no questions (harmonised)."],
             "learnerNote": "Question words lead; the little бы particle turns statements into questions.",
             "commonMistakes": ["Skipping бы", "Кайда/качан swaps"]},
        ],
    },
    "tg": {
        "name": "Tajik", "native": "тоҷикӣ",
        "about": ("Tajik (тоҷикӣ) is spoken by about 8 million people in Tajikistan. This starter pack covers greetings, "
                  "essentials and core grammar — a first taste, not a full course. It is the English-medium "
                  "starting point for Tajikistan."),
        "words": [
            ("ман", "mahn", "I", "pronoun", "people"),
            ("ту", "too", "you (informal)", "pronoun", "people"),
            ("ӯ", "oo", "he / she", "pronoun", "people"),
            ("мо", "moh", "we", "pronoun", "people"),
            ("шумо", "shoo-MOH", "you (plural/formal)", "pronoun", "people"),
            ("об", "ohb", "water", "noun", "essentials"),
            ("хӯрок", "khoor-OHK", "food", "noun", "essentials"),
            ("хона", "khoh-NAH", "house / home", "noun", "home"),
            ("нон", "nohn", "bread", "noun", "food"),
            ("вақт", "vahkt", "time", "noun", "time"),
            ("рӯз", "rooz", "day", "noun", "time"),
            ("шаб", "shahb", "night", "noun", "time"),
            ("дӯст", "doost", "friend", "noun", "people"),
            ("оила", "oh-ee-LAH", "family", "noun", "people"),
            ("хуб", "khoob", "good", "adjective", "basics"),
            ("бад", "bahd", "bad", "adjective", "basics"),
            ("калон", "kah-LOHN", "big", "adjective", "basics"),
            ("хурд", "khoord", "small", "adjective", "basics"),
            ("ҳа", "hah", "yes", "particle", "essentials"),
            ("не", "neh", "no", "particle", "essentials"),
            ("пул", "pool", "money", "noun", "daily"),
            ("китоб", "kee-TOHB", "book", "noun", "objects"),
            ("одам", "oh-DAHM", "person", "noun", "people"),
            ("раҳмат", "rahkh-MAHT", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Салом", "sah-LOHM", "hello", "greetings", "neutral"),
            ("Рӯзи хуб", "roo-ZEE khoob", "good day", "greetings", "neutral"),
            ("Раҳмати калон", "rahkh-MAH-tee kah-LOHN", "big thanks", "essentials", "neutral"),
            ("Чӣ хел?", "chee khehl", "How are you? (informal)", "greetings", "informal"),
            ("Номи ту чист?", "noh-MEE too cheest", "What's your name? (informal)", "greetings", "informal"),
            ("Номи ман …", "noh-MEE mahn", "My name is …", "introductions", "neutral"),
            ("Ин чист?", "een cheest", "What is this?", "basics", "neutral"),
            ("Ман нафаҳмам", "mahn nah-fahkh-MAHM", "I don't understand", "problems", "neutral"),
            ("Хайр", "khahy-eehr", "goodbye", "greetings", "neutral"),
            ("Шумо англисӣ медонед?", "shoo-MOH ahn-glee-SEE meh-doh-NEHD", "Do you know English? (formal)", "survival", "formal"),
            ("Ин чанд сӯм?", "een chahnd soom", "How much is this? (somoni)", "shopping", "neutral"),
            ("… дар куҷост?", "dahr koo-JOHST", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns (no gender)",
             "pattern": "ман · ту · ӯ · мо · шумо · онҳо",
             "examples": [
                 {"target": "ман гап мезанам", "roman": "mahn gahp meh-zah-NAHM", "gloss": "I speak (I hit talk)"},
                 {"target": "ту гап мезанӣ", "roman": "too gahp meh-zah-NEE", "gloss": "you speak"},
                 {"target": "мо гап мезанем", "roman": "moh gahp meh-zah-NEHM", "gloss": "we speak"}],
             "exceptions": ["Шумо is formal singular and plural."],
             "learnerNote": "Ӯ covers he/she — Persian-family languages never developed grammatical gender.",
             "commonMistakes": ["Gender hunting (none)", "ту with elders (use шумо)"]},
            {"concept": "The ме- present tense",
             "pattern": "ме- + stem + ending: мезанам (I speak)",
             "examples": [
                 {"target": "мезанам", "roman": "meh-zah-NAHM", "gloss": "I speak / I am speaking"},
                 {"target": "медонам", "roman": "meh-doh-NAHM", "gloss": "I know"},
                 {"target": "мефаҳмам", "roman": "meh-fahkh-MAHM", "gloss": "I understand"}],
             "exceptions": ["'To be' is irregular: ҳастам (I am), ҳастӣ (you are)."],
             "learnerNote": "Ме- marks the present the way English -ing does — one prefix, every verb.",
             "commonMistakes": ["Dropping ме- (changes meaning)", "Regular endings on بودن (to be)"]},
            {"concept": "Negation with на-/не-",
             "pattern": "на- + verb (present: наме-)",
             "examples": [
                 {"target": "ман нафаҳмам", "roman": "mahn nah-fahkh-MAHM", "gloss": "I don't understand"},
                 {"target": "намедонам", "roman": "nah-meh-doh-NAHM", "gloss": "I don't know"},
                 {"target": "намезанам", "roman": "nah-meh-zah-NAHM", "gloss": "I don't speak"}],
             "exceptions": ["Не (no) answers; на- negates verbs."],
             "learnerNote": "На- prefixes the verb (наме- in present) — negation before everything.",
             "commonMistakes": ["Не after the verb", "не for не- (не is the answer word)"]},
            {"concept": "Question words",
             "pattern": "чӣ (what) · куҷо (where) · кай (when) · чаро (why) · кӣ (who)",
             "examples": [
                 {"target": "Вокзал дар куҷост?", "roman": "vohk-ZAHL dahr koo-JOHST", "gloss": "Where is the station?"},
                 {"target": "Ин чанд сӯм?", "roman": "een chahnd soom", "gloss": "How much is this?"},
                 {"target": "Ин чист?", "roman": "een cheest", "gloss": "What is this?"}],
             "exceptions": ["Оё opens formal yes/no questions (often just intonation)."],
             "learnerNote": "Question words lead; intonation rises; чи/кӣ are the core pair.",
             "commonMistakes": ["Куҷо/кай swaps", "English helpers"]},
        ],
    },
    "tk": {
        "name": "Turkmen", "native": "türkmençe",
        "about": ("Turkmen (türkmençe) is spoken by about 7 million people in Turkmenistan. This starter pack covers "
                  "greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Turkmenistan."),
        "words": [
            ("men", "mehn", "I", "pronoun", "people"),
            ("sen", "sehn", "you (informal)", "pronoun", "people"),
            ("ol", "ohl", "he / she", "pronoun", "people"),
            ("biz", "beez", "we", "pronoun", "people"),
            ("siz", "seez", "you (plural/formal)", "pronoun", "people"),
            ("suw", "soo-oo", "water", "noun", "essentials"),
            ("nahar", "nah-HAHR", "food / meal", "noun", "essentials"),
            ("öý", "ooy", "house / home", "noun", "home"),
            ("çörek", "chur-REHK", "bread", "noun", "food"),
            ("wagt", "vahght", "time", "noun", "time"),
            ("gün", "goon", "day", "noun", "time"),
            ("gije", "gee-JEH", "night", "noun", "time"),
            ("dost", "dohst", "friend", "noun", "people"),
            ("maşgala", "mahsh-gah-LAH", "family", "noun", "people"),
            ("gowy", "goh-VEE", "good", "adjective", "basics"),
            ("erbet", "ehr-BEHT", "bad", "adjective", "basics"),
            ("uly", "oo-LEE", "big", "adjective", "basics"),
            ("kiçi", "kee-CHEE", "small", "adjective", "basics"),
            ("hawa", "hah-VAH", "yes", "particle", "essentials"),
            ("ýok", "yohk", "no", "particle", "essentials"),
            ("pul", "pool", "money", "noun", "daily"),
            ("kitap", "kee-TAHP", "book", "noun", "objects"),
            ("adam", "ah-DAHM", "person", "noun", "people"),
            ("sag bol", "sahg bohl", "thanks (stay well)", "verb", "essentials"),
        ],
        "phrases": [
            ("Salam", "sah-LAHM", "hello", "greetings", "neutral"),
            ("Gününiz haýyrly bolsun", "goo-noo-NEEZ haih-uhr-LEE bohl-SOON", "good day (formal)", "greetings", "formal"),
            ("Köp sag bol", "kurp sahg bohl", "thanks a lot", "essentials", "neutral"),
            ("Işiň gowumy?", "ee-SHEENG goh-voo-MEE", "How are you? (informal)", "greetings", "informal"),
            ("Adyň kim?", "ah-DEENG keem", "What's your name? (informal)", "greetings", "informal"),
            ("Meniň adym …", "meh-NEENG ah-DEEM", "My name is …", "introductions", "neutral"),
            ("Bu näme?", "boo nah-MEH", "What is this?", "basics", "neutral"),
            ("Men düşünmeýärin", "mehn doo-shoon-meh-yah-REEN", "I don't understand", "problems", "neutral"),
            ("Hoş gal", "hohsh gahl", "goodbye (stay well)", "greetings", "neutral"),
            ("Siz iňlisçe gepleýärsiňizmi?", "seez eeng-lees-CHEH gehp-leh-yahr-seeng-eez-mee", "Do you speak English? (formal)", "survival", "formal"),
            ("Bu näçe?", "boo nah-CHEH", "How much is this?", "shopping", "neutral"),
            ("… nirede?", "nee-reh-DEH", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns (no gender)",
             "pattern": "men · sen · ol · biz · siz · olar",
             "examples": [
                 {"target": "men gepleýärin", "roman": "mehn gehp-leh-YAH-reen", "gloss": "I speak"},
                 {"target": "sen gepleýärsiň", "roman": "sehn gehp-leh-YAHR-seeng", "gloss": "you speak"},
                 {"target": "biz gepleýäris", "roman": "beez gehp-leh-YAH-rees", "gloss": "we speak"}],
             "exceptions": ["Siz is formal singular and plural."],
             "learnerNote": "Ol covers he/she/it; long vowels (aa, ee) are written and pronounced long.",
             "commonMistakes": ["Ignoring vowel length", "sen with elders"]},
            {"concept": "Vowel harmony + agglutination",
             "pattern": "öý → öýde (at home) · kitap → kitapda (in the book)",
             "examples": [
                 {"target": "öýde", "roman": "ooy-DEH", "gloss": "at home"},
                 {"target": "kitapda", "roman": "kee-tahp-DAH", "gloss": "in the book"},
                 {"target": "suwda", "roman": "soo-oo-DAH", "gloss": "in the water"}],
             "exceptions": ["Rounding harmony is weaker than in Kyrgyz — front/back is the main split."],
             "learnerNote": "Suffixes harmonise back/front with the stem — the Turkic engine, Turkmen-tuned.",
             "commonMistakes": ["Öýda (wrong harmony)", "Short vowels where long ones belong"]},
            {"concept": "Negation inside the verb",
             "pattern": "stem + ma/me + ending",
             "examples": [
                 {"target": "men düşünmeýärin", "roman": "mehn doo-shoon-meh-yah-REEN", "gloss": "I don't understand"},
                 {"target": "men bilmeýärin", "roman": "mehn beel-meh-yah-REEN", "gloss": "I don't know"},
                 {"target": "men geplemeýärin", "roman": "mehn gehp-leh-meh-yah-REEN", "gloss": "I don't speak"}],
             "exceptions": ["Ýok answers questions; -ma- negates inside verbs."],
             "learnerNote": "The negative -ma-/-me- sits inside the verb before the tense marker.",
             "commonMistakes": ["Ýok gepleýärin (wrong)", "Wrong harmony in -ma/-me"]},
            {"concept": "Question words + my/mi",
             "pattern": "näme (what) · nirede (where) · haçan (when) · näme üçin (why) · kim (who)",
             "examples": [
                 {"target": "Wokzal nirede?", "roman": "vohk-ZAHL nee-reh-DEH", "gloss": "Where is the station?"},
                 {"target": "Bu näçe?", "roman": "boo nah-CHEH", "gloss": "How much is this?"},
                 {"target": "Sizmi?", "roman": "seez-MEE", "gloss": "You? (formal, with particle)"}],
             "exceptions": ["The question particle my/mi/mu/mü harmonises four ways."],
             "learnerNote": "Näme (what) is Turkmen's signature word — neighbours say ne/emne.",
             "commonMistakes": ["Skipping the particle", "Nirede/haçan swaps"]},
        ],
    },
    "uz": {
        "name": "Uzbek", "native": "oʻzbekcha",
        "about": ("Uzbek (oʻzbekcha) is spoken by about 35 million people in Uzbekistan and neighbours. This starter "
                  "pack covers greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Uzbekistan."),
        "words": [
            ("men", "mehn", "I", "pronoun", "people"),
            ("sen", "sehn", "you (informal)", "pronoun", "people"),
            ("u", "oo", "he / she", "pronoun", "people"),
            ("biz", "beez", "we", "pronoun", "people"),
            ("siz", "seez", "you (plural/formal)", "pronoun", "people"),
            ("suv", "soov", "water", "noun", "essentials"),
            ("ovqat", "ohv-KAHT", "food", "noun", "essentials"),
            ("uy", "oo-ee", "house / home", "noun", "home"),
            ("non", "nohn", "bread", "noun", "food"),
            ("vaqt", "vahkht", "time", "noun", "time"),
            ("kun", "koon", "day", "noun", "time"),
            ("tun", "toon", "night", "noun", "time"),
            ("doʻst", "dohst", "friend", "noun", "people"),
            ("oila", "oh-ee-LAH", "family", "noun", "people"),
            ("yaxshi", "yahkh-SHEE", "good", "adjective", "basics"),
            ("yomon", "yoh-MOHN", "bad", "adjective", "basics"),
            ("katta", "kaht-TAH", "big", "adjective", "basics"),
            ("kichik", "kee-CHEEK", "small", "adjective", "basics"),
            ("ha", "hah", "yes", "particle", "essentials"),
            ("yoʻq", "yohk", "no", "particle", "essentials"),
            ("pul", "pool", "money", "noun", "daily"),
            ("kitob", "kee-TOHB", "book", "noun", "objects"),
            ("odam", "oh-DAHM", "person", "noun", "people"),
            ("rahmat", "rahkh-MAHT", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Salom", "sah-LOHM", "hello", "greetings", "neutral"),
            ("Xayrli kun", "khahy-EER-lee koon", "good day", "greetings", "neutral"),
            ("Katta rahmat", "kaht-TAH rahkh-MAHT", "big thanks", "essentials", "neutral"),
            ("Qalaysiz?", "kah-lah-EE-seez", "How are you? (formal)", "greetings", "formal"),
            ("Ismingiz nima?", "ees-meen-GEEZ nee-MAH", "What's your name? (formal)", "greetings", "formal"),
            ("Mening ismim …", "meh-NEENG ees-MEEM", "My name is …", "introductions", "neutral"),
            ("Bu nima?", "boo nee-MAH", "What is this?", "basics", "neutral"),
            ("Men tushunmayman", "mehn too-shoon-mahy-MAHN", "I don't understand", "problems", "neutral"),
            ("Xayr", "khahy-EER", "goodbye", "greetings", "neutral"),
            ("Siz inglizcha gapirasizmi?", "seez een-gleez-CHAH gah-pee-rah-seez-MEE", "Do you speak English? (formal)", "survival", "formal"),
            ("Bu qancha?", "boo kahn-CHAH", "How much is this?", "shopping", "neutral"),
            ("… qayerda?", "kah-yehr-DAH", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns (no gender)",
             "pattern": "men · sen · u · biz · siz · ular",
             "examples": [
                 {"target": "men gapiraman", "roman": "mehn gah-pee-rah-MAHN", "gloss": "I speak"},
                 {"target": "sen gapirasan", "roman": "sehn gah-pee-rah-SAHN", "gloss": "you speak"},
                 {"target": "biz gapiramiz", "roman": "beez gah-pee-rah-MEEZ", "gloss": "we speak"}],
             "exceptions": ["Siz is formal singular and plural — default with strangers."],
             "learnerNote": "U covers he/she/it; Uzbek lost most vowel harmony, so suffixes are simpler than Kazakh.",
             "commonMistakes": ["sen with strangers (use siz)", "Kazakh-style harmony guesses"]},
            {"concept": "Agglutination without much harmony",
             "pattern": "uy → uyda (at home) · kitob → kitobda (in the book)",
             "examples": [
                 {"target": "uyda", "roman": "oo-ee-DAH", "gloss": "at home"},
                 {"target": "kitobda", "roman": "kee-tohb-DAH", "gloss": "in the book"},
                 {"target": "suvda", "roman": "soov-DAH", "gloss": "in the water"}],
             "exceptions": ["-da/-ga/-dan endings barely change — Uzbek's famous simplification."],
             "learnerNote": "Uzbek keeps Turkic suffix-stacking but dropped strict harmony — easier endings.",
             "commonMistakes": ["Over-harmonising (unnecessary)", "Prepositions + endings together"]},
            {"concept": "Negation inside the verb",
             "pattern": "stem + ma + ending",
             "examples": [
                 {"target": "men tushunmayman", "roman": "mehn too-shoon-mahy-MAHN", "gloss": "I don't understand"},
                 {"target": "men bilmayman", "roman": "mehn beel-mahy-MAHN", "gloss": "I don't know"},
                 {"target": "men gapirmayman", "roman": "mehn gah-peer-mahy-MAHN", "gloss": "I don't speak"}],
             "exceptions": ["Yoʻq answers; -ma- negates inside verbs."],
             "learnerNote": "The negative -ma- sits inside the verb — same Turkic engine, Uzbek tune.",
             "commonMistakes": ["Yoʻq gapiraman (wrong)", "Wrong vowel in -ma"]},
            {"concept": "Question words + mi",
             "pattern": "nima (what) · qayerda (where) · qachon (when) · nega (why) · kim (who)",
             "examples": [
                 {"target": "Vokzal qayerda?", "roman": "vohk-ZAHL kah-yehr-DAH", "gloss": "Where is the station?"},
                 {"target": "Bu qancha?", "roman": "boo kahn-CHAH", "gloss": "How much is this?"},
                 {"target": "Sizmi?", "roman": "seez-MEE", "gloss": "You? (formal, with particle)"}],
             "exceptions": ["The question particle mi harmonises (mi/my)."],
             "learnerNote": "Nima (what) leads; mi turns statements into yes/no questions.",
             "commonMistakes": ["Skipping mi", "Qayerda/qachon swaps"]},
        ],
    },
    "azj": {
        "name": "Azerbaijani", "native": "azərbaycanca",
        "about": ("Azerbaijani (azərbaycanca) is spoken by about 25 million people in Azerbaijan and Iran. This starter "
                  "pack covers greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Azerbaijan."),
        "words": [
            ("mən", "mehn", "I", "pronoun", "people"),
            ("sən", "sehn", "you (informal)", "pronoun", "people"),
            ("o", "oh", "he / she", "pronoun", "people"),
            ("biz", "beez", "we", "pronoun", "people"),
            ("siz", "seez", "you (plural/formal)", "pronoun", "people"),
            ("su", "soo", "water", "noun", "essentials"),
            ("yemək", "yeh-MAHK", "food", "noun", "essentials"),
            ("ev", "ehv", "house / home", "noun", "home"),
            ("çörək", "chur-RAHK", "bread", "noun", "food"),
            ("vaxt", "vahkh", "time", "noun", "time"),
            ("gün", "goon", "day", "noun", "time"),
            ("gecə", "geh-JEH", "night", "noun", "time"),
            ("dost", "dohst", "friend", "noun", "people"),
            ("ailə", "ah-ee-LAH", "family", "noun", "people"),
            ("yaxşı", "yahkh-SHEE", "good", "adjective", "basics"),
            ("pis", "pees", "bad", "adjective", "basics"),
            ("böyük", "bur-YOOK", "big", "adjective", "basics"),
            ("kiçik", "kee-CHEEK", "small", "adjective", "basics"),
            ("bəli", "beh-LEE", "yes", "particle", "essentials"),
            ("xeyr", "khayr", "no", "particle", "essentials"),
            ("pul", "pool", "money", "noun", "daily"),
            ("kitab", "kee-TAHB", "book", "noun", "objects"),
            ("adam", "ah-DAHM", "person", "noun", "people"),
            ("sağ ol", "sahg ohl", "thanks (stay well)", "verb", "essentials"),
        ],
        "phrases": [
            ("Salam", "sah-LAHM", "hello", "greetings", "neutral"),
            ("Günaydın", "goo-nahy-DEEN", "good day (morning)", "greetings", "neutral"),
            ("Çox sağ ol", "chohkh sahg ohl", "thanks a lot", "essentials", "neutral"),
            ("Necəsən?", "neh-jeh-SEHN", "How are you? (informal)", "greetings", "informal"),
            ("Adın nədir?", "ah-DEEN neh-DEER", "What's your name? (informal)", "greetings", "informal"),
            ("Mənim adım …", "meh-NEEM ah-DEEM", "My name is …", "introductions", "neutral"),
            ("Bu nədir?", "boo neh-DEER", "What is this?", "basics", "neutral"),
            ("Mən başa düşmürəm", "mehn bah-SHAH doosh-moo-REHM", "I don't understand", "problems", "neutral"),
            ("Sağ ol", "sahg ohl", "goodbye (stay well)", "greetings", "neutral"),
            ("Siz ingiliscə danışırsınız?", "seez een-gee-lees-JEH dah-nee-sheer-see-NEEZ", "Do you speak English? (formal)", "survival", "formal"),
            ("Bu neçəyədir?", "boo neh-cheh-yeh-DEER", "How much is this?", "shopping", "neutral"),
            ("… haradadır?", "hah-rah-dah-DEER", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns (no gender)",
             "pattern": "mən · sən · o · biz · siz · onlar",
             "examples": [
                 {"target": "mən danışıram", "roman": "mehn dah-nee-shee-RAHM", "gloss": "I speak"},
                 {"target": "sən danışırsan", "roman": "sehn dah-nee-sheer-SAHN", "gloss": "you speak"},
                 {"target": "biz danışırıq", "roman": "beez dah-nee-shee-REEKH", "gloss": "we speak"}],
             "exceptions": ["Siz is formal singular and plural."],
             "learnerNote": "O covers he/she/it; Azerbaijani and Turkish are close cousins.",
             "commonMistakes": ["sən with strangers (use siz)", "Turkish endings pasted in"]},
            {"concept": "Vowel harmony + agglutination",
             "pattern": "ev → evdə (at home) · kitab → kitabda (in the book)",
             "examples": [
                 {"target": "evdə", "roman": "ehv-DEH", "gloss": "at home (front → -də)"},
                 {"target": "kitabda", "roman": "kee-tahb-DAH", "gloss": "in the book (back → -da)"},
                 {"target": "suda", "roman": "soo-DAH", "gloss": "in the water"}],
             "exceptions": ["Ə (schwa) counts as front; rounding harmony is partial."],
             "learnerNote": "Suffixes harmonise back/front — the Oghuz Turkic engine shared with Turkish.",
             "commonMistakes": ["Evda (wrong harmony)", "Ignoring ə in harmony"]},
            {"concept": "Negation inside the verb",
             "pattern": "stem + ma/mə + ending",
             "examples": [
                 {"target": "mən başa düşmürəm", "roman": "mehn bah-SHAH doosh-moo-REHM", "gloss": "I don't understand"},
                 {"target": "mən bilmirəm", "roman": "mehn beel-mee-REHM", "gloss": "I don't know"},
                 {"target": "mən danışmıram", "roman": "mehn dah-neesh-mee-RAHM", "gloss": "I don't speak"}],
             "exceptions": ["Xeyr answers; -ma-/-mə- negates inside verbs."],
             "learnerNote": "The negative sits inside the verb and harmonises — no separate word.",
             "commonMistakes": ["Xeyr danışıram (wrong)", "Wrong harmony in -ma/-mə"]},
            {"concept": "Question words + mı/mi",
             "pattern": "nə (what) · hara (where) · nə vaxt (when) · niyə (why) · kim (who)",
             "examples": [
                 {"target": "Vağzal haradadır?", "roman": "vahgh-ZAHL hah-rah-dah-DEER", "gloss": "Where is the station?"},
                 {"target": "Bu neçəyədir?", "roman": "boo neh-cheh-yeh-DEER", "gloss": "How much is this?"},
                 {"target": "Sizmi?", "roman": "seez-MEE", "gloss": "You? (formal, with particle)"}],
             "exceptions": ["Mı/mi/mu/mü harmonises four ways."],
             "learnerNote": "Nə leads what-questions; the mı particle turns statements into questions.",
             "commonMistakes": ["Skipping mı", "Hara/nə vaxt swaps"]},
        ],
    },
    "khk": {
        "name": "Mongolian", "native": "монгол",
        "about": ("Mongolian (монгол, Khalkha standard) is spoken by about 6 million people in Mongolia. This starter "
                  "pack covers greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Mongolia."),
        "words": [
            ("би", "bee", "I", "pronoun", "people"),
            ("чи", "chee", "you (informal)", "pronoun", "people"),
            ("тэр", "tehr", "he / she", "pronoun", "people"),
            ("бид", "beed", "we", "pronoun", "people"),
            ("та", "tah", "you (formal)", "pronoun", "people"),
            ("ус", "oos", "water", "noun", "essentials"),
            ("хоол", "khohl", "food", "noun", "essentials"),
            ("гэр", "gehr", "house / yurt-home", "noun", "home"),
            ("талх", "tahlkh", "bread", "noun", "food"),
            ("цаг", "tsahg", "time", "noun", "time"),
            ("өдөр", "oh-DOHR", "day", "noun", "time"),
            ("шөнө", "shoh-NOH", "night", "noun", "time"),
            ("найз", "nah-eez", "friend", "noun", "people"),
            ("гэр бүл", "gehr bool", "family", "noun", "people"),
            ("сайн", "sah-eeh", "good", "adjective", "basics"),
            ("муу", "moo", "bad", "adjective", "basics"),
            ("том", "tohm", "big", "adjective", "basics"),
            ("жижиг", "jee-JEEG", "small", "adjective", "basics"),
            ("тийм", "teem", "yes", "particle", "essentials"),
            ("үгүй", "oo-GOO-ee", "no", "particle", "essentials"),
            ("мөнгө", "mohn-GOH", "money", "noun", "daily"),
            ("ном", "nohm", "book", "noun", "objects"),
            ("хүн", "khoon", "person", "noun", "people"),
            ("баярлалаа", "bah-yuhr-lah-LAH", "thanks", "verb", "essentials"),
        ],
        "phrases": [
            ("Сайн байна уу", "sah-eeh BAH-ee-nah oo", "hello (are you well)", "greetings", "neutral"),
            ("Өглөөний мэнд", "ohg-loh-NEEN mehnd", "good morning", "greetings", "neutral"),
            ("Маш их баярлалаа", "mahsh eekh bah-yuhr-lah-LAH", "thanks very much", "essentials", "neutral"),
            ("Юу байна?", "yoo BAH-ee-nah", "How are you? / What's up? (informal)", "greetings", "informal"),
            ("Таны нэр хэн бэ?", "tah-NEE nehr khehn beh", "What's your name? (formal)", "greetings", "formal"),
            ("Миний нэр …", "mee-NEEN nehr", "My name is …", "introductions", "neutral"),
            ("Энэ юу вэ?", "EH-neh yoo veh", "What is this?", "basics", "neutral"),
            ("Би ойлгохгүй байна", "bee oy-lohkh-GOO-ee BAH-ee-nah", "I don't understand", "problems", "neutral"),
            ("Баяртай", "bah-yuhr-TAH-ee", "goodbye", "greetings", "neutral"),
            ("Та англиар ярьдаг уу?", "tah ahn-glee-AHR yahry-dahg oo", "Do you speak English? (formal)", "survival", "formal"),
            ("Энэ хэд вэ?", "EH-neh khehd veh", "How much is this?", "shopping", "neutral"),
            ("… хаана байна?", "khah-NAH BAH-ee-nah", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns (no gender)",
             "pattern": "би · чи · тэр · бид · та · тэд",
             "examples": [
                 {"target": "би ярьдаг", "roman": "bee YAH-ry-dahg", "gloss": "I speak"},
                 {"target": "чи ярьдаг", "roman": "chee YAH-ry-dahg", "gloss": "you speak"},
                 {"target": "бид ярьдаг", "roman": "beed YAH-ry-dahg", "gloss": "we speak"}],
             "exceptions": ["Та is formal you; verbs barely change per person."],
             "learnerNote": "Тэр covers he/she; verbs stay nearly fixed — pronouns do the person-work.",
             "commonMistakes": ["чи with elders (use та)", "Verbs barely conjugate — don't over-change them"]},
            {"concept": "Vowel harmony + long vowels",
             "pattern": "гэр → гэрт (at home) · ном → номд (in the book)",
             "examples": [
                 {"target": "гэрт", "roman": "gehrt", "gloss": "at home (front → -т)"},
                 {"target": "номд", "roman": "nohmd", "gloss": "in the book (back → -д)"},
                 {"target": "усанд", "roman": "oo-SAHND", "gloss": "in the water"}],
             "exceptions": ["И is neutral — it lets the other vowels decide harmony."],
             "learnerNote": "Suffixes harmonise with stem vowels; long vowels (аа, оо) hold their length.",
             "commonMistakes": ["Гэрд (wrong harmony)", "Shortening long vowels"]},
            {"concept": "Negation with -гүй",
             "pattern": "verb + гүй + байна (present negative)",
             "examples": [
                 {"target": "би ойлгохгүй байна", "roman": "bee oy-lohkh-GOO-ee BAH-ee-nah", "gloss": "I don't understand"},
                 {"target": "би мэдэхгүй", "roman": "bee meh-dehkh-GOO-ee", "gloss": "I don't know"},
                 {"target": "би ярьдаггүй", "roman": "bee YAH-ry-dahg-goo-ee", "gloss": "I don't speak"}],
             "exceptions": ["Үгүй (no) answers; -гүй negates verbs."],
             "learnerNote": "The negative -гүй attaches to the verb — one suffix, every verb.",
             "commonMistakes": ["Үгүй before verbs (wrong slot)", "Forgetting байна in present negatives"]},
            {"concept": "Question words + уу/үү",
             "pattern": "юу (what) · хаана (where) · хэзээ (when) · яагаад (why) · хэн (who)",
             "examples": [
                 {"target": "Вокзал хаана байна?", "roman": "vohk-ZAHL khah-NAH BAH-ee-nah", "gloss": "Where is the station?"},
                 {"target": "Энэ хэд вэ?", "roman": "EH-neh khehd veh", "gloss": "How much is this?"},
                 {"target": "Та англиар ярьдаг уу?", "roman": "tah ahn-glee-AHR yahry-dahg oo", "gloss": "Do you speak English?"}],
             "exceptions": ["Уу/үү particle marks yes/no questions (harmonised)."],
             "learnerNote": "Юу leads what-questions; уу/үү floats at the end of yes/no ones.",
             "commonMistakes": ["Skipping уу/үү", "Хаана/хэзээ swaps"]},
        ],
    },
    "my": {
        "name": "Burmese", "native": "မြန်မာ",
        "about": ("Burmese (မြန်မာ) is spoken by about 33 million people in Myanmar. This starter pack covers greetings, "
                  "essentials and core grammar — a first taste, not a full course. It is the English-medium "
                  "starting point for Myanmar."),
        "words": [
            ("ကျွန်တော်", "choh-NOH", "I (male speaker)", "pronoun", "people"),
            ("ကျွန်မ", "chah-MAH", "I (female speaker)", "pronoun", "people"),
            ("နင်", "neen", "you (informal)", "pronoun", "people"),
            ("သူ", "thoo", "he / she", "pronoun", "people"),
            ("တို့", "toh", "we", "pronoun", "people"),
            ("ရေ", "yay", "water", "noun", "essentials"),
            ("အစား", "ah-SAH", "food", "noun", "essentials"),
            ("အိမ်", "ay-AYN", "house / home", "noun", "home"),
            ("ပေါင်မုန့်", "pow-moh", "bread", "noun", "food"),
            ("အချိန်", "ah-CHAYN", "time", "noun", "time"),
            ("နေ့", "nay", "day", "noun", "time"),
            ("ည", "nya", "night", "noun", "time"),
            ("သူငယ်ချင်း", "thoo-ngeh-JEEN", "friend", "noun", "people"),
            ("မိသားစု", "mee-thah-ZOO", "family", "noun", "people"),
            ("ကောင်း", "kown", "good", "adjective", "basics"),
            ("ဆိုး", "soh", "bad", "adjective", "basics"),
            ("ကြီး", "jee", "big", "adjective", "basics"),
            ("သေး", "thay", "small", "adjective", "basics"),
            ("ဟုတ်တယ်", "hoh-teh", "yes", "particle", "essentials"),
            ("မဟုတ်ဘူး", "mah-hoh-BOO", "no", "particle", "essentials"),
            ("ပိုက်ဆံ", "pie-sahn", "money", "noun", "daily"),
            ("စာအုပ်", "sah-oh", "book", "noun", "objects"),
            ("လူ", "loo", "person", "noun", "people"),
            ("ကျေးဇူး", "chay-ZOO", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("မင်္ဂလာပါ", "meen-gah-LAH-bah", "hello (blessings)", "greetings", "neutral"),
            ("မင်္ဂလာနံနက်", "meen-gah-LAH nahn-NEHK", "good morning", "greetings", "neutral"),
            ("ကျေးဇူးတင်ပါတယ်", "chay-ZOO teen-BAH-teh", "thank you", "essentials", "neutral"),
            ("နေကောင်းလား", "nay-kown-LAH", "How are you? (informal)", "greetings", "informal"),
            ("နာမည်ဘယ်လိုခေါ်လဲ", "nah-MEH beh-loh KHOH-leh", "What's your name? (informal)", "greetings", "informal"),
            ("ကျွန်တော်/ကျွန်မ နာမည် …", "choh-NOH nah-MEH", "My name is …", "introductions", "neutral"),
            ("ဒါဘာလဲ", "dah-bah-LEH", "What is this?", "basics", "neutral"),
            ("နားမလည်ဘူး", "nah-mah-LEH-boo", "I don't understand", "problems", "neutral"),
            ("သွားတော့မယ်", "thwah-doh-MEH", "goodbye (I'm going now)", "greetings", "neutral"),
            ("အင်္ဂလိပ်စကားပြောတတ်လား", "een-gah-LAY sah-GAH pyoh-tah-LEH", "Do you speak English? (informal)", "survival", "informal"),
            ("ဒါဘယ်လောက်လဲ", "dah-beh-LOW-leh", "How much is this?", "shopping", "neutral"),
            ("… ဘယ်မှာလဲ", "beh-HMAH-leh", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Pronouns shift by speaker",
             "pattern": "ကျွန်တော် (I, male) · ကျွန်မ (I, female) · သူ (he/she)",
             "examples": [
                 {"target": "ကျွန်တော်ပြောတယ်", "roman": "choh-NOH pyoh-TEH", "gloss": "I speak (male speaker)"},
                 {"target": "ကျွန်မပြောတယ်", "roman": "chah-MAH pyoh-TEH", "gloss": "I speak (female speaker)"},
                 {"target": "သူပြောတယ်", "roman": "thoo pyoh-TEH", "gloss": "he/she speaks"}],
             "exceptions": ["သူ covers he and she — no gender in third person."],
             "learnerNote": "First person changes by YOUR gender — pick ကျွန်တော် or ကျွန်မ for yourself.",
             "commonMistakes": ["Wrong I-form for your gender", "နင် with strangers (too intimate)"]},
            {"concept": "Verb-final + politeness particles",
             "pattern": "subject · object · verb + တယ် (statement) / လား (question)",
             "examples": [
                 {"target": "နေကောင်းတယ်", "roman": "nay-kown-TEH", "gloss": "I am well (well + statement)"},
                 {"target": "နေကောင်းလား", "roman": "nay-kown-LAH", "gloss": "Are you well? (well + question)"},
                 {"target": "ဒါဘာလဲ", "roman": "dah-bah-LEH", "gloss": "What is this?"}],
             "exceptions": ["ပါ/တယ် soften statements politely — use them liberally."],
             "learnerNote": "The verb goes LAST; little particles at the end mark statements vs questions.",
             "commonMistakes": ["English SVO order", "Dropping politeness particles (sounds blunt)"]},
            {"concept": "Negation wraps: မ…ဘူး",
             "pattern": "မ + verb + ဘူး",
             "examples": [
                 {"target": "နားမလည်ဘူး", "roman": "nah-mah-LEH-boo", "gloss": "I don't understand"},
                 {"target": "မသိဘူး", "roman": "mah-THEE-boo", "gloss": "I don't know"},
                 {"target": "မပြောဘူး", "roman": "mah-PYOH-boo", "gloss": "I don't speak / won't say"}],
             "exceptions": ["မဟုတ်ဘူး (it is not) negates nouns and adjectives."],
             "learnerNote": "Negation HUGS the verb: မ before, ဘူး after — both required.",
             "commonMistakes": ["Forgetting ဘူး", "မဟုတ်ဘူး on verbs (it is for nouns)"]},
            {"concept": "Question words",
             "pattern": "ဘာ (what) · ဘယ် (which/where) · ဘယ်တော့ (when) · ဘာကြောင့် (why) · ဘယ်သူ (who)",
             "examples": [
                 {"target": "ဘူတာဘယ်မှာလဲ", "roman": "boo-TAH beh-HMAH-leh", "gloss": "Where is the station?"},
                 {"target": "ဒါဘယ်လောက်လဲ", "roman": "dah-beh-LOW-leh", "gloss": "How much is this?"},
                 {"target": "ဒါဘာလဲ", "roman": "dah-bah-LEH", "gloss": "What is this?"}],
             "exceptions": ["ဘယ်- starts most question words — one root, many questions."],
             "learnerNote": "Learn ဘယ် as the question-root; endings specify where/when/who.",
             "commonMistakes": ["Word order (verb stays last!)", "Missing လဲ particle"]},
        ],
    },
    "km": {
        "name": "Khmer", "native": "ខ្មែរ",
        "about": ("Khmer (ខ្មែរ) is spoken by about 16 million people in Cambodia. This starter pack covers greetings, "
                  "essentials and core grammar — a first taste, not a full course. It is the English-medium "
                  "starting point for Cambodia."),
        "words": [
            ("ខ្ញុំ", "k'nyoh", "I (formal)", "pronoun", "people"),
            ("អ្នក", "ah-NAHK", "you (formal)", "pronoun", "people"),
            ("គាត់", "kee-AHT", "he", "pronoun", "people"),
            ("នាង", "nee-ANG", "she", "pronoun", "people"),
            ("យើង", "yoh-ENG", "we", "pronoun", "people"),
            ("ទឹក", "tuhk", "water", "noun", "essentials"),
            ("អាហារ", "ah-HAH", "food", "noun", "essentials"),
            ("ផ្ទះ", "ptyeh", "house / home", "noun", "home"),
            ("នំបុ័ង", "nohm-PAHNG", "bread", "noun", "food"),
            ("ពេល", "payl", "time", "noun", "time"),
            ("ថ្ងៃ", "t'ngai", "day", "noun", "time"),
            ("យប់", "yohp", "night", "noun", "time"),
            ("មិត្ត", "miht", "friend", "noun", "people"),
            ("គ្រួសារ", "kroo-AH", "family", "noun", "people"),
            ("ល្អ", "l'aw", "good", "adjective", "basics"),
            ("អាក្រក់", "ah-krahk", "bad", "adjective", "basics"),
            ("ធំ", "thohm", "big", "adjective", "basics"),
            ("តូច", "tohch", "small", "adjective", "basics"),
            ("បាទ", "baht", "yes (male speaker)", "particle", "essentials"),
            ("ចាស", "chahs", "yes (female speaker)", "particle", "essentials"),
            ("លុយ", "loo-ee", "money", "noun", "daily"),
            ("សៀវភៅ", "see-eh-P'OO", "book", "noun", "objects"),
            ("មនុស្ស", "mih-NOOH", "person", "noun", "people"),
            ("អរគុណ", "ah-KOON", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("ជំរាបសួរ", "chohm-REE-ehp SOO-ah", "hello (formal)", "greetings", "formal"),
            ("អរុណសួស្តី", "ah-roon-ah soo-AH-stee", "good morning", "greetings", "neutral"),
            ("អរគុណច្រើន", "ah-KOON ch'rohn", "thanks a lot", "essentials", "neutral"),
            ("សុខសប្បាយទេ?", "sohk-sah-BAH-ee tay", "How are you? (are you well?)", "greetings", "informal"),
            ("តើអ្នកឈ្មោះអ្វី?", "tuh ah-NAHK ch'moo-ah ah-VEE", "What's your name? (formal)", "greetings", "formal"),
            ("ខ្ញុំឈ្មោះ …", "k'nyoh ch'moo-ah", "My name is …", "introductions", "neutral"),
            ("នេះជាអ្វី?", "neeh chee-ah ah-VEE", "What is this?", "basics", "neutral"),
            ("ខ្ញុំមិនយល់ទេ", "k'nyoh meen YOOL tay", "I don't understand", "problems", "neutral"),
            ("លាហើយ", "lee-ah HOH-ee", "goodbye", "greetings", "neutral"),
            ("តើអ្នកចេះភាសាអង់គ្លេសទេ?", "tuh ah-NAHK cheh phee-AH-sah ahn-KLAY tay", "Do you speak English? (formal)", "survival", "formal"),
            ("នេះថ្លៃប៉ុន្មាន?", "neeh t'lai pohn-MAHN", "How much is this?", "shopping", "neutral"),
            ("…នៅឯណា?", "noh AY-nah", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Pronouns by register and gender",
             "pattern": "ខ្ញុំ (I, formal) · អ្នក (you, formal) ·គាត់/នាង (he/she)",
             "examples": [
                 {"target": "ខ្ញុំនិយាយ", "roman": "k'nyoh nee-YEE-ay", "gloss": "I speak (formal)"},
                 {"target": "អ្នកនិយាយ", "roman": "ah-NAHK nee-YEE-ay", "gloss": "you speak (formal)"},
                 {"target": "យើងនិយាយ", "roman": "yoh-ENG nee-YEE-ay", "gloss": "we speak"}],
             "exceptions": ["Intimate pronouns (អញ/ឯង) exist — never use them as a learner."],
             "learnerNote": "Khmer pronouns encode respect levels — stick to the formal set and you are safe.",
             "commonMistakes": ["Intimate pronouns with strangers", "បាទ/ចាស swapped by gender"]},
            {"concept": "No conjugations, no tones",
             "pattern": "same verb, every person · time words mark tense",
             "examples": [
                 {"target": "ខ្ញុំនិយាយ", "roman": "k'nyoh nee-YEE-ay", "gloss": "I speak"},
                 {"target": "ម្សិលមិញខ្ញុំនិយាយ", "roman": "mmm-SEHL-meen k'nyoh nee-YEE-ay", "gloss": "yesterday I spoke (time word does it)"},
                 {"target": "គាត់ល្អ", "roman": "kee-AHT l'aw", "gloss": "he is good (no 'is' needed)"}],
             "exceptions": ["Classifiers count nouns: two books = books two volume."],
             "learnerNote": "Verbs never change — add time words (yesterday, tomorrow) instead of tenses.",
             "commonMistakes": ["Conjugating verbs (don't)", "Forgetting classifiers when counting"]},
            {"concept": "Negation with មិន",
             "pattern": "មិន + verb (+ ទេ)",
             "examples": [
                 {"target": "ខ្ញុំមិនយល់ទេ", "roman": "k'nyoh meen YOOL tay", "gloss": "I don't understand"},
                 {"target": "ខ្ញុំមិនដឹងទេ", "roman": "k'nyoh meen DEHNG tay", "gloss": "I don't know"},
                 {"target": "ខ្ញុំមិននិយាយទេ", "roman": "k'nyoh meen nee-YEE-ay tay", "gloss": "I don't speak"}],
             "exceptions": ["ទេ at the end strengthens negatives and questions."],
             "learnerNote": "មិន before the verb, optional ទេ at the end — negation with a frame.",
             "commonMistakes": ["Post-verb មិន", "ទេ on affirmative statements"]},
            {"concept": "Question words + តើ",
             "pattern": "អ្វី (what) · ឯណា (where) · ពេលណា (when) · ហេតុអ្វី (why) · នរណា (who)",
             "examples": [
                 {"target": "ស្ថានីយនៅឯណា?", "roman": "stah-nee noh AY-nah", "gloss": "Where is the station?"},
                 {"target": "នេះថ្លៃប៉ុន្មាន?", "roman": "neeh t'lai pohn-MAHN", "gloss": "How much is this?"},
                 {"target": "តើអ្នក…ទេ?", "roman": "tuh ah-NAHK tay", "gloss": "Do you…? (question frame)"}],
             "exceptions": ["តើ…ទេ frames formal yes/no questions."],
             "learnerNote": "តើ opens polite questions, ទេ closes them — a courteous question sandwich.",
             "commonMistakes": ["Skipping the frame in formal speech", "ឯណា/ពេលណា swaps"]},
        ],
    },
}
