# -*- coding: utf-8 -*-
"""194-country program, batch A1 — Europe north/west/central (authored, not MT).

Same schema and honesty rules as every other pack: 24 words + 12 phrases +
4 grammar concepts, BETA starter reference content. Hindi stays the only
PRODUCTION language. Each pack is the English-medium starting point for the
countries whose flagship language it is.
"""

EXTRA_PACKS_194_EU1 = {
    "ro": {
        "name": "Romanian", "native": "română",
        "about": ("Romanian (română) is spoken by about 25 million people, chiefly in Romania "
                  "and Moldova. This starter pack covers greetings, essentials and core grammar — "
                  "a first taste, not a full course. It is the English-medium starting point for Romania and Moldova."),
        "words": [
            ("eu", "eh-oo", "I", "pronoun", "people"),
            ("tu", "too", "you (informal)", "pronoun", "people"),
            ("el", "yehl", "he", "pronoun", "people"),
            ("ea", "yah", "she", "pronoun", "people"),
            ("noi", "noy", "we", "pronoun", "people"),
            ("apă", "AH-puh", "water", "noun", "essentials"),
            ("mâncare", "muhn-KAH-reh", "food", "noun", "essentials"),
            ("casă", "KAH-suh", "house / home", "noun", "home"),
            ("pâine", "puh-EE-neh", "bread", "noun", "food"),
            ("timp", "teemp", "time", "noun", "time"),
            ("zi", "zee", "day", "noun", "time"),
            ("noapte", "NWAH-teh", "night", "noun", "time"),
            ("prieten", "pree-eh-TEHN", "friend", "noun", "people"),
            ("familie", "fah-MEE-lyeh", "family", "noun", "people"),
            ("bun", "boon", "good", "adjective", "basics"),
            ("rău", "ruh-oo", "bad", "adjective", "basics"),
            ("mare", "MAH-reh", "big", "adjective", "basics"),
            ("mic", "meek", "small", "adjective", "basics"),
            ("da", "dah", "yes", "particle", "essentials"),
            ("nu", "noo", "no", "particle", "essentials"),
            ("bani", "BAH-nee", "money", "noun", "daily"),
            ("carte", "KAHR-teh", "book", "noun", "objects"),
            ("om", "ohm", "person / man", "noun", "people"),
            ("mulțumesc", "mool-tsoo-MEHSH", "thank you", "verb", "essentials"),
        ],
        "phrases": [
            ("Bună ziua", "BOO-nuh ZEE-wah", "hello / good day", "greetings", "neutral"),
            ("Mulțumesc mult", "mool-tsoo-MEHSH moolt", "thank you very much", "essentials", "neutral"),
            ("Ce mai faci?", "cheh MY FAHCH", "How are you? (informal)", "greetings", "informal"),
            ("Cum te cheamă?", "koom teh KYAH-muh", "What's your name? (informal)", "greetings", "informal"),
            ("Mă numesc …", "muh noo-MEHSH", "My name is …", "introductions", "neutral"),
            ("Ce este asta?", "cheh YEH-steh AH-stah", "What is this?", "basics", "neutral"),
            ("Nu înțeleg", "noo uhn-tseh-LEHG", "I don't understand", "problems", "neutral"),
            ("La revedere", "lah reh-veh-DEH-reh", "goodbye", "greetings", "neutral"),
            ("Te rog", "teh rohg", "please (informal)", "essentials", "informal"),
            ("Vorbiți engleză?", "vohr-BEETZ ehn-GLEH-zuh", "Do you speak English? (formal)", "survival", "formal"),
            ("Cât costă?", "kuht KOH-stuh", "How much is it?", "shopping", "neutral"),
            ("Unde este …?", "OON-deh YEH-steh", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "eu · tu · el/ea · noi · voi · ei/ele",
             "examples": [
                 {"target": "eu vorbesc", "roman": "eh-oo vohr-BEHSH", "gloss": "I speak"},
                 {"target": "tu vorbești", "roman": "too vohr-BEHSH-tee", "gloss": "you speak (informal)"},
                 {"target": "noi vorbim", "roman": "noy vohr-BEEM", "gloss": "we speak"}],
             "exceptions": ["Pronouns are often dropped: vorbesc alone already means I speak."],
             "learnerNote": "Like Spanish and Italian, Romanian verb endings show the subject, so eu/tu/noi are optional emphasis.",
             "commonMistakes": ["Saying eu in every sentence (sounds emphatic)", "Using tu with strangers — use voi/dumneavoastră"]},
            {"concept": "The definite article attaches to the noun",
             "pattern": "un băiat → băiatul · o fată → fata",
             "examples": [
                 {"target": "băiatul", "roman": "buh-YAH-tool", "gloss": "the boy"},
                 {"target": "fata", "roman": "FAH-tah", "gloss": "the girl"},
                 {"target": "omul", "roman": "OH-mool", "gloss": "the man"}],
             "exceptions": ["Neuter nouns behave masculine in singular, feminine in plural."],
             "learnerNote": "Romanian is the only major Romance language with an attached definite article — -ul/-a at the END of the word.",
             "commonMistakes": ["Putting the article before the noun (English habit)", "Confusing fată (a girl) with fata (the girl)"]},
            {"concept": "Negation with nu",
             "pattern": "nu + verb",
             "examples": [
                 {"target": "nu înțeleg", "roman": "noo uhn-tseh-LEHG", "gloss": "I don't understand"},
                 {"target": "nu știu", "roman": "noo SHTEE-oo", "gloss": "I don't know"},
                 {"target": "nu vorbesc", "roman": "noo vohr-BEHSH", "gloss": "I don't speak"}],
             "exceptions": ["In some tenses nu merges: n-am (I don't have / I haven't)."],
             "learnerNote": "Negation is beautifully simple: put nu directly before the verb, always.",
             "commonMistakes": ["Putting nu after the verb", "Using nu where nici (neither/nor) is needed"]},
            {"concept": "Questions: words + rising intonation",
             "pattern": "ce (what) · unde (where) · cât (how much) · de ce (why) · cine (who)",
             "examples": [
                 {"target": "Unde este gara?", "roman": "OON-deh YEH-steh GAH-rah", "gloss": "Where is the station?"},
                 {"target": "Cât costă?", "roman": "kuht KOH-stuh", "gloss": "How much is it?"},
                 {"target": "De ce?", "roman": "deh cheh", "gloss": "Why?"}],
             "exceptions": ["Yes/no questions need no helper word — just raise your voice at the end."],
             "learnerNote": "Word order barely changes in questions; intonation does the work.",
             "commonMistakes": ["Adding a do/does helper (there is none)", "Forgetting the rising tone, so it sounds like a statement"]},
        ],
    },
    "el": {
        "name": "Greek", "native": "ελληνικά",
        "about": ("Greek (ελληνικά) is spoken by about 13 million people in Greece and Cyprus. "
                  "This starter pack covers greetings, essentials and core grammar — a first taste, "
                  "not a full course. It is the English-medium starting point for Greece and Cyprus."),
        "words": [
            ("εγώ", "eh-GOH", "I", "pronoun", "people"),
            ("εσύ", "eh-SEE", "you (informal)", "pronoun", "people"),
            ("αυτός", "ahf-TOHS", "he", "pronoun", "people"),
            ("αυτή", "ahf-TEE", "she", "pronoun", "people"),
            ("εμείς", "eh-MEES", "we", "pronoun", "people"),
            ("νερό", "neh-ROH", "water", "noun", "essentials"),
            ("φαγητό", "fah-yee-TOH", "food", "noun", "essentials"),
            ("σπίτι", "SPEE-tee", "house / home", "noun", "home"),
            ("ψωμί", "psoh-MEE", "bread", "noun", "food"),
            ("χρόνος", "HROH-nohs", "time", "noun", "time"),
            ("μέρα", "MEH-rah", "day", "noun", "time"),
            ("νύχτα", "NEEKH-tah", "night", "noun", "time"),
            ("φίλος", "FEE-lohs", "friend", "noun", "people"),
            ("οικογένεια", "ee-koh-YEH-nee-ah", "family", "noun", "people"),
            ("καλός", "kah-LOHS", "good", "adjective", "basics"),
            ("κακός", "kah-KOHS", "bad", "adjective", "basics"),
            ("μεγάλος", "meh-GHAH-lohs", "big", "adjective", "basics"),
            ("μικρός", "mee-KROHS", "small", "adjective", "basics"),
            ("ναι", "neh", "yes", "particle", "essentials"),
            ("όχι", "OH-khee", "no", "particle", "essentials"),
            ("χρήματα", "KHREE-mah-tah", "money", "noun", "daily"),
            ("βιβλίο", "vee-VLEE-oh", "book", "noun", "objects"),
            ("άνθρωπος", "AHN-throh-pohs", "person", "noun", "people"),
            ("ευχαριστώ", "ehf-hah-ree-STOH", "thank you", "verb", "essentials"),
        ],
        "phrases": [
            ("Γεια σου", "YAH soo", "hello (informal)", "greetings", "informal"),
            ("Καλημέρα", "kah-lee-MEH-rah", "good morning", "greetings", "neutral"),
            ("Ευχαριστώ πολύ", "ehf-hah-ree-STOH poh-LEE", "thank you very much", "essentials", "neutral"),
            ("Πώς είσαι;", "pohs EE-seh", "How are you? (informal)", "greetings", "informal"),
            ("Με λένε …", "meh LEH-neh", "My name is … (lit. they call me)", "introductions", "neutral"),
            ("Πώς σε λένε;", "pohs seh LEH-neh", "What's your name? (informal)", "greetings", "informal"),
            ("Δεν καταλαβαίνω", "dehn kah-tah-lah-VEH-noh", "I don't understand", "problems", "neutral"),
            ("Αντίο", "ahn-DEE-oh", "goodbye", "greetings", "neutral"),
            ("Παρακαλώ", "pah-rah-kah-LOH", "please / you're welcome", "essentials", "neutral"),
            ("Μιλάτε αγγλικά;", "mee-LAH-teh ahn-glee-KAH", "Do you speak English? (formal)", "survival", "formal"),
            ("Πόσο κάνει;", "POH-soh KAH-nee", "How much is it?", "shopping", "neutral"),
            ("Πού είναι …;", "poo EE-neh", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "εγώ · εσύ · αυτός/αυτή · εμείς · εσείς · αυτοί/αυτές",
             "examples": [
                 {"target": "εγώ μιλάω", "roman": "eh-GOH mee-LOH", "gloss": "I speak"},
                 {"target": "εσύ μιλάς", "roman": "eh-SEE mee-LAHS", "gloss": "you speak (informal)"},
                 {"target": "εμείς μιλάμε", "roman": "eh-MEES mee-LAH-meh", "gloss": "we speak"}],
             "exceptions": ["Pronouns drop freely: μιλάω alone means I speak."],
             "learnerNote": "Greek verbs carry the subject in their ending, so pronouns are optional — use them for emphasis.",
             "commonMistakes": ["Overusing εγώ (sounds insistent)", "Mixing up εσύ (informal) and εσείς (formal/plural)"]},
            {"concept": "Three genders, and adjectives agree",
             "pattern": "ο καλός (m) · η καλή (f) · το καλό (n)",
             "examples": [
                 {"target": "ο καλός φίλος", "roman": "oh kah-LOHS FEE-lohs", "gloss": "the good friend (male)"},
                 {"target": "η καλή μέρα", "roman": "ee kah-LEE MEH-rah", "gloss": "the good day"},
                 {"target": "το καλό παιδί", "roman": "toh kah-LOH peh-DEE", "gloss": "the good child"}],
             "exceptions": ["Some nouns surprise: η ώρα (hour) is feminine, το όνομα (name) neuter."],
             "learnerNote": "Every noun is masculine, feminine or neuter — articles and adjectives change to match.",
             "commonMistakes": ["Using masculine adjectives for feminine nouns", "Guessing gender from meaning instead of endings"]},
            {"concept": "Negation with δεν",
             "pattern": "δεν + verb",
             "examples": [
                 {"target": "δεν καταλαβαίνω", "roman": "dehn kah-tah-lah-VEH-noh", "gloss": "I don't understand"},
                 {"target": "δεν ξέρω", "roman": "dehn KSEH-roh", "gloss": "I don't know"},
                 {"target": "δεν μιλάω", "roman": "dehn mee-LOH", "gloss": "I don't speak"}],
             "exceptions": ["Prohibitions use μην instead: μην ανησυχείς (don't worry)."],
             "learnerNote": "One word does almost all negation: δεν goes directly before the verb.",
             "commonMistakes": ["Using όχι (no) to negate verbs — όχι answers questions, δεν negates verbs"]},
            {"concept": "Question words",
             "pattern": "τι (what) · πού (where) · πόσο (how much) · γιατί (why) · ποιος (who)",
             "examples": [
                 {"target": "Πού είναι η παραλία;", "roman": "poo EE-neh ee pah-rah-LEE-ah", "gloss": "Where is the beach?"},
                 {"target": "Τι είναι αυτό;", "roman": "tee EE-neh ahf-TOH", "gloss": "What is this?"},
                 {"target": "Γιατί;", "roman": "yah-TEE", "gloss": "Why?"}],
             "exceptions": ["Yes/no questions just rise in tone; no helper word needed."],
             "learnerNote": "Greek questions keep normal word order — the question word plus rising intonation is enough.",
             "commonMistakes": ["Confusing πού (where) with που (that/which — no accent)", "Adding English-style do/does"]},
        ],
    },
    "da": {
        "name": "Danish", "native": "dansk",
        "about": ("Danish (dansk) is spoken by about 6 million people in Denmark and parts of "
                  "Schleswig. This starter pack covers greetings, essentials and core grammar — a first "
                  "taste, not a full course. It is the English-medium starting point for Denmark."),
        "words": [
            ("jeg", "yai", "I", "pronoun", "people"),
            ("du", "doo", "you (informal)", "pronoun", "people"),
            ("han", "hahn", "he", "pronoun", "people"),
            ("hun", "hoon", "she", "pronoun", "people"),
            ("vi", "vee", "we", "pronoun", "people"),
            ("vand", "vahn", "water", "noun", "essentials"),
            ("mad", "mael", "food", "noun", "essentials"),
            ("hus", "hoos", "house", "noun", "home"),
            ("brød", "brurl", "bread", "noun", "food"),
            ("tid", "teedh", "time", "noun", "time"),
            ("dag", "dahg", "day", "noun", "time"),
            ("nat", "naht", "night", "noun", "time"),
            ("ven", "vehn", "friend", "noun", "people"),
            ("familie", "fah-MEEL-yuh", "family", "noun", "people"),
            ("god", "goh", "good", "adjective", "basics"),
            ("dårlig", "DAWR-lee", "bad", "adjective", "basics"),
            ("stor", "stohr", "big", "adjective", "basics"),
            ("lille", "LEE-luh", "small", "adjective", "basics"),
            ("ja", "yah", "yes", "particle", "essentials"),
            ("nej", "nai", "no", "particle", "essentials"),
            ("penge", "PEHNG-uh", "money", "noun", "daily"),
            ("bog", "boh", "book", "noun", "objects"),
            ("mand", "mahn", "man / person", "noun", "people"),
            ("tak", "tahg", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Hej", "hai", "hello", "greetings", "neutral"),
            ("Mange tak", "MAHNG-uh tahg", "many thanks", "essentials", "neutral"),
            ("Hvordan har du det?", "VEHL-dahn hahr doo deh", "How are you? (informal)", "greetings", "informal"),
            ("Hvad hedder du?", "vahl HEHDH-uhr doo", "What's your name? (informal)", "greetings", "informal"),
            ("Jeg hedder …", "yai HEHDH-uhr", "My name is …", "introductions", "neutral"),
            ("Hvad er det?", "vahl ehr deh", "What is it?", "basics", "neutral"),
            ("Jeg forstår ikke", "yai foh-STOHR ee-guh", "I don't understand", "problems", "neutral"),
            ("Farvel", "fahr-VEHL", "goodbye", "greetings", "neutral"),
            ("Vær så venlig", "vehr saw VEHN-lee", "please (be so kind)", "essentials", "formal"),
            ("Taler du engelsk?", "TAH-luhr doo EHNG-ehlsk", "Do you speak English? (informal)", "survival", "informal"),
            ("Hvad koster det?", "vahl KOHS-tuhr deh", "How much is it?", "shopping", "neutral"),
            ("Hvor er …?", "vohr ehr", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "jeg · du · han/hun · vi · I · de",
             "examples": [
                 {"target": "jeg taler", "roman": "yai TAH-luhr", "gloss": "I speak"},
                 {"target": "du taler", "roman": "doo TAH-luhr", "gloss": "you speak"},
                 {"target": "vi taler", "roman": "vee TAH-luhr", "gloss": "we speak"}],
             "exceptions": ["Formal you (De) is rare today — du works almost everywhere."],
             "learnerNote": "Great news: Danish verbs barely conjugate — taler works for I, you, we, they alike.",
             "commonMistakes": ["Changing the verb per person (don't — it stays the same)", "Using formal De like German Sie"]},
            {"concept": "Two genders, attached articles",
             "pattern": "en mand → manden · et hus → huset",
             "examples": [
                 {"target": "manden", "roman": "MAHN-uhn", "gloss": "the man"},
                 {"target": "huset", "roman": "HOO-sehdh", "gloss": "the house"},
                 {"target": "bogen", "roman": "BOH-uhn", "gloss": "the book"}],
             "exceptions": ["Gender (en vs et) must be memorised per noun."],
             "learnerNote": "The definite article glues onto the END: -en for common gender, -et for neuter.",
             "commonMistakes": ["Saying en hus (it is et hus)", "Putting the before the noun"]},
            {"concept": "Negation with ikke",
             "pattern": "verb + ikke",
             "examples": [
                 {"target": "jeg forstår ikke", "roman": "yai foh-STOHR ee-guh", "gloss": "I don't understand"},
                 {"target": "jeg ved ikke", "roman": "yai vehdh ee-guh", "gloss": "I don't know"},
                 {"target": "det er ikke", "roman": "deh ehr ee-guh", "gloss": "it is not"}],
             "exceptions": ["Questions and orders move ikke: forstår du ikke? (don't you understand?)."],
             "learnerNote": "Ikke usually comes AFTER the verb — the opposite order from English don't.",
             "commonMistakes": ["Ikke forstår (verb must come first)", "Confusing ikke with ingen (none/no)"]},
            {"concept": "Question words",
             "pattern": "hvad (what) · hvor (where) · hvornår (when) · hvorfor (why) · hvem (who)",
             "examples": [
                 {"target": "Hvor er stationen?", "roman": "vohr ehr stah-SHOHN-uhn", "gloss": "Where is the station?"},
                 {"target": "Hvad koster det?", "roman": "vahl KOHS-tuhr deh", "gloss": "How much is it?"},
                 {"target": "Hvem er du?", "roman": "vehm ehr doo", "gloss": "Who are you?"}],
             "exceptions": ["Hv- is silent-ish: hvad sounds like vahl."],
             "learnerNote": "Danish question words all start with hv- (pronounced v-), cousins of English wh-.",
             "commonMistakes": ["Pronouncing the h in hvad/hvor", "Mixing hvor (where) with hvornår (when)"]},
        ],
    },
    "sv": {
        "name": "Swedish", "native": "svenska",
        "about": ("Swedish (svenska) is spoken by about 10 million people in Sweden and parts of "
                  "Finland. This starter pack covers greetings, essentials and core grammar — a first "
                  "taste, not a full course. It is the English-medium starting point for Sweden."),
        "words": [
            ("jag", "yahg", "I", "pronoun", "people"),
            ("du", "doo", "you (informal)", "pronoun", "people"),
            ("han", "hahn", "he", "pronoun", "people"),
            ("hon", "hoon", "she", "pronoun", "people"),
            ("vi", "vee", "we", "pronoun", "people"),
            ("vatten", "VAH-tehn", "water", "noun", "essentials"),
            ("mat", "maht", "food", "noun", "essentials"),
            ("hus", "hews", "house", "noun", "home"),
            ("bröd", "brurd", "bread", "noun", "food"),
            ("tid", "teed", "time", "noun", "time"),
            ("dag", "dahg", "day", "noun", "time"),
            ("natt", "naht", "night", "noun", "time"),
            ("vän", "vehn", "friend", "noun", "people"),
            ("familj", "fah-MEEL-yuh", "family", "noun", "people"),
            ("bra", "brah", "good", "adjective", "basics"),
            ("dålig", "DAW-leeg", "bad", "adjective", "basics"),
            ("stor", "stohr", "big", "adjective", "basics"),
            ("liten", "LEE-tehn", "small", "adjective", "basics"),
            ("ja", "yah", "yes", "particle", "essentials"),
            ("nej", "nay", "no", "particle", "essentials"),
            ("pengar", "PEHNG-ahr", "money", "noun", "daily"),
            ("bok", "book", "book", "noun", "objects"),
            ("man", "mahn", "man / person", "noun", "people"),
            ("tack", "tahk", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Hej", "hay", "hello", "greetings", "neutral"),
            ("Tack så mycket", "tahk saw MEW-keh", "thank you very much", "essentials", "neutral"),
            ("Hur mår du?", "hewr mohr doo", "How are you? (informal)", "greetings", "informal"),
            ("Vad heter du?", "vahl HEH-tuhr doo", "What's your name? (informal)", "greetings", "informal"),
            ("Jag heter …", "yahg HEH-tuhr", "My name is …", "introductions", "neutral"),
            ("Vad är det?", "vahl ehr deh", "What is it?", "basics", "neutral"),
            ("Jag förstår inte", "yahg fur-SHTOHR een-teh", "I don't understand", "problems", "neutral"),
            ("Hej då", "hay daw", "goodbye", "greetings", "neutral"),
            ("Snälla", "SNEH-lah", "please", "essentials", "neutral"),
            ("Talar du engelska?", "TAH-lahr doo ehng-EHL-skah", "Do you speak English? (informal)", "survival", "informal"),
            ("Vad kostar det?", "vahl KOHS-tahr deh", "How much is it?", "shopping", "neutral"),
            ("Var är …?", "vahr ehr", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "jag · du · han/hon · vi · ni · de",
             "examples": [
                 {"target": "jag talar", "roman": "yahg TAH-lahr", "gloss": "I speak"},
                 {"target": "du talar", "roman": "doo TAH-lahr", "gloss": "you speak"},
                 {"target": "vi talar", "roman": "vee TAH-lahr", "gloss": "we speak"}],
             "exceptions": ["Ni (formal you) is uncommon; du works nearly everywhere."],
             "learnerNote": "Swedish verbs don't change per person — one form (talar) serves them all.",
             "commonMistakes": ["Conjugating verbs like German", "Overusing formal ni"]},
            {"concept": "Two genders, attached articles",
             "pattern": "en man → mannen · ett hus → huset",
             "examples": [
                 {"target": "mannen", "roman": "MAH-nehn", "gloss": "the man"},
                 {"target": "huset", "roman": "HEW-seht", "gloss": "the house"},
                 {"target": "boken", "roman": "BOO-kehn", "gloss": "the book"}],
             "exceptions": ["En vs ett gender must be learned word by word (most are en)."],
             "learnerNote": "Like Danish, the article sticks to the end: -en/-n for common, -et/-t for neuter.",
             "commonMistakes": ["En hus (it is ett hus)", "Forgetting the double consonant in mannen"]},
            {"concept": "Negation with inte",
             "pattern": "verb + inte",
             "examples": [
                 {"target": "jag förstår inte", "roman": "yahg fur-SHTOHR een-teh", "gloss": "I don't understand"},
                 {"target": "jag vet inte", "roman": "yahg veht een-teh", "gloss": "I don't know"},
                 {"target": "det är inte", "roman": "deh ehr een-teh", "gloss": "it is not"}],
             "exceptions": ["Inte moves before the verb in subordinate clauses."],
             "learnerNote": "Inte follows the verb in main sentences — mirror-image of English not.",
             "commonMistakes": ["Jag inte förstår (wrong order)", "Using nej to negate verbs"]},
            {"concept": "Question words",
             "pattern": "vad (what) · var (where) · när (when) · varför (why) · vem (who)",
             "examples": [
                 {"target": "Var är stationen?", "roman": "vahr ehr stah-SHOON-ehn", "gloss": "Where is the station?"},
                 {"target": "Vad kostar det?", "roman": "vahl KOHS-tahr deh", "gloss": "How much is it?"},
                 {"target": "Vem är du?", "roman": "vehm ehr doo", "gloss": "Who are you?"}],
             "exceptions": ["Vart (where to) vs var (where at) — direction matters."],
             "learnerNote": "Swedish keeps statement word order in questions; the question word leads, tone rises.",
             "commonMistakes": ["Var vs vart mix-ups", "English-style do-support"]},
        ],
    },
    "no": {
        "name": "Norwegian", "native": "norsk",
        "about": ("Norwegian (norsk) is spoken by about 5 million people in Norway, in two equal written "
                  "standards (Bokmål and Nynorsk); this pack uses Bokmål. It covers greetings, essentials "
                  "and core grammar — a first taste, not a full course. It is the English-medium starting point for Norway."),
        "words": [
            ("jeg", "yai", "I", "pronoun", "people"),
            ("du", "doo", "you (informal)", "pronoun", "people"),
            ("han", "hahn", "he", "pronoun", "people"),
            ("hun", "hoon", "she", "pronoun", "people"),
            ("vi", "vee", "we", "pronoun", "people"),
            ("vann", "vahn", "water", "noun", "essentials"),
            ("mat", "maht", "food", "noun", "essentials"),
            ("hus", "hews", "house", "noun", "home"),
            ("brød", "brur", "bread", "noun", "food"),
            ("tid", "teed", "time", "noun", "time"),
            ("dag", "dahg", "day", "noun", "time"),
            ("natt", "naht", "night", "noun", "time"),
            ("venn", "vehn", "friend", "noun", "people"),
            ("familie", "fah-MEEL-yeh", "family", "noun", "people"),
            ("god", "goo", "good", "adjective", "basics"),
            ("dårlig", "DAWR-lee", "bad", "adjective", "basics"),
            ("stor", "stohr", "big", "adjective", "basics"),
            ("liten", "LEE-tehn", "small", "adjective", "basics"),
            ("ja", "yah", "yes", "particle", "essentials"),
            ("nei", "nay", "no", "particle", "essentials"),
            ("penger", "PEHNG-ehr", "money", "noun", "daily"),
            ("bok", "book", "book", "noun", "objects"),
            ("mann", "mahn", "man / person", "noun", "people"),
            ("takk", "tahk", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Hei", "hay", "hello", "greetings", "neutral"),
            ("Tusen takk", "TOO-sehn tahk", "a thousand thanks", "essentials", "neutral"),
            ("Hvordan har du det?", "VEHL-dahn hahr doo deh", "How are you? (informal)", "greetings", "informal"),
            ("Hva heter du?", "vah HEH-tuhr doo", "What's your name? (informal)", "greetings", "informal"),
            ("Jeg heter …", "yai HEH-tuhr", "My name is …", "introductions", "neutral"),
            ("Hva er det?", "vah ehr deh", "What is it?", "basics", "neutral"),
            ("Jeg forstår ikke", "yai foh-SHTOHR ee-kuh", "I don't understand", "problems", "neutral"),
            ("Ha det", "hah deh", "goodbye (take it)", "greetings", "neutral"),
            ("Vær så snill", "vehr saw sneel", "please (be so kind)", "essentials", "neutral"),
            ("Snakker du engelsk?", "SNAH-kuhr doo EHNG-ehlsk", "Do you speak English? (informal)", "survival", "informal"),
            ("Hva koster det?", "vah KOHS-tuhr deh", "How much is it?", "shopping", "neutral"),
            ("Hvor er …?", "vohr ehr", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "jeg · du · han/hun · vi · dere · de",
             "examples": [
                 {"target": "jeg snakker", "roman": "yai SNAH-kuhr", "gloss": "I speak"},
                 {"target": "du snakker", "roman": "doo SNAH-kuhr", "gloss": "you speak"},
                 {"target": "vi snakker", "roman": "vee SNAH-kuhr", "gloss": "we speak"}],
             "exceptions": ["Formal De is nearly extinct — du is universal."],
             "learnerNote": "One verb form for all persons (snakker) — Norwegian conjugation is minimal.",
             "commonMistakes": ["Conjugating per person", "Using formal De"]},
            {"concept": "Two (or three) genders, attached articles",
             "pattern": "en mann → mannen · et hus → huset",
             "examples": [
                 {"target": "mannen", "roman": "MAH-nehn", "gloss": "the man"},
                 {"target": "huset", "roman": "HEW-seh", "gloss": "the house"},
                 {"target": "boka", "roman": "BOO-kah", "gloss": "the book (feminine -a)"}],
             "exceptions": ["Bokmål allows feminine -a (boka) or common -en (boken) — both correct."],
             "learnerNote": "Articles attach to the end; Bokmål optionally keeps a feminine -a form.",
             "commonMistakes": ["En hus (it is et hus)", "Mixing Bokmål and Nynorsk forms randomly"]},
            {"concept": "Negation with ikke",
             "pattern": "verb + ikke",
             "examples": [
                 {"target": "jeg forstår ikke", "roman": "yai foh-SHTOHR ee-kuh", "gloss": "I don't understand"},
                 {"target": "jeg vet ikke", "roman": "yai veht ee-kuh", "gloss": "I don't know"},
                 {"target": "det er ikke", "roman": "deh ehr ee-kuh", "gloss": "it is not"}],
             "exceptions": ["Ikke moves before the verb in subordinate clauses."],
             "learnerNote": "Ikke follows the verb in main clauses — same Scandinavian pattern as Danish/Swedish.",
             "commonMistakes": ["Jeg ikke forstår (wrong order)", "Confusing ikke with ingen (none)"]},
            {"concept": "Question words",
             "pattern": "hva (what) · hvor (where) · når (when) · hvorfor (why) · hvem (who)",
             "examples": [
                 {"target": "Hvor er stasjonen?", "roman": "vohr ehr stah-SHOON-ehn", "gloss": "Where is the station?"},
                 {"target": "Hva koster det?", "roman": "vah KOHS-tuhr deh", "gloss": "How much is it?"},
                 {"target": "Hvem er du?", "roman": "vehm ehr doo", "gloss": "Who are you?"}],
             "exceptions": ["Hv- sounds like v-: hva ≈ vah."],
             "learnerNote": "Norwegian question words mirror Danish (hv-) — historical cousins, same roots.",
             "commonMistakes": ["Pronouncing the h", "Hvor vs hvorfor mix-ups"]},
        ],
    },
    "fi": {
        "name": "Finnish", "native": "suomi",
        "about": ("Finnish (suomi) is spoken by about 5 million people in Finland. This starter pack covers "
                  "greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Finland."),
        "words": [
            ("minä", "MEE-nah", "I", "pronoun", "people"),
            ("sinä", "SEE-nah", "you (informal)", "pronoun", "people"),
            ("hän", "hahn", "he / she", "pronoun", "people"),
            ("me", "meh", "we", "pronoun", "people"),
            ("te", "teh", "you (plural/formal)", "pronoun", "people"),
            ("vesi", "VEH-see", "water", "noun", "essentials"),
            ("ruoka", "ROO-oh-kah", "food", "noun", "essentials"),
            ("talo", "TAH-loh", "house", "noun", "home"),
            ("leipä", "LAY-pah", "bread", "noun", "food"),
            ("aika", "AH-ee-kah", "time", "noun", "time"),
            ("päivä", "PAH-ee-vah", "day", "noun", "time"),
            ("yö", "yur", "night", "noun", "time"),
            ("ystävä", "UWS-tah-vah", "friend", "noun", "people"),
            ("perhe", "PEHR-heh", "family", "noun", "people"),
            ("hyvä", "HUW-vah", "good", "adjective", "basics"),
            ("huono", "HOO-oh-noh", "bad", "adjective", "basics"),
            ("iso", "EE-soh", "big", "adjective", "basics"),
            ("pieni", "PYEH-nee", "small", "adjective", "basics"),
            ("kyllä", "KUWL-lah", "yes", "particle", "essentials"),
            ("ei", "ay", "no", "particle", "essentials"),
            ("raha", "RAH-hah", "money", "noun", "daily"),
            ("kirja", "KEER-yah", "book", "noun", "objects"),
            ("ihminen", "EEKH-mee-nehn", "person", "noun", "people"),
            ("kiitos", "KEE-tohs", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Hei", "hay", "hello", "greetings", "neutral"),
            ("Kiitos paljon", "KEE-tohs PAHL-yohn", "thanks a lot", "essentials", "neutral"),
            ("Mitä kuuluu?", "MEE-tah KOO-loo", "How are you? / What's up?", "greetings", "informal"),
            ("Mikä sinun nimesi on?", "MEE-kah SEE-noon NEE-meh-see ohn", "What's your name? (informal)", "greetings", "informal"),
            ("Minun nimeni on …", "MEE-noon NEE-meh-nee ohn", "My name is …", "introductions", "neutral"),
            ("Mikä tämä on?", "MEE-kah TAH-mah ohn", "What is this?", "basics", "neutral"),
            ("En ymmärrä", "ehn UWM-mahr-rah", "I don't understand", "problems", "neutral"),
            ("Näkemiin", "NAH-keh-meen", "goodbye", "greetings", "neutral"),
            ("Ole hyvä", "OH-leh HUW-vah", "please (be good)", "essentials", "neutral"),
            ("Puhutko englantia?", "POO-hoot-koh EHNG-lahn-tee-ah", "Do you speak English? (informal)", "survival", "informal"),
            ("Paljonko tämä maksaa?", "PAHL-yohn-koh TAH-mah MAHK-sah", "How much is this?", "shopping", "neutral"),
            ("Missä on …?", "MEES-sah ohn", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns (no he/she split)",
             "pattern": "minä · sinä · hän · me · te · he",
             "examples": [
                 {"target": "minä puhun", "roman": "MEE-nah POO-hoon", "gloss": "I speak"},
                 {"target": "sinä puhut", "roman": "SEE-nah POO-hoot", "gloss": "you speak"},
                 {"target": "hän puhuu", "roman": "hahn POO-hoo", "gloss": "he/she speaks"}],
             "exceptions": ["Spoken Finnish shortens: mä (I), sä (you) — but minä/sinä are always correct."],
             "learnerNote": "Hän covers he AND she — Finnish has no grammatical gender at all.",
             "commonMistakes": ["Looking for a she-pronoun (there is none)", "Using spoken mä/sä in writing"]},
            {"concept": "Cases instead of prepositions",
             "pattern": "talo (house) → talossa (in the house) → talosta (from the house)",
             "examples": [
                 {"target": "talossa", "roman": "TAH-lohs-sah", "gloss": "in the house (-ssa = in)"},
                 {"target": "Helsingissä", "roman": "HEHL-seeng-gees-sah", "gloss": "in Helsinki"},
                 {"target": "vedessä", "roman": "VEH-dehs-sah", "gloss": "in the water"}],
             "exceptions": ["Finnish has about 15 cases — beginners need only -ssa (in) and -sta (from) first."],
             "learnerNote": "Endings do the job of English in/from/to/with — nouns change shape instead.",
             "commonMistakes": ["Adding in before the noun (the ending already says it)", "Mixing -ssa (inside) with -lla (on top)"]},
            {"concept": "Negation is a verb: ei",
             "pattern": "en/et/ei/emme/ette/eivät + verb stem",
             "examples": [
                 {"target": "en ymmärrä", "roman": "ehn UWM-mahr-rah", "gloss": "I don't understand"},
                 {"target": "et puhu", "roman": "eht POO-hoo", "gloss": "you don't speak"},
                 {"target": "ei ole", "roman": "ay OH-leh", "gloss": "it is not"}],
             "exceptions": ["The main verb loses its personal ending after ei (ymmärrä, not ymmärrän)."],
             "learnerNote": "Ei conjugates (en/et/ei…) while the main verb freezes — negation with its own verb.",
             "commonMistakes": ["En ymmärrän (double ending)", "Using ei like English not (it comes FIRST)"]},
            {"concept": "Questions with -ko/-kö",
             "pattern": "statement + ko/kö on the questioned word",
             "examples": [
                 {"target": "Puhutko englantia?", "roman": "POO-hoot-koh EHNG-lahn-tee-ah", "gloss": "Do you speak English?"},
                 {"target": "Onko tämä hyvä?", "roman": "OHN-koh TAH-mah HUW-vah", "gloss": "Is this good?"},
                 {"target": "Tuletko?", "roman": "TOO-leht-koh", "gloss": "Are you coming?"}],
             "exceptions": ["Question words (mikä/missä/milloin) need no -ko."],
             "learnerNote": "Glue -ko (or -kö after ä/ö/y) onto a word to turn it into a yes/no question.",
             "commonMistakes": ["Using do/does helpers", "Forgetting vowel harmony (kö after front vowels)"]},
        ],
    },
    "is": {
        "name": "Icelandic", "native": "íslenska",
        "about": ("Icelandic (íslenska) is spoken by about 350,000 people in Iceland. This starter pack covers "
                  "greetings, essentials and core grammar — a first taste, not a full course. It is the "
                  "English-medium starting point for Iceland."),
        "words": [
            ("ég", "yeh", "I", "pronoun", "people"),
            ("þú", "thoo", "you (informal)", "pronoun", "people"),
            ("hann", "hahn", "he", "pronoun", "people"),
            ("hún", "hoon", "she", "pronoun", "people"),
            ("við", "veedh", "we", "pronoun", "people"),
            ("vatn", "vahtn", "water", "noun", "essentials"),
            ("matur", "MAH-tyr", "food", "noun", "essentials"),
            ("hús", "hoos", "house", "noun", "home"),
            ("brauð", "broyth", "bread", "noun", "food"),
            ("tími", "TEE-mee", "time", "noun", "time"),
            ("dagur", "DAH-gyr", "day", "noun", "time"),
            ("nótt", "noht", "night", "noun", "time"),
            ("vinur", "VEE-nyr", "friend", "noun", "people"),
            ("fjölskylda", "FYUL-skeel-dah", "family", "noun", "people"),
            ("góður", "GOH-dhyr", "good", "adjective", "basics"),
            ("slæmur", "SLAI-myr", "bad", "adjective", "basics"),
            ("stór", "stohr", "big", "adjective", "basics"),
            ("lítill", "LEE-teedl", "small", "adjective", "basics"),
            ("já", "yow", "yes", "particle", "essentials"),
            ("nei", "nay", "no", "particle", "essentials"),
            ("peningar", "PEH-neen-gahr", "money", "noun", "daily"),
            ("bók", "bohk", "book", "noun", "objects"),
            ("maður", "MAH-dhyr", "person / man", "noun", "people"),
            ("takk", "tahk", "thanks", "noun", "essentials"),
        ],
        "phrases": [
            ("Halló", "hah-LOH", "hello (on phone)", "greetings", "neutral"),
            ("Góðan dag", "GOH-dhahn dahg", "good day", "greetings", "neutral"),
            ("Takk fyrir", "tahk FEE-reer", "thanks (for it)", "essentials", "neutral"),
            ("Hvernig hefurðu það?", "KVEHR-neeg HEH-vyr-dhoo thadh", "How are you? (informal)", "greetings", "informal"),
            ("Hvað heitir þú?", "kvadh HAY-teer thoo", "What's your name? (informal)", "greetings", "informal"),
            ("Ég heiti …", "yeh HAY-tee", "My name is …", "introductions", "neutral"),
            ("Hvað er þetta?", "kvadh ehr THYEH-tah", "What is this?", "basics", "neutral"),
            ("Ég skil ekki", "yeh skeel EHK-ee", "I don't understand", "problems", "neutral"),
            ("Bless", "blehs", "goodbye (be blessed)", "greetings", "neutral"),
            ("Talar þú ensku?", "TAH-lahr thoo EHNS-ky", "Do you speak English? (informal)", "survival", "informal"),
            ("Hvað kostar þetta?", "kvadh KOH-stahr THYEH-tah", "How much is this?", "shopping", "neutral"),
            ("Hvar er …?", "kvahr ehr", "Where is …?", "survival", "neutral"),
        ],
        "concepts": [
            {"concept": "Subject pronouns",
             "pattern": "ég · þú · hann/hún · við · þið · þeir/þær/þau",
             "examples": [
                 {"target": "ég tala", "roman": "yeh TAH-lah", "gloss": "I speak"},
                 {"target": "þú talar", "roman": "thoo TAH-lahr", "gloss": "you speak"},
                 {"target": "við tölum", "roman": "veedh TUR-lym", "gloss": "we speak"}],
             "exceptions": ["They has three genders: þeir (m), þær (f), þau (n)."],
             "learnerNote": "Icelandic kept the old þ (th) and full verb conjugations — the most conservative Germanic language.",
             "commonMistakes": ["Using one verb form for all persons (endings change!)", "Mixing þú (you) with þau (they, neuter)"]},
            {"concept": "Four cases, attached articles",
             "pattern": "maður → maðurinn (the man)",
             "examples": [
                 {"target": "maðurinn", "roman": "MAH-dhyr-een", "gloss": "the man"},
                 {"target": "húsið", "roman": "HOO-seedh", "gloss": "the house"},
                 {"target": "bókin", "roman": "BOH-keen", "gloss": "the book"}],
             "exceptions": ["Articles change by case AND gender — beginners learn nominative first."],
             "learnerNote": "Nouns change ending by case (who did what to whom) and the article glues on the end.",
             "commonMistakes": ["Using nominative everywhere", "Putting the article before the noun"]},
            {"concept": "Negation with ekki",
             "pattern": "verb + ekki",
             "examples": [
                 {"target": "ég skil ekki", "roman": "yeh skeel EHK-ee", "gloss": "I don't understand"},
                 {"target": "ég veit ekki", "roman": "yeh vayt EHK-ee", "gloss": "I don't know"},
                 {"target": "það er ekki", "roman": "thadh ehr EHK-ee", "gloss": "it is not"}],
             "exceptions": ["Short answers use nei: Nei, ekki (no, not)."],
             "learnerNote": "Ekki follows the verb — same Scandinavian logic as Danish ikke and Swedish inte.",
             "commonMistakes": ["Ég ekki skil (wrong order)", "Using nei to negate verbs"]},
            {"concept": "Question words",
             "pattern": "hvað (what) · hvar (where) · hvenær (when) · af hverju (why) · hver (who)",
             "examples": [
                 {"target": "Hvar er stöðin?", "roman": "kvahr ehr STUR-dheen", "gloss": "Where is the station?"},
                 {"target": "Hvað kostar þetta?", "roman": "kvadh KOH-stahr THYEH-tah", "gloss": "How much is this?"},
                 {"target": "Hver ert þú?", "roman": "kvehr ehrt thoo", "gloss": "Who are you?"}],
             "exceptions": ["Hv- sounds like kv-: hvað ≈ kvadh."],
             "learnerNote": "Icelandic hv- kept an older kv- sound — a living museum of Germanic.",
             "commonMistakes": ["English w-sounds for hv", "Hvar vs hvenær mix-ups"]},
        ],
    },
}
